### ISSUE TITLE
Uncaught errors reported when no workspace is open

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#1004]
The uncaught errors are coming from here, which I'm pretty sure is unrelated to this PR:

https://github.com/intersystems-community/vscode-objectscript/blob/225df7689c499c792174464f3f2f04bf8da74a8a/src/utils/index.ts#L364-L369

_Originally posted by @isc-bsaviano in https://github.com/intersystems-community/vscode-objectscript/issues/1003#issuecomment-1292594921_

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I agree.
