### ISSUE TITLE
Explorer always shown when selecting ISFS file

### ISSUE THREAD

**Issue by LogMull** [intersystems-community/vscode-objectscript#1005]
I always use server side editing with ISFS, so this may not be a problem when editing locally.  

When switching between tabs of already opened editors, the explorer in the primary sidebar is always focused.  This occurs even when the sidebar is closed and explorer is unchecked from the list of items to display in the sidebar.  This is not how VS Code normally operates, there are some options such as explorer.autoreavel which can change what happens when a file is selected, but such options do not forcefully open the explorer pane.  With the limited knowledge I have of how the plugin works, my best guess is that is happening here 
https://github.com/intersystems-community/vscode-objectscript/blob/efb39c52e6c6ded9800bbc9f70d9e362734ac9ed/src/extension.ts#L428
and here (for projects)
https://github.com/intersystems-community/vscode-objectscript/blob/9869c622934dcce3be6b7037408980f843c7673a/src/commands/project.ts#L902

**Comment by isc-bsaviano** [comment]
@LogMull The first source is likely the cause of the behavior you reported. 

@gjsjohnmurray Is there any reason why we refresh the explorers every time we check the connection? I would expect that if the connection status didn't change nothing would be refreshed.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano can you repro what @LogMull reported? I'm not seeing that behaviour here.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I can't reproduce it either. I opened an ISFS workspace with files open from 2 different folders, hid the explorer then collapsed the left side panel. When I switch between the 2 tabs, the explorer remains hidden and the left side panel remains collapsed.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano our inability to repro it may be down to timing, if a uri-less checkConnection hasn't completed by the time one specifying a uri occurs.

@LogMull please try the VSIX at https://github.com/intersystems-community/vscode-objectscript/suites/8997166305/artifacts/414372201 which removes the call in extension.ts

If this resolves the issue I'll do some more analysis about whether it is ever needed.

**Comment by LogMull** [comment]
@gjsjohnmurray  Yes, that vsix seems to address the issue.  Looks like this addresses similar behavior when other primary views are open too (such as the debug and search in files view), so all the better.

**Comment by gjsjohnmurray** [comment]
@LogMull https://github.com/intersystems-community/vscode-objectscript/suites/8999114144/artifacts/414507765 is an updated VSIX which reinstates some Explorer refreshing. Please check whether it still resolves your issue.

**Comment by LogMull** [comment]
@gjsjohnmurray Yes, this version still fixes what I was originally seeing.
