### ISSUE TITLE
Parameter/Property/Class keyword case changes on compile

### ISSUE THREAD

**Issue by Dudelmoser** [intersystems-community/vscode-objectscript#101]
Whenever I compile the initial letter of the above mentionned keywords changes to uppercase, even though my command case is "lower". Am I missing something?

**Comment by daimor** [comment]
I'm not controlling this case. This goes from Cache/IRIS side. When you compile I'm checking new view of class from the server, in case if updated on a server, like when you compile %Persistent classes it can update your storage. As well as the case of keywords, it can also change the order of some properties for these keywords.

**Comment by Dudelmoser** [comment]
I was afraid this might be the case, although I'm a bit confused cause this doesn't seem to happen on my colleagues Studio. Do you by any chance know how to disable this on IRIS side?

**Comment by daimor** [comment]
It's interesting did not know that Studio can do it this way. So, I don't know how to solve it yet, by now.

**Comment by isc-jamien** [comment]
There should be no difference between VSCode and Studio, If Studio is doing something different then it's doing it itself. I don't propose we do anything about this, especially as Studio doesn't export UDL so it should not be an issue for source control. An important side note here is that the export UDL facility on the server need to be consistent with what is returned to VSCode. If not we will have DIFF chaos breaking out at some indeterminate but extremely inconvenient moment in the future

**Comment by isc-jamien** [comment]
The reason there is a perceived difference with the colleagues Studio is that if you make a change which is not semantic, i.e. you just change the case of a keyword like parameter and compile. The studio document does not get refreshed. If you close the class and re-open you will see that it HAS been changed to the canonical form
