### ISSUE TITLE
Unable to open a class in VSCode which is created using DDL from JDBC client (DBeaver)

### ISSUE THREAD

**Issue by arunmaskara** [intersystems-community/vscode-objectscript#1012]
Type: <b>Bug</b>

WRC (https://wrc.intersystems.com/wrc/eucustprob2.csp?OBJID=967660) was unable to reproduce the issue.

This only happens in IRIS 2022.1 works in 2020.1

Please use following steps to reproduce the bug:

 

Step 1: Execute the following DDL from DBeaver

 

create function arun.testjson(injson varchar(3641144), lastUsedAt date) returns varchar(1000)

language ObjectScript {

      set inobj = [].%FromJSON(injson)

      quit "hello"

}

 

Step 2:

 

Got to visual code and open the file functestjson.cls – You will be able to open the file.

 

Step 3: Execute the following DDL from DBeaver

 

drop function arun.testjson;

 

Step 4: Execute the following DDL from DBeaver

 

create function arun.testjson(injson varchar(3641144), lastUsedAt date) returns varchar(1000)

language ObjectScript {

      set inobj = [].%FromJSON(injson)

      quit "hello"

}

 

Step 5:

 

Got to visual code and open the file functestjson.cls – You will not be able to open the file.

 

Regards,

 

Arun Maskara

Extension version: 2.2.0
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.83GB free)|
|Process Argv|--crash-reporter-id 606855d6-e873-4bdf-adcd-183590f4fb93|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce2:30605431
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by isc-bsaviano** [comment]
Resolved internally
