### ISSUE TITLE
Using a single web server for multi instance include pathPrefix in connection info 

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#1013]
If I have multiple servers defined (below) the connection info says localhost:80[HSLIB], it would be helpful for it to include the pathPrefix when defined.

		"bfc": {
			"webServer": {
				"scheme": "http",
				"host": "localhost",
				"port": 80,
				"pathPrefix": "/bfc",
			},
			"username": "_system",
		},
		"fsql": {
			"webServer": {
				"scheme": "http",
				"host": "localhost",
				"port": 80,
				"pathPrefix": "/fsql",
			},
			"username": "_system",
		},

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray This shouldn't be hard for me to fix but I wonder what we should do if the connection string becomes very long. Maybe if it's over a certain length, show the full string in the tooltip and some placeholder in the status bar itself?

**Comment by bourette** [comment]
What about an optional description, if defined in place of host port and path prefix

**Comment by bourette** [comment]
lol, the tooltip already indicates the path prefix and user, it's just not that convenient.
