### ISSUE TITLE
Attaching to interoperability job works, but I can't get into user code

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/vscode-objectscript#1015]
I have a following debug configuration:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "objectscript",
            "request": "attach",
            "name": "Test.BO",
            "processID": "${command:PickProcess}"
        }
    ]
}
```

After I start debugging it connects (I pick a BO job) and I'm in Ens.Queue.int, waiting as that's where BO process waits for new messages.

However, there's no way to get into user code. 

I tried setting a breakpoint in BO code, but after sending a message, BO is still in Ens.Queue.int. If I press "step over" or "run to breakpoint" it does not get me to the user code.

**Comment by gjsjohnmurray** [comment]
Are INTs always being retained by compilation? Perhaps set the "k" flag, recompile your user code, then try again.

**Comment by eduard93** [comment]
`k` flag is present for the compilation.

After setting break flag in the int code it works.

**Comment by eduard93** [comment]
Thank you, John!
