### ISSUE TITLE
Open class server-side with dot notation

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1018]
Currently, I can't find any way to open a class using the "dot notation", e.g. Package.package.class
The only way is to replace the dots with a slash, e.g. Package/package/class
I'm used to using Studio, where I use this notation quite often, because it allows you to copy the path to a class from code and immediately open it with ctrl+O
![immagine](https://user-images.githubusercontent.com/115481064/204777159-a53f6d6c-604a-47fc-8747-3becd94ce32d.png)
![immagine](https://user-images.githubusercontent.com/115481064/204777377-0c4ba7e6-4465-4c49-93eb-0e7bb5ce7c67.png)

**Comment by gjsjohnmurray** [comment]
Please try `User/PAAdm.cls`

**Comment by gjsjohnmurray** [comment]
Also, if you have already opened in VS Code the same class as your Studio screenshot, try right-clicking between the parentheses of the `##class(User.PAAdm)` text and choosing `Go to Definition`.

**Comment by gbertolottiKS** [comment]
Oh, right, there was probably a misunderstanding: my "problem" is not being able to open the class (using the slashes I always managed to open any class), but being able to do it using the dots instead of the slashes.
In our team it is quite common that we are told to work on a certain class, and that this class is referred to in the format "package.package.class": having to replace dots with slashes each time or having to explore the class tree is not very convenient…

Thanks in advance!

**Comment by gjsjohnmurray** [comment]
Does it work if you add the `.cls` suffix onto what you are entering in the Open File dialog, e.g. `User.PAAdm.cls`?

**Comment by gbertolottiKS** [comment]
Yes! Thank you!
I don't know why I didn't try adding the class 😅
It works with any extension: .cls, .mac, ecc..
