### ISSUE TITLE
Errors when trying to use server-side search

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1019]
Hi,
I'm getting these errors while trying to use the server-side search:
![immagine](https://user-images.githubusercontent.com/115481064/204774672-658678aa-cdd3-4c18-a821-2b4d53ae4644.png)
I've followed these instructions: https://github.com/intersystems-community/vscode-objectscript#enable-proposed-apis
It seems to be installed correctly:
![immagine](https://user-images.githubusercontent.com/115481064/204775157-8a125ca4-97d9-4109-a2f5-4c15eaf40ff1.png)
I'm searching using the ctrl+shift+F combo

_Originally posted by @gbertolottiKS in https://github.com/intersystems-community/vscode-objectscript/issues/126#issuecomment-1331952630_

**Comment by gjsjohnmurray** [comment]
@gbertolottiKS what is the $ZVERSION string of the InterSystems server you have connected to?

**Comment by gbertolottiKS** [comment]
Hi,
thanks for your fast answer!
![immagine](https://user-images.githubusercontent.com/115481064/204779439-a47ef710-48ca-465a-a739-b60ae67f1afd.png)

**Comment by gjsjohnmurray** [comment]
Please try submitting that GET request from a tool which will let us see the raw response. Here's one way:

1. Install the [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) extension.
2. Create a new text file containing two lines like this:

```
GET http://yourserver:port/api/atelier/v3/UPGRADE/action/search?yourLoggedQueryParams
Authorization: basic yourIRISusername:password
```

3. From Command Palette run `Rest Client: Send Request`

What does the response tab contain? Take care not to reveal your credentials here on GH.

**Comment by gjsjohnmurray** [comment]
I wonder if the username you are connecting with needs a SQL permission GRANTed. Please see the final bullet point at https://github.com/intersystems-community/vscode-objectscript/blob/master/README.md#notes to grant user xxx (or a SQL role they hold) Execute permission for the following SQL Procedure in the target namespace.
```sql
GRANT EXECUTE ON %Library.RoutineMgr_StudioOpenDialog TO xxx
```

**Comment by gbertolottiKS** [comment]
I tried to make the GET request, but it gave me timeout error:

![immagine](https://user-images.githubusercontent.com/115481064/204815247-38d8573e-482e-46ff-b236-ab6455f5fd0c.png)

I'm not sure about 2 things:

1. the text file should be saved server-side?
2. where do I have to execute the command 
`GRANT EXECUTE ON %Library.RoutineMgr_StudioOpenDialog TO xxx`
In the iris terminal ? (it didn't work) In the embedded VS Code terminal ? (it didn't work)

**Comment by gjsjohnmurray** [comment]
1. No need to save the text file, but if you do then save it on your local filesystem. It's just a script for REST Client to use.

Strange that you are getting a Gateway Timeout error. Does the Server Manager connection that your VS Code workspace is using specify http or https as the protocol? Are you using the IRIS private Apache web server? Does the start of the URL in that GET line look like the URL you use when accessing the IRIS Portal for this server?

2. In an IRIS terminal session in the UPGRADE namespace, first run this:
```
UPGRADE>d $system.SQL.Shell()
```

Then use the SQL shell to run the GRANT statement.

To exit the shell type `quit` and press Enter.

**Comment by gbertolottiKS** [comment]
I've figured out how to get working the GET (I didn't have to save the .txt file), and this is the result; is what I've expected, because is what I get on Studio:

```
HTTP/1.1 200 OK
Date: Wed, 30 Nov 2022 14:17:42 GMT
Server: Apache
CACHE-CONTROL: no-cache
EXPIRES: Thu, 29 Oct 1998 17:04:19 GMT
PRAGMA: no-cache
CONTENT-ENCODING: gzip
CONTENT-LENGTH: 388
Connection: close
Content-Type: application/json; charset=utf-8

{
  "status": {
    "errors": [],
    "summary": ""
  },
  "console": [
    "",
    "Searching for 'GetMappedNationalCodes' in 'Custom.*.cls'",
    "Custom.EUOL.REST.FollowUp.cls(GetDecisioneDimissione+23): set codiceEsitoPrevisto = ##class(Custom.EUOL.Utils).GetMappedNationalCodes(\"PAC_DischCondit\",\"ARIA\",\"DISCON_Code\",codiceEsitoPrevisto)",
    "Custom.EUOL.REST.FollowUp.cls(GetDimissione+30): set codiceEsitoPS = ##class(Custom.EUOL.Utils).GetMappedNationalCodes(\"PAC_DischCondit\",\"ARIA\",\"DISCON_Code\",codiceEsitoPS)",
    "Custom.EUOL.Utils.cls(GetMappedNationalCodes): Method GetMappedNationalCodes ",
    "Found 3 occurrence/s in 2 file/s."
  ],
  "result": [
    {
      "doc": "Custom.EUOL.REST.FollowUp.cls",
      "matches": [
        {
          "member": "GetDecisioneDimissione",
          "line": 23,
          "text": "set codiceEsitoPrevisto = ##class(Custom.EUOL.Utils).GetMappedNationalCodes(\"PAC_DischCondit\",\"ARIA\",\"DISCON_Code\",codiceEsitoPrevisto)"
        },
        {
          "member": "GetDimissione",
          "line": 30,
          "text": "set codiceEsitoPS = ##class(Custom.EUOL.Utils).GetMappedNationalCodes(\"PAC_DischCondit\",\"ARIA\",\"DISCON_Code\",codiceEsitoPS)"
        }
      ]
    },
    {
      "doc": "Custom.EUOL.Utils.cls",
      "matches": [
        {
          "member": "GetMappedNationalCodes",
          "text": "Method GetMappedNationalCodes "
        }
      ]
    }
  ]
}
```

But if I make the same search using the ctrl+shift+f menu, it shows me only the results in the opened files, and, after a bit of time, it gives me the same NON-Json response error:

![immagine](https://user-images.githubusercontent.com/115481064/204819811-060e9f9c-6119-4e00-8696-bd039dd3f5ce.png)

**Comment by gbertolottiKS** [comment]
> 1. No need to save the text file, but if you do then save it on your local filesystem. It's just a script for REST Client to use.
> 
> 
> Strange that you are getting a Gateway Timeout error. Does the Server Manager connection that your VS Code workspace is using specify http or https as the protocol? Are you using the IRIS private Apache web server? Does the start of the URL in that GET line look like the URL you use when accessing the IRIS Portal for this server?
> 
>     2. In an IRIS terminal session in the UPGRADE namespace, first run this:
> 
> 
> ```
> UPGRADE>d $system.SQL.Shell()
> ```
> 
> Then use the SQL shell to run the GRANT statement.
> 
> To exit the shell type `quit` and press Enter.

1. If I don't save the file, it works
2. Thanks. I made it, but apparently nothing changed

**Comment by gjsjohnmurray** [comment]
What is the exact text of the failure message in the ObjectScript output channel when the Search panel gives you the result shown in your latest screenshot?

Is this exactly the same query as you used for the successful REST request?

How any seconds passed between you starting that search and the "An error occurred" message appearing?

**Comment by gjsjohnmurray** [comment]
OK, so I'm guessing that if you use REST Client to do the same search query, i.e. `files=*.cls%2C*.inc%2C*.mac%2C*.int&gen=0&sys=0&regex=0&case=0&wild=0&word=0&query=GetMappedNationalCodes&max=20000` then you will get a 504 timeout after 60 seconds,

Presumably the target namespace contains a large amount of code.

**Comment by gbertolottiKS** [comment]
Yes, all correct:

```
HTTP/1.1 504 Gateway Timeout
Content-type: text/html; charset=utf-8
Connection: close
Expires: Thu, 29 Oct 1998 17:04:19 GMT
Cache-Control: no-cache
Pragma: no-cache
```
Is there any other way to achieve the 'search-in-all-files' ?
In Studio I reach the goal in fractions of a second...

![immagine](https://user-images.githubusercontent.com/115481064/204837251-7589935a-c886-4052-b2c0-d7d1873754f6.png)

**Comment by gjsjohnmurray** [comment]
We need to fix a bug. Current implementation of server-side search doesn't send the 'files to include' and 'files to exclude' patterns to the server.

**Comment by gjsjohnmurray** [comment]
Please download the zip from https://github.com/intersystems-community/vscode-objectscript/suites/9591473530/artifacts/457214424 and install the dev VSIX it contains. This should make server-side search use whatever 'includes' and 'excludes' values you specify. Let me know if it works for you.

**Comment by gjsjohnmurray** [comment]
Updated VSIX is at https://github.com/intersystems-community/vscode-objectscript/suites/9591878280/artifacts/457243115

**Comment by gbertolottiKS** [comment]
Hi!
Thanks for your update.
I installed the new VSIX and tried again the search, but I think I don't understand what is the vs code include files syntax: if I try the same Studio pattern, it returns nothing

![immagine](https://user-images.githubusercontent.com/115481064/205047631-beb10a0f-63b3-4bfc-b307-0fdb81a49ce2.png)

![immagine](https://user-images.githubusercontent.com/115481064/205047671-e2340707-202a-456f-9bfc-7c994fae7ddc.png)

Should I use a different pattern, e.g. "Custom/*/.cls ecc"?

**Comment by gjsjohnmurray** [comment]
Please use the new VSIX in https://github.com/intersystems-community/vscode-objectscript/suites/9610151104/artifacts/458625849 and enter `Custom/*.cls,U*.mac,HL7*.mac`

**Comment by gbertolottiKS** [comment]
Thanks, now it works perfectly!!
I figured out that the right syntax is `Custom/**/*.cls,U*.mac,HL7*.mac`

A final question: to spread the solution to the rest of the team, have I to tell picking the above VSIX file, or do you have also updated the one at https://github.com/intersystems-community/vscode-objectscript/releases/tag/v2.2.1-beta.1 ?

**Comment by gjsjohnmurray** [comment]
Excellent!

Once my PR has been approved and merged it will create a new v2.2.1-beta.X which you can point the team at.

**Comment by gbertolottiKS** [comment]
Perfect.
Thanks for your outstanding work!

**Comment by gjsjohnmurray** [comment]
Please try the latest dev build from https://github.com/intersystems-community/vscode-objectscript/suites/9623118934/artifacts/459536603 in which I have done some refactoring of the include/exclude logic. I hope it still works the way you expect. Let me know of any problems you find with it.

Thanks!

**Comment by gbertolottiKS** [comment]
Ok, thanks, I'll try and I'll let you know if I encounter any issues

**Comment by gbertolottiKS** [comment]
I already found a difference with Studio (I don't know if it's a bug or if it's intended):
in one search, Studio gave me also a result which is inside a value tag of a class storage

![immagine](https://user-images.githubusercontent.com/115481064/205287058-b08a0684-9ab9-4013-9d4d-15dbc6be612c.png)

VS Code instead didn't find it:

![immagine](https://user-images.githubusercontent.com/115481064/205287270-82525dac-f70c-44ae-80df-74a2bc33d787.png)

All the other classes match

**Comment by gjsjohnmurray** [comment]
I have opened a separate issue (#1022) for this. 

Interesting though that the string appears in the Storage section of the class definition but apparently there's no Property with the same name. I guess the property got deleted but the storage entry remains.

**Comment by gbertolottiKS** [comment]
Yes, it's pretty "common" here to find remaining storage values without the corresponding deleted properties

**Comment by gjsjohnmurray** [comment]
The latest dev VSIX at https://github.com/intersystems-community/vscode-objectscript/suites/9743661134/artifacts/467678834 should resolve the failure to find the Storage match.

**Comment by gjsjohnmurray** [comment]
Now merged and available in https://github.com/intersystems-community/vscode-objectscript/releases/download/v2.2.1-beta.6/vscode-objectscript-2.2.1-beta.6.vsix or later.

**Comment by gbertolottiKS** [comment]
Thank you for all!
So this VSIX now available at the release section superseded the one at https://github.com/intersystems-community/vscode-objectscript/pull/1025#issuecomment-1342410320 ?
