### ISSUE TITLE
Changing git branch should reimport files

### ISSUE THREAD

**Issue by psteiwer** [intersystems-community/vscode-objectscript#102]
Is it possible to detect that the git branch was changed and then reimport the project files to the server? Often times I will switch between branches and then get errors because files are in different states.

**Comment by evshvarov** [comment]
Hi @psteiwer! I believe it's not a VSCode ObjectScript extension question. It's the matter more of your dev lifecycle. A lot of devs checkout from repo every time when open the project.
Also if you code in your branch nobody other than you can update the branch.
I also recommend GitLens VSCode extension which is extremely helpful with Git related repos. very handy.

**Comment by mvhenderson** [comment]
If you do this please make configurable for those of us that total control over when synchronization to the server occurs.

**Comment by daimor** [comment]
Yeah, it's actually quite arguing task. We have so many different projects and doing automatic import what's changed not looking good. So many ways how to break compilation in this way. I would better recommend building the project entirely when switching branches. It may take some time but solves many possible issues. And using docker makes it even easier. With a CI process, you can get some prepared images, so, you would not need to build it by yourself.

**Comment by isc-bsaviano** [comment]
Closing because this doesn't appear to be possible using the [current VS Code API](https://code.visualstudio.com/api/references/vscode-api)
