### ISSUE TITLE
Debugging not possible in Docker, WSL on Windows 

### ISSUE THREAD

**Issue by uleimberger** [intersystems-community/vscode-objectscript#1026]
Good evening,

I have a Docker WSL environment on Windows and deployed the AoC2022 - template from the Community. When I try to debug a program/class it is not possible because of this error message:
 Failed to start the debug session. Check that the Intersystems server's web server supports WebSockets.

I checked everything and it seems to be ok. So how can I debug this behavior. The tip in the documentation dies not work becuase - no connection. 
Anyway I translate the web service port in composer.yml to a different and had no issue to edit, config, start, etc etc etc .. only debugging is not possible.
Any help is appreciated.

**Comment by isc-bsaviano** [comment]
@uleimberger Can you get an HTTP trace using Wireshark or another tool so we can see the exact reason why the REST request to start debugging is failing? (GET `/api/atelier/v5/%25SYS/debug`)

**Comment by uleimberger** [comment]
@isc-bsaviano Here is what I did:
calling management - portal: http://localhost:9092/csp/sys/%25CSP.Portal.Home.zen -- works 
I try to call the atelier rest with the url you provided:
http://localhost:9092/api/atelier/v5/%25SYS/debug -- end in a 500 Internal Server Error
but when I call it without the debug: http://localhost:9092/api/atelier/v5/%25SYS - i get this answer:
<html><body>


status |  
-- | --
errors | []
summary | ""
console | []
result |  
content |  
name | "%SYS"
db |  
0 |  
name | "IRISSYS"
crhash | "5EC973884D83D"
default | true
dbsys | true
1 |  
name | "IRISLIB"
crhash | "5EB91DA637B53"
default | false
dbsys | true
2 |  
name | "ZPM"
crhash | "5EE5FE2023007"
default | false
dbsys | false
features |  
0 |  
name | "ENSEMBLE"
enabled | false


</body>
</html>

Any clue why debug is not working ?

**Comment by isc-bsaviano** [comment]
@uleimberger There should be a response body for the 500 Server Error as well. Can you send me that? It should be of the same general format as the other endpoint that is working. The `errors` and `summary` keys in the `status` object in the response body should tell us why the debugger couldn't start.

**Comment by uleimberger** [comment]
@isc-bsaviano Sorry no answer at all -- here are two screens:
![image](https://user-images.githubusercontent.com/1407860/206474193-c7813a55-d6be-4f12-be51-04dd48712249.png)
![image](https://user-images.githubusercontent.com/1407860/206474449-0b4767da-6ce4-4317-9231-e8ca223bd60c.png)

**Comment by uleimberger** [comment]
@isc-bsaviano : Hint: When I do a : http://localhost:9092/api/atelier/v5/%25SYS/cspdebugid
I get the following response:
{"status":{"errors":[],"summary":""},"console":[],"result":{"content":42392298}}
So is there anything wrong with the use of the atelier version ?

**Comment by isc-bsaviano** [comment]
@uleimberger Nope, your version is fine. If you were using a higher version in the URL than your server supports, you'd be getting 404 errors on everything. What is the `$ZV` for your IRIS instance? There is a known bug in some kits that prevents debug sessions from being started at all but it has been fixed.

**Comment by uleimberger** [comment]
Here is the version I use:
USER>W $ZV
IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2022.2 (Build 368U) Fri Oct 21 2022 17:18:04 EDT

**Comment by isc-bsaviano** [comment]
Unfortunately that version has the bug in it. If you use the [2022.3 preview kit](https://community.intersystems.com/post/intersystems-publishes-developer-preview-3-intersystems-iris-iris-health-healthshare-health) then the problem should go away.

**Comment by uleimberger** [comment]
The hint with the version was the solution. I changed now to the latest container to:
containers.intersystems.com/intersystems/iris-community:2022.3.0.555.0
and everything works like a charm. 
Thank you very much. Problem solved.
