### ISSUE TITLE
export filters and one click reexport

### ISSUE THREAD

**Issue by xoxloviwan** [intersystems-community/vscode-objectscript#103]
`objectscript.export.generated`
What means "generated" source code files? I'm not understand. I know saved and compiled routines and classes and I know exported scripts.
And how I can update (export) my local definite files if it modified on server by other developers?
I can sort it by `objectscript.export.addCategory` to folders with single uploads. But I can't pull it again only in one click.

**Comment by daimor** [comment]
Generated mostly means, classes where property [GeneretedBy](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=ROBJ_class_generatedby) not empty. Or int routines generated when class or mac compiled. You can see generated code, by command [View Other](https://cedocs.intersystems.com/latest/csp/documatic/%25CSP.Documatic.cls?PAGE=CLASS&LIBRARY=%25SYS&CLASSNAME=%25Library.RoutineMgr#METHOD_GetOther) in VSCode and in Studio.

You can export the server's code as many times as you want. You can configure `objectscript.export` [settings](https://github.com/intersystems-community/vscode-objectscript/wiki/Export-settings), to make it possible to export only what you need and how you need it. By exporting a whole namespace from command, or just manually export only what you select from server explorer.

**Comment by xoxloviwan** [comment]
Can I export only selected scripts not from server explorer? i.e. export it by writting selected names in settings.json? If yes, how get it.

**Comment by daimor** [comment]
At the moment you have two options, to export partially.
With server explorer, you can manually select each package you would like to export, one by one.
Change `objectscript.export.filter` setting, which will be used to find what to export as `Name Like '%"_filter_"%'`

**Comment by daimor** [comment]
And anyway you can export source code programmatically with $system.OBJ.ExportUDL("anything.cls,or.mac","/path/to/src")

**Comment by isc-bsaviano** [comment]
This is covered adequately by the setting reference doc page IMO.
