### ISSUE TITLE
"Override Class Members" does not support overriding projections

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems-community/vscode-objectscript#1032]
"Override Class Members" does not offer Projection as an option. This is a sort of class member that might reasonably be overridden, even if rarely.

**Comment by isc-bsaviano** [comment]
@isc-tleavitt That command is contributed by the Language Server extension, so I'm going to open this issue there and close this one.

**Comment by isc-tleavitt** [comment]
@isc-bsaviano great - thank you!
