### ISSUE TITLE
Import from local file

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1034]
Hi.
Another feature request from a Studio user... 😅
Would be very convenient to have an option to import to a remote IRIS namespace a local .cls or .xml class, like it does Studio with the Tools -> Local import, without the need to connect to a local folder (so, exiting the server-side connection).
Thanks in advance

**Comment by isc-bsaviano** [comment]
@gbertolottiKS We may consider adding support for importing `.cls`, `.mac`, `.int` and `.inc` routines using a server-side workspace folder to determine connection info but we will not be adding support for legacy `.xml` files, which has been our long standing policy (see #79).
