### ISSUE TITLE
Support for Studio NEW Templates

### ISSUE THREAD

**Issue by SCanzano-ready** [intersystems-community/vscode-objectscript#1039]
Type: <b>Feature Request</b>

I have a number of IRIS Studio templates that look like 

/// </br>Create a JSON Proxy object provided a source object
Class %ZRC.Studio.Template.JSONProxy Extends %ZEN.Template.studioTemplate
{

Parameter TEMPLATENAME = "Ready Computing JSON Proxy Object Wizard";

Parameter TEMPLATETITLE = "Ready Computing JSON Proxy Object Wizard";

Parameter TEMPLATEDESCRIPTION = "Create a new JSON Proxy Object.";

Parameter TEMPLATETYPE = "cls";

/// What type of template.
Parameter TEMPLATEMODE = "new";

Parameter TEMPLATEGROUP = "Custom";

/// Domain used for localization.
Parameter DOMAIN = "%ZEN";

which I can invoke in IRIS Studio by selecting File->New and on the pop-up dialog select the Custom Category.  After custom New Template is selected a  zen page is presented and allows me to enter some data.  After all of the data is entered I select a Finish button and this is called

/// This method is called when the template is complete. Any
/// output to the principal device is returned to the Studio.
Method %OnTemplateAction() As %Status
{

1. Does this capability exist in VS Code?
2. Can it be enabled/implemented in VS Code if it is not a current feature?

Extension version: 2.2.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by isc-bsaviano** [comment]
@SCanzano-ready If the templates are like the SOAP Wizard then you can link to them in the [Server Actions menu](https://intersystems-community.github.io/vscode-objectscript/configuration/#server-actions-menu) and they should "just work". If they rely on sending data back to Studio to insert into a document (like the HTML Color template) then we can't support them.

**Comment by isc-bsaviano** [comment]
@SCanzano-ready I mean that templates that pass data back to Studio like that are not currently supported and I haven't found a way to support them yet. Since the template UI would be shown in an iframe in VS Code I can't access the contents due to cross-site scripting security guardrails.

**Comment by isc-bsaviano** [comment]
Closing as wontfix because implementing this would require chnanges to `%ZEN.Template.studioTemplate`, which is deprecated.
