### ISSUE TITLE
How to use objectscriptquality server-side

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1041]
Hi.
I know that this is **not** an issue of this extension, but the [official repo](https://github.com/litesolutions/objectscriptquality-vscode) seems inactive from more than a year, so I can't receive an answer from there.
I would like to know if someone use that extension and know how to use it when working server-side on an IRIS server.
I have no problem when coding on a file saved locally.
Thanks in advance

**Comment by isc-bsaviano** [comment]
@gbertolottiKS The [Developer Community](https://community.intersystems.com/) is the proper forum for this question since it's not related to this extension in particular.
