### ISSUE TITLE
Cannot open server-side class in class explorer

### ISSUE THREAD

**Issue by lscalese** [intersystems-community/vscode-objectscript#1049]
Hello,

I have a strange problem with a project in VSCode.  
When I would like to open a server-side class nothing happen and there is no error message.
If I click on a class that exists in my project, there is no problem the class has been opened.

![](https://cdn.discordapp.com/attachments/704982469937594375/1064440209686667375/image.png)

If I export classes locally from the class explorer, It will show them.

I have found an error message in a log ~/.config/Code/logs/20230116T080834/window1/renderer.log

```
2023-01-16 08:20:53.511 [error] cannot open objectscript://openapi-client-gen/YAML/Utils.cls?ns%3DIRISAPP. Detail: An unknown error occurred. Please consult the log for more details.: Error: cannot open objectscript://openapi-client-gen/YAML/Utils.cls?ns%3DIRISAPP. Detail: An unknown error occurred. Please consult the log for more details.
    at s.h (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:107798)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I don't know if there is another log file with more details about this error.
Have you got an idea ?

Thank you.
Lorenzo.

**Comment by isc-bsaviano** [comment]
@lscalese I couldn't reproduce your issue but I created a VSIX that should log any errors during explorer file opens to the `ObjectScript` Output channel. Can you install this VSIX and try again?

[vscode-objectscript-2.4.2-SNAPSHOT.vsix.zip](https://github.com/intersystems-community/vscode-objectscript/files/10435227/vscode-objectscript-2.4.2-SNAPSHOT.vsix.zip)

**Comment by lscalese** [comment]
Hi @isc-bsaviano ,

Thank you for your reply.
I installed the vsix and the output error is : 

```
cannot open isfs://openapi-client-gen/YAML/Utils.cls?ns%3DIRISAPP. Detail: Unable to read file 'isfs://openapi-client-gen/YAML/Utils.cls?ns=IRISAPP' (TypeError: Cannot read properties of undefined (reading 'errorText'))
```

However, when I 'ctrl+click' on the isfs://link it opens.  
See the small video : 

[Screencast from 01-18-2023 07:10:52 AM.webm](https://user-images.githubusercontent.com/16834099/213098412-a10a3192-6e4c-48fe-89c9-dcc18e2ab823.webm)

Hope these pieces of information will be interesting to identify the root cause.
Thank you.

**Comment by isc-bsaviano** [comment]
@lscalese Thanks for the details and video. I still can't reproduce your issue. I attached a VSIX to this comment which fixes that "reading properties of undefined" error. That's not the cause of your issue, it's a bug in our error reporting code. This should report a more useful error message.

[vscode-objectscript-2.4.2-SNAPSHOT.vsix.zip](https://github.com/intersystems-community/vscode-objectscript/files/10446560/vscode-objectscript-2.4.2-SNAPSHOT.vsix.zip)

**Comment by lscalese** [comment]
Hi @isc-bsaviano ,

Thank you, the message is now : 

```
cannot open isfs://openapi-client-gen/YAML/Utils.cls?ns%3DIRISAPP. Detail: Unable to read file 'isfs://openapi-client-gen/YAML/Utils.cls?ns=IRISAPP' (Error: Unable to resolve nonexistent file 'isfs://openapi-client-gen/YAML/Utils.cls?ns=IRISAPP')
```

It works when I 'ctrl+click' the link.  Do you think It could be a permission problem ?

**Comment by isc-bsaviano** [comment]
No, I don't think it's a permissions problem. I'm not sure why ctrl-clicking the link works, that should be calling the same code. Can you use Wireshark to get an HTTP trace and repeat the open the causes the error so we can see if the HTTP response from the server is an error response?

**Comment by lscalese** [comment]
Hello @isc-bsaviano,

I installed Wireshark for the first time on my Linux and there are a lot of problems.
I'll solve my problem with Wireshark as soon as possible and get the HTTP trace.

**Comment by lscalese** [comment]
Hello,

I Installed Wireshark to launch the capture.
When I double-click on the class explorer I don't see HTTP trace.
Only when I 'ctrl+clink' the link I can see HTTP trace.
The problem probably occurs before sending the HTTP request.


[Screencast from 01-20-2023 08:42:39 AM.webm](https://user-images.githubusercontent.com/16834099/213643722-c1770f43-c953-4655-9ae6-0d3898c59e0c.webm)

Don't spend a lot of time on this problem, because I noticed everything works fine when I work on another repository...

**Comment by isc-bsaviano** [comment]
@lscalese If you turn off the `objectscript.serverSideEditing` setting and try again, does it work? You will get a read-only editor instead of read-write though. I appreciate you help debugging this.

**Comment by lscalese** [comment]
Hi @isc-bsaviano ,

With `"objectscript.serverSideEditing": true` this is the following message : 
```
cannot open isfs://openapi-client-gen/EnsPortal/ActivityVolumeAndDuration.cls?ns%3DIRISAPP. Detail: Unable to read file 'isfs://openapi-client-gen/EnsPortal/ActivityVolumeAndDuration.cls?ns=IRISAPP' (Error: Unable to resolve nonexistent file 'isfs://openapi-client-gen/EnsPortal/ActivityVolumeAndDuration.cls?ns=IRISAPP')
```
And `"objectscript.serverSideEditing": false`, it's : 
```
cannot open objectscript://openapi-client-gen/EnsPortal/ActivityVolumeAndDuration.cls?ns%3DIRISAPP. Detail: An unknown error occurred. Please consult the log for more details.
```
I don't know what does it mean, but the protocol change from `isfs://` to `objectscript://`.

**Comment by isc-bsaviano** [comment]
@lscalese The protocol switch is expected. `isfs` is the read-write virtual FileSystem that is provided by our extension. `objectscript` is a read-only provider just for document text and it predates `isfs`. That fact that this doesn't work with either protocol tells me that the buggy code is something shared by both of them. I need to do some more investigating. @gjsjohnmurray Do you have any ideas?

**Comment by lscalese** [comment]
small update:

I have this problem only with the following repository [OpenAPI-Client-Gen](https://github.com/lscalese/OpenAPI-Client-Gen.git).

Maybe, can you try this to reproduce : 

```
git clone https://github.com/lscalese/OpenAPI-Client-Gen.git
cd OpenAPI-Client-Gen
docker-compose up -d
```

And then try to explore server-side class VSCode.

**Comment by isc-bsaviano** [comment]
@lscalese After opening that repo I was able to reproduce the issue. See #1055 for a fix.
