### ISSUE TITLE
opening terminal to docker-compose errors out

### ISSUE THREAD

**Issue by lindensc** [intersystems-community/vscode-objectscript#105]
Hi,
when using docker-compose with i get an error message when first starting vscode and also when trying to execute open terminal in docker:

The terminal process command 'docker-compose -f docker-compose.yml exec iris /bin/bash -c 'command -v ccontrol >/dev/null 2>&1 && ccontrol session $ISC_PACKAGE_INSTANCENAME -U DEMO-TEST || iris session $ISC_PACKAGE_INSTANCENAME -U DEMO-TEST'' failed to launch (exit code: {2})

I have redacted the namespace setting. As i see it the issue is that the ISC_PACKAGE_INSTANCENAME variable is not replaced in the call if i run the call manually with the correct values it succeeds and i get the iris shell in the terminal.

Best Eragrds

Timo

**Comment by daimor** [comment]
Hi, could you say your OS? is it windows?

**Comment by lindensc** [comment]
Hi, this is on windows.
Regards

**Comment by jtsalten** [comment]
I've tried also with WSL2 in Windows 10 Pro release 2004 (May 2020). VS Code is launched in the host OS (Windows) but from within the Ubuntu distribution to which then VS Code connects to. The extensions have to be explicitely installed for such remote connection.
It also fails.
The full command :
docker-compose exec iris /bin/bash -c 'command -v ccontrol >/dev/null 2>&1 && ccontrol session $ISC_PACKAGE_INSTANCENAME -U IRISAPP || iris session $ISC_PACKAGE_INSTANCENAME -U IRISAPP'
works, from Windows Terminal/PowerShell and also from Ubuntu Console.
