### ISSUE TITLE
need EXECUTE on %Library.RoutineMgr_StudioOpenDialog to get class list

### ISSUE THREAD

**Issue by IRISMeister** [intersystems-community/vscode-objectscript#106]
When I login with a less privileged user (user who doesn't have %All Role but does have %Developer Role), it connects but objectscript explorer complains with 'ERROR #5540: SQLCODE: -99 Message: User test is not privileged for the operation' and fails to get class/routine/Includes list.
I then explicitly granted a following SQL Procedure and it starts working.

grant execute on %Library.RoutineMgr_StudioOpenDialog to test

I've confirmed the same behavior against Cache'2016.2.3 and IRIS 2020.1(preview version at the moment).
If this is always required, mentioning in Notes section of README.md  might be useful because I couldn't find anything related.

**Comment by daimor** [comment]
Thanks for testing it from a security perspective. 
At the moment I'm working there only with %ALL role, so, did not face it, yet.

If you would like, you can make a Pull Request with suggested changes to README.

**Comment by IRISMeister** [comment]
Sure.  Am I receiving invitation?

**Comment by daimor** [comment]
You should just fork this repository, and make any changes in your repository, then create pull request.
