### ISSUE TITLE
Unable to connect to IRIS over https using self signed certificate

### ISSUE THREAD

**Issue by isc-krakshith** [intersystems-community/vscode-objectscript#1075]
VS Code fails to connect to a server which uses a self signed certificate. The error message says "Failed to fetch namespace list..."
However, after aceepting a certificate exception, both Postman as well as Chrome browser succeed in making /api/atelier/ REST calls to the same server. Possibly related to [this](https://github.com/intersystems-community/vscode-objectscript/issues/17) closed issue.

Environment:
-  LOCAL:
  -    M1 Macbook Pro MacOS Monterey v 12.6.1
  -    VS Code v 1.74.3
  -    Objectscript Extension Pack v 1.0.3
  -    InterSystems Server Manager v 3.2.1
-   #REMOTE:
  -    AWS EC2 Ubuntu 20.04
  -    IRIS for UNIX (Ubuntu Server 20.04 LTS for x86-64) 2022.1.2 (Build 574U) (running natively NOT container)
  -   Web Gateway Version 2022.1.2.574.0
  -   Apache2 Web Server
    -    Server version: Apache/2.4.41 (Ubuntu)
    -    Server built:   2023-01-23T18:36:09

![VSCodeError](https://user-images.githubusercontent.com/73292865/216612137-d73bfcae-8a1d-4708-b0df-269641b50275.png)

![PostmanWarningSuccess](https://user-images.githubusercontent.com/73292865/216613633-edcbcbd7-3b6f-43e4-8747-9d371ce7f85f.png)

![ChromeWarningSuccess](https://user-images.githubusercontent.com/73292865/216613683-a212c947-5b7c-4cf7-a5cb-4c9703ca61e9.png)

**Comment by isc-bsaviano** [comment]
Have you tried setting `http.proxyStrictSSL` to `false` in your user settings? We have seen issues where that doesn't work on Windows but on Mac that has worked in the past. Our extensions check that setting to determine whether the REST requests they make should check certificates. Also, are there any errors written to the `ObjectScript` Output channel?

**Comment by isc-krakshith** [comment]
> Have you tried setting `http.proxyStrictSSL` to `false` in your user settings? We have seen issues where that doesn't work on Windows but on Mac that has worked in the past. Our extensions check that setting to determine whether the REST requests they make should check certificates. I have a local instance set up to use a self-signed certificate and that setting works for me. Also, are there any errors written to the `ObjectScript` Output channel?

Hi, Yes, I have proxyStrctSSL parameter set to false. No, there is no ObjectScript Output shown. Could you share an apache conf file which is known to work in a setup using WEb Gateway? I am not confident of the one I have. But that may be a red herring in this cae.

![ProxyStrictSSLFalse](https://user-images.githubusercontent.com/73292865/216628422-a7c1eee8-84ef-413c-bc97-15e116a55e66.png)

**Comment by isc-bsaviano** [comment]
@isc-krakshith According to the VS Code team, the `http.proxyStringSSL` setting is ignored by their http(s).Agent (see https://github.com/microsoft/vscode/issues/173314#issuecomment-1459899482). You should add your certificate to the OS's root certificates and re-load VS Code to see if that fixes your issue.

**Comment by gjsjohnmurray** [comment]
@isc-krakshith I'd also be interested to know if either of these settings make a difference for you without having resorted to adding the self-signed cert as a root (assuming you still have `http.proxyStrictSSL: false`

![image](https://user-images.githubusercontent.com/6726799/223758392-d4187938-9591-4896-91ba-eeabc75efc68.png)

**Comment by isc-krakshith** [comment]
@isc-bsaviano I have generated self-signed certificate using the server's root certificate, but I still cannot connect.
@gjsjohnmurray None of the options in Http: Proxy Support appear to make any difference to my attempts to connect to the server.
There might stll be a gap in my understanding of root ca certificates. That being said, when I download the PEM chain in my browser, I can see the root ca which I created. All help is most welcome.

**Comment by gjsjohnmurray** [comment]
@isc-krakshith please be sure to restart VS Code between each change you make to the Http: Proxy Support setting.

When I test using Server Manager to browse namespaces on an Apache HTTPS server with self-signed cert, running on a local test machine, every setting except the default (override) succeeds in giving me the namespaces tree, provided I also have `http.proxyStrictSSL: false`.

I guess it's possible that your setup means you must use a proxy to get to your target server. But if you don't this should work. 🤞

**Comment by isc-bsaviano** [comment]
I'm glad your setup is working now!
