### ISSUE TITLE
Private variables are garbled if non-ascii characters are included in QUERY PARAMETERS or BODY in Debug REST Service.

### ISSUE THREAD

**Issue by iijimam** [intersystems-community/vscode-objectscript#1078]
Example:QUERY PARAMETERS (non-ascii-あいうえお)
![image](https://user-images.githubusercontent.com/26560156/217287182-4a3b21ec-1611-4023-a36f-64cafa2cb115.png)

Example:BODY(non-asciiあいうえお)
![image](https://user-images.githubusercontent.com/26560156/217287394-d14d7332-2aad-432d-a308-16b6345bf94c.png)

VARIABLES view:
![image](https://user-images.githubusercontent.com/26560156/217287473-ccf4b665-c663-4b47-9689-57dfc34a1f1b.png)

I use this class:
```
Class Simple.REST Extends %CSP.REST
{

XData UrlMap [ XMLNamespace = "http://www.intersystems.com/urlmap" ]
{
<Routes>
<Route Url="/test1" Method="POST" Call="test1POST" Cors="true"/>
</Routes>
}

Parameter CHARSET = "utf-8";

Parameter CONTENTTYPE = "application/json";

Parameter CONVERTINPUTSTREAM = 1;

ClassMethod test1POST() As %Status [ Language = objectscript ]
{
	#dim ex As %Exception.AbstractException
	#dim %request As %CSP.Request
	set status=$$$OK
	try {
        //QueryParameter
		set moji=%request.Get("q")
		//Body
		set body=%request.Content.Read()

		set returnjson={}
		set returnjson.QueryParameter=moji
		set returnjson.BodyText=body
		do returnjson.%ToJSON()
	}
	catch ex {
		set status=ex.AsStatus()
	}
	quit status
}

}
```

**Comment by isc-bsaviano** [comment]
The issue with the garbled query parameter is definitely a bug in the extension. We are incorrectly double-encoding the query parameter string.

**Comment by iijimam** [comment]
I use this version.
IRIS for Windows (x86-64) 2022.1.2 (Build 574U) Fri Jan 13 2023 15:00:26 EST
