### ISSUE TITLE
Delete of subpackage over isfs fails

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems-community/vscode-objectscript#1079]
Connecting over isfs, if right click a subpackage by right clicking the folder for it in the workspace view, I get (for example, deleting SourceControl.Git, where multiple classes in that package exist):
`ERROR #16006: Document 'SourceControl.Git' name is invalid`
Oddly, deleting a top-level folder/package seems to work properly. It's just subpackages that don't work.

**Comment by isc-bsaviano** [comment]
@isc-tleavitt I'll take a look
