### ISSUE TITLE
zenPage not recognized

### ISSUE THREAD

**Issue by psteiwer** [intersystems-community/vscode-objectscript#108]
Some of my files have yellow names indicating a number of "problems" with the file.

After opening and navigating to the problem area, zenPage is marked as an unrecognized command

**Comment by daimor** [comment]
Could you show an example, so, I need context where it happens, to solve it.

**Comment by daimor** [comment]
btw, it does not recognize methods written in javascript, yet.

**Comment by psteiwer** [comment]
https://github.com/psteiwer/AnalyzeThis/blob/master/AnalyzeThis/UI/Dialog/CSVImport.cls

Line 562

![image](https://user-images.githubusercontent.com/24307254/78068953-497d5e00-7367-11ea-9509-bc0845c530df.png)
