### ISSUE TITLE
.cls file saves are failing with an Unable to write file 'isfs://...'

### ISSUE THREAD

**Issue by theflyingape** [intersystems-community/vscode-objectscript#1082]
Type: <b>Bug</b>

Open class source, any edit, then press Ctrl/S to save causes a write file failure dialog box.

The backend webserver log shows '304' errors:
```
172.27.2.216 - - [08/Feb/2023:11:00:28 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:00:28 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:00:28 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 472 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:00:28 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 232 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:00:28 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 316 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:00:30 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:00:30 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:00:30 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 352 "-" "node-fetch"
```
Save as option can write a new class file, but only as an empty class without any implementation source lines in it:

```
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 404 244 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "PUT /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls?ignoreConflict=0 HTTP/1.1" 201 223 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 200 275 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 200 275 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 91 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:01:59 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 352 "-" "node-fetch"
```

Deleting a class permananetly out of the Worksapce works too:

```
172.27.2.216 - - [08/Feb/2023:11:02:41 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 304 - "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 472 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "DELETE /api/atelier/v5/HSCUSTOM/doc/Common.Production.AppRegistry2.cls HTTP/1.1" 200 238 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 232 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:50 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:51 -0500] "GET /api/atelier/ HTTP/1.1" 200 463 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:51 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 316 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:51 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 472 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:51 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 232 "-" "node-fetch"
172.27.2.216 - - [08/Feb/2023:11:02:51 -0500] "POST /api/atelier/v5/HSCUSTOM/action/query HTTP/1.1" 200 316 "-" "node-fetch"

```

Extension version: 2.4.3
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.14393
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|24.00GB (15.78GB free)|
|Process Argv|--crash-reporter-id 5a19e7d5-8c31-4259-a5c9-ca2e69eb3cb0|
|Screen Reader|no|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
89544117:30613380
pythonsymbol12:30657548

```

</details>

**Comment by theflyingape** [comment]
Sure, it's server-side editing. I've rolled out proper %Developer access to the namespaces and assigned routine manager stored procedure and project tables in each eligible namespace.  Ensemble DevOps and ISC Studio.exe work as expected.  Unclear to me exactly when this started to occur, but I noticed new 'stuff' updated in Code and these extensions recently. 
`IRIS for UNIX (Red Hat Enterprise Linux for x86-64) 2021.1.2 (Build 338U) Tue Apr 12 2022 12:03:31 EDT`
**Audit Details:**
Description	/api/atelier/ login
Timestamp	2023-02-08 13:37:44.625
UTCTimestamp	2023-02-08 18:37:44.625
Event Source	%System
Event Type	%Login
Event	Login
Username	rxh59
Pid	448893
JobId	1543241766
JobNumber	38
IP Address	172.27.2.216
Executable	CSPap.so
System ID	lvhshcadd01g1:HCDEV
Index	3124239
Roles	%Developer,%DB_BILHHOSPITALS,%DB_ENSLIB,%DB_HSCUSTOM,%DB_LAHEYHEALTH,%DB_LAHEYHEALTHDATA,%DB_LAHEYHEALTHRTN,%EnsRole_Administrator,%EnsRole_Developer,%EnsRole_Operator,%EnsRole_RulesDeveloper,%EnsRole_WebDeveloper,%Operator,%DB_BILHSFTP,%DB_BILHWORKDAY
Authentication	Delegated
Namespace	%SYS
Routine	
User Info	
O/S Username	CSP Gateway
Status	
Event Data	Web Application: /api/atelier/
Login roles: %Developer,%DB_BILHHOSPITALS,%DB_ENSLIB,%DB_HSCUSTOM,%DB_LAHEYHEALTH,%DB_LAHEYHEALTHDATA,%DB_LAHEYHEALTHRTN,%EnsRole_Administrator,%EnsRole_Developer,%EnsRole_Operator,%EnsRole_RulesDeveloper,%EnsRole_WebDeveloper,%Operator,%DB_BILHSFTP,%DB_BILHWORKDAY
$I: |TCP|1972|448893
$P: |TCP|1972|448893
![image](https://user-images.githubusercontent.com/19166945/217622913-eb6baf03-abf8-476e-8d41-f8613abb6fd3.png)

**Comment by theflyingape** [comment]
It just occurred to me that this might be complicating matters in regards to "nothing changed" here, although I am editing on the source Namespace HSCUSTOM.  So, I tried deleting this %All package mapping, restarted VS Code, kept a copy of the class code in my paste buffer, deleted the AppRegistry.cls permanently, created a new class file under the same path which in turn gave me the empty class in the editor, I pasted the source code in it -- dramatic pause -- no joy, same error.
![image](https://user-images.githubusercontent.com/19166945/217627306-c23fa3ae-cf13-49d6-95e4-8160916a0aa6.png)

**Comment by isc-bsaviano** [comment]
@theflyingape Do you use the Language Server? If so, does the intellisense like hover and code completion work? If not, then this is probably the same issue as #1077. The newest version of this extension queries %Dictionary directly to see if a class is deployed before trying to save it instead of using the Atelier index API for performance reasons. If you can't select on %Dictionary then the query will fail. Executing this query in your namespace should fix it:

```sql
GRANT SELECT ON SCHEMA %Dictionary TO <USERNAME>
```

**Comment by theflyingape** [comment]
Ah, I do see the Language Server is failing until it crashes.  After your excellent suggestion, it works as expected now.  I'll add this requirement into our scripts.  Is this "corrected", or its security profile relaxed, in newer IRIS versions?
```
$ sudo irisdb

Node: lvhshcadd01g1, Instance: HCDEV

%SYS>zn "hscustom"

HSCUSTOM>do $SYSTEM.SQL.Shell()
SQL Command Line Shell
----------------------------------------------------

The command prefix is currently set to: <<nothing>>.
Enter <command>, 'q' to quit, '?' for help.
[SQL]HSCUSTOM>>GRANT SELECT ON SCHEMA %Dictionary TO %Developer;

ERROR #5540: SQLCODE: -25 Message:  Input (;) encountered after end of query^GRANT SELECT ON SCHEMA %Dictionary TO %Developer;
[SQL]HSCUSTOM>>GRANT SELECT ON SCHEMA %Dictionary TO %Developer
1.      GRANT SELECT ON SCHEMA %Dictionary TO %Developer

0 Rows Affected
statement prepare time(s)/globals/cmds/disk: 0.0069s/782/13215/0ms
          execute time(s)/globals/cmds/disk: 0.0002s/4/164/0ms
                          cached query class: %sqlcq.HSCUSTOM.cls2
---------------------------------------------------------------------------
[SQL]HSCUSTOM>>q
```

**Comment by isc-bsaviano** [comment]
@theflyingape In recent versions of IRIS (2022.2+, 2022.1.1+, 2021.1.3+) only `%Development` is required, not the SQL permissions.
