### ISSUE TITLE
isfs with project-based filter doesn't pick up packages, "others"

### ISSUE THREAD

**Issue by isc-tleavitt** [intersystems-community/vscode-objectscript#1084]
Steps to reproduce:
* Create a project via Studio with packages (e.g., right click the package and add to project), CSP files, and DFIs (under "Other") and save it
* Drill down to the project in Server Manager and choose to edit it

Expected behavior:
* Everything that shows up as part of the project in Studio is there

Actual behavior:
* Packages and DFIs (more generally, all "Other" types) are missing

$zv: 
IRIS for UNIX (Red Hat Enterprise Linux 7 for x86-64) 2022.1 (Build 209U) Tue May 31 2022 12:13:58 EDT

**Comment by isc-bsaviano** [comment]
@isc-tleavitt `PKG` entries are intentionally expanded so the containing classes are shown but the "other" files should be shown. I will try to reproduce.

**Comment by isc-tleavitt** [comment]
@isc-bsaviano my point is in part reusing projects already created via Studio. In my world (and I guess yours too), where we're using server-side source control with local development instances, it's super convenient to be able to define a project and source control it. Expanding PKG to be all constituent classes makes this more complicated because every time a new class in the package is created it must be added to the project. (So I'd rather if we could respect and leverage PKG entries.)

**Comment by isc-bsaviano** [comment]
@isc-tleavitt Sorry, I think I wasn't clear. VS Code don't change the actual ^oddPROJECT entry from `PKG` to a bunch of `CLS` entry. We just have the server tell us what classes in the package exist so we can show all of them. If you create a new class and it's package is already in your project, ^oddPROJECT will not be modified.

**Comment by isc-bsaviano** [comment]
@isc-tleavitt Please try the vsix found [here](https://github.com/intersystems-community/vscode-objectscript/suites/10909697004/artifacts/551191722) and let me know if it works for you.

**Comment by isc-tleavitt** [comment]
@isc-bsaviano that fixes the "other" file issue, but didn't fix the PKG issue.

**Comment by isc-tleavitt** [comment]
... which I forgot to explicitly mention in the issue description (facepalm)

**Comment by isc-tleavitt** [comment]
Specifically, in the project I sent you, there should be an AppS package and there isn't.

**Comment by isc-bsaviano** [comment]
Oh, I see now. You want the package to show up even if it's empty?

**Comment by isc-tleavitt** [comment]
@isc-bsaviano the package isn't empty.

**Comment by isc-bsaviano** [comment]
@isc-tleavitt Please try this one: https://github.com/intersystems-community/vscode-objectscript/suites/10911314838/artifacts/551319426

**Comment by isc-tleavitt** [comment]
@isc-bsaviano that does it - thank you!
