### ISSUE TITLE
Unable to debug methods with naming "xxx_xxx"

### ISSUE THREAD

**Issue by AlanCaballero** [intersystems-community/vscode-objectscript#1085]
Hello!
I'm trying to debug a method with the name "hello_world" and vsCode disables my breakpoints and doesn't stop at those lines. After execution, the breakpoints are enabled.
![image](https://user-images.githubusercontent.com/50097685/218120114-eadb3618-ae8f-42a1-abb4-b854ceaf3901.png)
![image](https://user-images.githubusercontent.com/50097685/218119953-5092a8f6-56c4-4ef3-ae1e-8cb6d6999878.png)
This is the "Copy invocation" output:
##class(Testing.DebugMethodName)."Hello_World"()

If I change the name to HelloWorld the debug works fine but the debug is running in another vsCode tab file.
Before debug:
![image](https://user-images.githubusercontent.com/50097685/218120527-d064aa09-5189-42d8-85ff-bc41e77f9dd1.png)
![image](https://user-images.githubusercontent.com/50097685/218123175-2f6b5af1-1690-4369-bad9-9383a8caa92d.png)

**Comment by AlanCaballero** [comment]
We have the same problem using the intersystems IRIS Studio
![image](https://user-images.githubusercontent.com/50097685/218125622-b673c8c9-3b8f-48b7-9c83-5fbee7ca3c40.png)

**Comment by AlanCaballero** [comment]
Hi Brett,
This is my IRIS version.
![image](https://user-images.githubusercontent.com/50097685/218129596-9adb8474-30f0-4e06-9624-8224243c177b.png)

Thanks for reviewing the issue so quickly.

**Comment by isc-bsaviano** [comment]
I think I can fix this in the extension by stripping the quotes from the method name before sending it to the server
