### ISSUE TITLE
code of conduct missing

### ISSUE THREAD

**Issue by kazamatzuri** [intersystems-community/vscode-objectscript#109]
We should define an unambiguous code of conduct for this repository, to avoid any discussions about inappropriate behaviour. 
For example https://opensource.guide/code-of-conduct/

**Comment by daimor** [comment]
How about this one: https://github.com/domgetter/NCoC

**Comment by kazamatzuri** [comment]
not having that might work for the most part, but since this is now a officially endorsed repository for InterSystems, everybody involved should know to keep their political and personal views out of this. The NCoC also doesn't really address the problem of ad-hominem attacks in discussions. 
As long as we're making sure that this keeps community keeps to be a welcoming forum for everybody, it should be fine. 
'We are all adults. Capable of having adult discussions.' is unfortunately not true for the whole population on github ;)

**Comment by zrml** [comment]
This [contributor covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/) looks interesting and at times has been adopted and adapted by other forums and languages.
HTH

**Comment by daimor** [comment]
done with #114
