### ISSUE TITLE
HTTP headers don't work correctly on the Debug REST Service if it contains uppercase letters.

### ISSUE THREAD

**Issue by iijimam** [intersystems-community/vscode-objectscript#1091]
When I set "Content-Type:application/json;charset=utf-8" in the HEADER, non-ascii characters in the BODY are garbled in the VALIABLES window.
![image](https://user-images.githubusercontent.com/26560156/218657804-d080734b-3829-48c5-a441-e91987d02fde.png)

![image](https://user-images.githubusercontent.com/26560156/218657759-2aeb5a2c-788e-4bef-85e7-d189ae540b17.png)

But I set all lowercase "content-type:application/json;charset=utf-8", I got correct view as follows:
![image](https://user-images.githubusercontent.com/26560156/218658012-56e9cb1d-ea62-4f25-ba22-dd70ccc19716.png)
![image](https://user-images.githubusercontent.com/26560156/218658076-2cf9ba06-8c68-4a41-83af-6ce00a47ad6a.png)

[Http headers are case insensitive.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers)

It's good for developers if we can write case insensitive in the HEADER of the Debug REST Service.

**Comment by isc-bsaviano** [comment]
@iijimam You're not supposed to set the Content-Type header manually if you have a body set. I can add the charset to all of the Content-Type headers that I add but it's my understanding that you aren't supposed to add it for application/* types.
