### ISSUE TITLE
Add a hot-key or command to Open "other" code upon an error message

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#1094]
E.g. here is the error:
<UNDEFINED>zOnPhase+79^%ZPM.PackageManager.Developer.Processor.Default.Document.1

Let's have a hot-key or command that will expect such line and open an editor window with this routine and on this line.
In one "click"

**Comment by isc-bsaviano** [comment]
@evshvarov I'm not sure I understand your request. Where is this error? Printed in the Output channel? If so, something similar already exists (via #609). Do you expect to type this in somewhere and have the file be automatically opened?

**Comment by evshvarov** [comment]
Yes, exactly - receive an error, e.g. in terminal or somewhere in the application. And have an option to type it in some input field and be travelled to the automatically opened routine and with cursor positioned to the line mentioned in the error message.

**Comment by gjsjohnmurray** [comment]
@evshvarov have you tried this extension?

https://marketplace.visualstudio.com/items?itemName=georgejames.gjlocate

**Comment by evshvarov** [comment]
@gjsjohnmurray Looks promising! 
Just've tried:
<img width="462" alt="Screenshot 2023-02-17 at 7 18 35 PM" src="https://user-images.githubusercontent.com/2781759/219693867-442ec798-8522-4344-94fb-460145007280.png">

**Comment by isc-bsaviano** [comment]
@evshvarov Can you try to VSIX found [here](https://github.com/intersystems-community/vscode-objectscript/suites/11050407322/artifacts/561552514) and let me know if this functionality is what you expected?
