### ISSUE TITLE
No connection with roleset that can't see %SYS

### ISSUE THREAD

**Issue by majortomL** [intersystems-community/vscode-objectscript#1096]
When trying to connect to a server with a user that does not have the privileges required to access, or even "see", the %SYS namespace, connection fails **immediately**, with an **instant** error message 

`This server does not have specified namespace '%SYS'. You must select one of the following: USER.`

Usually, with user that are able to see and use %SYS, we get a list of namespaces available to connect to, with the problematic case it goes straight to the error message and does not provide a dropdown list. %SYS was never specified in server settings or during attempts to connect.

**Comment by isc-bsaviano** [comment]
@majortomL Can you send me your connection settings for this workspace? is it `isfs` for a local workspace folder? Do you see this error right when the extension activates/you open your workspace, or after you try to set up a connection?

**Comment by majortomL** [comment]
hey @isc-bsaviano! This is a local workspace folder, could I send you the connection settings privately? The error occurs as soon as I start connecting either via "Toggle Connection" of the command palette or "Choose Server and Namespace" in the plugin's tab. I get prompted to choose the workspace folder and the host I want to connect to, then to enter the password for the user specified in my connection settings, then the error pops up.

**Comment by isc-bsaviano** [comment]
@majortomL Thanks for the info. No need to send the connection settings, I think I can locate the cause of the error from what you just gave me.

**Comment by isc-bsaviano** [comment]
@majortomL Actually, can you tell me if you have an `objectscript.conn` setting in your workspace or user settings, and if so what the value of their `ns` properties are?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray This is caused by #682. We should either add an argument to `serverInfo()` that disables the namespace check (on by default), or set the "default" namespace for these checks to USER instead.

**Comment by majortomL** [comment]
@isc-bsaviano I have no objectscript.conn, all my connections are configured via the `webServer, scheme, host, port` scheme.
