### ISSUE TITLE
Server-side search doesn't find results in view queries

### ISSUE THREAD

**Issue by dgonzalez-intersystems** [intersystems-community/vscode-objectscript#1100]
When using the Server-side search, no results are found for queries defined in view type classes (queries defined using the keyword ViewQuery), unless the class is open in the editor.

**Comment by isc-bsaviano** [comment]
@dgonzalez-intersystems Can you paste the text of a simple example class below please?

**Comment by dgonzalez-intersystems** [comment]
Sure @isc-bsaviano 

Class Test.PatientView [ ClassType = view, CompileAfter = Test.Patient, DdlAllowed, Owner = {_SYSTEM}, Not ProcedureBlock, SqlTableName = PatientView, ViewQuery = {
    select  GivenName, LastName, BirthDate from Test.Patient where Gender = 'female' } ]
{

}

And here there's the Persistent class used in the view
Class Test.Patient Extends %Persistent
{

Property GivenName As %String(MAXLEN = "");

Property LastName As %String(MAXLEN = "");

Property Gender As %String;

Property BirthDate As %Date;
}

**Comment by isc-bsaviano** [comment]
Thanks. And what specifically isn't being found? The SQL value of the ViewQuery keyword?

**Comment by dgonzalez-intersystems** [comment]
Indeed. I was looking for uses of a specific table (Test.Table in this case), and no results where found in view classes. Anyway, in case it could help, my feeling is that texts within square brackets [] are not found. For example, if you search for "Required", required properties in Persistent classes are not found either.

**Comment by isc-bsaviano** [comment]
@dgonzalez-intersystems I verified that you can find compiler keywords by name (i.e. searching for `CompileAfter` works). The bug in the extension is with keyword values that span multiple lines. I will fix it once #1045 is merged.

**Comment by dgonzalez-intersystems** [comment]
Just to confirm that I downloaded the latest release and it worked perfectly! Many thanks @isc-bsaviano !
