### ISSUE TITLE
Option "Multiline Method Args" appears to have no effect

### ISSUE THREAD

**Issue by isc-aray** [intersystems-community/vscode-objectscript#1108]
I have enabled the option "Multiline Method Args" in VSCode, but it seems to have no effect, as my method definitions are still collapsed onto a single line:

``` objectscript
Method GetCodeTables(
    tables As %List,
    scheme As %String,
    options As %DynamicObject = {{}},
    Output response As %Net.HttpResponse,
    Output json As %DynamicObject
) As %Status
{
    ; ...
}
```

still gets replaced when saved with:

``` objectscript
Method GetCodeTables(tables As %List, scheme As %String, options As %DynamicObject = {{}}, Output response As %Net.HttpResponse, Output json As %DynamicObject) As %Status
{
    ; ...
}
```

## Version info for VSCode:
Version: 1.75.1 (system setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.500.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044

## Version info for extensions:
InterSystems ObjectScript: v2.6.0
InterSystems Language Server: v2.3.1

## Version info for remote server
IRIS for UNIX (Red Hat Enterprise Linux 8 for x86-64) 2022.1 (Build 209_0_21889U) Mon Sep 19 2022 15:46:48

**Comment by isc-aray** [comment]
@isc-bsaviano I am using client-side editing.

**Comment by isc-bsaviano** [comment]
@isc-aray I can't reproduce this using client-side editing either. Here's exactly what I did:

1. Open a local folder.
2. Set `objectscript.multilineMethodArgs` to `true` in my user settings.
3. Export a class that contains a method with multiple args.
4. Observe that the export preserved the args on multiple lines.
5. Create a new method int he class with 3 args on the same line.
6. Save the class, which causes an import and compile.
7. Observe that both methods now have args on multiple lines.

How does this differ from your steps or configuration? Which level of your settings is `objectscript.multilineMethodArgs` set in?

**Comment by isc-aray** [comment]
Here are all my objectscript settings:

### User level
``` json
{
    "objectscript.serverSideEditing": false,
    "objectscript.autoPreviewXML": true,
    "objectscript.compileFlags": "bcuk",
    "objectscript.ignoreInstallServerManager": true,
    "objectscript.conn": {
        "password": "[REDACTED]",
        "username": "[REDACTED]",
        "active": true
    },
    "objectscript.export": {
        "folder": ".",
        "addCategory": true,
        "atelier": true,
        "generated": true,
        "filter": "",
        "category": "*",
        "noStorage": false,
        "dontExportIfNoChanges": false,
        "maxConcurrentConnections": 0
    },
    "objectscript.multilineMethodArgs": true
}
```

### Workspace-level settings
``` json
{
    "objectscript.conn": {
        "host": "[REDACTED]",
        "port": [REDACTED],
        "ns": "[REDACTED]",
        "active": true,
        "https": true
    },
    "objectscript.serverSideEditing": true,
    "objectscript.compileFlags": "buck"
}
```

**Comment by isc-bsaviano** [comment]
Ok, that matches where I have the `objectscript.multilineMethodArgs` setting. I still can't reproduce this. Can you provide a screen recording, or exact steps to reproduce?

**Comment by isc-aray** [comment]
Is it possible that another setting is conflicting?

**Comment by isc-aray** [comment]
It appears to be an issue with detecting the API version of the server. If I add `"objectscript.conn.apiVersion": 4` to my settings.json, it works.

**Comment by isc-bsaviano** [comment]
`apiVersion` is not part of the `objectscript.conn` spec so I'm not sure why that fixes the problem. I will try to fix the faulty check now.

**Comment by isc-aray** [comment]
Yes, I am aware it's not a documented setting; nevertheless, including such a line in settings.json fixes the problem. I assume it exists for developer testing purposes and this isn't some sort of magical coincidence.

**Comment by isc-bsaviano** [comment]
@isc-aray Can you download and install the vsix found [here](https://github.com/intersystems-community/vscode-objectscript/suites/11382854482/artifacts/585748533) and verify that it fixes your issue?

**Comment by isc-aray** [comment]
@isc-bsaviano Yes, that fixes the issue. Thank you.
