### ISSUE TITLE
auto formatting of {}.%FromJSON generates an error

### ISSUE THREAD

**Issue by spotashnyk** [intersystems-community/vscode-objectscript#111]
When compiling the following line of code the auto formatting of {}.%FromJSON() adds spacing in between the brackets and in-between the close bracket and punctuation mark.

Before Save
Set dynObject = {}.%FromJSON(tStream)
After Save
Set dynObject = { } .%FromJSON(tStream)

The code fails to compile.
ERROR #5475: Error compiling routine: Installer.jreport.1.  Errors:  ERROR: Installer.jreport.cls(LoadDefaultVar+13) #1026: Invalid command : '} .%FromJSON(tStream)' : Offset:24 [zLoadDefaultVar+7^Installer.jreport.1]

**Comment by MaxAbrahams** [comment]
i use this command a lot and i have not seen this behavior ;  perhaps there's another plugin trying to manage the spacing between braces?

![image](https://user-images.githubusercontent.com/11665665/80404355-10190f00-888f-11ea-990a-ccb3eabfe730.png)
