### ISSUE TITLE
Adopt `LogOutputChannel` API which finalized in VS Code 1.74

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1112]
See https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I think our current OutputChannel is sufficient. What does adopting this API do to improve what we have?

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano see https://github.com/microsoft/vscode/issues/176481 for a list of benefits.

**Comment by gjsjohnmurray** [comment]
OK, closing.
