### ISSUE TITLE
Consider removing `objectscript.serverSideEditing` setting

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#1115]
I think we should remove the `objectscript.serverSideEditing` configuration setting for the following reasons:

- Users will confuse it with [server-side editing mode](https://intersystems-community.github.io/vscode-objectscript/serverside/), leading to them using a sub-optimal workflow.
- The setting blurs the line between client-side and server-side editing. Having two supported editing paradigms is a major feature of this extension, but having this middle-ground setting makes documenting more difficult. It doesn't make sense conceptually to have the ObjectScript Explorer open editable server-side files when the workflow dictates that you should be exporting files to edit.
- Users who enable this setting may make edits that are not tracked by their client-side source control, leading to pain down the road as things don't work the same way on different systems. 

The only downside to removing this setting is that some existing users are using it, so their workflows may be disrupted. However, I think the benefits outweigh that temporary friction and that those users will be happier being firmly in one of the paradigms. 

@gjsjohnmurray @isc-rsingh @daimor What do you think?

**Comment by isc-rsingh** [comment]
I agree with your reasoning.

**Comment by gjsjohnmurray** [comment]
Makes good sense to me.
