### ISSUE TITLE
objectscript.export.filter and objectscript.export.mapped do not work when exporting classes in ObjectScript Explorer

### ISSUE THREAD

**Issue by miniclub** [intersystems-community/vscode-objectscript#1120]
I edited my settings.json as below and right-clicked on "Classes" folder in the ObjectScript explorer, then selected "Export".
But All classes were exported including Ens* and HS*, even though the 'exactFilter'  was 'Search%' and 'mapped' was false.

                {
                    "objectscript.export": {
                        "folder": "srctest2",
                        "addCategory": false,
                        "map": {},
                        "atelier": true,
                        "generated": false,
                        "filter": "",
                        "exactFilter": "Search%",
                        "category": "*",
                        "noStorage": false,
                        "dontExportIfNoChanges": false,
                        "maxConcurrentConnections": 0,
                        "mapped": false
                    }
                }
 
Regards,

**Comment by isc-bsaviano** [comment]
@miniclub The `objectscript.export` settings only affect the `ObjectScript: Export Code From Server` command. If you export a node from the ObjectScript Explorer, that node and all of its children will be exported.
