### ISSUE TITLE
Braces not correctly matched for expression-mode method returning %DynamicObject or XData block with MimeType application/json

### ISSUE THREAD

**Issue by isc-aray** [intersystems-community/vscode-objectscript#1122]
The syntax highlighter does not correctly match curly braces when JSON object syntax is introduced immediately following the start of a block. I am aware of two cases where this is valid:

* When an expression-mode method returns a %DynamicObject   
    ``` objectscript
    Class Example.WithExpressionMethod
    {
    
    Method DynamicObject() As %DynamicObject [ CodeMode = expression ]
    {
    {
        "test": "test"
    }
    }
    
    }
    ```
    ![image](https://user-images.githubusercontent.com/43610734/225694587-8dc41477-0aa6-4145-afcf-2a3e2509b4d5.png)

* When an XData block with MimeType application/json contains a top-level JSON object
    ``` objectscript
    Class Example.WithXData
    {
    
    XData JSON [ MimeType = application/json ]
    {
    {
        "test": "test"
    } 
    }

    }
    ```
    ![image](https://user-images.githubusercontent.com/43610734/225694503-c81c8540-785f-4cc4-906d-ce5e7efcbb05.png)

**Comment by isc-bsaviano** [comment]
@isc-aray The bracket matching colorization is a feature of VS Code core and not our extension. There is nothing we can do to fix or override it.
