### ISSUE TITLE
Syntax highlighting in for JSON and YAML within xdata blocks

### ISSUE THREAD

**Issue by spotashnyk** [intersystems-community/vscode-objectscript#113]
Syntax highlighting works fine within an xdata block when it contains xml.   

Add Syntax highlighting for JSON and YAML within an xdata block

**Comment by isc-bsaviano** [comment]
@spotashnyk  This feature is implemented in the Language Server so any issues related to it should be posted in that repository. @daimor This should probably be closed because it's out of scope for this extension.
