### ISSUE TITLE
Consider supporting Python when using Copy Invocation feature

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1132]
Way, way. back in August 2022, when the Copy Invocation feature was added (https://github.com/intersystems-community/vscode-objectscript/issues/974) I was wondering if we should try to support Embedded Python developers with the feature, based on the `[language = ]` attribute. I've decided to revisit this and make an **alternate** proposal, which does not involve the `[language = ]` attribute.

- Change “Copy Invocation” to “Copy ObjectScript Invocation” which would work the same as it does now, copying `##class(package.class).method(,,,)` to the clipboard (with the correct number of commas).
- Add another item “Copy Python Invocation” which would copy `iris.cls(‘package.class’).method(,,,)` to the clipboard.

Providing special features for ObjectScript and not Python undermines our support of Python developers (who also appreciate features that speed up development). I realize this adds clutter to the editor. Maybe someone else has a suggestion about that.

**Comment by isc-bsaviano** [comment]
@isc-solon Other than the clutter I don't mind this idea in theory but I don't think it's possible to implement accurately. We can't produce a Python expression to call a method without knowing the context that the user is going to paste it in. The user could have imported the `iris` python module using an alias, have only imported parts of it other than `cls`, or not imported it at all.

**Comment by isc-solon** [comment]
I didn't consider "import iris as ..." and until a few minutes ago I didn't know about "from iris import ... as ...". That's too bad. Unless someone else has an improved suggestion, I guess this is close-able.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano you might be able to use this proposed API to add metadata to the VS Code clipboard when copying the class method signature there, then use this metadata when pasting into a Python document in VS Code, massaging what gets inserted.

https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.documentPaste.d.ts

**Comment by gjsjohnmurray** [comment]
There's a sample demonstrating this API at https://github.com/microsoft/vscode-extension-samples/tree/main/document-paste
