### ISSUE TITLE
documatic link missing URLEncode

### ISSUE THREAD

**Issue by S-Hahne** [intersystems-community/vscode-objectscript#1139]
Hi,

Hopefully I've picked the correct project to add this issue to.
I've recently found that using VSCode with the ObjectScript extension, the links to documatic don't work as expected.

That's what VS Code shows when hovering over the link of a class definition
![grafik](https://user-images.githubusercontent.com/75479680/235098521-1c8ed909-ced2-4e72-8cf2-e6ab5ae2e0f5.png)

And when I click the link, the browser just shows a "400 Bad request" page.

Looking at the depicted link, it reads "[...]%CSP[...]" but % itself is the escape character for URLEncoding. So it needs to be replaced/enhanced to %25.
Adding the "25" to the URL, the expected documatic entry opens:
![grafik](https://user-images.githubusercontent.com/75479680/235100825-29b44e39-e530-4463-8a37-7bf9a2e5b774.png)

Is there a chance to get this fixed?
Seems to be a very little bug though but I'm not familiar with Extension coding.

Best regards,
Sebastian

**Comment by isc-bsaviano** [comment]
@S-Hahne This is a language server issue but yes, I can fix it.
