### ISSUE TITLE
 <Ctrl/Mouse pointer> stopped referencing the methods of another class

### ISSUE THREAD

**Issue by AlexeyM64** [intersystems-community/vscode-objectscript#1145]
Type: <b>Bug</b>

E.g., if AA.cls is inherited from A.cls, I expect referencing to A::methodA when it's called from AA using ".." (e.g. set sc=..methodA(x,...)) on mouse pointer + Ctrl.
The same story is with $$function^routineA calls from other routines but routineA.mac.
IRIS for Windows (x86-64) 2022.1.3 (Build 668U) Fri Apr 7 2023 12:37:55 EDT
P.S. I've noticed it soon after upgrading IRIS from 2021.1.1.

Extension version: 2.8.0
VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:48:08.683Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by isc-bsaviano** [comment]
@AlexeyM64 Are you sure your server connection is active? It sounds like you don't since the only features that are working are the ones that don't require the server connection.

**Comment by AlexeyM64** [comment]
Yes, I'm sure, as class or routine compilation works without any problem.

**Comment by isc-bsaviano** [comment]
@AlexeyM64 Can you use Wireshark or the web gateway's HTTP trace feature to capture the REST request and response that get sent when you hover the cursor over the method from the superclass? Just hover, don't press CTRL because that sends a second request.

**Comment by AlexeyM64** [comment]
Very strange:
- I've noticed POST request with some response in HTTP trace after hovering the cursor,
- then updated Chrome,
- and no longer see any requests, while other functions (compilation, etc) still provide them.

I see the similar picture in Wireshark: no packets on the cursor hover, some packets on compilation.

**Comment by isc-bsaviano** [comment]
@AlexeyM64 Do you have the Language Server installed, and is it active? If it's not then you won't see the POST /query packets. If it is, then maybe there's an error being reported somewhere. Do you see any errors in the `ObjectScript` or `InterSystems Language Server` Output channels?

**Comment by AlexeyM64** [comment]
Hi Brett,
It seems that I've found the reason of the issue.
Just noticed that all my servers use password authentication but the problematic one which used unauthenticated access. After adding the line to its definition in settings.json:
`            "username":"myUser", `
hovering starts working.
Before this small fix pop-up on the cursor hover didn't work even with local class methods.
It seems that IRIS 2022.1 is acting with server connections more strictly than 2021.1.
Thank you!

**Comment by isc-bsaviano** [comment]
@AlexeyM64 I'm glad you got this fixed! The Language Server does support unauthenticated access but your server may not have been configured properly for it.
