### ISSUE TITLE
Add Debug and Copy Invocation methods for Unittest methods

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#1147]
Currently unittests methods being methods of instance cannot be executed or debugged which could be very handy in understanding why the test method fails.

But there is a way to run unittest separately via the following method:
Do ##class(%UnitTest.Manager).DebugRunTestCase("", "[ClassName]", "", "[MethodName]")

Also let's add the options to debug.

[The related discussion](https://community.intersystems.com/post/unittests-intersystems-iris#comments0)

**Comment by gjsjohnmurray** [comment]
Instead let's focus on https://github.com/intersystems-community/intersystems-testingmanager

It has an open issue about debugging when using the client side paradigm, and the VSIX isn't yet published on Marketplace.

Pinging @isc-rsingh

**Comment by evshvarov** [comment]
Oh, wow!
Missed it somehow.
Why instead!
Let's do both :)

**Comment by isc-bsaviano** [comment]
I don't think we should do this. It requires that the `^UnitTestRoot` is set properly for the autoload feature to work so the user's test could fail to run despite the body of their method being correct.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray @daimor Unless either of you feel strongly about this I think we should close it

**Comment by gjsjohnmurray** [comment]
I agree. Let's close it.
