### ISSUE TITLE
Is debugging broken on IRIS 2021.1.3 ?

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1149]
I get this failure when trying to debug on 2021.1.3

![image](https://github.com/intersystems-community/vscode-objectscript/assets/6726799/13916487-087e-44bc-9611-dc5971c8b6bd)

I have tested on two different servers, and two different VS Code installations:
- IRIS for Windows (x86-64) 2021.1.3 (Build 389U) Wed Feb 15 2023 14:50:06 EST
- IRIS for UNIX (Ubuntu Server LTS for x86-64) 2021.1.3 (Build 389U) Wed Feb 15 2023 14:54:29 EST

The same VS Code instances can debug OK on 2022.1 and 2023.1

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray A security related change designed to harden access to the debug agent WebSocket inadvertently denied all access to the Atelier debug agent. This was included in 2022.2. Another change that partially rolled back the first was included in 2022.3. The first change must have made its way into the 2021 MR kit stream without the second one.

**Comment by isc-bsaviano** [comment]
Yes, I will try to get it fixed

**Comment by isc-bsaviano** [comment]
This will be fixed in the next CE maintenance kit (2018.1.9) but since maintenance kits are only provided for the last 2 EM releases (2022.1 and 2023.1) an adhoc or upgrade will be required to fix this for 2021.1.3 users.
