### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cristianojs** [intersystems-community/vscode-objectscript#115]
- Issue Type: `Performance`
- Extension Name: `vscode-objectscript`
- Extension Version: `0.8.5`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.2`

(https://github.com/intersystems-community/vscode-objectscript/files/4516050/daimor.vscode-objectscript-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by daimor** [comment]
I don't see any issues with CPU in these particular logs, which just only 5 seconds. And most of the time here in opening files.
Could you explain what you did when you got high CPU?

**Comment by gjsjohnmurray** [comment]
Closing in the absence of more information from @cristianojs
