### ISSUE TITLE
Hide "Debug this method"

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/vscode-objectscript#116]
VSCode:  1.44.2
ObjectScript: 0.8.5

Is there a way to hide/remove these links that are injected before every classmethod?

![image](https://user-images.githubusercontent.com/669176/80027308-29921380-84a9-11ea-81f2-9f66f02fd127.png)

**Comment by bourette** [comment]
"objectscript.debug.debugThisMethod": false,

**Comment by daimor** [comment]
yes, you can change this by setting `objectscript.debug.debugThisMethod` which is true by default. You can find more available settings, in VSCode, extensions view, open the extension description, and go there to Feature contribution tab

**Comment by mvhenderson** [comment]
Thanks
