### ISSUE TITLE
Docs at https://intersystems-community.github.io/vscode-objectscript/ don't display well on a mobile phone

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1160]
In my case, using Chrome on Android.

![Screenshot_20230601-101441](https://github.com/intersystems-community/vscode-objectscript/assets/6726799/a79b21f7-e673-4784-aa1c-63e7ea44029b)

**Comment by isc-rsingh** [comment]
Ouch that's bad. But I hesitate to fix it as this documentation is planned to migrate to ISC official docs soon but let me check on that status.

**Comment by isc-bsaviano** [comment]
The new official docs display well on my iPhone. Since we will migrating to them soon, I don't think this is worth fixing.
