### ISSUE TITLE
Debugger loses sync after Step Over (F10)

### ISSUE THREAD

**Issue by jpa95** [intersystems-community/vscode-objectscript#1169]
Hi,

for the last few weeks I have been having difficulties debugging ObjectScript in VsCode. Breakpoints work fine but if I Step over (F10), the debugger seems to disconnect. I can reproduce this 100% of the time, on the first F10 I do

I am using
- InterSystems 2022.1.2.574.0
- VsCode 1.79.2
- InterSystems Language Server v2.3.5
- InterSystems ObjectScript v2.8.1
- Intersystems Server Manager v3.2.2

Any tips welcome, Best Regards.

**Comment by isc-bsaviano** [comment]
Hi @jpa95, thanks for reporting this issue. I was able to reproduce it and will look into it now.

**Comment by isc-bsaviano** [comment]
@jpa95 I'm investigating the cause of this problem but I haven't found it yet. Do you know when this started happening, and what could have changed around that time? Maybe this was caused by a VS Code version update.

**Comment by jpa95** [comment]
Maybe the last month? I think there have been a couple of new VsCode versions in that timeframe. For my part there was no other change i can think of.

**Comment by isc-bsaviano** [comment]
I just downgraded to VS Code version 1.78.2 and stepping works, so something changed in version 1.79.0 that broke our debug adapter. I will need to figure out what that is.

**Comment by jpa95** [comment]
Indeed, must have been something else on my part. Please disregard the comment about DynamicObjects

**Comment by jpa95** [comment]
Thanks @isc-bsaviano!
