### ISSUE TITLE
Compilation errors explaination now missing (VSCode update ?)

### ISSUE THREAD

**Issue by GendronAC** [intersystems-community/vscode-objectscript#1172]
Running VSCode 1.79.2, IRIS 2023.1

![image](https://github.com/intersystems-community/vscode-objectscript/assets/45271725/8bb041c1-0192-4225-8ca2-db3b29cf2d78)

vs, in Studio : 

![image](https://github.com/intersystems-community/vscode-objectscript/assets/45271725/9c5ffa9d-bab6-4ad3-a774-98f3d5816d02)

I feel like this used to work.

**Comment by CraigRegester** [comment]
@isc-bsaviano Is there an adhoc or otherwise that interested parties can ask WRC to tag us on to address this bug?

**Comment by isc-bsaviano** [comment]
@CraigRegester The internal tracking number for the fix is DP-424221. AFAICT it will be in 2022.1.4, 2023.1.2 and 2023.3.
