### ISSUE TITLE
Code deletion without confirmation

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/vscode-objectscript#1175]
There's a reported issue on Ideas:
https://ideas.intersystems.com/ideas/DPI-I-392

**Comment by gjsjohnmurray** [comment]
I transferred this here because unless the person reporting it provides evidence to the contrary it's unlikely to relate to Server Manager.

**Comment by isc-bsaviano** [comment]
This is an issue with this extensuion. The ObjectScript Explorer `Delete` command only asks for confirmation if you're deleting more than one explorer node. I can change this to always ask.
