### ISSUE TITLE
Inability to log in to Show CCR Control Source Control

### ISSUE THREAD

**Issue by hbadian** [intersystems-community/vscode-objectscript#1177]
Hi,

I have been setting up VS Code to work in a new system. It mostly seems to work, but the one problem I am running into is that I cannot log in to the "Show CCR Control Source Control" web page.

I put in my correct username and password and it just takes me back to the username prompt again.

Thanks for the help.

Hugh

**Comment by hbadian** [comment]
Yes, that worked. Thanks for the quick reply. 
I had seen "Autodetect" being needed for other web apps, but not realized that this one also needs it.

This can be closed.

**Comment by isc-bsaviano** [comment]
Glad that worked!

**Comment by hbadian** [comment]
Brett,

By the way, the correct web app I needed to fix was /isc/studio/templates. I wasn’t sure if that is what you said.

Hugh
