### ISSUE TITLE
Import fails via external WebGateway: "file on server is newer"

### ISSUE THREAD

**Issue by S-Hahne** [intersystems-community/vscode-objectscript#1178]
Type: <b>Bug</b>

Dear community,

We are moving away from the IRIS private web server (PWS) for our IRIS environment.
The new gateway servers are based on the InterSystems-provided webgateway-nginx container and configured to use HTTPS encrypted connections. The /api/atelier path is configured with "CSP On;" to forward all requests to the IRIS server.
We're using server-side editing via the ObjectScript extension.

After configuring VS Code to use the external web gateway to access the IRIS server, we're getting errors when  trying to save (import) any class to the server with the following error:

"Failed to import 'Example.My.cls': The version of the file on the server is newer"
![grafik](https://github.com/intersystems-community/vscode-objectscript/assets/75479680/0832111b-cc37-49ea-b7bd-8a7d124fedd7)

We've tried this on a windows machine and my Ubuntu laptop. When clicking compare, the compare window opens in Windows. In Ubuntu it shows this error
![grafik](https://github.com/intersystems-community/vscode-objectscript/assets/75479680/308226fd-7a5d-4b81-ab77-7471bbef8775)
Perhaps that generates some ideas?

The outputs of ObjectScript, Main and Extension Host don't include any hint what exactly has failed. Thus I thought to ask here if anyone could shed any light on the mechanism that compares the server version against the local one prior to importing?
Probably something is still missing on the new web gateway (and not the ObjectScript extension) but to find the missing piece I need some help on the Extension internals.

Many thanks in advance for your help!!

Best regards,
Sebastian

Extension version: 2.8.2-beta.11
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:59:55.818Z)
OS version: Linux x64 5.19.0-46-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 4147)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.03GB (24.00GB free)|
|Process Argv|--unity-launch --enable-proposed-api intersystems-community.vscode-objectscript --enable-proposed-api georgejames.intersystems-serverdiff --crash-reporter-id d928b960-374c-41ed-9ac8-6bb637890344|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by S-Hahne** [comment]
I have modified the nginx config to write an access log.
Here is the excerpt from opening and saving the unmodified class:
![grafik](https://github.com/intersystems-community/vscode-objectscript/assets/75479680/7698aaad-7c5e-48cb-9ab7-4575778e5a3b)

I think the last entry is astonishing. Nginx returns 409 on the attempt to save the code to the server. But why should it if the class isn't changed?

**Comment by isc-bsaviano** [comment]
@S-Hahne Can you have nginx log the full requests and responses, including the headers and bodies? The PUT /doc/ endpoint uses a HTTP header to do timestamp checking so you don't overwrite newer changes. It's possible that header is getting stripped, so the server always thinks your version of the file is "old".
