### ISSUE TITLE
Issue with being asked to sign in

### ISSUE THREAD

**Issue by hbadian** [intersystems-community/vscode-objectscript#1188]
Hi,
We are having a problem with being asked to sign in all the time. Sometimes I am being asked to sign in 7 times when I first start.
Also, when I try to access a new system, it quickly skips past the Username prompt before I can type in there, and goes to Password assuming 'Undefined User'. We get the message "Not Authorized. Enter password to connect as user 'undefined' to ...(Namespace)" I think this may be related to a popup we are seeing that does not help us.
Please help us to understand how to eliminate these annoying signons and also avoid the Undefined User problem.
Thank you

**Comment by isc-bsaviano** [comment]
@hbadian Can you share your settings.json file please? Are you using the server manager extension to store your password securely?

**Comment by hbadian** [comment]
Hi Brett,
Sorry, I missed this yesterday.
Here is the settings.json file.
No, I have not figured out how to use the server manager extension to store the password securely.

Hugh

**Comment by isc-bsaviano** [comment]
I worked this out with Hugh internally
