### ISSUE TITLE
2.10.1-beta.1 release didn't happen

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1189]
Previously a release of, say v2.8.1 also triggered a proposed-API-enabled VSIX release v2.8.2-beta.1

That didn't happen when @isc-bsaviano published v2.10.0 just now.

Maybe this is a clue [(CI run 1449)](https://github.com/intersystems-community/vscode-objectscript/actions/runs/5613347686/job/15209266579):

![image](https://github.com/intersystems-community/vscode-objectscript/assets/6726799/05c62aa5-d10c-47ed-b9f3-512ccb6005f0)

**Comment by isc-bsaviano** [comment]
I noticed that. I wonder what that rule is coming from.

**Comment by isc-bsaviano** [comment]
Ok, I turned off the protection. I'll try to re-trigger it

**Comment by gjsjohnmurray** [comment]
If an attempt to retrigger seems risky perhaps create a PR that sets version to 2.10.1.beta-0 and see if that auto-increments to give a -beta.1 release.

**Comment by isc-bsaviano** [comment]
That still didn't trigger. John, can you try making a commit?

**Comment by gjsjohnmurray** [comment]
Working on it...

**Comment by gjsjohnmurray** [comment]
I made a small text change in package.json and pushed directly to upstream/master and this did the trick. But I don't like us not having the branch protection on master so I propose I reinstate it and we continue to investigate how to get the bump-after-release working as before. @isc-bsaviano is that OK with you?

Maybe @daimor has an idea about what broke. Our last change to the workflow script predates the 2.8.1 release that successfully produced 2.8.2-beta.1. I'm pretty sure our branch protection on master isn't that new either, which makes me think something changed in GH.

**Comment by isc-bsaviano** [comment]
Sure, I can reinstate the protection

**Comment by gjsjohnmurray** [comment]
Please also reinstate the checkmark to dismiss stale approvals.

**Comment by gjsjohnmurray** [comment]
Reopening so we don't lose sight of this. If we don't fix this by the time of the next release we'll need to disable branch protection temporarily again.

**Comment by gjsjohnmurray** [comment]
Interestingly the [CI for the Server Manager 3.4.0 release](https://github.com/intersystems-community/intersystems-servermanager/actions/runs/5646216539) just now successfully produced a 3.4.1-beta.1 release despite its repo having the same branch protection settings for master as this one.

The "Bypassed rule" message appeared

![image](https://github.com/intersystems-community/vscode-objectscript/assets/6726799/77e6ab28-d251-4688-820b-fda967711d6f)

and I now understand that it's telling us the CI was permitted to push direct to that repo's master despite the protection rule.

Reviewing this repo it's clear that the "auto bump version with release" push succeeded and updated package.json to contain 2.10.1-beta.1, but that push didn't trigger CI to create the corresponding release.

Either it was a one-off glitch or there's some other key difference between the workflows of this repo and the ones of the servermanager repo.

Let's see what happens when we do a 2.10.1 release in due course.

**Comment by gjsjohnmurray** [comment]
The 2.10.1 release just now correctly created 2.10.2-beta.1

Closing this.
