### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by ltjand** [intersystems-community/vscode-objectscript#1199]
Type: <b>Bug</b>

I tried to switch namespace on my dev server, and ever since, i have not been able to connect back to the server.  Here's the error:

"Failed to fetch a list of namespaces.  Check 'Objectscript' output channel for details.
Source: Intersystems ObjectScript (Extension)"

Service Unavailable
Check your server details in Settings (iris01-dev[SCANCODE]).

The server at iris01-dev.scanhealthplan.com:443 is unavailable. Check License Usage.

I can login to my server through management portal just fine, so it's not an issue w/ the server

Thank you

Extension version: 2.10.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (10.90GB free)|
|Process Argv|--crash-reporter-id 7d2841b2-426d-4ce1-81dd-0f8726e2c3ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
gsofa:30797621
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by isc-bsaviano** [comment]
@ltjand Can you log into the management portal and check your license usage? The extension only shows that error message when a REST request returns HTTP status code 503, which IRIS uses to signal that the request couldn't get a license.

**Comment by isc-bsaviano** [comment]
@ltjand I suggest you go the License Usage page of the management portal and see if you've used all of your license units recently. If yes, then that is what caused the connection failure. If not, then you should contact the WRC and tell them that the Atelier API was returning HTTP 503 even though you have license units available. They will have to help you with that because it's a possible issue with IRIS and not this extension. The extension is merely reporting what IRIS responded with.

**Comment by ltjand** [comment]
Ok, so you’re saying even though I can open iris via mgmt. portal, the license issue for atelier is separate from that?  Bc if that’s not the case then it doesn’t make sense that I can open as many instance via mgmt. portal, but not able to connect via vscode…

Is it possible that some settings got corrupted…?

**Comment by ltjand** [comment]
I tried deleting my user profile from iris, but that didn’t work… I am using AD login, btw…  I also tried logging out of vscode, and re-entering my AD psw.

I seem to be ok now, but since it had happened before, I thought I should try to find out if it’s something I am doing.  But if this doesn't ring a bell then you can close the case.  I will keep an eye on it and reopen if it happens again – maybe I can figure out a pattern…

Thanks,
Lena

**Comment by isc-bsaviano** [comment]
I'm not sure what AD authentication is, but if you see this happen again you can try to reproduce it outside of VS Code. You can make the same REST request that VS Code uses to check the connection from a browser. Just open a new tab and navigate to the /api/atelier/ path on your server (in this case, the url appears to be `https://ris01-dev.scanhealthplan.com:443/api/atelier/`). You will need to log in, and you can use the browser tools to investigate the network traffic and verify that you get the same 503 status code. You should then contact the WRC and mention that you were able to reproduce the issue outside of VS Code, so they know that there might be an IRIS issue. I hope that helps.
