### ISSUE TITLE
Server-side search don't work on extended class string

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1200]
Hi.
We recently noticed that searching for a string which is contained in a class "Extends" definition does not return any result.
In Studio everything is searchable; and anyway is useful to search every class that extends another one.

Below an example:
In Studio:
![immagine](https://github.com/intersystems-community/vscode-objectscript/assets/115481064/7da7988a-e414-40f8-aa58-d52158d25cf0)

In VS Code:
![immagine](https://github.com/intersystems-community/vscode-objectscript/assets/115481064/845bc31b-b98b-4275-bb68-e6ed1ef995ce)

**Comment by isc-bsaviano** [comment]
@gbertolottiKS What is the `$ZV` of your server? You can view all subclasses of a class in VS Code by right-clicking on the class name and selecting "show type hierarchy".

**Comment by isc-bsaviano** [comment]
@gbertolottiKS This was a bug in the extension. I opened a PR to fix it.
