### ISSUE TITLE
Class Called AT not showing

### ISSUE THREAD

**Issue by Sparkei** [intersystems-community/vscode-objectscript#1203]
Type: <b>Bug</b>

Create a class class called Component.Clinicom.Outbound.AT.cls (studio)
Try view the class in VS Code. 
Class is not visible
![image](https://github.com/intersystems-community/intersystems-servermanager/assets/72390562/6d81037e-e7b8-404a-9e54-bf29ad1de964)
![image](https://github.com/intersystems-community/intersystems-servermanager/assets/72390562/13e815bd-6191-4cfb-9b21-81c15c5bc181)

Extension version: 3.4.1
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.81GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 952c7ea7-2dbd-4a2e-bb38-b321d5c60a99|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by isc-bsaviano** [comment]
@Sparkei Can you send me the text of your `code-workspace` file?

**Comment by Sparkei** [comment]
Think i found the problem. 
Is 
?generated=1 needs added to "uri": "isfs://dev:srft/?generated=1"

You then though would need to alter the namespace if you don't want to view the .int files to exclude them (which can be done) . Would be useful (so more of a enhancement request rather than a bug) that classes that were created by generatedby appear by default in the vs code viewer.

**Comment by isc-bsaviano** [comment]
@Sparkei The class isn't showing up because generated documents are hidden by default. You cna show them by adding `?generated=1` to the end of your folder's URI, or by right-clicking on the workspace folder in the Explorer tree and seelcting the `Modify Server-side Workspace Folder...` option.

**Comment by isc-bsaviano** [comment]
Closing since this isn't a bug. I'm personally not in favor of showing generated documents by default. Generally you don't want to edit them and your folder will get very cluttered.

**Comment by Sparkei** [comment]
Thanks, just think it needs considered if a tree view is different in Studio and VS code and items you will see in namespace Classes view are not visible in studio by default then this will cause lots of questions about missing classes ect.
