### ISSUE TITLE
"Go to Definition" read-only

### ISSUE THREAD

**Issue by SaihttamR** [intersystems-community/vscode-objectscript#1212]
Sometime I need to edit my source control files in namespace %SYS. So I use "Go to Definition" (F12) and the file opens. 

Since version 2.10.0 is the file "... (read-only)".

I guess the newly removed setting "objectscript.serverSideEditing" is responsible for it - see #1163.

Would you confirm this? 
Is there or will come a new setting to control this behaviour?

**Comment by gjsjohnmurray** [comment]
Are you using the client-side editing paradigm in VS Code (i.e. editing your app code in local files which get automatically imported to a server namespace for compilation and execution)? Or are you using the server-side editing paradigm, editing directly in a server namespace, in the way you perhaps used to do with InterSystems Studio?

**Comment by SaihttamR** [comment]
I'm using the client-side editing.

**Comment by gjsjohnmurray** [comment]
If you also want to be able to edit your %-code server-side then I suggest you set up a multi-root workspace in which one root is your local folder and the other is an isfs connection to the %SYS namespace on your server.

I haven't tested whether a "Go to Definition" on a %-reference in one of your local files will then load the %-code editable or readonly, but it's worth trying. If it doesn't you' should still be able to open the %-code directly from the second root of your workspace (the isfs one).

**Comment by isc-bsaviano** [comment]
@SaihttamR If you're using source control in your client-side folder then I strongly recommend against editing any code on the server that you haven't exported there to be tracked. You could put yourself at risk of submitting incorrect or incomplete code if you have edits on the server that don't make it into your sour control system.

**Comment by isc-bsaviano** [comment]
Closing since we don't plan on supporting this workflow
