### ISSUE TITLE
Confusing duplicate CodeLenses at top of .mac or .int

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1213]
![image](https://github.com/intersystems-community/vscode-objectscript/assets/6726799/75ac9bf3-022e-4f23-8942-6f6a1e82495c)

I find this duplication confusing. The only justifications I can think of for the CodeLenses above line 1 are:

1. If the first line (2) of the actual code doesn't have a label there would be no convenient way to start debugging from the top of the routine.
2. The "Copy Invocation" on line 1 produces "^HelloWorld" whereas the one on line 2 produces "HelloWorld^HelloWorld"

In my experience the convention of labelling the first line of a routine to match the routine's name is universally followed. I suppose we could be smart, detecting the absence if a code-line 1 label and using that as a trigger for adding the "Debug" codelens to the preamble line.

We can apply the same logic to "Copy Invocation" on the preamble line. I doubt anyone will mind no longer having a way to get "^HelloWorld" onto the clipboard unprefixed by a label.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I agree that this is confusing. If the first non-empty and non-comment line is a label then we shouldn't show the line 1 CodeLenses. If you implement this I'll approve a PR
