### ISSUE TITLE
New server-side .cls file starts with a class stub that doesn't inherit

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1219]
When `New File...` is used from the title button or context menu of Explorer in an ISFS workspace the stub class created after the blank name field in the tree has been completed looks like this:
```objectscript
Class Hello.World
{

}
```
I propose changing it to:
```objectscript
Class Hello.World Extends %RegisteredObject
{

}
```

This makes it easier for the developer to set the inheritance they require, or to remove all inheritance (rarely done, IMO).

I'm proposing %RegisteredObject rather than %Persistent because the latter will create a storage definition and a SQL table as soon as it is compiled. I think it's better to require devs to opt in to persistence.

**Comment by isc-bsaviano** [comment]
Eh, I'm not sure this is necessary. The user is going to have to add their own inheritance logic anyways, so why try to guess what they want?

**Comment by isc-bsaviano** [comment]
Ok, sounds reasonable.
