### ISSUE TITLE
Filing .INT causes error and then it clears up

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#122]
I have a routine that has no problems in Cache Studio. When I file it in VSCode, I get:

Compilation started on 04/23/2020 13:18:22 with qualifiers 'cuk'
Compiling routine : UDRULE2.int
ERROR: UDRULE2.int(67) #1002: Invalid character in tag : ';' : Offset:1 [;^UDRULE2]
 TEXT: ;
Detected 1 errors during compilation in 0.004s.
ERROR #5475: Error compiling routine: UDRULE2.  Errors:  ERROR: UDRULE2.int(67) #1002: Invalid character in tag : ';' : Offset:1 [;^UDRULE2]

but... nothing is wrong with it? When I file again, the error goes away but this is after it's been reformatted.

I tried copying it in pieces to see if I could find the error, but each piece seems fine. I can't attach the routine here for legal reasons, but if you contact me, I can privately email it.

**Comment by daimor** [comment]
Hi, it's very interesting, could you please send it to me to mrdaimor@gmail.com, so, I'll try to investigate it?

**Comment by daimor** [comment]
So, I found the issue, which comes from reformatting, it around line 67, when it places `;` with the same indention as closing brace, so, without any spaces.
I'll fix it later.

**Comment by RyszardWithAZ** [comment]
Very good, thank you!
