### ISSUE TITLE
Import files edited locally ERROR #5865

### ISSUE THREAD

**Issue by persa26** [intersystems-community/vscode-objectscript#1223]
When I import a local file and compile it, I get error 5865 indicating that the file is not checked out from version control.

What I have is create a new window, and there export all the files I have on the server of the project I work with it, edit them and save.
When saving it seems like it tries to import them but it can't do it because I don't have them in check out.

I think the only way would be to manually check out the file I want to edit and then import it, but it is very tedious.

Maybe there is another more efficient way to work?

Thanks!

Extension version: 2.10.1
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621

**Comment by isc-bsaviano** [comment]
@persa26 If you're using server-side source control then you need to use [server-side editing](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_ssworkflow). The extension intentionally doesn't support firing source control hooks for local copies of files. You should only be exporting your files if you're using client-side editing like Git directly through your OS.

**Comment by persa26** [comment]
Ok, thank you very much for the clarification.

I will use server-side instead of trying the other one and if we ever move to git I will use client-side.
