### ISSUE TITLE
MAC routines inside a pkg not shown in project workspacefolder

### ISSUE THREAD

**Issue by Nemesis1990** [intersystems-community/vscode-objectscript#1224]
Hi,

we have a MAC-Routine inside a Pkg e.g. Test.Testheimer.mac.
We currently working with serverside editing. When we use the whole namespace as workspace-folder the mac-files are shown. But when we create a project, add the file to the project, the file is not shown in the workspace folder. The explorer only shows the folder where the mac should be. 

I searched for a bit inside the sources. I found out that in src/utils/FileProviderUtil.ts is a Query that transforms the name:

```typescript
const nameCol =
 "CASE WHEN Type = 'CSP' OR Type = 'DIR' THEN $PIECE(Name,'/') " +
        "WHEN (Type != 'CSP' AND Type != 'DIR' AND $LENGTH(Name,'.') > 2 AND UPPER($PIECE(Name,'.',$LENGTH(Name,'.'))) != 'DFI') " +
        "OR Type = 'CLS' OR Type = 'PKG' THEN $PIECE(Name,'.') ELSE Name END";
```

The Result for that Routine is:
| Name | Type|
|---|---|
| Test  | MAC  |

Excluding MAC in the 2nd part of the case gives the expected result:

```typescript
const nameCol =
 "CASE WHEN Type = 'CSP' OR Type = 'DIR' THEN $PIECE(Name,'/') " +
        "WHEN (Type != 'CSP' AND Type != 'DIR' AND Type != 'MAC' AND $LENGTH(Name,'.') > 2 AND UPPER($PIECE(Name,'.',$LENGTH(Name,'.'))) != 'DFI') " +
        "OR Type = 'CLS' OR Type = 'PKG' THEN $PIECE(Name,'.') ELSE Name END";
```
| Name | Type|
|---|---|
| Test.Testheimer.mac  | MAC  |

Extension Version: v2.10.2
VSCode Version: 1.81.1

Thanks in advance

**Comment by isc-bsaviano** [comment]
@Nemesis1990 This is indeed a bug, but your proposal isn't the bets solution. We want to split the dot in the routine name into a folder. I will take a look at this.

**Comment by Nemesis1990** [comment]
@isc-bsaviano indeed. I modified the query in the extension.js and the routine wasn't in a folder after that. It was shown in the root folder as Test.Testheimer.mac and not as Test/Testheimer.mac
Anyways. Thanks for looking into that :)

**Comment by isc-bsaviano** [comment]
@Nemesis1990 Can you download and install this [vsix](https://github.com/intersystems-community/vscode-objectscript/suites/15652575910/artifacts/893423764) and let me know if it fixes you bug? It works for me in my tests.

**Comment by Nemesis1990** [comment]
@isc-bsaviano It's working for me as expected. Folders with .mac inside

**Comment by isc-bsaviano** [comment]
Thanks for checking @Nemesis1990!
