### ISSUE TITLE
Why does this plugin automatically alter the contents of my cls files?

### ISSUE THREAD

**Issue by hsyhhssyy** [intersystems-community/vscode-objectscript#1233]
Whenever I drag a cls file from the File Explorer into the Project Folder in VSCode, or drag a cls file from one project folder to another, it automatically changes the content of my files, attempting to replace the package and class name, even if my directory isn't a Server directory. I haven't found any setting to control this behavior.

Specifically, some other software, like JReport, also use cls as an extension. This creates an issue when I try to drag such files into the project directory; they get overwritten, forcing me to manually copy them using the File Explorer.

I understand the initial intent behind this feature is to manage namespaces through the local folder structure, similar to many Java IDEs. However, even those IDEs display a warning or prompt instead of silently altering user files when they are located in an incorrect directory.

Also, during my work, I often need to modify only a part of the same file across multiple environments (while keeping other parts different). I frequently keep multiple versions of the same file in the same project directory, as illustrated below. In such cases, this drag-and-drop file renaming becomes quite inconvenient.

![image](https://github.com/intersystems-community/vscode-objectscript/assets/5977110/d2862015-7d66-425b-bdb4-7a45ecd032e0)

So, I'd appreciate it if you could add a toggle for this feature. That way, I could turn it off if I don't require it. 
(Furthermore, if possible, consider implementing a select option that allows different levels of behavior, including auto-modification, red highlighting, issuing a warning, or completely ignoring it.)

**Comment by isc-bsaviano** [comment]
@hsyhhssyy Juts to clarify, are you copying files within the File Explorer, or are you copying in files from your OS's file explorer into the VS Code window?

I will look into making this behavior toggleable, but I also wanted to explain why our extension behaves this way. This extension tries to be flexible w.r.t. a user's local folder structure, but it makes some assumptions that in most cases help it improve the user experience:

1. You are currently connected or will at some point connect to an InterSystems server for intellisense/compilation etc.
2. Your InterSystems file names are mappable to your folder structure (for example, A.B.cls -> <workspace_root>/src/A/B.cls or something similar).
3. Your `objectscript.export` settings match your folder structure (this is used to perform the mapping described in 2).

Assumptions 2 and 3 don't hold up for your workspace, and I assume 1 doesn't as well. This isn't a bad thing, and we want our extension to work well for our developers regardless of how they like to work. I thought it would be useful to have our assumptions posted somewhere public in the event other people come to this issue in the future.

As for other `.cls` files being overwritten, that would be resolved by a future toggle setting for this feature. VS Code itself does a good job of determining which extensions should act on which files but it some cases we only have the URI available when trying to perform an operation so we can't differentiate between different "types" of `.cls` files.

**Comment by hsyhhssyy** [comment]
@isc-bsaviano 

I have tested the following scenarios, all of which result in modifications to the content of the class file (changing PackageName and ClassName):

1. Copy a file in VSCode's Explorer by pressing Ctrl+C and then paste it into another folder using Ctrl+V.
2. Drag a file with a .cls extension from the Windows File Explorer and drop it into a folder in VSCode's Explorer.
3. In VSCode's Explorer, hold down Ctrl and drag a file with a .cls extension using the left mouse button, then drop it into another folder in VSCode's Explorer to create a duplicate of the file.

Additionally, there is a bug in scenario 3:

When you hold Ctrl and drag a file with the left mouse button to copy it to another directory in VSCode's Explorer, if the target directory already contains a file with the same name, VSCode will automatically rename the dragged file to "OriginalName copy.cls" and automatically open it. Because the file content is automatically modified, a syntax error is generated due to the "[space]copy" part in the filename. Normally, the parent folder should display a red highlight. However, if you delete the file in VSCode's Explorer by pressing Delete quick enough before the red highlight appears, the file will be deleted, but the red highlight still shows up. This causes the folder to be marked in red and this cannot be cleared unless VSCode is restarted.

**Comment by isc-bsaviano** [comment]
@hsyhhssyy Thanks for the additional information. That bug you identified in scenario 3 is an issue in VS Code core, so please report that on the [VS Code GitHub repo](https://github.com/microsoft/vscode/issues).

**Comment by isc-bsaviano** [comment]
Hi @hsyhhssyy, can you please download the vsix [here](https://github.com/intersystems-community/vscode-objectscript/suites/17315801574/artifacts/989311048) and let me know if it addresses your concerns?

**Comment by hsyhhssyy** [comment]
I'm not entirely sure if there's a specific setting I need to adjust or if I've missed something, but this plugin has only partially addressed my concerns.

Previously, when I opened a file via ObjectScript: Explorer and hit Ctrl+S to save, the ClassName and Package would be automatically altered upon saving to the disk. I gave it a try just now, and this no longer seems to be the case. However, I'm not certain whether the change is due to this update since I haven't used this function in quite a while. As a result of this past issue, my workflow for backing up files from the Server involved: 1) Opening in ObjectScript: Explorer. 2) Copying all the content. 3) Closing the file window. 4) Creating a new file in my local Workspace. 5) Opening the new file, removing the pre-generated content, and pasting everything from the clipboard.

I've also noticed that when I now create a new file in VSCode: Explorer, it doesn't automatically populate with a basic Class structure code. Personally, this works well for me since my directory structure doesn't reflect a Package, and I often have to delete the auto-generated code. However, I'm not sure how other users might feel about this change.

**Comment by hsyhhssyy** [comment]
Nevertheless, the issue I pointed out directly in the Issue section remains unaddressed. Specifically:
1) When dragging a file with a .cls extension from the Windows Operating System's File Explorer into the VSCode's File Explorer, the file content is still automatically cleared, similar to the original behavior.

https://github.com/intersystems-community/vscode-objectscript/assets/5977110/7a777a0c-0e15-45ff-bbeb-273196810026


2) When copying a Class file from one folder to another, either by holding down Ctrl to drag and copy or by using the copy-paste function, the ClassName of the file still gets modified, just like before.

https://github.com/intersystems-community/vscode-objectscript/assets/5977110/9c43796b-1be0-44be-9e8f-004df0b7afbb


https://github.com/intersystems-community/vscode-objectscript/assets/5977110/1ad67388-3757-4bec-9ac8-40b0f7689e00

**Comment by hsyhhssyy** [comment]
Moreover, I've stumbled upon a new bug. When I open two files with the same name and close one of them, deleting the closed file from the disk triggers a peculiar dialog box. Clicking "Overwrite" in the dialog doesn't seem to do anything, whereas selecting "CloseEditor" inadvertently closes the active tab.

https://github.com/intersystems-community/vscode-objectscript/assets/5977110/b6375877-d520-4c64-a161-fa94890526e4

**Comment by gjsjohnmurray** [comment]
This got closed automatically when I approved and subsequently merged the PR that @isc-bsaviano requested approval for, because the PR had been marked as closing this issue.

The beta VSIX containing those fixes is now available at https://github.com/intersystems-community/vscode-objectscript/releases/tag/v2.10.4-beta.7

Please install this and re-test, then open fresh issues for any problems that remain. Ideally create one per issue unless the symptoms you are reporting are very closely related. Thanks.
