### ISSUE TITLE
Remove some snippets

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1234]
Creating a new regular class file automatically creates the "Class package.class Extends %RegisteredObject" text. Also: "New File" (when connected to an interoperability namespace) presents the options:
* Business Operation
* Business Service
* Business Process
* Business Rule
* Data Transformation

Given that, should we remove the following snippets since they're not really needed anymore? It would reduce some clutter for code completion suggestions.
* Class definition without superclass
* Class definition with one superclass
* Class definition with multiple superclasses
* Business service
* Business process
* Business process BPL
* Business operation

**Comment by isc-bsaviano** [comment]
@isc-rsingh @gjsjohnmurray I'm all for de-cluttering so this sounds desirable to me. What do you think?

**Comment by gjsjohnmurray** [comment]
I agree.

**Comment by isc-solon** [comment]
I guess I coulda/shoulda done this. You guys are so fast! :-)

**Comment by PhilipStrohschein** [comment]
Maybe you want to adjust your tutorial as well - this was pretty confusing to me: https://learning.intersystems.com/course/view.php?id=1768
