### ISSUE TITLE
Interop wizard does not create correct classname on Windows

### ISSUE THREAD

**Issue by marceldenouden** [intersystems-community/vscode-objectscript#1240]
If I create a new class in VSCode, and then delete the contents because I want to use the "interop" keyword to create a more useful framework for me, the name is normally automatically created on my Mac. However, working on Windows it produces an incorrect classname which contains the whole filename:

/// Description
Class C:\InterSystems\Training\src\Test.MyProd Extends Ens.Production
{ ...

See also 
https://community.intersystems.com/post/vscode-interop

It seems consistent on Windows machines, Mac seems to have no problem with this.

Thanks,
Marcel

**Comment by isc-bsaviano** [comment]
@marceldenouden What are your `objectscript.export` settings in this workspace and the one that works on Mac?

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I can repro this, and I think the diagnosis at https://community.intersystems.com/post/vscode-interop#comment-235236 is correct. The regex needs to cater for backslash path-separators as well as forward-slash ones.

**Comment by isc-bsaviano** [comment]
Thanks for digging that up @gjsjohnmurray!

**Comment by isc-bsaviano** [comment]
Just opened a PR #1241. I don't have a Windows machine handy right now so I'd appreciate it if one of you could test the [dev VSIX](https://github.com/intersystems-community/vscode-objectscript/suites/16617123093/artifacts/949352247) before it gets merged. Thanks!

**Comment by gjsjohnmurray** [comment]
@marceldenouden please download [this zip](https://github.com/intersystems-community/vscode-objectscript/suites/16621580560/artifacts/949629385), extract the VSIX and drop it onto the Extensions view in VS Code on Windows. You will be prompted to reload. After doing that please test the fix. Assuming it works please also test the same dev VSIX on your Mac to verify we didn't break it there.

**Comment by marceldenouden** [comment]
I will test today and let you know the result!

**Comment by marceldenouden** [comment]
@gjsjohnmurray Tested on Windows and it works! Also tested in on the Mac and it doesn't break anything.

**Comment by gjsjohnmurray** [comment]
@marceldenouden thanks for confirming. This is now merged and available in the VSIX asset on https://github.com/intersystems-community/vscode-objectscript/releases/tag/v2.10.4-beta.2
