### ISSUE TITLE
Improve performance of export thousands source files

### ISSUE THREAD

**Issue by tobiasrdm** [intersystems-community/vscode-objectscript#1242]
From VSCode, we can use the ObjectScript Explorer to navigate on the server, right-click on the category (Classes, Routines, etc), and select Export. This export all files to the workspace folder.

However, when we have thousands of files (plus of 3 thousands), is very slow to export all. Takes several hours.

Analyzing the file [export.ts#L117](https://github.com/intersystems-community/vscode-objectscript/blob/v2.10.3/src/commands/export.ts#L117), I observe that it use [GetDoc](https://docs.intersystems.com/irisforhealthlatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSCF_ref#GSCF_ref_getdoc) `api.getDoc(name)`, getting one file at a time.

One suggestion to improve performance, is use [GetDocs](https://docs.intersystems.com/irisforhealthlatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSCF_ref#GSCF_ref_getdocs) to get multiple files at the same time with a single request.

**Comment by isc-bsaviano** [comment]
@tobiasrdm I'm not sure why you'd want to export thousands of files using VS Code. Using getDocs() would save on request overhead, but trying to transfer the text of thousands of files in one request would likely your web server to time out the request, or throw a "maximum body size reached" error. VS Code is development tool; the extension's code (and the server APIs) were not designed to operate on that scale. I suggest you write a ClassMethod that you call from the terminal that performs the export for you. You can use the [StudioOpenDialog query](https://docs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?LIBRARY=%25SYS&CLASSNAME=%25Library.RoutineMgr#StudioOpenDialog) from %Library.RoutineMgr to get the list of files to export, and  [$SYSTEM.OBJ.ExportUDL()](https://docs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?LIBRARY=%25SYS&CLASSNAME=%25SYSTEM.OBJ#ExportUDL) to export each file.

**Comment by tobiasrdm** [comment]
Ok, @isc-bsaviano . Thanks for the answer.

**Comment by isc-bsaviano** [comment]
@tobiasrdm Sorry for the disappointing answer. Here's a simple ClassMethod that will export all non-system and non-generated classes and routines into the instance's temp directory in UDL format (so they can be edited by VS Code). It splits dotted file names into folders. 

```
ClassMethod ExportClassesRoutines() As %Status
{
    #Dim tSC As %Status = $$$OK
    #Dim tEx As %Exception.AbstractException
    #Dim tPc As %ProcedureContext
    #Dim tRs As %SQL.ClassQueryResultSet

    Try {
        Set tSeparator = $CASE($$$isWINDOWS,1:"\",:"/"), tFolder = ##class(%SYS.System).TempDirectory()
        Set tStmt = ##class(%SQL.Statement).%New()
        Set tSC = tStmt.%PrepareClassQuery("%Library.RoutineMgr","StudioOpenDialog")
        If $$$ISERR(tSC) Quit
        Set tPc = tStmt.%Execute("*.cls,*.mac,*.int,*.inc",1,1,0,1,0,0)
        If tPc.%SQLCODE < 0 {
            Throw ##class(%Exception.SQL).CreateFromSQLCODE(tPc.%SQLCODE,tPc.%Message)
        }
        Set tRs = tPc.%NextResult(), tExportErrs = $$$OK
        While tRs.%Next(.tSC) {
            Set tDocName = tRs.%GetData(1), tFileName = tFolder_tSeparator_$TRANSLATE($PIECE(tDocName,".",1,*-1),".",tSeparator)_"."_$PIECE(tDocName,".",*)
            Try {
                Set tExportSC = $SYSTEM.OBJ.ExportUDL(tDocName,tFileName)
            } Catch tEx {
                Set tExportSS = tEx.AsStatus()
            }
            If $$$ISERR(tExportSC) Set tExportErrs = $$$ADDSC(tExportErrs,tExportSC)
        }
        If $$$ISERR(tSC) Set tSC = $$$ADDSC(tExportErrs,tSC)
        If $$$ISOK(tSC), $$$ISERR(tExportErrs) Set tSC = tExportErrs
    } Catch tEx {
        Set tSC = tEx.AsStatus()
    }

    Return tSC
}
```

**Comment by tobiasrdm** [comment]
Thank you very much, @isc-bsaviano.

**Comment by isc-bsaviano** [comment]
No problem, happy I could help in some way. I'm going to close this now but feel free to ping me again if you questions about the code I gave you.
