### ISSUE TITLE
Having a } in a string breaks brace matching

### ISSUE THREAD

**Issue by rwuttke** [intersystems-community/vscode-objectscript#1244]
If a line of code has a } in a string, it appears to affect the rendering is VSCode with respect to brace matching, also note the parenthesis have the incorrect colour as per all other parentheses.

![image](https://github.com/intersystems-community/vscode-objectscript/assets/2321176/5799ebb1-33ad-4962-af73-5c055560b8f5)

This shows the incorrect brace matching, if I change the "}" to $c(125), the brace matching will be corrected and the parenthesis will have the correct colour

![image](https://github.com/intersystems-community/vscode-objectscript/assets/2321176/7bfb2d70-3a01-4f43-8f56-32cd19cdd881)

With either a large block of code or a small viewport, it would be easy to lose track of your position and attach an else block to the incorrect level embedded statements.

VSCode Version
Version: 1.82.3 (user setup)
Commit: fdb98833154679dbaa7af67a5a29fe19e55c2b73
Date: 2023-10-02T10:51:22.294Z
Electron: 25.8.1
ElectronBuildId: 24153832
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

IRIS Version
IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2023.2 (Build 227U) Mon Jul 31 2023 18:04:28 EDT

Plugins:
ISC Objectscript Extension Pack: 1.0.3
ISC Language Server: 2.3.6
ISC ObjectScript: 2.10.3
ISC Server Manager: 3.4.2

**Comment by isc-bsaviano** [comment]
Hi @rwuttke, the bracket coloring is a feature of VS Code core and extensions can't modify its behavior. I suggest you post this issue on [VS Code's GitHub repository](https://github.com/microsoft/vscode/issues) and maybe they can help you.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/149552 is probably what we need.

**Comment by isc-bsaviano** [comment]
Closing since this isn't a bug in this extension
