### ISSUE TITLE
Interop wizard missing some components (BS, BP, BO)

### ISSUE THREAD

**Issue by marceldenouden** [intersystems-community/vscode-objectscript#1247]
In the versions after 2.2 some components are missing, see attachments. Only production and Req/Resp are available

![Interop-v2-14](https://github.com/intersystems-community/vscode-objectscript/assets/29229521/59baeae7-32db-4d57-9f66-19e4dbfbf52c)
![Interop-v2-2](https://github.com/intersystems-community/vscode-objectscript/assets/29229521/032e9fac-42d4-46e9-ab88-c02c5419b6c8)

Regards,
Marcel

**Comment by isc-bsaviano** [comment]
@marceldenouden Those snippets were redundant, so we got rid of them. You can create new Interoperability classes interactively from the File -> New File... menu.

**Comment by marceldenouden** [comment]
Ah OK. Thanks!
