### ISSUE TITLE
WSDL Wizard, create classes in %SYS namespace

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/vscode-objectscript#1249]
When using the WSDL Wizard introduce in v2.10.3.

The classe are generated in `%SYS` namespace, not in the current namespace.

**Comment by grongierisc** [comment]
settings.json used : 

```json
{
    "files.associations": {
        "iris.script": "objectscript"
      },
    "objectscript.conn" :{
      "ns": "USER",
      "active": true,
      "username": "SuperUser",
      "password": "***",
      "docker-compose": {
        "service": "iris",
        "internalPort": 52773
      }
    }

}
```

**Comment by isc-bsaviano** [comment]
@grongierisc What folders do you have open in your workspace? The extension uses the server connection for the open document if you have one, or else it falls back to the connection for the first folder in the workspace. This isn't unique to that menu option or even the Server Actions menu, it's a pretty common pattern.

**Comment by gjsjohnmurray** [comment]
@grongierisc when the wizard page opens in your web browser, what username and namespace does it display in the right-hand end of its banner header?

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I think this line needs changing:

https://github.com/intersystems-community/vscode-objectscript/blob/9c52efdece98be3eeb8e1962dca1a63ec97517e0/src/commands/serverActions.ts#L254

to become:

```
vscode.Uri.parse(`${serverUrl}${addin.id}?Namespace=${nsEncoded}&CSPCHD=${token}`)
```

It seems that templates/add-ins based on %ZEN.Template.studioTemplate (as %ZEN.Template.AddInWizard.SOAPWizard is) need to have the target namespace passed to their first page in queryparam `Namespace`, not `$NAMESPACE`.

Shall I prepare a PR?

**Comment by isc-bsaviano** [comment]
Sure, thanks John!

**Comment by grongierisc** [comment]
@gjsjohnmurray this vsix this the issue on my environment

**Comment by gjsjohnmurray** [comment]
@grongierisc thanks for verifying. The fix is now present in https://github.com/intersystems-community/vscode-objectscript/releases/tag/v2.10.4-beta.5

@isc-bsaviano can we publish v2.10.4 next week? If yes, do you want to do it or shall I?
