### ISSUE TITLE
Format ObjectScript code with indent

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/vscode-objectscript#1254]
Is it possible in the format module to add indent for "For","While","If": 

Example

From
```objectscript
for value = "Red","Green","Blue" {
write value, !
}
```

To
```objectscript
For value = "Red","Green","Blue" {
   Write value, !
}
```

**Comment by isc-bsaviano** [comment]
@grongierisc Formatting is handled by the Language Server extension. Regardless, I'm not sure we want to get into the business of messing with indents. VS Code does a pretty good job of carrying over the correct indent when you hit Enter. I think that users' indenting style varies pretty widely (for example, some people might want your example on a single line). @gjsjohnmurray What do you think?

**Comment by isc-solon** [comment]
I don't understand this, I must be missing something. When I type:

`For I = 1:1:10 {`

and press Return, VS Code changes it to this:
`For I = 1:1:10 {`
`    `
` }`

with the cursor indented.

**Comment by isc-bsaviano** [comment]
@isc-solon I think the request is for having the formatter adjust the indent of code that's already written.

**Comment by isc-bsaviano** [comment]
I'm going to move this to the Language Server repository and put it on the backlog there.
