### ISSUE TITLE
VSCode Plugin Clears File Content When Copying

### ISSUE THREAD

**Issue by hsyhhssyy** [intersystems-community/vscode-objectscript#1256]
As previously mentioned in Issue #1233 , the latest version v2.10.4-beta.7 still exhibits the following issues related to the 'Copy' action:

**Case 1**: When dragging a file with a .cls extension from the Windows Operating System's File Explorer into VSCode's File Explorer, the file's content is automatically cleared. I expect the file to remain untouched and its content unchanged.

![ExplorerDrag](https://github.com/intersystems-community/vscode-objectscript/assets/5977110/f4f3b74b-e677-4909-b709-ab35bfa18031)

**Case 2**: When dragging copy a file (drag while holding Ctrl key) with a .cls extension from one folder in the VSCode File Explorer to another folder, the file's content is automatically cleared. Again, I expect the file to remain untouched and its content unchanged.

![CtrlDrag](https://github.com/intersystems-community/vscode-objectscript/assets/5977110/1079ac39-6c15-4ccd-ac97-ad55b0fe07dd)

**Case 3**: When I perform the COPY command (either using Ctrl+C or the Copy menu item) and paste it into the VSCode File Explorer, the file's content is automatically cleared. As with the previous cases, I expect the file to remain untouched and its content to be preserved.

![CopyPaster](https://github.com/intersystems-community/vscode-objectscript/assets/5977110/252a2869-a472-4b3c-9a9f-6d979faa2bf0)

Are the behaviors described above intentional or are they bugs?

**Comment by isc-bsaviano** [comment]
@hsyhhssyy Sorryb for not responding on your previous issue, I was on vacation. I will try to reproduce this now.

**Comment by isc-bsaviano** [comment]
I was not able to reproduce the "file clearing" bug in any of your three cases using version 2.10.3 (the latest released version) on my Mac. I will try to use a Windows machine in case this is Windows-specific.

**Comment by hsyhhssyy** [comment]
Upon further investigation, it appears that the behavior of this case might be influenced by the specific environment you're connecting to. Depending on whether or not a connection to a server is established, and whether this class is present on that server, the plugin may exhibit varied behaviors. I'll attempt to recreate this in a more controlled environment, like a new VM, to better understand the underlying issue.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I think it's significant that in the screen recording the top line of the input file begins with lowercase "class", which the following line will not detect:

https://github.com/intersystems-community/vscode-objectscript/blob/44e35752be6bbc1b513ac8e3dc3043a84118a5b2/src/providers/FileSystemProvider/FileSystemProvider.ts#L48)

**Comment by isc-bsaviano** [comment]
Good catch, John. I didn't notice that. Let's make that check case-insensitive and see if that fixes this issue.

**Comment by gjsjohnmurray** [comment]
Perhaps after the while loop we should add this (untested) so we transfer sourceLines verbatim in cases where no class header line is found:

```ts
if (!content.length) {
  content.push(...preamble);
}
```

**Comment by isc-bsaviano** [comment]
Yes, that seems desirable too, at least for non-ISFS folders.

**Comment by gjsjohnmurray** [comment]
Can I leave you to create the PR, since it was your work originally?

**Comment by isc-bsaviano** [comment]
Yes, I'll have that done soon.
