### ISSUE TITLE
I can't find the Jump to Tag+Offset feature

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1259]
https://github.com/intersystems-community/vscode-objectscript/pull/351

Was it removed? Command palette search doesn't show anything. Clicking current line number allows you to pick line number only, no tag.

**Comment by isc-bsaviano** [comment]
@isc-solon It's still there! You need to have a routine open and click the `[tag]+offset^routine` entry in the bottom status bar:

<img width="859" alt="Screenshot 2023-10-26 at 12 39 43 PM" src="https://github.com/intersystems-community/vscode-objectscript/assets/44776135/ab717d1b-a639-495c-84c8-1113eb795df2">

**Comment by isc-solon** [comment]
I see it now. Why didn't I notice that entry until you pointed it out? Probably my cursor was not inside the routine itself. Thanks!
