### ISSUE TITLE
Search option on the server side

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/vscode-objectscript#126]
Is it possible to have search option on the server side ?

API :
localhost:57772/api/atelier/v2/:namespace/action/search

**Comment by daimor** [comment]
Unfortunately, not [everything is finished](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Asearch+label%3Aapi-finalization) on VSCode side, to make it easier in use.
It is already implemented here in some way, but not not publicly available, yet.

**Comment by gjsjohnmurray** [comment]
@grongierisc if you want to try server-side searching, here's how:

1. Install VS Code Insiders
2. In it, install the beta VSIX from https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.8.9-beta.9
3. Follow [these instructions](https://github.com/intersystems-community/vscode-objectscript/pull/270#issuecomment-674080534) to make Insiders able to give our extension the proposed APIs.
4. Use a workspace with an isfs:// type folder.

**Comment by gjsjohnmurray** [comment]
Starting with 0.9.3-beta.2 you will now see this in the ObjectScript output channel as confirmation you've configured things right to get proposed APIs.
```
intersystems-community.vscode-objectscript version 0.9.3-beta.2 activating with proposed APIs available.
```

**Comment by copperschnack** [comment]
Thanks @gjsjohnmurray - Unfortunately, I see no output on `ObjectScript `output channel. Neither when just using `argv.json` setting, nor when additionally providing the directive via command line. (I do not run VS Code insiders with elevated privileges).

![image](https://user-images.githubusercontent.com/14861913/93080658-5cbe8480-f68e-11ea-8d5b-6e3c726b9108.png)

**Comment by daimor** [comment]
you should use `intersystems-community.vscode-objectscript`  instead of `daimor.vscode-objectscript`

**Comment by copperschnack** [comment]
@daimor - well seen! I was using the previous id from https://github.com/intersystems-community/vscode-objectscript/pull/270#issuecomment-674080534. Search is working now :-)

Thank you!

**Comment by gjsjohnmurray** [comment]
@copperschnack it seems you don't actually need to be using Insiders to make this work. I have updated my previous comment above.

**Comment by copperschnack** [comment]
@gjsjohnmurray - very right and even better!

**Comment by copperschnack** [comment]
@gjsjohnmurray in extension intersystems-community.vscode-objectscript v1.0.5 the server side search seems not to be working. Although enabled in argv.json, the following is not showing up in the "ObjectScript" output channel:

`intersystems-community.vscode-objectscript version X.X.X activating with proposed APIs available.`

**Comment by daimor** [comment]
@copperschnack this feature not allowed in public releases, and available only with betas.
https://github.com/intersystems-community/vscode-objectscript#enable-proposed-apis

**Comment by copperschnack** [comment]
@daimor - check, thanks!

**Comment by gjsjohnmurray** [comment]
Available if workaround is used to enable proposed APIs. See README.

**Comment by gbertolottiKS** [comment]
Hi,
I'm getting these errors while trying to use the server-side search:
![immagine](https://user-images.githubusercontent.com/115481064/204774672-658678aa-cdd3-4c18-a821-2b4d53ae4644.png)
I've followed these instructions: https://github.com/intersystems-community/vscode-objectscript#enable-proposed-apis
