### ISSUE TITLE
Unable to Create New Class in 2.10.4

### ISSUE THREAD

**Issue by isc-jsmith** [intersystems-community/vscode-objectscript#1265]
Type: <b>Bug</b>

Since upgrading to 2.10.4 I can no longer create a new class when using server side editing. I right click on the "Classes" folder in my workspace and enter the class name including the extension. When I press enter, I get the following error appear:
```Unable to write file 'isfs://scratch:user/zJES.Test.cls?filter=*.cls' (Unavailable (FileSystemError): ERROR #5002: ObjectScript error: <UNDEFINED>GetMetaDataFromDocArray+4^%apiSRC *pTextArray(0))```
All environments are running $zv = IRIS for UNIX (Red Hat Enterprise Linux 8 for x86-64) 2022.1 (Build 209_0_22408U) Tue Apr 25 2023 15:55:01 EDT

This issue no longer occurs if I roll back to the previous version.

Extension version: 2.10.3
VS Code version: Code 1.84.0 (Universal) (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:30:19.406Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Bisect indicates it broke in [2.10.4-beta.7](https://github.com/intersystems-community/vscode-objectscript/releases/tag/v2.10.4-beta.7) which was PR #1253

**Comment by gjsjohnmurray** [comment]
@isc-jsmith please the zip at download https://github.com/intersystems-community/vscode-objectscript/suites/17846995663/artifacts/1023894920, extract the dev VSIX, install it and verify the fix.

**Comment by isc-jsmith** [comment]
> @isc-jsmith please the zip at download https://github.com/intersystems-community/vscode-objectscript/suites/17846995663/artifacts/1023894920, extract the dev VSIX, install it and verify the fix.

Done. Looks good. I can create a new class and save it.

**Comment by gjsjohnmurray** [comment]
Thanks for verifying. We have published 2.10.5 to resolve this.
