### ISSUE TITLE
Update link to Compile flags documentation

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1271]
Type: <b>Feature Request</b>

In the Compile Flags Settings, the link to the documentation is: RCOS_vsystem#RCOS_vsystem_flags_qualifiers
It should be changed to: RCOS_vsystem_flags_qualifiers

Extension version: 2.10.5
VS Code version: Code 1.84.1 (Universal) (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:37:18.666Z)
OS version: Darwin arm64 22.6.0
Modes:

**Comment by isc-bsaviano** [comment]
@isc-solon I silently fixed this as part of #1269, so I'm going to link that PR to this issue instead of opening a new one for this one-line change
