### ISSUE TITLE
debug terminal does not display all output from class

### ISSUE THREAD

**Issue by ltjand** [intersystems-community/vscode-objectscript#1273]
Type: <b>Bug</b>

when passing a json object to a recursive function, it does not 'write' all output to the debug console.  It works when the class method is run from intersystems terminal, but does not seem to work from vscode

Extension version: 2.10.5
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (11.00GB free)|
|Process Argv|--crash-reporter-id 7d2841b2-426d-4ce1-81dd-0f8726e2c3ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30880073
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2cf:30871583
pyreplss2:30886141
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30886110
dsvsc017cf:30886113
dsvsc018cf:30886115
aa_t_chat:30882232

```

</details>

**Comment by isc-bsaviano** [comment]
@ltjand Can you paste an example ClassMethod that I can use to reproduce your issue?

**Comment by ltjand** [comment]
Hi @Brett ***@***.***>, please see attached code and sample file.

Thanks,
Lena

**Comment by isc-bsaviano** [comment]
Hi @ltjand, you need to use the GitHub website to attach files to your comment. Files attached via email aren't attached to the issue. You cna do that my dragging your .zip file into the text box with your comment befroe you click "comment". Thanks!

**Comment by ltjand** [comment]
I uploaded the files

**Comment by isc-bsaviano** [comment]
@ltjand I ran your test method on the test JSON you gave me and everything looks fine to me. I got a bunch of console output and the debugger started and stopped normally. Here's a gif of what I did:

![output](https://github.com/intersystems-community/vscode-objectscript/assets/44776135/86573f5b-6f80-45ad-b445-a1b572a36945)

**Comment by ltjand** [comment]
I uploaded my .gif – as you can see, the debugger doesn’t complete, and the output is stopped – not always at the same place…

**Comment by isc-bsaviano** [comment]
@ltjand What's your IRIS version? Also, can you update your VS Code? It shouldn't matter for this case but it's always good to be on the lets version. You're almost a year behind. Can you follow the steps listed [here](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_debug#GVSCO_debug_troubleshoot) to get a trace of the communication between the VS Code debugger and the server? That may tell us what is going wrong.

**Comment by ltjand** [comment]
Hi @Brett ***@***.***>, I thought I was running 1.80.1, but it seemed I still have the older version installed.  I tried it w/ 1.80.1, and that seem to work!
So, you can close this.

Thank you,
Lena

**Comment by isc-bsaviano** [comment]
I'm glad that worked! The most recent VS Code version is 1.84.2.

**Comment by ltjand** [comment]
Thank you.  Will try it out.

**Comment by ltjand** [comment]
I installed the extension, but I am a little confused… I thought I can search a server side method and it will take me to the class file that the method is in, but doesn’t seem to be working…  isn’t this what it’s supposed to do?

Ex, I search, “DeletePackage” in ctrl-shft-f, and it doesn’t return anything.

It’s supposed to be in the file: HS.FHIRServer.Config.RestHandler

-L

**Comment by isc-bsaviano** [comment]
Yes, searching for text in a server-side class using ctrl-shift-f should work. Did you reload VS Code after installing extension version 2.10.6-beta.1? VS Code should have prompted you to do that but if you didn't then the old version of the extension is still active.

**Comment by ltjand** [comment]
Yes, I did reload, and got the message in output window as it indicated:
intersystems-community.vscode-objectscript version 2.10.6-beta.1 activating with proposed APIs available.

**Comment by isc-bsaviano** [comment]
Ok, I'll see if I can reproduce your problem. Can you tell me your server version please? The searching code is different for newer versions (2023.1+)

**Comment by ltjand** [comment]
IRIS for Windows (x86-64) 2023.1 (Build 229U) Fri Apr 14 2023 17:17:41 EDT [Health:5.1.0]

Do you want me to create a new report?

**Comment by isc-bsaviano** [comment]
Thanks! It's ok, I'll create a new issue if I can reproduce the searching problem. I am off tomorrow though so I may not respond until Friday.

**Comment by ltjand** [comment]
Ok, thx

**Comment by ltjand** [comment]
Thanks for the update!
