### ISSUE TITLE
Work with objectscriptQuality

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1274]
Hi.
I find useful to use the objectscriptQuality plugin, to catch some errors while writing.
But it seems it works only in local mode: when I asked the maintainer if it was possible to make it work also server-side, he said that it's out of scope, and that it would require [some integration with main InterSystems extension](https://github.com/litesolutions/objectscriptquality-vscode/issues/5#issuecomment-1377698606).

Can something be done about it?

Thanks in advance,
Giacomo

**Comment by gbertolottiKS** [comment]
Hi, thanks for your reply!
I like the highlights of some common bad practice or quality issue, so a larger set of what Language Server already checks
Basically, the ObjectScript sonarLint rules are what I have in mind.
Giacomo

**Comment by isc-bsaviano** [comment]
@gbertolottiKS Are there any specific rules that you think we should implement in the Language Server? It looks like there's [a lot of them](https://objectscriptquality.com/docs/objectscriptquality-release/rules).

**Comment by gbertolottiKS** [comment]
Yeah, I know.
Maybe we can filter by the smell level: can we start with "blocking" and "critical" ones?
Would be VERY useful if a rule could be disabled/re-enabled by hand

**Comment by isc-bsaviano** [comment]
@gbertolottiKS I don't think any of those rules are a must-add, but I can reconsider some specific ones that you find really valuable.
