### ISSUE TITLE
With multiple new or changed classes unsaved, "Save All" compiles and loads at most one class.

### ISSUE THREAD

**Issue by jmarkmorris** [intersystems-community/vscode-objectscript#128]
I made multiple simple classes (hello world simplicity) a.cls, b.cls, c.cls, d.cls. With all of these classes new or changed and unsaved in separate tabs, when I click on the "Save All" icon then at most one of the classes is compiled and loaded into IRIS. All four change to "Saved" state though.

**Comment by daimor** [comment]
Can't reproduce, looks like maybe fixed in VSCode itself. Could you update to the latest version and try to reproduce again?

**Comment by jmarkmorris** [comment]
Verified that this is no longer an issue. Thank you.
