### ISSUE TITLE
webSocketTerminal: add support for home + end keys in line recall 

### ISSUE THREAD

**Issue by EnricoParisi** [intersystems-community/vscode-objectscript#1281]
I'm using/testing the new webSocketTerminal and I noticed that when I use the line recall (up arrow key) the home and end keys are not implemented when editing a line.
Looking at the code, cursor home (Move the cursor to the beginning of the line) is mapped to ctrl+A.
Interestingly cursor end (Move the cursor to the end of the line) is ctrl+E in webSocketTerminal, however in my default installation of vscode (Windows) ctrl+E trigger the vscode search file.

Implementing home + end keys should be trivial, the corresponding keys are:
home: "\x1b\x5b\x48"
end: "\x1b\x5b\x46"

Then is just a matter to add two additional "case:" in addition to keys.ctrlA and keys.ctrlE.

**Comment by isc-bsaviano** [comment]
@EnricoParisi Thanks for trying this feature out! I like this suggestion.
