### ISSUE TITLE
Add OS command execution to webSocketTerminal

### ISSUE THREAD

**Issue by EnricoParisi** [intersystems-community/vscode-objectscript#1282]
[TerminalAgent.cls.txt](https://github.com/intersystems-community/vscode-objectscript/files/13625024/TerminalAgent.cls.txt)
As you may have noticed I'm testing and using the new webSocketTerminal and I think it's a great improvement to vscode ObjecScript.
I think that one useful functionality is missing, the the ability to run Operating System (Linux or Windows) commands.
Having the ability do run simple OS commands directly from webSocketTerminal would be a big advantage.
Using "normal" IRIS terminal, be it Windows IRIS console, Windows Telnet or within "iris session" in linux, running OS commands is simple, from the IRIS terminal prompt just precede the OS command with "$" or "!".

Running OS commands from IRIS code is not difficult, so I had a look to the backend code (%Atelier.v7.TerminalAgent.cls) and realized that could be easily implemented (hacked?) there without any change in the vscode extension.

I attach a modified version (from 2023.3 Build 254) of %Atelier.v7.TerminalAgent.cls that implement OS command execution.
If anyone what to test it, after loading the modified class to the backend IRIS system, from the webSocketTerminal OS commands can be run just typing "!" or "$" before the command, like "!dir" or "!ls -la".

Again this is just an hack, nevertheless it works for simple OS commands.

P.S.: I know that the backend classes, while being tightly related, are not part of this project, but I think that this is the right place to ask for this enhancement.

**Comment by isc-bsaviano** [comment]
@EnricoParisi Thanks for the suggestion! I'm not sure that this is worth adding. VS Code's UI for having multiple terminals open is great, so I'd rather users lean on that. 

@isc-rsingh What do you think?
