### ISSUE TITLE
webSocketTerminal : del key does not erase (last) first char when editing a command line

### ISSUE THREAD

**Issue by EnricoParisi** [intersystems-community/vscode-objectscript#1284]
In webSocketTerminal, if I type a command, then press the home key and use/press the del key to erase all characters, the last character is (visually) not deleted.

My guess is that the issue is in line 377:
this._hideCursorWrite(actions.cursorForward + actions.deleteChar + actions.cursorBack);

I think it should be:
this._hideCursorWrite(actions.deleteChar);

Not critical, but worth fixing it.

**Comment by isc-bsaviano** [comment]
Thanks for pointing this out @EnricoParisi
