### ISSUE TITLE
Server-side (isfs) search ignores Context Lines feature of Search Editor

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1286]
Type: <b>Bug</b>

1. Be using a beta version of the extension, with proposed APIs enabled.
2. Use Server Manager to create a workspace giving isfs access to a namespace.
3. Click 'Search' in Activity Bar and perform a search that returnes some results. in the Side Bar .
4. Click the 'Open in editor' link alongside the search counts.
5. In the Search Editor tab that appears, make sure the 'Toggle Context Lines' button at the right-hand end of the search field line is selected nand that the adjacent number field contains a positive integer.

:bug: no context lines are displayed.

The fault is that this function ignores `options.beforeContext` and `options.afterContext`.

https://github.com/intersystems-community/vscode-objectscript/blob/66f0f37e156eda4bde4831c846db9f458f29813b/src/providers/FileSystemProvider/TextSearchProvider.ts#L307-L308

Extension version: 2.10.6-dev.1270
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray The descriptions of those options are poor IMO. How are consumers of this API supposed to task those into account? It's not clear from the .d.ts file
