### ISSUE TITLE
Performance improvement for exporting/importing files from Server to File system

### ISSUE THREAD

**Issue by svetozarstojkovic** [intersystems-community/vscode-objectscript#1288]
I really like what you guys are doing here with VSCode, it's light years ahead of Studio but there are some performance improvements that would be necessary so our app moves to use this.

First one would be through this ticket and that is performance improvement for import/export function.
We have around 11k of files to be moved back and forth with Studio and FileSystem, and at the moment it takes us around 5m 30s to export everything from Studio.

Possible improvements:
1. We check last modified date, if it's before last export we don't need to export it to FileSystem, we only focus on the remaining one.
2. Second level of improvement would be to make it async, each file for itself, since they are not dependent on eachother.

Thanks in advance, if you need any info please ping me so we can use this in the future.

Regards,
Svetozar

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic Thanks for the feedback! Can you please provide some more details on your workflow? How are you performing the export, and why do you need to export 11k files often? See #1242 for a similar request.

**Comment by svetozarstojkovic** [comment]
@isc-bsaviano Thanks for writing back to me... We are using custom external tool that pulls everything from Server to FileSystem in some specific way and all the people are using that approach except for me so I need to use that tool first to pick everything up from directory that is working with version control and then puts it to Server, then I pull everything down to different directory where I connected VSCode to.

If we solve these two issues that I wrote about we might migrate to VSCode.

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic Thanks for the quick response. Why not open VS Code in the directory with the initial server export and edit the files there? If you can't do that, why do you need to re-export all of the files to another directory to use VS Code? If you're not using source control on your file system you can edit the files directly on the server like Studio (called [server-side editing](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_ssworkflow) in VS Code).

**Comment by svetozarstojkovic** [comment]
@isc-bsaviano this full export is only for transition period, later we would only be using import function once we change branch or pull new code to FileSystem, so we can sync files to server.

Regarding Server Side Editing, I noticed that search trough all the files (Ctrl + Shift + F) doesn't work. :/

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic Server-side find in files does work, but it requires a special version of the extension due to a VS Code limitation that we hope will be lifted soon. [Here](https://github.com/intersystems-community/vscode-objectscript#enable-proposed-apis) are the directions to get that working. If the large import/exports are just transitional, I suggest you use the terminal to perform them instead of VS Code. That will perform much better. The VS Code import/export features are for development use so you can get your changes on a server for testing and intellisense. VS Code is not the best tool for moving code between servers.

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic I'm going to close this because I think it's the same request as the previous issue, but feel free to re-open if you think I'm missing something.
