### ISSUE TITLE
Global export/import to/from FileSystems

### ISSUE THREAD

**Issue by svetozarstojkovic** [intersystems-community/vscode-objectscript#1289]
Second request would be to add an option to use the same logic to globals like we are using for .cls and .mac files.

We have some globals that should go through version control so this option would be amazing to have.

Thanks in advance,
Svetozar

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic Can you elaborate on what the functionality would look like? You can't export globals using the Atelier API so this can't be added easily.

**Comment by gjsjohnmurray** [comment]
@svetozarstojkovic in case you don't already know, the Deltanji source control tool can handle globals (or subtrees of globals) as source control artefacts (we call them components) in exactly the same way as it handles .cls, .mac, .inc and dozens of other types, including host filesystem files.

https://georgejames.com/deltanji/

**Comment by svetozarstojkovic** [comment]
@isc-bsaviano Hello, the idea here is to extend Import/Export function with a list of specific globals. Our use case is that we have ~20 developers at this point and our application relies on globals as well, it would be great if we could make them presentable as `global_name.gbl` as a file in the file system.

**Comment by isc-bsaviano** [comment]
The server-side Atelier REST API doesn't support getting an XML representation of a global, so this isn't possible without some significant server-side work. I'm not sure we'd even want to support editing globals as files. I understand that there's a need for them to be in source control, but projecting globals to files for editing is something that would be entirely new for ISC.

@isc-rsingh This requires more discussion.

**Comment by isc-rsingh** [comment]
I think of globals as being data. There are certainly many use cases where you would want to version small bits of data, but these are different use cases than versioning code. @svetozarstojkovic without more details on how you use globals in this case I can't tell if it would make sense to transition to a code-based strategy, but I agree with @isc-bsaviano this isn't a small project if done right.

**Comment by svetozarstojkovic** [comment]
@isc-bsaviano @isc-rsingh @gjsjohnmurray  thank you guys, so far we will start testing how it behaves when using Server Side Editing, later we might transition to use your tool as it is, but keep our custom solution just for exporting/importing globals.

We will see later how this project advances and decide at what capacity to transition to it.

Thank you all for your involvement,
Svetozar

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic Do you mind elaborating on why this feature is a blocker in your migration from Studio? Studio doesn't allow you to edit globals either. VS Code with server-side editing should be a drop-in replacement for Studio in your workflow with minimal friction. We have a [documentation page](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_fromstudio) that covers migrating from Studio that you may find helpful.

**Comment by svetozarstojkovic** [comment]
@isc-bsaviano So far we are using Studio Plugin which is used for this purpose, it has an option to move .cls, .mac and .gbl to files and from files to server. Through time we orginized our logic around it.

If we eliminate Studio from the equation we are losing that plugin and would need to figure out a better solution...

**Comment by isc-bsaviano** [comment]
Is your Studio plugin [a subclass of `%Studio.Extension.Base`](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=ASC#ASC_Hooks_creating_and_activating_sc_class), or are you using some other Studio extensibility feature? I'd like to learn more about what your team is doing so I can provide better advice.

**Comment by svetozarstojkovic** [comment]
@isc-bsaviano Hey, sorry for late reply... 
We have a custom solution that is running outside of Server Side Version Control, it's a separate plugin that is handling .mac, .cls and specific .gbl and copying them to files when we run the plugin.

But anyway even if this new solution is still far away I managed to extract that logic from that plugin so it can be called from "Run and Debug" in VS Code and we can us ServerSideEditing in VSCode... except for one thing...

You can tell me if I need to create another issue for this, namely, is it possible to use "read" command from Debug Console somehow, when I am using InterSystems terminal it works fine for both "write" and "read"  commands, but when I am running in Debug Console and have "read" command in code I cannot read a command from console and code just hangs forever on that line.

Thanks in advance,
Svetozar

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic That's interesting. How do you invoke your plugin in Studio? Since it sounds like you're just running some ObjectScript commands, why not adapt your plugin to be a class that extends `%Studio.Extension.Base` so it can be easily used by Studio and VS Code users?

To answer your question, the best way to run ObjectScript commands from VS Code is using the [WebSocket Terminal](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_debug#GVSCO_debug_websocket). It does require that your connected server be version 2023.2 or newer though. If you don't have that, [this community article](https://community.intersystems.com/post/accessing-iris-terminal-comprehensive-guide-visual-studio-code-users) may help.

**Comment by isc-lindensc** [comment]
Another idea, that is used ISC internally , is to define the persistent class as XML enabled, then use XML projection to export changes to a global into a source control tree as an xml file. ISC ChangeControlRecord (CCR) Tier2 is essentially based on this.
