### ISSUE TITLE
Not all routines being shown in explorer

### ISSUE THREAD

**Issue by Fobiwan** [intersystems-community/vscode-objectscript#1295]
Might be duplicate of #1226 and #712

IRIS for Windows (x86-64) 2023.3 (Build 254U) Wed Nov 8 2023 13:17:47 EST

VSCodium Version 1.85.1

Only some routines in the namespace are shown:
![Screenshot 2024-01-02 113642](https://github.com/intersystems-community/vscode-objectscript/assets/64836841/03eb8287-f6b1-4a4d-979d-0d91e05cc829)

![Screenshot 2024-01-02 113536](https://github.com/intersystems-community/vscode-objectscript/assets/64836841/991b44b1-d487-40cf-95e9-14846461e332)

Happens both with Server-Side Editing aswell as Client-Side Editing.

Tried extension versions 2.10.5, 2.10.6 beta 1, 2.10.6 beta 2 and 2.10.6 beta 3.
Quick Search is enabled, but only shows the same files as explorer. 

Tried recompiling routines.
^rIndex has correct entries for all routines.
NEW>ZW ^rINDEX("WWWFORM")
^rINDEX("WWWFORM","INT")=$lb("2024-01-02 11:18:41.0011811",101055,1)
^rINDEX("WWWFORM","MAC")=$lb("2023-12-27 09:41:37.183894",101055,1)
^rINDEX("WWWFORM","OBJ")=$lb("2024-01-02 11:18:41",44288)
NEW>ZW ^rINDEX("WWWFORMF")
^rINDEX("WWWFORMF","INT")=$lb("2024-01-02 09:27:48.0387259",78778,1)
^rINDEX("WWWFORMF","MAC")=$lb("2023-12-07 17:11:01.973068",78788)
^rINDEX("WWWFORMF","OBJ")=$lb("2024-01-02 09:27:48",35604)

When trying to create for example WWWFORM.mac in VSCode, I get the expected error that the file already exists. Still doesn't show up afterwards

I looked at the conversations in Issues #1226 and #712, both fixes should be impletemented in newest Version.

**Comment by gjsjohnmurray** [comment]
In Studio do you get the same list when you uncheck the option for showing generated routines?

**Comment by Fobiwan** [comment]
Yes, seems missing files are generated ones.

**Comment by Fobiwan** [comment]
I modified the settings in the workspace folder to show generated files, and now I see them all. Thanks very much.
