### ISSUE TITLE
Error when searching "xxx is not a descendant of isfs://server:namespace

### ISSUE THREAD

**Issue by wojciechczyz** [intersystems-community/vscode-objectscript#1304]
![Screenshot 2024-01-23 at 15 06 23](https://github.com/intersystems-community/vscode-objectscript/assets/11516644/b6f33a80-ef88-485d-b65a-6b9e1e799692)

**Comment by isc-bsaviano** [comment]
@wojciechczyz What version of the extension and IRIS are you using?

**Comment by isc-bsaviano** [comment]
I think this was fixed by #1294
