### ISSUE TITLE
Open API - Spec First Approach - New method missing

### ISSUE THREAD

**Issue by lscalese** [intersystems-community/vscode-objectscript#131]
Hi,

I found a problem when we update a Rest service using API http://localhost:52773/api/mgmnt/ 
If the "Impl" class already exists and exported for editing, VSCode does show the newly generated method.
After analysis, I didn't found problems with the code of %REST.Generator.
I added a TCP tunnel between VSCode and /api/atelier/ and there are no activities when we open the "Impl" class (even in ObjectScript: Explorer).
The generated method exists on IRIS server, but never retrieved and show in VScode.

Lorenzo.
![capture-tunel](https://user-images.githubusercontent.com/16834099/81485754-d8777300-924f-11ea-88e6-649b170507e8.png)

**Comment by lscalese** [comment]
There is a simple workaround.  
After API Update : 
Remove the file from your project.
Use ObjectScript Explorer and export again the "Impl" class to your project.

**Comment by rajrsingh** [comment]
@lscalese do you consider this a bug that needs fixing? If so what would you suggest is the solution?

**Comment by lscalese** [comment]
Hello @rajrsingh,
Sorry, I didn't see your comment.
In fact, when @daimor said on Discord a simple "export" is enough from Objectscript explorer is enough to solve the problem.  For me, it's okay like that :-)
