### ISSUE TITLE
Find in files returns error

### ISSUE THREAD

**Issue by trevorfstrong** [intersystems-community/vscode-objectscript#1315]
Type: <b>Bug</b>

Opening my workspace connected to local irishealth system I can open server side files no problem, but find in files action fails and displays this error in the Objectscript output window.
intersystems-community.vscode-objectscript version 2.12.2-beta.2 activating with proposed APIs available.

ERROR #16002: Invalid JSON Content
NOTE: api/atelier/ web app is marked for password authentication only.

Extension version: 1.0.3
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (3.15GB free)|
|Process Argv|--enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id 6908b51a-5f63-40ad-85f8-24f898e529cc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww1:30959800
b5d27386:30958190
a89i1917:30961429
e3gdj431:30958358
ccp2r3:30958157

```

</details>

**Comment by isc-bsaviano** [comment]
Hi @trevorfstrong, I see that you created a WRC ticket for this issue, and that the error message there is different than the one you posed here. Which error message is correct `ERROR #16002: Invalid JSON Content` or `Non-JSON response to ...`?

**Comment by trevorfstrong** [comment]
It appears to be the invalid json content when attempting to get "find in files" to trigger.

**Comment by isc-bsaviano** [comment]
Thanks for clarifying. Can you use Wireshark or the web gateway's HTTP trace feature to capture the REST request and response that get sent when you try to search through files? The request will be a POST to the /api/atelier/v6/<namespace>/work endpoint. The response will have a 400 Bad Request header. Seeing the body of the request and response will help me diagnose the cause of the issue.

**Comment by trevorfstrong** [comment]
Is this what you need?
![image](https://github.com/intersystems-community/vscode-objectscript/assets/159860830/a8a58c0c-6d17-4212-9a97-71cce9542d04)

**Comment by trevorfstrong** [comment]
[CSP.zip](https://github.com/intersystems-community/vscode-objectscript/files/14351394/CSP.zip)

**Comment by isc-bsaviano** [comment]
@trevorfstrong Unfortunately, that doesn't have the oe piece of data that I need. What I need is the body of the request that prompts the 16002 error. I need to check if it's valid JSON. If it is, then there may be a bug on the server. If it's not, then there's a bug in this extension because it should always send JSON.

**Comment by trevorfstrong** [comment]
Very odd.
I have traced the api call, and edited the server side method.
My terminal testing seems true, however the isfs call fails with the error as seen in my debug trap

OMNI:DLS>zw ^%TREV(13)
^%TREV(13)="{""request"":""search"",""console"":false,""query"":""hang 5"",""regex"":false,""project"":""2235-Waters-NBS Standalone"",""word"":false,""case"":false,""wild"":false,""documents"":""*.cls,*.inc,*.mac,*.int"",""system"":false,""generated"":false,""mapped"":true,""max"":20000}"
 
OMNI:DLS>s tRequest={}.%FromJSON(^%TREV(13))                                     
OMNI:DLS>i tRequest.request="search" && ((tRequest.%GetTypeOf("query")'="string") || ((tRequest.%IsDefined("documents")) && (tRequest.%IsDefined("project"))) ||(('tRequest.%IsDefined("documents")) && ('tRequest.%IsDefined("project"))) ||((tRequest.%GetTypeOf("system")'="unassigned") && (tRequest.%GetTypeOf("system")'="boolean")) ||((tRequest.%GetTypeOf("generated")'="unassigned") && (tRequest.%GetTypeOf("generated")'="boolean")) ||((tRequest.%GetTypeOf("regex")'="unassigned") && (tRequest.%GetTypeOf("regex")'="boolean")) ||((tRequest.%GetTypeOf("max")'="unassigned") && (tRequest.%GetTypeOf("max")'="number")) ||((tRequest.%GetTypeOf("word")'="unassigned") && (tRequest.%GetTypeOf("word")'="boolean")) ||((tRequest.%GetTypeOf("case")'="unassigned") && (tRequest.%GetTypeOf("case")'="boolean")) ||((tRequest.%GetTypeOf("wild")'="unassigned") && (tRequest.%GetTypeOf("wild")'="boolean")) ||((tRequest.%GetTypeOf("mapped")'="unassigned") && (tRequest.%GetTypeOf("mapped")'="boolean")) ||((tRequest.%GetTypeOf("include")'="unassigned") && (tRequest.%GetTypeOf("include")'="string")) ||((tRequest.%GetTypeOf("exclude")'="unassigned") && (tRequest.%GetTypeOf("exclude")'="string")) ||((tRequest.%GetTypeOf("console")'="unassigned") && (tRequest.%GetTypeOf("console")'="boolean"))) w "yes"
yes
OMNI:DLS>zw ^%TREV(14)                                                          ^%TREV(14)=$lb("8@%Library.DynamicObject","0 "_$lb($lb(16002,,,,,,,,,$lb(,"APL",$lb("e^QueueAsync+66^%Api.Atelier.v6.1^1","e^DispatchRequest+34^%CSP.REST.1^1","e^DispatchRequest+48^%CSP.REST.1^1","e^zPage+25^%CSP.REST.1^1","e^zPage+2^%Atelier.REST.1^1","e^CSPDispatch+495^%SYS.cspServer^2","d^CSPDispatch+274^%SYS.cspServer^1","d^ProcessRequest+1^%CSP.Session.1^1","d^Request+683^%SYS.cspServer2^1","d^Request+25^%SYS.cspServer2^1","d^ProcessRequest+1^%CSP.Request.1^1","d^css+21^%SYS.cspServer2^1","d^SuperServer+60^%SYS.SERVER^2","d^^^0"))))/* ERROR #16002: Invalid JSON Content */)                                                        

OMNI:DLS>w tRequest.%ToJSON()
{"request":"search","console":false,"query":"hang 5","regex":false,"project":"2235-Waters-NBS Standalone","word":false,"case":false,"wild":false,"documents":"*.cls,*.inc,*.mac,*.int","system":false,"generated":false,"mapped":true,"max":20000}

**Comment by trevorfstrong** [comment]
Here are the mods to atelier class at point of error...
        } ElseIf tRequest.request="search" && (
            (tRequest.%GetTypeOf("query")'="string") ||
            ((tRequest.%IsDefined("documents")) && (tRequest.%IsDefined("project"))) ||
            (('tRequest.%IsDefined("documents")) && ('tRequest.%IsDefined("project"))) ||
            ((tRequest.%GetTypeOf("system")'="unassigned") && (tRequest.%GetTypeOf("system")'="boolean")) ||
            ((tRequest.%GetTypeOf("generated")'="unassigned") && (tRequest.%GetTypeOf("generated")'="boolean")) ||
            ((tRequest.%GetTypeOf("regex")'="unassigned") && (tRequest.%GetTypeOf("regex")'="boolean")) ||
            ((tRequest.%GetTypeOf("max")'="unassigned") && (tRequest.%GetTypeOf("max")'="number")) ||
            ((tRequest.%GetTypeOf("word")'="unassigned") && (tRequest.%GetTypeOf("word")'="boolean")) ||
            ((tRequest.%GetTypeOf("case")'="unassigned") && (tRequest.%GetTypeOf("case")'="boolean")) ||
            ((tRequest.%GetTypeOf("wild")'="unassigned") && (tRequest.%GetTypeOf("wild")'="boolean")) ||
            ((tRequest.%GetTypeOf("mapped")'="unassigned") && (tRequest.%GetTypeOf("mapped")'="boolean")) ||
            ((tRequest.%GetTypeOf("include")'="unassigned") && (tRequest.%GetTypeOf("include")'="string")) ||
            ((tRequest.%GetTypeOf("exclude")'="unassigned") && (tRequest.%GetTypeOf("exclude")'="string")) ||
            ((tRequest.%GetTypeOf("console")'="unassigned") && (tRequest.%GetTypeOf("console")'="boolean"))
        ) {
        	s ^%TREV($I(^%TREV))=tRequest.%ToJSON()
			
            Set tSC = $$$ERROR($$$InvalidJSONContent)
        	s ^%TREV($I(^%TREV))=$lb(tRequest,tSC)
            Set %response.Status = ..#HTTP400BADREQUEST
            Quit
        }

**Comment by isc-bsaviano** [comment]
@trevorfstrong Thanks, that's really helpful. I've identified what the problem is. The client is sending a value for both "project" and "documents". That should never happen. Can you send me the contents of the `.code-workspace` file that you're using?

**Comment by trevorfstrong** [comment]
Is this what you want?
Not sure if this helps or is a separte topic but, we work heavily with projects and would want the project info for the currently opened file sent to SourceControl serverside hooks too. If this doesn't happen, we will have to identify the current project in a different manner.
{
    "folders": [
		{
			"name": "2235-Waters-NBS Standalone - omnilocal:APL",
			"uri": "isfs://omnilocal:apl/?project=2235-Waters-NBS Standalone"
		}
	],
	"settings": {
		"objectscript.conn": {
			"active": false
		}
	}
}

**Comment by isc-bsaviano** [comment]
@trevorfstrong Yes, that's what I was looking for! That looks fine to me, so I'm not sure why the extension is sending both "project" and "documents". I will dig into the code when I have time. I think your project source control request is covered by #1313 and #1313.

**Comment by trevorfstrong** [comment]
Thanks. that works.
The CTRL+SHIFT+F only seems to search on the local files previously accessed.
I can't seem to get it to search all files on the server side and how to restrict the search to a specific server/namespace escapes me. Any thoughts or advice?

**Comment by gjsjohnmurray** [comment]
Have you followed me steps in the README to enable proposed APIs?

**Comment by trevorfstrong** [comment]
Yep. I see this in the output too.
intersystems-community.vscode-objectscript version 2.12.2-dev.1318 activating with proposed APIs available.

**Comment by trevorfstrong** [comment]
Maybe this will help.
[CSP.zip](https://github.com/intersystems-community/vscode-objectscript/files/14379901/CSP.zip)

**Comment by trevorfstrong** [comment]
Doesn't look like it passed the search param thru at all now.
![image](https://github.com/intersystems-community/vscode-objectscript/assets/159860830/b2b8af11-3e38-4b9e-b7ec-94e05816cba2)

**Comment by isc-bsaviano** [comment]
@trevorfstrong I see requests to the /work endpoints so unless you compiled a file at the same time, those requests are searches. The request bodies are still not in that log so I couldn't tell what exactly it was trying to search for. Based on the image, I think you mean to turn off the regex option (the `.*` icon). That uses a JavaScript (or `$MATCH`) style regex. I'm not sure what type of pattern matching you're trying to do with the `*` character. I use [regexr.com](https://regexr.com/) to validate my regexes.

**Comment by trevorfstrong** [comment]
Hi Brett. It doesn't matter what i type in or what regex expression i use, nothing shows up in the CSP.log for the work request with that search string.
Did you break something or am i missing a config step here after installing, reloading and restarting VSC with your new extension?
The doco says I don't need to do anything if already done with previous beta extension but maybe i have misread the instructions. Something seems to be blocking the sending of serverside payload despite this showing in the output. Has it not activated?
intersystems-community.vscode-objectscript version 2.12.2-dev.1318 activating with proposed APIs available.

**Comment by trevorfstrong** [comment]
![image](https://github.com/intersystems-community/vscode-objectscript/assets/159860830/02637f64-8c0c-494d-b039-58b3c9bfe124)

**Comment by trevorfstrong** [comment]
![image](https://github.com/intersystems-community/vscode-objectscript/assets/159860830/0f58bce3-db83-4b9e-aa18-39fb42387097)

**Comment by isc-bsaviano** [comment]
Thanks for the screenshots. That vsix definitely works; I'm using it right now in my own workspace. If you see that message then proposed APIs are enabled, so that's not the issue. I'm going to download a community edition container with the same $ZV as your server just to be sure that there's nothing wrong with that version, but I doubt that there is.
