### ISSUE TITLE
Auto formatting on save changing commands to underfined

### ISSUE THREAD

**Issue by spotashnyk** [intersystems-community/vscode-objectscript#132]
I have come across an issue where the formatting on save changes all commands to underfined

Saving and compiling without formatting works fine.

Before Save
<img width="393" alt="Screen Shot 2020-05-12 at 4 29 21 pm" src="https://user-images.githubusercontent.com/14516934/81646372-75175c00-946e-11ea-8e0c-5159627645db.png">
.
After Save
<img width="374" alt="Screen Shot 2020-05-12 at 4 29 31 pm" src="https://user-images.githubusercontent.com/14516934/81646361-70eb3e80-946e-11ea-9867-4d72debc65bf.png">

**Comment by daimor** [comment]
It looks like, you have something like this, in your settings
`"objectscript.format.commandCase": ""`
While it allows only: "word", "lower", "upper".
I'll fix it, for case when it contains not allowed value.

**Comment by spotashnyk** [comment]
Thanks that fixed it, for some reason was set to null, i do not remember adding that preference.
