### ISSUE TITLE
InterSystems Explorer doesn't automatically refresh a class changed from outside VS Code 

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1320]
Consider a class that's been opened in VS Code from the InterSystems Explorer view. It may or may not have been exported to the local file system for editing. Now, change the class using a different interface. For example:

- If the class is a persistent class, run ALTER TABLE ADD COLUMN from the SQL section of the Portal.
- If the class is a DTL class, add something to the DTL in the Portal.

Both of these actions change the class on the server. However, closing and reopening the class **doesn't** show the updated class definition. I don't think "Refresh Explorer" is designed to do this, but it doesn't show the updated class either. It's as if VS Code has its own local copy and doesn't know that the server version has been changed.

From the InterSystems Explorer view, the following actions **do** update the class:
- Exporting the class from the server.
- Compiling the class (if the "u" compiler option is **not** set).

**Comment by isc-solon** [comment]
Sorry I filed this in the wrong place! @isc-bsaviano I agree with everything you wrote in your first paragraph. I don't expect the local copy to update automatically. But if I'm using the InterSystems Explorer, I expect it to always show me what's on the server. Maybe I'm using VS Code to simply view the effect of changes I make using a different interface. So I guess what I'm reporting here is that closing the file and re-opening it is **not** causing the contents to refresh from the server in some cases.

**Comment by isc-bsaviano** [comment]
> But if I'm using the InterSystems Explorer, I expect it to always show me what's on the server. 

The `objectscript.explorer.alwaysShowServerCopy` setting will do that for you.

> So I guess what I'm reporting here is that closing the file and re-opening it is not causing the contents to refresh from the server in some cases.

If this is the case then there's a bug. I will investigate.

**Comment by isc-solon** [comment]
I didn't have the alwaysShowServerCopy checked! So I checked it. Unfortunately, I'm seeing the same behavior. Closing/opening doesn't refresh. If I export, the local copy is up-to-date. But the server copy still shows the old (cached, now that I've read your EDIT above) copy.

**Comment by isc-bsaviano** [comment]
Thanks for reporting this @isc-solon. It's definitely a bug. IMO the server copy should refresh in this case.

**Comment by isc-bsaviano** [comment]
@isc-solon Please try [this vsix](https://github.com/intersystems-community/vscode-objectscript/actions/runs/8025388797/artifacts/1271044072) and let me know if it's an improvement.

**Comment by isc-solon** [comment]
The update works! However, it works **regardless** of the alwaysShowServerCopy setting. Is that the intent?

**Comment by isc-bsaviano** [comment]
Thanks for checking Joel! Yes, this should work for any read-only file opened from the Explorer, regardless of that setting.
