### ISSUE TITLE
Jump to Tag+Offset autocomplete

### ISSUE THREAD

**Issue by rafjohnson** [intersystems-community/vscode-objectscript#1323]
Using JumpToTag+Offset as described in #351 should allow for autocompletion of a method name while typing, or up and down arrows to select a tag without navigating to it. 
![Screenshot 2024-02-28 101819](https://github.com/intersystems-community/vscode-objectscript/assets/19212747/e849d324-93b9-433d-852b-efdd5cff9dbd)

I should be able to partially type a tag, then press the down arrow to select an existing tag, and have the full tag name be populated in the text box, with the cursor at the end ready to type "+12". OR the name should autocomplete as I type as it does in Studio.

Currently the full tag must be entered manually. 

In Studio, the full name was autocompleted as you typed. 
![Screenshot 2024-02-28 102015](https://github.com/intersystems-community/vscode-objectscript/assets/19212747/a2891660-6fee-4826-8845-4ceb65af0789)

**Comment by isc-bsaviano** [comment]
@rafjohnson Thanks for the suggestion.

> I should be able to partially type a tag, then press the down arrow to select an existing tag, and have the full tag name be populated in the text box, with the cursor at the end ready to type "+12".

This I can look into and should be possible.

> OR the name should autocomplete as I type as it does in Studio.

I don't think the VS Code UI supports this.

**Comment by rafjohnson** [comment]
> Hi @rafjohnson, I've opened PR #1325 to implement your suggestion. Please see the PR for a description and demo of what I changed. If you'd like to try it out you can download the version of the extension found [here](https://github.com/intersystems-community/vscode-objectscript/actions/runs/8084940519/artifacts/1283315890).

Looks great! Thanks for the quick turnaround!

**Comment by isc-bsaviano** [comment]
You're welcome, happy to help!
