### ISSUE TITLE
Add Ability to Edit Project Description After Creation

### ISSUE THREAD

**Issue by mathewrimmingtoncds** [intersystems-community/vscode-objectscript#1324]
After a project is created via the ObjectScript extension, it is not possible to edit the description. In Studio we use project descriptions to make notes about a piece of development. As a piece of development progresses, the notes need to keep changing.

It'd be really good if we had the same ability via VS Code.

**Comment by isc-bsaviano** [comment]
Hi @mathewrimmingtoncds, I've opened PR #1326 to implement your suggestion. Please see the PR for a description of the new command. If you'd like to try it out you can download the version of the extension found [here](https://github.com/intersystems-community/vscode-objectscript/actions/runs/8085897539/artifacts/1283554396).

**Comment by mathewrimmingtoncds** [comment]
Hi @isc-bsaviano, this works perfectly thanks.
