### ISSUE TITLE
HEAD request to /api/atelier

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#1327]
Extension call /api/atelier with HTTP method HEAD

https://github.com/intersystems-community/vscode-objectscript/blob/9e2d8265736600cc114f3a4e3565297661899241/src/api/index.ts#L327

By some reasons /api/atelier does not drop connection after response and just hangs
and VSCode-ObjectScript just hangs as well, can't start at all
```
$ curl -v -X HEAD -u _SYSTEM:SYS http://localhost:52773/api/atelier/                                                                                                
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the 
Warning: way you want. Consider using -I/--head instead.
*   Trying [::1]:52773...
* Connected to localhost (::1) port 52773
* Server auth using Basic with user '_SYSTEM'
> HEAD /api/atelier/ HTTP/1.1
> Host: localhost:52773
> Authorization: Basic X1NZU1RFTTpTWVM=
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 04 Mar 2024 14:56:00 GMT
< Server: Apache
< SET-COOKIE: CSPSESSIONID-SP-52773-UP-api-atelier-=001000000000NWKcyveA4ejZDN$jSS3nCWw2ZbTImm$babzwKJ; path=/api/atelier/;  httpOnly; sameSite=strict;
< CACHE-CONTROL: no-cache
< EXPIRES: Thu, 29 Oct 1998 17:04:19 GMT
< PRAGMA: no-cache
< SET-COOKIE: CSPWSERVERID=hzXxuMHJ; path=/; httpOnly;
< Content-Type: application/json; charset=utf-8
* no chunk, no close, no size. Assume close to signal end
< 
```

**Comment by isc-bsaviano** [comment]
@daimor What version are you connecting to? This works fine for me. Nothing on the server changed that could affect this. Does GET on that endpoint work?

**Comment by daimor** [comment]
No idea why it's happening, I'm using docker, on Arm64
quite old version behave the same
containers.intersystems.com/intersystems/iris-community:2023.1
newest preview also hangs

I've created a new profile in VScode, just only with three InterSystems extensions and one for Docker
<img width="1131" alt="image" src="https://github.com/intersystems-community/vscode-objectscript/assets/1212251/12b672ea-ca0a-4fb0-b46b-a9a97a20b437">

**Comment by isc-bsaviano** [comment]
I still couldn't reproduce this with $ZV of `IRIS for UNIX (Ubuntu Server LTS for ARM64 Containers) 2023.1.3 (Build 517U) Wed Jan 10 2024 13:31:31 EST`. I added an isfs folder connected to that server to my workspace and restarted VS Code. The extension activated right away. The behavior with CURL is the same as my locally installed instance that doesn't use the PWS.

**Comment by daimor** [comment]
no idea, just strange behaviour, updated VSCode itself solved the issue with connection, and I did not get why.
