### ISSUE TITLE
Extension not showing in Activity Bar

### ISSUE THREAD

**Issue by KurtHofman** [intersystems-community/vscode-objectscript#133]
Hello, starting from version 0.8.0 the extension is not showing anymore in the activity bar.
The last working version is 0.7.13.  I'm using vscode 1.45.1 on Windows 10.
Any idea how to solve this ?
Regards.

**Comment by daimor** [comment]
This possible if you did not open any folder in VSCode.

**Comment by KurtHofman** [comment]
Thanks for the quick response, I'll try to open a workspace in Vscode with the right settings.

**Comment by rajrsingh** [comment]
I've been convinced that this behavior is not ideal. It makes sense in some cases to see the icon whether or not you are in a directory with the right settings. Let's discuss.

**Comment by gjsjohnmurray** [comment]
> I've been convinced that this behavior is not ideal. It makes sense in some cases to see the icon whether or not you are in a directory with the right settings. Let's discuss.

@rajrsingh in what situations does it make sense to show the ObjectScript Explorer even though no `objectscript.conn`is present?

**Comment by rajrsingh** [comment]
@gjsjohnmurray now that documentation is more comprehensive I think it now makes more sense to me to keep the behavior as it is, so I'm flip-flopping again and I am happy to have this issue closed (again).
