### ISSUE TITLE
Blank Line Endings in Routines Lost on Save

### ISSUE THREAD

**Issue by mathewrimmingtoncds** [intersystems-community/vscode-objectscript#1333]
Hi,

We have spotted what looks like a fault with blank line endings when saving routines in VS Code. If the routine ends with a blank line, the blank line is removed by the time it is sent to the PutDoc Atelier API.

Saving a routine which looks like this:

![image](https://github.com/intersystems-community/vscode-objectscript/assets/85876726/a6779b9e-5341-4906-8df9-a107df5238c6)

Ends up looking like this after one save:
![image](https://github.com/intersystems-community/vscode-objectscript/assets/85876726/e84327d6-8db6-411b-ad0f-274c87d755ec)

And after multiple saves:
![image](https://github.com/intersystems-community/vscode-objectscript/assets/85876726/cacad4f3-73a9-42c8-9f58-74fd7022412b)

It looks like the code responsible is here: https://github.com/intersystems-community/vscode-objectscript/blob/0a446be77a012fb2e99f9bf2d7d18a91ebf32ce2/src/commands/compile.ts#L102C8-L102C102

`

    content = file.content.split(/\r?\n/);

    // Avoid appending a blank line on every save, which would cause a web app file to grow each time
    if (content.length > 1 && content[content.length - 1] === "") {
      content.pop();
    }

`

The comment reads as though the string.split is adding a blank line, and that the code below it is removing it. I can't imagine why doing a string.split would add a new line. The issue this causes us is that some of our routines end with a blank line, and when developers simply import and compile one of these routines the developer is left wondering why the file is picked up as an unstaged change.  

Does anyone know why this behaviour is necessary?

Thanks

Mat

**Comment by isc-bsaviano** [comment]
@mathewrimmingtoncds I think this was added due to the server adding a blank new line at the end of every web application file, so if you saved a file and then refreshed its content you'd have an extra line. Regardliss, this code shouldn't be run for non-web application files.
