### ISSUE TITLE
Azure DevOps/TFS - Handling Cache/IRIS routines with .mac file extension

### ISSUE THREAD

**Issue by PaulSiml** [intersystems-community/vscode-objectscript#134]
TFS 2015 treats the .mac file extension as an image file.  Therefore it will not allow us to perform a code comparison on the Pull Request because if considers .mac files as images.  We have found no way to alter the handling of the file extension in TFS.  We are attempting to get some more information from Microsoft without success.
 
We suspect this is a "feature" of TFS 2015 since all other file extensions work correctly.  This is where the ObjectScript extension may be able to help us.  If we could have a setting in the ObjectScript extension that would allow us to use a different extension for .mac files – perhaps .tmac – this would fix the issue for us.  ObjectScript would see this replacement extension .tmac and ,on the push to Cache/IRIS, convert it to a .mac extension.  In this manner we would just store our Cache code in TFS (Git) with the .tmac extension.  When we build an area we could flip the extension back to the normal .mac extension.

**Comment by daimor** [comment]
I think this should be configurable from TFS side.
I don't have my own TFS server, but this documentation seems relevant to this issue.
https://docs.microsoft.com/en-us/azure/devops/server/admin/manage-file-types?view=azure-devops#add-file-types

**Comment by PaulSiml** [comment]
Hi Dmitry,

Thanks for the quick response.  We are running TFS 2015 on both a centralized (TFVC) and distributed (Git) repositories.
We are using VS Code/ObjectScript extension on a TFS (Git) repository.

Yes … We have manipulated the extensions on both the TFS server and workstations without success as outline in the article.
The .mac file seems to be hardwired to image handling on both repository types.

It may be specific to our older version of TFS 2015 (five years old).

We would still like to get a response from Microsoft but are doubtful they will assist us.  I believe that InterSystems wants to provide the ObjectScript extension as a viable option for Azure DevOps customers.  They will need to overcome this issue in some manner because our Pull Request is completely broken right now.

It would be interesting to see the experience of a client running a new version of TFS - now called Azure DevOps.

So, unless we can get some type of resolution from Microsoft, an ObjectScript enhancement to manipulate the extension would be our only solution.

I will revisit the file extension again on our server and workstation just in case I missed something.

Thanks for your hard work on this extension … when will you be doing another training webinar?

-Paul

**Comment by daimor** [comment]
As you have git, did you try to change this behaviour with .gitattributes?

**Comment by PaulSiml** [comment]
Hi Dmitry,

I am not an expert in Git but I would like to try it.

How would you recommend implementing it?

Thanks,

-Paul

**Comment by daimor** [comment]
You can start with a very simple content
`.gitattributes`
```
*.cls text
*.mac text
*.int text
*.inc text
```

**Comment by PaulSiml** [comment]
Hi Dimtry,

I tried various settings within the .gitattributes without success.

Here is what a .cls file looks like in TFS 2015 (Git).  It is text and can be edited either here or in VS Code.
Comparisons work correctly on a Pull Request.

[cid:image007.jpg@01D62A9D.00131150]

Here is what a routine file (.mac) looks like in TFS 2015 (Git).  It is treated like an image, cannot be edited, and can only be downloaded.

[cid:image008.jpg@01D62A9D.00131150]


Here is a Pull Request:

[cid:image009.jpg@01D62A9D.00131150]

Notice how the gitattributes displays text but the .mac is treated like an image.

Here is my directory setup in case I did not configure correctly.  I also pushed the attribute file into the repository.

[cid:image010.jpg@01D62A9D.00131150]


Suggestions?

Thanks,

-Paul

**Comment by rajrsingh** [comment]
@PaulSiml I'll also try to connect with Microsoft via our channels. I agree with @daimor the "right" solution is on the TFS side.

**Comment by gjsjohnmurray** [comment]
Outside our control. Can this be closed here?

**Comment by rajrsingh** [comment]
I've had no luck connecting with MS, so I think we have to close it.

**Comment by PaulSiml** [comment]
Yes.
