### ISSUE TITLE
Unit testing view (test tube) doesn't auto-refresh when unit test methods are renamed

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1340]
I renamed the 2 Test* methods in a unit testing class (TestPerson() to TestPersonAccount() and TestPersonSQL() to TestPersonAccountSQL()). VS Code was confused by this in two spots. In the test tube view on the left it was showing a mix of the old method names and the new method names. In the unit test results tab on the lower right it was reporting that tests named Person (old) and PersonAccount (new)  had run. After clicking the refresh icon at the top left the test tube view is correct. After that, running the tests again produces accurate output in the results tab.

**Comment by isc-solon** [comment]
Loaded the vsix. When I change the name of a method, it is **immediately** updated in the testing view on the left. And running the tests shows the updated name on the right. All good.

**Comment by isc-bsaviano** [comment]
Thanks for confirming Joel!
