### ISSUE TITLE
support minimap-section-headers

### ISSUE THREAD

**Issue by isc-lindensc** [intersystems-community/vscode-objectscript#1344]
Hi, 
with the recent VScode update minimap-section-headers were introduced.

Would it be possible to add support for Method, ClassMethod and line labels to be recognized by the minimap as section headers?

ref: https://code.visualstudio.com/updates/v1_88#_minimap-section-headers

**Comment by isc-bsaviano** [comment]
@isc-lindensc Based on the VS Code issue that implemented that feature, it only works for the comment types in the example. See https://github.com/microsoft/vscode/issues/74843
