### ISSUE TITLE
VSCode features not supported for Embedded Python method

### ISSUE THREAD

**Issue by Yuanhao-Zheng** [intersystems-community/vscode-objectscript#1348]
Type: <b>Bug</b>

When writing Method/ClassMethod in Embedded Python (set language=Python), the following VSCode features don't work:
1. Syntax Highlighting
2. Debugging

Extension version: 2.10.6-beta.1
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1370P (20 x 2189)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.38GB (9.03GB free)|
|Process Argv|C:\\DEV\\IRIS\\VSCode\\aungpycups\\aungpycups.code-workspace --enable-proposed-api intersystems-community.vscode-objectscript --crash-reporter-id f305fbe5-76d3-42ab-8737-65872636490e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
bdiig495:31013172

```

</details>

**Comment by isc-bsaviano** [comment]
@Yuanhao-Zheng The Language Server extension provides syntax coloring for python methods. The IRIS server doesn't support debugging E,bedded Python, so there's nothing we can do to support it. Also, I noticed that you're using an old beta version of this extension. I recommend keeping it up to date so you get all bug fixes and new features.
