### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by Patresko** [intersystems-community/vscode-objectscript#1355]
There is a bug when you click Go to definition on the label which is defined like this

```
label
 DO gOverviewRefresh,
       gDetail
 QUIT

label2

 DO gOverviewRefresh,
       gDetail
 QUIT

gDetail

 QUIT
```

When you try to go to defintion of gDetail it does not take you to that label but to label where is used.

**Comment by isc-bsaviano** [comment]
@Patresko Thanks for reporting this. This is a bug in the Language Server extension, so I will move the issue to that extension's repository.
