### ISSUE TITLE
Is it possible to share configuration through a committed config file.

### ISSUE THREAD

**Issue by jpa95** [intersystems-community/vscode-objectscript#1356]
Apologies if this has been asked or if it is already possible; I could not find it.

Basically I am hoping that the three InterSystems extensions could look for a config file in the current project folder, as do many other extensions such as editor.config and prettier.

Having the configuration in the VS Code settings (regardless of project/user/workspace level) make it impossible to share config between developers on the same project easily. In our environment, Ideally a developer would pull the configuration for all extensions as part of the code on git,.

Regards,
Joel

**Comment by isc-bsaviano** [comment]
@jpa95 Why not put your settings in a .vscode/settings.json within your repo so all developers who clone your repo have access to it? We do that for this extension's repo for example.

**Comment by jpa95** [comment]
Hi Brett,
currently .vscode/settings.json contains the following, and this can change for each developer (we work with local instances of our namespaces), so i cannot commit this because it would end up "always changed"
{
  "objectscript.conn": {
    "server": "localhost",
    "ns": "REG05_ENSEMBLE",
    "active": true
  },
}

Also, if i try to add a config item, it simply is not supported at this level:
 "objectscript.multilineMethodArgs": true, // this will be greyed out.

**Comment by isc-bsaviano** [comment]
@jpa95 You can move the `objectscript.conn` to your user-level settings so it doesn't make it into source control. You can define most settings, including `objectscript.multilineMethodArgs` at the user or workspace level so it should work in that file.

**Comment by jpa95** [comment]
For reference, our current User file has the following content. Our current methodology is to share the user settings, and everyone needs to update their copy manually.
{
   "intersystems.servers": {
      "server1": {
         "username": "USERNAME",
         "webServer": {
            "host": "redacted",
            "port": 8971,
            "scheme": "http"
         }
      },
      "server2": {
         "username": "USERNAME",
         "webServer": {
            "host": "redacted",
            "port": 8971,
            "scheme": "http"
         }
      },
      "server3": {
         "username": "USERNAME",
         "webServer": {
            "host": "redacted",
            "port": 443,
            "scheme": "https"
         }
      },
   },
   "objectscript.compileFlags": "cukb",
   "intersystems.language-server.formatting.system.case": "word",
   "intersystems.language-server.formatting.system.length": "long",
   "intersystems.language-server.formatting.commands.length": "long",
   "intersystems.language-server.formatting.commands.case": "lower",
   "objectscript.conn": {
      "active": true,
      "links": {
         "Documentation": "https://docs.intersystems.com/irisforhealth20211/csp/docbook/DocBook.UI.Page.cls",
         "Portal Explorer": "${serverUrl}/csp/sys/exp/%25CSP.UI.Portal.ClassList.zen?$NAMESPACE=${ns}",
         "Launch Zen page": "http://${host}:${port}/csp/healthshare/${namespace}/${classname}.cls",
         "SOAP Wizard": "${serverUrl}/isc/studio/templates/%25ZEN.Template.AddInWizard.SOAPWizard.cls?Namespace=${namespace}${serverAuth}",
         "Generate unit tests": "http://${host}:${port}/PathtoFile.cls?classname=${classname}",
         "$(terminal) WebTerminal": "${serverUrl}/terminal/?ns=${ns}${serverAuth}"
      }
   },
   "objectscript.multilineMethodArgs": true,
   "objectscript.overwriteServerChanges": true,
   "objectscript.showExplorer": true,
   "objectscript.suppressCompileErrorMessages": true,
   "objectscript.export": {
      "folder": "Src"
   },
}

**Comment by jpa95** [comment]
Ok for `objectscript.conn`, however using User settings is not really an option because this file is not under source control. I'll have to dig into workspace level because we do not use that as of yet.

**Comment by jpa95** [comment]
Thanks, I will do some tests. Are you saying that even if a line in .vscode/setting.json is greyed-out and the UI tells me this is not supported, that the setting will still apply?
![image](https://github.com/intersystems-community/vscode-objectscript/assets/99364505/8a351aa6-12f9-4f9e-a56a-81d276256097)

**Comment by isc-bsaviano** [comment]
The hover hint it's giving you is accurate. the setting will take affect when you open the `InterSystems` folder as your current workspace. Is `REG05_ENSEMBLE` a `.code-workspace` file? If so, is that something that is shared between developers/is in source control? I'm trying to understand your workflow.

**Comment by jpa95** [comment]
No it's not a workspace. We are still (evidently) building up our knowledge of VS Code. 

Currently we do not use Workspaces officially, the workspace files are not committed. I am personally using a multi-root workspace. One of my workspaces opens 3 repos (folders):

```
{
  "folders": [
    {
      "path": "InterSystems"
    },
    {
      "path": "ens-reg05-ensemble"
    },
    {
      "path": "ENS-QCPR"
    }
  ],
}
```

Maybe standardising use of Workspaces is the way to go, I'll do some reading and tests, thanks!

**Comment by isc-bsaviano** [comment]
@jpa95 Thanks for clarifying! You can put your settings in your `.code-workspace` file if you want them to take effect for all of those folders:

```json
{
  "folders": [
    {
      "path": "InterSystems"
    },
    {
      "path": "ens-reg05-ensemble"
    },
    {
      "path": "ENS-QCPR"
    }
  ],
  "settings": {
    "objectscript.compileFlags": "cukb"
  }
}
```

**Comment by isc-bsaviano** [comment]
@jpa95 I'm going to close this issue since there isn't a bug in this extension but feel free to reach out again if you have any questions.
