### ISSUE TITLE
Debugger stops on the line with error but doesn't show it

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#136]
The debugger just stops now on the line not giving the indication of what is the error.
Please add this info

**Comment by daimor** [comment]
At the moment, there is no way to detect if it was stopped by error or by ordinary breakpoint. It will need some changes on AtelierAPI side to make it more clear.

**Comment by isc-bsaviano** [comment]
@daimor Can you please describe the change needed to the Atelier APIs for you to make this enhancement?

**Comment by isc-bsaviano** [comment]
@evshvarov If the debugger stops with an error, it will be printed out in the debug console window. You can also see the list if breakpoints in the debug pane, so you can tell if you're at one of them.
