### ISSUE TITLE
Number looking STRING Parameter is reformatted to a number

### ISSUE THREAD

**Issue by janihur** [intersystems-community/vscode-objectscript#1360]
Create a new class with a STRING parameter that looks like a number:
```
Class OSEX.Foo Extends %RegisteredObject
{

Parameter Foo As STRING = "123";

}
```

Save the class.

Now the extension formats the parameter as:

```
Parameter Foo As STRING = 123;
```

And complains "Parameter value and type do not match".

![Näyttökuva 2024-05-13 073236](https://github.com/intersystems-community/vscode-objectscript/assets/954293/729a0689-04fa-4d0e-b3cf-c10e356328c7)

**Comment by isc-bsaviano** [comment]
@janihur That behavior is caused by the server and is not controlled by this extension. I suggest you contact the WRC and describe it to them. They may be able to help you understand why it's happening or open a bug report on your behalf.
