### ISSUE TITLE
Extension 2.12.14 doesn't allow login on minimal security 

### ISSUE THREAD

**Issue by GYurkovicArtera** [intersystems-community/vscode-objectscript#1364]
Type: <b>Bug</b>

1. Update the Intersystems ObjectScript extention to 2.12.14.
2. Close VSCode.
3. Reopen VSCode.
4. Connect to an Intersystems instance. Click 'Allow' to allow VSCode to connect. Choose server and namespace. 
5. Normally, you would be prompted for a username and password. However, now no username prompt is given. Only a password prompt for 'undefined' user. No login is allowed.
6. By downgrading to 2.12.13, user can login the old way with username/password prompting.

Extension version: 2.12.3
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (2.66GB free)|
|Process Argv|--crash-reporter-id cc250050-2f11-473b-9c3a-f3ae840c8b86|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideot:31016892
chatpanelt:31048053
dsvsc021:30996838
da93g388:31013173
pythoncenvptcf:31049071
fchga941:31046352
dvdeprecationcf:31040882
pythonprc:31047982
dwnewjupytercf:31046870
fa862199:31048878

```

</details>

**Comment by isc-bsaviano** [comment]
@GYurkovicArtera Can you please share your server configuration? A screenshot of the prompt might help too.

**Comment by GYurkovicArtera** [comment]
P.S. I added the 'on minimal security' note to the title because of this entry in [the Change Log from yesterday's release](https://marketplace.visualstudio.com/items/intersystems-community.vscode-objectscript/changelog):
_Don't prompt for Server Manager credentials when using minimal security (#1351)_

**Comment by isc-bsaviano** [comment]
@GYurkovicArtera Sorry, I meant your VS Code server definition. You can find it by opening the settings UI (`Ctrl-,` on Windows), searching for `intersystems.servers` and then clicking `Edit in settings.json`. Feel free to hide any sensitive information.

**Comment by GYurkovicArtera** [comment]
Here you go:
```
{
    "workbench.startupEditor": "none",
    "intersystems.language-server.suggestTheme": false,
    "intersystems.servers": {
        



        "acsiris": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 52774
            },
            "description": "Connection to local InterSystems IRIS™ installed with default settings."
        },
        "/default": "acsiris"
    },
    "security.workspace.trust.untrustedFiles": "open",
    "git.confirmSync": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.renderWhitespace": "none",
    "extensions.autoUpdate": false
}
```

**Comment by isc-bsaviano** [comment]
Thanks for that. Are you sure your server is configured to not require username and password to connect? Your configuration looks correct to me for a minimal security instance, but I wouldn't expect that instance to respond with a `401 Unauthorized`. You said that in that past you entered your credentials via the prompt. Do you expect to be entering credentials? You can see if your server is configured to allow Unauthenticated access by open your web application settings and looking at the configuration for the `/api/atelier` web application.

**Comment by GYurkovicArtera** [comment]
Yes, I expect to enter credentials. We have always entered them in the past. 
In the settings for `/api/atelier`, Security Settings / Allowed Authentication Methods only has the 'Password' option checked ... 'Unauthenticated', etc. are unchecked.

**Comment by isc-bsaviano** [comment]
Ok, now I understand what the problem is. The extension sees that you don't have a username configured, so it assumes you want to connect with no credentials. If you edit your server definition to include your username then the extension will prompt you for the password. You can also store your password in the `settings.json` if you don't want to keep entering it every time. Here's what your updated settings would look like:

```json
{
    "workbench.startupEditor": "none",
    "intersystems.language-server.suggestTheme": false,
    "intersystems.servers": {
        "acsiris": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 52774
            },
            "description": "Connection to local InterSystems IRIS™ installed with default settings.",
            "username": "<your username>",
            "password": "<your password>"
        },
        "/default": "acsiris"
    },
    "security.workspace.trust.untrustedFiles": "open",
    "git.confirmSync": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "editor.renderWhitespace": "none",
    "extensions.autoUpdate": false
}
```

If you don't want your password in plain text you can omit that key. You can also use the Server Manager extension to [store your password securely](https://github.com/intersystems-community/intersystems-servermanager?tab=readme-ov-file#the-authentication-provider).

**Comment by GYurkovicArtera** [comment]
Thank you! Adding a username to the settings JSON allows me to login on the newest version of the extension.

**Comment by isc-bsaviano** [comment]
Thanks, happy to help! If you're satisfied with either of my proposed configuration changes please close this issue.

**Comment by GYurkovicArtera** [comment]
Closed. Thanks.
