### ISSUE TITLE
Users cannot connect to IRIS with "username": "" in settings.json

### ISSUE THREAD

**Issue by sduncan01** [intersystems-community/vscode-objectscript#1371]
A customer had been using 
```
"username": "" 
```
for IRIS server connections in their settings.json. They explained that this had worked in the past as a way to allow connections from different IRIS users from the same VSCode instance - they would be prompted for both the username and password for IRIS. Recently, however, they started to see errors in VSCode when attempting to log in to IRIS:
```
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on \<host\>[\<namespace\>]
```

We looked into this and saw login failures for UnknownUser on the IRIS instance:
```
Error message: ERROR #862: User UnknownUser is restricted from running application /api/atelier, %Development:U required -- cannot execute.
Web Application: /api/atelier
$I: |TCP|1972|8412
$P: |TCP|1972|8412
``` 

These continued even though UnknownUser was disabled and unauthenticated access was not allowed instance-wide or in the /api/atelier settings. vscode-objectscript seemed to be producing errors reading "Anonymous access rejected by \<host\>[\<namespace\>]" when we looked at the VSCode Developer Tools console. 

Setting a specific IRIS user for "username" in settings.json corrected this issue, but I'm wondering whether this was the expected behavior, especially since the customer reports not having this problem in the past. If this is expected, is there another supported way to have VSCode prompt for both username and password (allowing different IRIS users to connect from the same VSCode instance)? Removing the "username" attribute from the server connection in settings.json doesn't work - it causes VSCode to prompt the user to "Enter Password to connect as user 'undefined'...".

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano maybe a consequence of #1351

**Comment by isc-bsaviano** [comment]
This definitely caused by that change and was previously reported in #1364. I think the correct thing to do is to assume unauthenticated first, and then if that returns a 401 ask for the username like before.

**Comment by sduncan01** [comment]
@isc-bsaviano Thanks for fixing this! As of v2.12.5 this seems to be working as expected - when I test with "username": "" I am prompted for a username and password to connect to IRIS and can access code on my instance after providing the credntials. However, immediately before that prompt (at the same time as the popup saying that the extension wants to sign in), I get an error notification saying "Unauthenticated access rejected by '\<host\>'." I think that's tolerable if there isn't a good way to avoid it (and in some cases maybe it's even informative), but I can open a new issue if that isn't what you were expecting.

![image](https://github.com/intersystems-community/vscode-objectscript/assets/14204397/53b09eb4-fb1e-4905-bc19-3b018b338508)

**Comment by isc-bsaviano** [comment]
@sduncan01 Yes, that's expected. In order to support unauthenticated access, we need to try it before prompting for a username. I left that message in because someone who wanted to use unauthenticated access will want to know that it was rejected.
