### ISSUE TITLE
Support command stepping in debugger

### ISSUE THREAD

**Issue by antechdavid** [intersystems-community/vscode-objectscript#1375]
Type: <b>Feature Request</b>

Hi in mumps, we have B "S". This way one can step command by command. How can we do this with vscode? F10 only step to the next line.

Say, if I have a line like

S A=1 S B=2 S C=A+B

I cannot step within the line. But with "S", one can.

Do you have any idea?

Thanks,

David

Extension version: 2.12.5
VS Code version: Code 1.89.1 (Universal) (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:24.611Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by isc-bsaviano** [comment]
@antechdavid You can't do this right now. The Atelier debug agent that VS Code uses only does line stepping. Command stepping is definitely something I'd like to support. Ideally this would be configurable with command stepping being the default. However, this requires an IRIS change that I doubt could be back ported to it would only work for new versions of IRIS.

**Comment by antechdavid** [comment]
Hi Brett,

If I install the latest IRIS, will I be able to use it?

If so, that gives me a reason to upgrade.

Thanks,
David

**Comment by isc-bsaviano** [comment]
@antechdavid No, not yet. I clarified my earlier comment to say "future versions of IRIS".

**Comment by antechdavid** [comment]
Thank you.
