### ISSUE TITLE
Cannot connect to server: "Request to <link> failed, reason: unable to verify the first certificate"

### ISSUE THREAD

**Issue by shanwen-liu** [intersystems-community/vscode-objectscript#1382]
Hello!

I am running an IRIS instance on a remote Linux Redhat 8 server, and the associated Apache webserver is built from source.  Since setting up SSL, I have been unable to connect to the server via the VSCode extension. The error I am getting is "Request to <link> failed, reason: unable to verify the first certificate". The access attempts don't even make it to the Apache access_log file. However, when I query /api/atelier/ from a browser, it returns the expected JSON. The icon that opens a browser to the management portal also works as expected. 

From my research, this issue seems to be related to the way our webserver is set up and the completeness of the certificate chain. However, the folks over at WRC would like me to ask if this could be caused by anything else just in case. For context, browsers do not detect any issues with the way our SSL certificate is set up, but I do know sometimes browsers complete certificate chains for you. 

Please let me know if this could be an issue with the extension, or if this is an issue on our end. Thanks!

**Comment by isc-bsaviano** [comment]
@shanwen-liu I believe that your research is correct. VS Code core handles the certificate loading from the OS. [Here's our documentation](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_config#GVSCO_config_addserver_selfsignedhttps) on how to resolve HTTPS connection errors.
