### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by jtsalten** [intersystems-community/vscode-objectscript#139]
I gave another try to VS Code... it's a great IDE... but, either I'm doing something wrong, of there is no intellisense for ObjectScript whatsoever... I mean, if we declare a variable with #dim we should get inmediate support from the Intellisense mechanism to assist when we need to use properties or methods of that type... otherwise is useless. Perhaps I'm doing something wrong... but I've no intellisense help at all for any of my classes or system classes when I want to know which methods and/or properties are available. If that's so... I can't use VSCode yet for OS.. too painful.

**Comment by daimor** [comment]
there are no intellisense for object members, yet. But there are already many others

- commands
- functions
- classnames, e.g. ##class(), As, Extends
- macroses
- class members by ..

**Comment by jtsalten** [comment]
Now I've just realized that this is same as #73 and #30... sorry to duplicate. Is this enhancement in the near-term roadmap? I think it's a must. Of course there will be many other things to add/improve... but that's sort of minimum...

**Comment by daimor** [comment]
Sure, this in roadmap, should be finished until version 1.0

**Comment by rajrsingh** [comment]
Duplicates  #73 and #30.
