### ISSUE TITLE
Data Transform XData - Open Graphical Editor not working for IRIS For Health

### ISSUE THREAD

**Issue by rwuttk02** [intersystems-community/vscode-objectscript#1392]
Type: <b>Bug</b>

Install Intersystems IRIS for Health 2024.1, for our servers we upgraded from 2023.1.3, either directly to the server or via a container.

Open an existing transform.
Find the XData DTL Block.
Click the Open Graphical Editor link and click OK on the dialog.

Expected Result:

The url is generated correctly based on the Product of IRIS installed and shows the transform.

Actual Result:

A browser window opens with a 404 Not Found error, as the url does not have /healthshare in it for IRIS For Health.

Extension version: 2.12.5
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.21GB free)|
|Process Argv|.code-workspace.code-workspace --crash-reporter-id 6a2fd4dc-7cae-4beb-982b-d7278517d34c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by isc-bsaviano** [comment]
@rwuttk02 Thanks for reporting this. I think the bug is that the extension always uses the `/csp/<namespace>` web application instead of asking the server for the default web application for that namespace.
