### ISSUE TITLE
Allow server-side file to readonly if server-side source control class for namespace returns that status

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1397]
Some source control systems require code to be reserved/checked-out before it is changed.

Since ISFS was originally implemented VS Code's `FileSystemProvider` API has gained the ability for its `stat` method's [FileStat](https://code.visualstudio.com/api/references/vscode-api#FileStat) return value to include an optional `permissions` property of type [FilePermission](https://code.visualstudio.com/api/references/vscode-api#FilePermission). One of its bitmask values is `Readonly`.

I propose adding a boolean setting to make `stat` return `permissions` with the `Readonly` bit set or cleared depending on the value of the `Editable` boolean returned from the [GetStatus](https://docs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?LIBRARY=%25SYS&CLASSNAME=%25Studio.Extension.Base#GetStatus) method of the server-side source control class (if any) of the namespace.

The new setting would default to `false` so the new behaviour is opt-in and thus won't break existing environments.

It would be a resource-level setting so it can be configured server-side per namespace if desired.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray It might be a good idea to mark a class as "read-only" if it's deployed as well
