### ISSUE TITLE
VSCode file open and close events don't register in UserAction of %Studio.SourceControl.Base

### ISSUE THREAD

**Issue by isc-hwojnick** [intersystems-community/vscode-objectscript#1405]
As a part of the git-source-control package, we would like to be able to have the file open and close events register with the %Studio.SourceControl.Base class. This will allow us to make some of our features compatible in VSCode and not just studio and the management portal.

**Comment by isc-bsaviano** [comment]
@isc-hwojnick Should the events be fired only for documents opened in an editor tab, or any document that's "touched"? For example, expanding the unit test tree will "open" the document to resolve its methods, and then it immediately gets "closed".

**Comment by isc-tleavitt** [comment]
@isc-bsaviano I'd vote for editor tab only.
