### ISSUE TITLE
When a project contains CSP files these don't display in Explorer

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1406]
Type: <b>Bug</b>

In the screenshot below compare Studio's representation of the Coffe project's contents with VS Code's:

![image](https://github.com/user-attachments/assets/c6f6d52a-6f4e-4d7e-989f-d10c25793432)

Extension version: 2.12.7-beta.1
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I wasn't able to reproduce this with a project that has a CSP directory in it among other files. Does this only happen with CSP files are the only contents?
