### ISSUE TITLE
Handling of projects gets confused when class package root name matches webapp root name

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1407]
Type: <b>Bug</b>

1. Have a namespace with a Coffee package and a /coffee webapp.
2. Set up an ISFS workspace accessing this namespace.
3. Use the Projects view to add a project (e.g. Coffee).
4. Use the Projects view to add items to this project.
5. Select the coffee folder but not the Coffee package.
6. Try browsing the project in the Projects view.

:bug: the CSP Files folder contains nothing but the Classes folder shows a subfolder named 'coffee' which is empty when expanded.

Extension version: 2.12.7-beta.1
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Can you export your project and send it to me so I can use it to debug this?

**Comment by gjsjohnmurray** [comment]
[Show1407.zip](https://github.com/user-attachments/files/16362287/Show1407.zip)

1. Add a /show1407 web application to your IRIS server, making it a copy of the existing /csp/user one but appending `\show1407` to its physical path.
2. Import the .xml file in the attached ZIP into your USER namespace, e.g. from Studio. This should do the following:

- Create a Show1407 project.
- Add a Show1407 package containing a single class.
- Write a CSP file into the folder that the /show1407 webapp points to.

3. In VS Code use Server Manager to find the project, then create a workspace to edit its contents.
4. Compare what Explorer shows with what the Projects view shows:

![image](https://github.com/user-attachments/assets/b2f80698-bdfe-433d-b0cc-089c8bf4aff3)

Notice that Explorer only shows the class.

To see the issue originally reported, proceed as follows:

1. From a context menu in Projects view, create a new project "New1407".
2. Use the "Add Items" context menu option to add the "show1407" folder but not the "Show1407" package.
3. Explore the "New1407" project in Projects view:

![image](https://github.com/user-attachments/assets/504bc8c4-9f3d-4407-a470-3416a7c249b9)

Notice that the Classes folder unexpectedly contains "show1407", presumably because a package of the same (case-insensitively) name exists in the namespace.

Also notice that the CSP files folder doesn't contain the "show1407" folder despite that being what I added to the project.

**Comment by isc-bsaviano** [comment]
Thanks, John. I will look at this.
