### ISSUE TITLE
Add a confirmation step to the `Delete Project` command.

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#1409]
Type: <b>Feature Request</b>

I think it is currently too easy for people to delete projects, with no undo mechanism. By comparison, in Studio you have to use Open Project... to bring up the project selector dialog, then right-click on the one you want to delete, choose the delete option, then go through a confirmation dialog.

Extension version: 2.12.7-beta.1
VS Code version: Code - Insiders 1.92.0-insider (7ed4cdc56d037146b2c4c890f09e78b2ba14b49d, 2024-07-24T07:50:18.385Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by isc-bsaviano** [comment]
Seems reasonable to me
