### ISSUE TITLE
 it is not possible to work with csp on the server side on windows

### ISSUE THREAD

**Issue by kseledkov** [intersystems-community/vscode-objectscript#142]
Долго не мог настроить редактирование csp по приведенной инструкции. Оказалось, схема работает только если vscode работает под unix, под windows код правиться, но не сохраняется на сервер и не компилируется. Причем это при обращении к одному и тому-же серверу cache.
Похоже проблема в обратных слешах в адресе файла которые vscode шлет в api atelier.
В unix среде ссылка для компиляции имеет вид /api/atelier/v3/sirena/doc/sirena/idx1.CSP и все работает, а под windows requested URL /api/atelier/v3/sirena/doc/\\sirena\\idx1.CSP и файл не находится.
Можно сделать так, чтобы редактирование на стороне сервера работало и под windows тоже?

**Comment by daimor** [comment]
Спасибо, посмотрю как можно поправить

**Comment by daimor** [comment]
Could you check it with the latest [beta release](https://github.com/intersystems-community/vscode-objectscript/releases)? It looks like it works well now.

**Comment by kseledkov** [comment]
I checked it on the last beta, now everything works under Windows. Thanks you.
