### ISSUE TITLE
When access to 'Source Control' appears user 'UnknownUser' instead of the logged in user.

### ISSUE THREAD

**Issue by EcheJP** [intersystems-community/vscode-objectscript#1422]
Type: <b>Bug</b>

A new installation of CCR was made on the server a few weeks ago. When we try to perform any action with the version control from vscode it appears that it has been performed with the user 'UnknownUser' instead of the one we logged into the server.

For example, if we 'Check-out' a document to edit it, if we access the 'CCR Controls' panel from the Studio, we will see that it has been done with the 'UnknownUser' user. This prevents us from being able to work 100% with vscode.

To reproduce the error we access to 'ObjectScript: Server Source Control...' and to the option 'Show CCR Controls' the user 'UnknownUser' appears.

Extension version: 2.12.7
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2400G with Radeon Vega Graphics (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.93GB (5.14GB free)|
|Process Argv|--crash-reporter-id ba8e4b40-083f-4379-b845-2e916596fc46|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31118572

```

</details>

**Comment by isc-bsaviano** [comment]
@EcheJP I activated a test source control class and verified that the `$USERNAME` when I add an item to source control is the user that I am connected to IRIS as. Have you contacted the WRC to see if this could be a CCR issue? Can you show me your VS Code server configuration that you're using?

**Comment by gjsjohnmurray** [comment]
@EcheJP please also confirm the $ZVERSION of your server.

**Comment by EcheJP** [comment]
> @EcheJP I activated a test source control class and verified that the `$USERNAME` when I add an item to source control is the user that I am connected to IRIS as. Have you contacted the WRC to see if this could be a CCR issue? Can you show me your VS Code server configuration that you're using?

The VS Code server configuration I am using is as follows:

```json
{
    "intersystems.servers": {
        "trak-int": {
            "webServer": {
                "scheme": "http",
                "host": "traklnxint",
                "port": 57772
            },
            "username": "jpsanchez"
        }
    },
    "intersystems.language-server.suggestTheme": false,
    "intersystemsServerManager.credentialsProvider.deletePasswordOnSignout": "never",
    "redhat.telemetry.enabled": false,
    "better-comments.highlightPlainText": true,
    "terminal.integrated.enableMultiLinePasteWarning": false,
    "terminal.integrated.fontSize": 14,
    "editor.inlineSuggest.enabled": true,
    "objectscript.showProposedApiPrompt": false,
    "window.title": "${dirty}${remoteName}${separator}${activeEditorShort}${separator}${rootName}",
    "security.workspace.trust.untrustedFiles": "open",
    "objectscript.export": {
        "folder": "src",
        "addCategory": false,
        "map": {},
        "atelier": true,
        "generated": false,
        "filter": "",
        "exactFilter": "",
        "category": "*",
        "noStorage": false,
        "dontExportIfNoChanges": false,
        "maxConcurrentConnections": 0,
        "mapped": true
    }
}
```

I have contacted WRC but we are awaiting a response.


> @EcheJP please also confirm the $ZVERSION of your server.

I use IRIS for UNIX (Red Hat Enterprise Linux 9 for x86-64) 2023.1.3 (Build 517U) Wed Jan 10 2024

**Comment by EcheJP** [comment]
Yes, that server is correct. Well, I'm looking to see if WRC can solve what is happening.

Thank you very much for your attention.
