### ISSUE TITLE
Proposed APIs don't work on VS Code 1.93.0 if the server-side folder URI contains query parameters

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#1427]
Originally it stopped working for me in VSCode Insiders a few weeks ago, but I thought it was me, and I needed to find whether I messed up a setting.

But my stable VSCode just upgraded to 1.93.0 and Ctrl-P stopped working there as well. It's possible they renamed their Quick Open API or did something with the FileSearchProvider?

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ Are you sure you have a beta version installed? This is working for me on VS Code 1.93.0 with extension version 2.12.8-beta.1. The VS Code team has been doing work on the `FileSearchProvider` and `TextSearchProvider` in preparation for finalizing them, but that work hasn't broken the existing proposals.

**Comment by RyszardWithAZ** [comment]
I am running 
intersystems-community.vscode-objectscript version 2.12.8-beta.2 activating with proposed APIs available.
I also tried downgrading this to an older version and same deal.
That's weird that it's still working for you. I've done nothing else except let VSCode upgrade. Hm. And it's weird that my Insiders stopped working a while ago, and TODAY stable stopped working after I saw it upgraded.

**Comment by isc-bsaviano** [comment]
Does the server-side text search work?

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ I believe this is a VS Code bug that only appears when the folder being searched has query parameters in the URI. I've opened https://github.com/microsoft/vscode/issues/227836 to report it.

**Comment by RyszardWithAZ** [comment]
Hmm, the server-side text search also doesn't work.  Although now my entire shared dev env just went down. It's a Friday at 5:15. Yay. As soon as it comes back up (probably Monday), I can test that by rewriting my URI to not include any query parameters.

**Comment by isc-bsaviano** [comment]
This issue has been fixed in the latest Insiders and the fix will be available in VS Code 1.95.0.

**Comment by isc-bsaviano** [comment]
1.95.0 has been released
