### ISSUE TITLE
Import and Compile has become very slow since VS Code 1.93

### ISSUE THREAD

**Issue by jpa95** [intersystems-community/vscode-objectscript#1428]
The process seems to work but it will import 4-5 files, then block for 10+secs, then get 4-5 more, etc. Not usable in out context.

Downgrading to VS Code 1.92.2 solves my problem.

InterSystems ObjectScript v2.12.7
InterSystems Server Manager v3.6.2
InterSystems Language Server v2.6.1

**Comment by mathewrimmingtoncds** [comment]
The company I work for are also getting this problem. I did have a look through the source code on this repo and can see some suspect looking code in the request method of index.ts, but I can't explain why it would have worked fine prior to VSCode 1.93.

**Comment by GendronAC** [comment]
Reproduced in 1.93.1 too

**Comment by gjsjohnmurray** [comment]
> some suspect looking code in the request method of index.ts

@mathewrimmingtoncds Are you able to be more specific?

**Comment by mathewrimmingtoncds** [comment]
> > some suspect looking code in the request method of index.ts
> 
> @mathewrimmingtoncds Are you able to be more specific?

Take a look at this: https://github.com/intersystems-community/vscode-objectscript/blob/a53daf7bad0b6aeb1fbfc747dbc893e9dcf5a9b9/src/api/index.ts#L306C1-L310C8
It appears to be creating a new keep alive connection for every single request! Full disclosure here: I don't know how to debug VSCode extensions so haven't proved this is the cause. It just looks bad.

I logged a WRC ticket too, the saliant bit of the response from them was:
> I looked into this and I think the problem is that VSCode does not reuse the already-established HTTP connections for new requests. Just about any action in VSCode (including compiling or import-and-compile) will result in API calls to the backend. We set the keepAlive flag to true with the intention of saving the connections in a pool. In 1.93 we apparently never pull connections out of the pool, and so the number of ESTABLISHED connections in netstat keeps rising.

Unfortunately WRC have denied being able to help to repair this. It's a shame that IRIS will soon have no editor and the one one nice way of editing source code is not supported by them.

**Comment by gjsjohnmurray** [comment]
If you have a reliable repro for this issue and are willing to try an updated VSIX please download the zipfile at https://github.com/intersystems-community/vscode-objectscript/actions/runs/10928954754/artifacts/1949752034 and extract the VSIX it contains. Install that (drag/drop onto the Extensions view is one way), restart VS Code, then try your repro again.

**Comment by jpa95** [comment]
Hi John,

on v2.12.8-dev.1432 with VS Code 1.93.1:
Import and Compile of a folder with a small number of files (less than 10), it works well, speed seems as good as before.

On larger number of files, the first 30-50 imports go fast, then the process slows down to a crawl. Files are still being imported but at seemingly random points the process stops writing the import message, nothing happens for many seconds (random amount of time, sometimes 1+ min).

When it finished importing my 168 files (took 5 minutes), it started compiling and took about 2-3 minutes to report that "Compilation finished successfully in 0.159s."

Went back to VS Code 1.92.2 and it works.

**Comment by gjsjohnmurray** [comment]
@jpa95 please try running this command from outside VS Code (prerequisite is a local install of Node.js):

npx --yes @vscode/vscode-bisect@latest --releasedOnly --bad 4849ca9bdf9666755eb463db297b69e53
85090e3 --good b1c0a14de1414fcdaa400695b4db1c0799bc3124

It will download a 1.93.0-insider build and launch it. Use it to run your repro. This first build should be about half way between the start of 1.93 (i.e. just after 1.92 Stable shipped) and the end of it (when 1.93 Stable shipped). The command session you launched the bisect command wants you to answer "Good" or "Bad", at which point it will close the VS Code it launched and download either an earlier one (if you said "Bad") or a later one (if "Good").

I hope this procedure may eventually point to the first 1.93.0-insider build that has the problem. Builds usually happen once per weekday, so success here ought to narrow down the set of commits for me to seek clues in.

**Comment by gjsjohnmurray** [comment]
> Unfortunately WRC have denied being able to help to repair this. It's a shame that IRIS will soon have no editor and the one nice way of editing source code isn't working very well and is not supported by them.

@mathewrimmingtoncds this has been miscommunicated. WRC have referred the issue to the extension devs (I am one of them) and we are working to resolve it.

If you are in a position to follow the VS Code bisect procedure I described above this may help us pinpoint what changed in 1.93 to cause it.

**Comment by gjsjohnmurray** [comment]
New VSIX for testing is in https://github.com/intersystems-community/vscode-objectscript/suites/28622933729/artifacts/1956331615

This one no longer sets`keepAlive: true` on its http[s].Agent, which had long been done by us but which until 1.93 was apparently not forwarded to Node.js by the proxy agent.

🤞

**Comment by jpa95** [comment]
Houston, we don't have a problem!

Looks very good @gjsjohnmurray, thanks! Tested with VS Code 1.93.1. Imported two separate filesets that have 1k+ files in them (in one go each), as usual.

I'll keep using it in my everyday tasks and get back here if I see a problem.

**Comment by jpa95** [comment]
Oh and apologies I did not see your `npx --yes` answer yesterday.

**Comment by gjsjohnmurray** [comment]
Anyone experiencing this problem should download https://github.com/intersystems-community/vscode-objectscript/releases/download/v2.12.8-beta.3/vscode-objectscript-2.12.8-beta.3.vsix and verify (hopefully) that the slowdowns no longer occur on VS Code 1.93+

If it passes your testing please add a comment here. Unless there are any adverse reports we plan to publish v2.12.8 on Marketplace early next week.

**Comment by jpa95** [comment]
@gjsjohnmurray beta 3 looking good.

**Comment by mathewrimmingtoncds** [comment]
@gjsjohnmurray, this release works for me too, thanks. I can import a few hundred routines quickly and I'm not left with any established connections when running netstat.

**Comment by gjsjohnmurray** [comment]
Thanks all. Please update to v2.12.8 from Marketplace, or if you want to use proposed APIs get [v2.12.9-beta.1](https://github.com/intersystems-community/vscode-objectscript/releases/download/v2.12.9-beta.1/vscode-objectscript-2.12.9-beta.1.vsix) and install it.
