### ISSUE TITLE
support objectscript in MD fenced codeblock

### ISSUE THREAD

**Issue by isc-lindensc** [intersystems-community/vscode-objectscript#1430]
Hi,

not sure if this is the correct area or if this should go into languageserver.

Could we consider to provide fenced code block support for markdown? ref https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example/tree/master

Currently if you write markdown you can highlight a codeblock with 3 ticks plus language and if supported the code inside the codeblock will be highlighted according to the language.

currently using <code>```objectscript</code>

```objectscript
write !,"This is a test!"
```

is not getting highlighted
while below works <code>```sql</code>
```sql
select sample from sample.table
```

above is github working as intended here now same from vscode:
![image](https://github.com/user-attachments/assets/5e96343e-2ada-4ea9-9f93-23db1e0ca43a)

**Comment by gjsjohnmurray** [comment]
Related to #964

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Is there anything we can do about this? I assume that even if we could only the TextMate coloring would be available.

**Comment by isc-bsaviano** [comment]
Thanks for the link John
