### ISSUE TITLE
Outline view mixes Foreign Key and Trigger definitions together with Properties

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1441]
I have these items in my class definition:
 `ForeignKey CustomerFK(Owner) References Bank.Customer();`
`Trigger AccountUpdate [ Event = UPDATE, Foreach = row/object ]`

Their types **are** listed correctly in the Outline view.
However, they both use the Property icon (wrench) and they are sorted together with other properties. Also, the hover text is confusing because it shows "(property)".

<img width="1000" alt="Screenshot 2024-10-01 at 11 50 43 AM" src="https://github.com/user-attachments/assets/41ece204-0cdc-4ca2-9dae-f5a426c56a3a">
<img width="1000" alt="Screenshot 2024-10-01 at 11 50 17 AM" src="https://github.com/user-attachments/assets/ff69624a-26e0-4fe6-b874-41ca04f43e19">

**Comment by isc-bsaviano** [comment]
@isc-solon Those icons and hover text are generated from the VS Code `SymbolKind` we assign to each element. The full list of options can be found [here](https://code.visualstudio.com/api/references/vscode-api#SymbolKind). I thought the property one made sense for those types as well.

**Comment by isc-solon** [comment]
I didn't know that. I wonder how the team/community would feel about using Event (23) for Triggers and FKs. I don't know if that's the intent of Event. But both Triggers and FKs cause special extra code to run when saving/deleting events happen. So it matches up, kind of.

**Comment by isc-bsaviano** [comment]
I agree that Event could make sense for Triggers, but I still see ForeignKey as more of a type of Property than an event. The actual code that controls this is in the Language Server but some code here might need to change as well.

**Comment by isc-bsaviano** [comment]
[Here's](https://github.com/intersystems/language-server/blob/221486ac99e50b03ab0a0d73ff8f42a7fedf55f7/server/src/providers/documentSymbol.ts#L96-L108) the relevant Language Server code. We may want to add even more granularity:

```typescript
var kind: SymbolKind = SymbolKind.Property;
if (keywordtextlower.indexOf("method") !== -1 || keywordtextlower === "query") {
	kind = SymbolKind.Method;
}
else if (keywordtextlower === "parameter") {
	kind = SymbolKind.Constant;
}
else if (keywordtextlower === "index") {
	kind = SymbolKind.Key;
}
else if (keywordtextlower === "xdata" || keywordtextlower === "storage") {
	kind = SymbolKind.Struct;
}
```
What do you think @gjsjohnmurray?
