### ISSUE TITLE
Syntax highlighting issue

### ISSUE THREAD

**Issue by martin-weber-mycts** [intersystems-community/vscode-objectscript#145]
The right side of the = sign is always highlighted as command though it should be a variable
` 	set xy = set `
` 	if set = do `
` 	set set = test`

The lefthand side doesn't seem to be affected. 
When placing the variable directly to the = without spacing the highlighting is correct. 
` 	set set =do`
In our case this was when using  ` i` for iteration purpose.

**Comment by jmarkmorris** [comment]
The following code also reveals some syntax highlighting issues.

set a = 0
    set b = 0

    write a , !
    write a, !
    write b , !
    write b, !
    write a _ b , !
    write a _ b, !

**Comment by daimor** [comment]
Yeah, due to simplicity of current syntax highlighting based on textmate, it’s not so easy to solve. The new way is on the way, and should arrive this fall I hope

**Comment by aray-isc** [comment]
On the topic of syntax highlighting, see also #175.

**Comment by rajrsingh** [comment]
This will all be fixed by the upcoming syntax highlighting support, so I'll close it as wontfix.
