### ISSUE TITLE
Copy+paste in lite terminal causes misformatting

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems-community/vscode-objectscript#1450]
When I try to copy+paste into the lite terminal, the formatting gets messed up. This can be seen in the screen recording below.
Note that this happens from any sort of copy. Not just from the "Copy Invocation". 
You can see that a part of the text still appears in the view when I use up arrows to change to older commands in the terminal.

VS Code version:

Version: 1.94.1
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0

Extension version: 2.12.9-beta.5

https://github.com/user-attachments/assets/265a556f-ab80-4f3f-bb03-07a301bd0477

**Comment by isc-bsaviano** [comment]
@isc-kiyer Can you please try the vsix found [here](https://github.com/intersystems-community/vscode-objectscript/actions/runs/11505972034/artifacts/2100821282) and let me know if it fixes your issue? Thanks.

**Comment by isc-kiyer** [comment]
@isc-bsaviano that fixed the issue!
