### ISSUE TITLE
Enhancement request for ZPM package creation

### ISSUE THREAD

**Issue by zrml** [intersystems-community/vscode-objectscript#146]
Hi,

_Issue_:
When I am done working on a development project I usually need to wrap the package(s) in an artefact/module/component so that I can quickly share it or move it to a testing environment.

_Enhancement Request_:
The VS Code plugin should have an option to create a ZPM module so that code installation on a different node can be automated and even driven by the same VS Code as it points to this second node.

**Comment by gjsjohnmurray** [comment]
Maybe implement this as a separate extension.

**Comment by isc-bsaviano** [comment]
I agree with John
