### ISSUE TITLE
Respect windows line-endings

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/vscode-objectscript#149]
https://github.com/intersystems-community/vscode-objectscript/blob/7338a1de3942b7c05601c4e117b65b044096d50d/src/commands/compile.ts#L51

When a file is saved/compiled through this extension the line-ending is hardcoded to \n. 

It should either be determined by platform or respect the `files.eol` VSCode setting.

Where this issue manifests is git repos maintained by Linix/macOS and Windows developers. On windows it is typical for the windows developers to use `core.autocrlf=true` to let git manage the line endings; but that doesn't work when files are written using \n endings and leads to whitespace-only diffs.

One workaround is to have Windows users set `core.autocrlf=input` which will keep the \n line-endings instead of converting to CRLF.  This only works though if all the tools the Windows developer uses are capable of read/write \n endings - VSCode does but others may not (e.g. a windows script, or a file consumed by a IRIS/Ensemble script).

**Comment by daimor** [comment]
VSCode itself, already have own control over line endings in files. So, I think the best way to be here is to respect this. The status bar shows what's it uses now.
