### ISSUE TITLE
Unable to create multi-environment workspace

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#162]
Hi Dmitriy,

Here's the layout in VS Code's Explorer:

![image](https://user-images.githubusercontent.com/4532366/85233311-555f4600-b3d3-11ea-9bea-b45d2fa779b8.png)

The code-workspace file from the Workspace top-level directory:

![image](https://user-images.githubusercontent.com/4532366/85233322-60b27180-b3d3-11ea-857d-193b4c681238.png)

Note that I've tried both manually creating the file and adding directories to the workspace using the VS Code menus. The only difference I can see in the result is that the json name value appears in the explorer tree rather than the actual directory name.

Heres's a .vscode\settings.json file from one of the directories referenced in the code-workspace file shown above:

![image](https://user-images.githubusercontent.com/4532366/85233341-6d36ca00-b3d3-11ea-8bce-a9e66c4e082b.png)

The oddest symptom is that when I change just one of the settings.json files, all directories change to those value in the OBJECTSCRIPT:EXPLORER view (only the file I've actually edited and saved has the changes in it, though):

![image](https://user-images.githubusercontent.com/4532366/85233345-758f0500-b3d3-11ea-9c91-48f452aba022.png)

Also, another weird issue is that if I select a directory in the OBJECTSCRIPT:EXPLORER view and choose "View another namespace," it opens the namespace for that directory but duplicates all of the existing directories including the one that just had it's namespace changed.

Before:

![image](https://user-images.githubusercontent.com/4532366/85234183-9fe3c100-b3d9-11ea-91d8-e5768aad9186.png)

Select namespace (FTP):

![image](https://user-images.githubusercontent.com/4532366/85234217-e20d0280-b3d9-11ea-9ca2-b5b82d40a442.png)

After:

![image](https://user-images.githubusercontent.com/4532366/85234265-15e82800-b3da-11ea-8c79-258ce51e4581.png)

Thanks for looking into this.

PS.

Just in case it matters:

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by DodgeDeBoulet** [comment]
Hi Dmitry, is there anything else I can do to help troubleshoot this? It would be a very useful feature on a project I am currently working on.

Thanks!

**Comment by gjsjohnmurray** [comment]
@DodgeDeBoulet are you able to re-test in 0.8.7? Does "View another namespace" still create multiple entries?

**Comment by DodgeDeBoulet** [comment]
Same issue in 0.8.7. It refuses to honor the configuration settings in each directory defined under the workspace, and while it seems to be fetching the namespaces from the connection in the first directory it finds, it shows them all like this in the Objectscript view:
![image](https://user-images.githubusercontent.com/4532366/88689255-45204200-d0c8-11ea-9bce-1ab8a469107d.png)

Here's the dropdown with the namespace list:
![image](https://user-images.githubusercontent.com/4532366/88689535-94ff0900-d0c8-11ea-9ee7-9fc279649724.png)

And finally what the list looks like after I selected the ADN namespace (new server added to list):

![image](https://user-images.githubusercontent.com/4532366/88689730-dabbd180-d0c8-11ea-99fb-384edd45e84c.png)

Interestingly it shows a different list of namespaces when selecting different servers, but it does NOT show all namespaces for any of them!

**Comment by gjsjohnmurray** [comment]
@DodgeDeBoulet please download [this zip](https://github.com/intersystems-community/vscode-objectscript/suites/975684267/artifacts/12425057) to get a pre-beta vsix I'd like you to try your workspace with.

**Comment by DodgeDeBoulet** [comment]
Looking a lot better! I see all of the servers now. BUT ...

I'm getting this error/warning in the OUTPUT window for ObjectScript:
Studio Action "Changed Namespace" not supported
Studio Action "Changed Namespace" not supported
Studio Action "Changed Namespace" not supported

And when I select a new namespace, it creates another server object in the ObjectScript Explorer window. That may be by design, since I think it might be useful in some cases. I think it would be better to make it optional; ask the user if they want to open a new server in the workspace or change the namespace for the existing one.

**Comment by gjsjohnmurray** [comment]
> Looking a lot better! I see all of the servers now.
Excellent! Thanks for testing and confirming,

> I'm getting this error/warning in the OUTPUT window for ObjectScript:
> Studio Action "Changed Namespace" not supported

This is #171.

> And when I select a new namespace, it creates another server object in the ObjectScript Explorer window. 

Yes, I think this is by design. It ensures you always have a root folder in OE that corresponds to the namespace your client-side folder is linked to.

Perhaps there should be a way of removing the root folder of an additional namespace you opened. Or of switching that to a different namespace.

Personally I prefer using isfs:// or isfs-readonly:// root folders in the main VS Code Explorer view rather than the separate ObjectScript Explorer. You can set up any number of these, and target specific namespaces.

**Comment by DodgeDeBoulet** [comment]
So as I said yesterday, I'm able to see the servers and list all the classes in each namespace. What I don't seem to be able to do now is actually open and edit any of the code. I don't get a preview on selection, and it doesn't open the class/routine when I double-click. Is there a setting I'm missing?

The isfs:// method sounds intriguing but I'm not sure how to take advantage of it.. Is it new?

**Comment by gjsjohnmurray** [comment]
> I don't get a preview on selection, and it doesn't open the class/routine when I double-click.

I wonder if your connection is disabled. Do you see this in the status line?

![image](https://user-images.githubusercontent.com/6726799/88872478-2928b780-d212-11ea-96b1-1b992dfc93f7.png)

If yes, click on it to get a "Toggle Connection" command in a quickpick in the top centre of the VS Code window. Choose that to connect.

> The isfs:// method sounds intriguing but I'm not sure how to take advantage of it.. Is it new?

isfs has been available for a while, but isfs-readonly is new. There's some isfs doc at https://github.com/intersystems-community/vscode-objectscript/wiki/Server-side-editing but that wiki page hasn't yet been updated to reflect 0.8.7's introduction of `intersystems.servers`. That makes it easier to set up a single workspace that accesses multiple servers over isfs or isfs-readonly.

**Comment by DodgeDeBoulet** [comment]
I get an occasional error that it's disconnected, but nothing showing that it's disabled. Cycling the connection doesn't make a difference. And sometimes, rarely, I can open and at least view a class, but most of the time not.

The particular site I'm working with is migrating from Cache/Ensemble 2018.2.1 to IRIS for Health 2020.1. The former is on SUSE Linux while the latter is on RedHat (but I doubt that really makes a difference).

I do keep getting **host, port and ns must be specified.** But they ARE specified for all of the folders I've defined with connection settings.

**Comment by DodgeDeBoulet** [comment]
Sorry if this isn't the right avenue for asking this, but can I use a Server Manager entity as the "server" value in the folder configuration? It seems to work, sort of. I just get this:

![image](https://user-images.githubusercontent.com/4532366/88933024-d7515300-d24c-11ea-9ea4-bb5e383dfaa8.png)

**Comment by gjsjohnmurray** [comment]
When `server` is set in `objectscript.conn` the `username` and `password` properties are ignored and have to come from Server Manager. There's a bug in 0.8.7 that means Server Manager doesn't always provide these to a caller. I suggest you install [this beta VSIX](https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.8.8-beta.14), where the bug is fixed.

**Comment by gjsjohnmurray** [comment]
@DodgeDeBoulet  0.8.8 is now published. Please update and let us know the state of this issue.

**Comment by DodgeDeBoulet** [comment]
Hi John, 

I now get errors and the connections are no longer established.

Has the requirement to include the password in the Server configuration been removed? I'm reluctant to experiment too much given that the IRIS servers I'm trying to work with are LDAP-enabled and my last troubleshooting session deactivated my Active Directory account. Here's the error:

```
{
	"resource": "/C:/Users/Jeff/AppData/Roaming/Code/User/settings.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Storing password in plaintext is not recommended. Instead, use the Command Palette command to store it in your keychain.",
	"startLineNumber": 15,
	"startColumn": 13,
	"endLineNumber": 15,
	"endColumn": 47
}
```

**Comment by gjsjohnmurray** [comment]
That's copied from an entry on the Problems panel when you've opened your settings.json, right?

It's not an error, only a warning. When you view that line of the settings.json file you'll see a yellow squiggly underneath your `password` property. Hovering over this gives the same message.

I recommend you remove the line, then use Command Palette to run `InterSystems Server Manager: Store Password in Keychain`, choose your server and enter your password.

Now restart VS Code and reopen your workspace. You should find it connects using the password it retrieved from your keychain.

**Comment by DodgeDeBoulet** [comment]
Yes, that was from the Problems panel. I didn't expect to get JSON from copying the output, but it had all of the supplied information so I pasted it anyway 😀

I appear to be connected to all servers now. The issue is that none were appearing when I selected the ISC icon, and the only error indicator I was getting was the word ERROR in the status bar. This is apparently the only information provided when there are no servers with an "active" value of true in the workspace.

I'm still having an issue, though, and it's one that I experienced previously and reported. Here's how I triggered it:

I closed all editors from the Explorer menu (most had the individual directories' .vscode/settings.json open in them), returned to the ObjectScript Explorer, and could no longer open a class or routine for viewing or editing for any of the servers. Right clicking on a class name gives me a context menu, but there is no "Open" or "View" option.

If I go back to Explorer and re-open the settings.json file in the server's .vscode directory, I can return to the ObjectScript Explorer and again open classes and routines. This seems counterintuitive to me.

**Comment by gjsjohnmurray** [comment]
> Right clicking on a class name gives me a context menu, but there is no "Open" or "View" option.

I don't recall ever seeing "Open" or "View" in the OE context menu. Just clicking on a class in the OE tree should open it, albeit in preview mode (tab in italics).

I suggest you open a fresh issue and paste some screenshots. Info shown in the status bar and in the ObjectScript Output panel may be useful.

**Comment by DodgeDeBoulet** [comment]
I'm also continually getting "host, port and ns must be specified" errors even though the host and port are specified in the Server settings and the namespace is provided in the individual directory settings files.

**Comment by DodgeDeBoulet** [comment]
> > Right clicking on a class name gives me a context menu, but there is no "Open" or "View" option.
> 
> I don't recall ever seeing "Open" or "View" in the OE context menu. Just clicking on a class in the OE tree should open it, albeit in preview mode (tab in italics).
Apologies, I should have been clearer. I assumed that Open or View would be a context menu choice based on my experience with non-VS Code editors 😉 
> 
> I suggest you open a fresh issue and paste some screenshots. Info shown in the status bar and in the ObjectScript Output panel may be useful.

I get no output in the ObjectScript Output panel, and I'm not sure how to post a screenshot of nothing happening when I click on the classname ... is there some debug feature I can turn on that shows what should be executing when I click on a class?

**Comment by gjsjohnmurray** [comment]
@DodgeDeBoulet are you happy to close this one?

**Comment by DodgeDeBoulet** [comment]
Yes, delighted to. Thanks.
