### ISSUE TITLE
Use host keystore for password storage

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#196]
Deprecate/remove `objectscript.conn.password` property and replace it with the option to store connection passwords in the keystore of the VS Code host platform.

Relevant to #119, #135, #192

**Comment by daimor** [comment]
I'm Ok with password storage, but I think we should keep stored password as is as well.

**Comment by gjsjohnmurray** [comment]
Server Manager 0.0.4 can store passwords in the host keystore/keychain. Release 0.8.7 is able to use Server Manager. Closing.
