### ISSUE TITLE
Output window does not get updated until there is an issue

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#204]
Start VS code, create new class and save, nothing appears in the output.  Add an issue say remove the ; from the end of the property and save, the output window is now updated with the new and old information.

`Class MyPackage.MyClass 
{

Property Foo As %String;

}`

**Comment by bourette** [comment]
This is using the server manager connection.

**Comment by daimor** [comment]
> Add an issue say remove the ; from the end of the property and save
Where it's appeared?

**Comment by bourette** [comment]
The compile issue then appeared in a pop up in and in the output window.  At that time, if you scroll up you can see all the positive outcomes.

**Comment by gjsjohnmurray** [comment]
@bourette is your issue that the ObjectScript output channel isn't automatically shown in the case where the new class saves successfully?

If you had manually selected that output channel before saving the new class, do you see the expected message upon saving?

**Comment by bourette** [comment]
No the issue is that the Output window is empty, even after selecting the output channel before saving.  Very easy to reproduce, restart vscode, create class User.Foo and save, there is a notification that it saved, but in my case it told me it couldn't add it source control because of my settings, but all of that was hidden until there was a subsequent save failure.  I do say hidden, because it's all there, just not visible.

**Comment by gjsjohnmurray** [comment]
@bourette so is it specifically some output text from your source control class that's not displaying in a timely fashion? If so, maybe @ty-d can help diagnose the cause.

**Comment by bourette** [comment]
I wouldn't say it's specific to source control.  I think you should just try the steps to see, it only takes a few seconds, the restart of VSCode is the most important.

**Comment by gjsjohnmurray** [comment]
I **have** tried them but I can't reproduce what you seem to be describing.

Are you positive that your output panel is set to the "Output" tab **and** the dropdown is set to "ObjectScript" before you save your changed but syntactically valid class?

![image](https://user-images.githubusercontent.com/6726799/90275965-08d83a00-de5b-11ea-8d53-86a7bfb6d5b5.png)

**Comment by bourette** [comment]
User error.
