### ISSUE TITLE
Dynamic objects created with {} cause compile errors

### ISSUE THREAD

**Issue by Dudelmoser** [intersystems-community/vscode-objectscript#214]
This issue appeared a few weeks ago, but I don't know if it's caused by the IRIS 2019.1 backend or this extension.

Curly braces will be separated by a space on compile which in turn makes the code uncompilable because the compiler seems to confuse the DynamicObject with a code block.

I can work around it by replacing `set obj = {}` with `set obj = ##class(%DynamicObject).%New()`, but the first syntax is obviously much cleaner and always worked in the past. Furthermore it breaks existing classes as soon as I slightly alter and compile them.

**Comment by daimor** [comment]
Could you check with the latest [beta release](https://github.com/intersystems-community/vscode-objectscript/releases)?

**Comment by Dudelmoser** [comment]
The beta seems to fix the issue but has another bug.

`Class 'Example.Package.ClassName' contains invalid characters '..'`

listing exactly the number of dots I used for the full class name (including package).

**Comment by daimor** [comment]
That issue already fixed and should be ok in 0.8.7-beta.30

**Comment by Dudelmoser** [comment]
![image](https://user-images.githubusercontent.com/16316772/88393372-cec8ca80-cdbd-11ea-9d17-15fe9e96936f.png)

![image](https://user-images.githubusercontent.com/16316772/88393431-e43df480-cdbd-11ea-948f-37b8860870c4.png)

Doesn't seem to be fixed 😕

**Comment by daimor** [comment]
Sorry, did not notice, that release build failed, now beta.31 should have that fix

**Comment by Dudelmoser** [comment]
Indeed, thank you a lot for the quick fix :)
