### ISSUE TITLE
As of version 0.8.7 in VS Code my workspace can no longer connect to the InterSystems IRIS server, I did not change any settings, the settings are no longer available

### ISSUE THREAD

**Issue by BuzzyLizzy** [intersystems-community/vscode-objectscript#223]
As of version 0.8.7 in VS Code my workspace can no longer connect to the InterSystems IRIS server, I did not change any settings, the settings are no longer available. In the Settings panel under "InterSystems Objectscript: the connection settings have disappeared, they are no longer available and my VS Code no longer connects to IRIS server, I checked the JSON settings but it does not work I also installed InsterSytems server Manager still no luck.
When I downgrade to 0.8.6 so that I can see the connection settings again and set them up correctly it connects, so there is nothing wrong with my connection to the server, when I upgrade again to 0.8.7 without changing any settings (well I cannot change in settings because they have disappeared, can only change in JSON), then it no longer connects, it is broken.

**Comment by daimor** [comment]
Please could you add your settings here?
Since this version, all the properties in the connection settings are mandatory to define. So, you have to specify, `host`, `port`, `username`, `password`, `ns`

**Comment by BuzzyLizzy** [comment]
I tried these settings in workspace:
these are the same settings I used before in v8.0.6
![image](https://user-images.githubusercontent.com/14235027/88554930-6715b800-d027-11ea-9d1c-111d976a9570.png)

I uploaded a screenshot of settings, please let me know if you do not get

**Comment by daimor** [comment]
You have to define port as well

**Comment by BuzzyLizzy** [comment]
O gosh, thank you, that was embarrassing :-$

**Comment by BuzzyLizzy** [comment]
We still have an issue connecting to IRIS server. I now have another project open where I entered settings exactly correct, it does not connect, my colleagues are experiencing the same, the connection does not connect even if I click the "refresh" in the ObjectScript panel on the left
![image](https://user-images.githubusercontent.com/14235027/88814762-d2dc5a00-d1ba-11ea-855f-7ce89ec09b22.png)

**Comment by gjsjohnmurray** [comment]
Anything being reported in the ObjectScript view of the Output panel?

Does the Refresh button on the "OBJECTSCRIPT: EXPLORER" header make anything happen?

**Comment by BuzzyLizzy** [comment]
My apologies for the late reply.
The refresh button does not make anything happen.
How does one see the "Objectscript view of the output panel", I see the standard Output panel at the bottom and there is nothing displayed there.

**Comment by BuzzyLizzy** [comment]
OK, I found where to change output to "objectscript", and nothing there.

![image](https://user-images.githubusercontent.com/14235027/88894865-ddddcb80-d248-11ea-8edc-76477a9ec6c2.png)

**Comment by BuzzyLizzy** [comment]
I also installed InterSystemsServer Mnaager extension and tried that, not working also.
I then downgraded again to 0.8.6 and then it works, it is definitely the version 0.8.7 having different behavior.

**Comment by gjsjohnmurray** [comment]
When you click on that status line message:

![image](https://user-images.githubusercontent.com/6726799/88903285-5cd40380-d24b-11ea-894c-6b17a0f9fc80.png)

you should get a quickpick top centre of your VS Code window, with an option to toggle the connection. When you select that does anything appear in the ObjectScript Output window?

**Comment by BuzzyLizzy** [comment]
Yes! it does, connected, yeah!
