### ISSUE TITLE
Authentication keeps failing despite having the correct password

### ISSUE THREAD

**Issue by henryvincent96** [intersystems-community/vscode-objectscript#224]
In my vscode settings.json I have this:
`"intersystems.servers": {
        "cache": {
            "webServer": {
                "scheme": "http",
                "host": "localhost",
                "port": 57772
            },
            "username": "_SYSTEM"
        },
        "/default": "cache"
    }, "objectscript.conn": {
        "active": true,
        "ns": "LOCALDEV",
        "server": "cache",
        "password": "examplePassword"
    }`
but I keep getting disconnected, and when it tries to reconnect it errors saying the authentication fails. I type the password in and it fails again. Only when I toggle the connection and type the password in again does it finally work. This is also happening for other members of my team. Is there something we're doing wrong?

**Comment by gjsjohnmurray** [comment]
Are you using a workspace (e.g. XYZ.code-workspace)? If so, can you share the JSON contents of that file (substituting any confidential information)?

Rather than setting a password in your `objectscript.conn` object, how about using the `InterSystems Server Manager: Store Password in Keychain` command to set it for your `cache` server definition?

**Comment by henryvincent96** [comment]
Our code workspace doesn't have an awful lot in there:

```
{
	"folders": [
		{
			"path": "C:\\ef-core-system\\static-content\\components\\source"
		},
		{
			"path": "C:\\ef-core-system\\cache\\CLS"
		},
		{
			"path": "C:\\ef-core-system\\cache\\efCSP\\CSP\\efcspapp"
		},
		{
			"path": "C:\\ef-core-system\\cache\\INC"
		},
		{
			"path": "C:\\ef-core-system"
		}
	]
}
```

I just tried using the `store password in  keychain` command and it doesn't seem to have made any difference, even after removing the password setting in `objectscript.conn`

**Comment by daimor** [comment]
If you use `intersystems.servers` the password also has to be stored there instead of `objectscript.conn`

**Comment by gjsjohnmurray** [comment]
I am puzzled that even after storing the password in the keychain you are still being prompted to enter a password at connect time. I'd only expect that to happen if the password in the keychain isn't the correct one for the username.

> Our code workspace doesn't have an awful lot in there, no settings just folders.

Are these local folders? Or are you using the isfs:// notation to work directly on the server?

Do you get the same problem if you create a brand new workspace that consists of a single folder (i.e. not a multi-root workspace)?

Please also confirm that your Extensions view shows these versions:
![image](https://user-images.githubusercontent.com/6726799/88660399-887daf00-d0ce-11ea-8839-f0b86de37816.png)

**Comment by henryvincent96** [comment]
Yep - we're using those versions, and all our folders are local; we don't edit on the server directly using vscode. I created a new instance of vscode only opening one directory and tried connecting and got the same problem.

**Comment by bourette** [comment]
Henry, for a baseline, can you try this workspace?  Updating your server connection.



On Jul 28, 2020, at 7:45 AM, Henry Vincent <notifications@github.com<mailto:notifications@github.com>> wrote:



Yep - we're using those versions, and all our folders are local; we don't edit on the server directly using vscode. I created a new instance of vscode only opening one directory and tried connecting and got the same problem.

**Comment by henryvincent96** [comment]
I just created a new workspace with these settings:
```
{
	"folders": [
		{
			"path": "..\\..\\..\\cache\\CLS"
		}
	],
	"settings": {
		"intersystems.servers": {
			"iris": {
				"webServer": {
					"scheme": "http",
					"host": "127.0.0.1",
					"port": 52773
				},
				"description": "Connection to local InterSystems IRIS™ installed with default settings."
			},
			"cache": {
				"webServer": {
					"scheme": "http",
					"host": "127.0.0.1",
					"port": 57772
				},
				"description": "Connection to local InterSystems Caché® installed with default settings.",
				"username": "_SYSTEM"
			},
			"ensemble": {
				"webServer": {
					"scheme": "http",
					"host": "127.0.0.1",
					"port": 57772
				},
				"description": "Connection to local InterSystems Ensemble® installed with default settings."
			},
			"/default": "iris"
		},
		"objectscript.conn": {
			"active": true,
			"ns": "LOCALDEV",
			"server": "cache"
		}
	}
}
```
I added the password to the keychain and then tried to connect, and the authentication still failed. I tried to keep everything as default as possible.

**Comment by daimor** [comment]
The simplest config would be as previously, will it work for you?
```
"objectscript.conn": {
"active": true,
"ns": "LOCALDEV",
"host": "127.0.0.1",
"port": 57772,
"username": "_SYSTEM",
"password": "SYS"
}
```

**Comment by henryvincent96** [comment]
Oh that works fine.

**Comment by daimor** [comment]
So, the issue in conjunction with `intersystems.servers`.
And working configuration should be like this.
```
    "objectscript.conn": {
      "active": true,
      "ns": "USER",
      "server": "iris",
    },
    "intersystems.servers": {
      "iris": {
        "webServer": {
          "scheme": "http",
          "host": "127.0.0.1",
          "port": 52773,
        },
        "username": "_SYSTEM",
        "password": "SYS"
      },  
    },
```
Sometime when something not working as expected, you can reload VSCode window itself (by the command from command palette).

**Comment by gjsjohnmurray** [comment]
@henryvincent96 what platform are you running VS Code on? And what version?

**Comment by henryvincent96** [comment]
@gjsjohnmurray Windows 10 1909 with vscode version:
```
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by gjsjohnmurray** [comment]
[This zip](https://github.com/intersystems-community/vscode-objectscript/suites/974796305/artifacts/12404904) contains the VSIX of a 0.8.8-SNAPSHOT build that should fix this.

**Comment by gjsjohnmurray** [comment]
@henryvincent96 0.8.8 is now published. Please update and verify this issue is fixed.

**Comment by henryvincent96** [comment]
@gjsjohnmurray Okay that's working with no issue now. Thanks very much for the help!
