### ISSUE TITLE
broken intellisense for commands with 0.8.7

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#225]

**Comment by gjsjohnmurray** [comment]
@daimor The "beta" step of the CI action failed when merging this PR. Please investigate at https://github.com/intersystems-community/vscode-objectscript/actions/runs/187495035. I will hold off merging any more PRs until I hear back from you.

**Comment by gjsjohnmurray** [comment]
This was the first PR merged after #234 merged, which made changes to the CI scripts.

**Comment by daimor** [comment]
It's ok, it just attempts to create the same beta release, as two beta releases were at the same time.

**Comment by gjsjohnmurray** [comment]
OK, it completed after you retriggered it. I thought I had waited for the first merge's CI actions to complete before I merged the second one, but perhaps not long enough.
