### ISSUE TITLE
Error: no auth mechanism defined

### ISSUE THREAD

**Issue by JeffSemmens** [intersystems-community/vscode-objectscript#229]
I have the following server and connection defined in my settings.json:

{
    "workbench.startupEditor": "newUntitledFile",
     "intersystems.servers": {
        "iris": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 52773,
            },
            "description": "Connection to local InterSystems IRIS™ installed with default settings.",
        },
        "cache": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 57772
            },
            "description": "Connection to local InterSystems Caché® installed with default settings."
        },
        "ensemble": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 57772
            },
            "description": "Connection to local InterSystems Ensemble® installed with default settings."
        },
        "/default": "iris"
    },
    "objectscript.conn": {
        "server": "iris",
        "host": "127.0.0.1",
        "port": 52773,
        "username": "username",
        "password": "password",
        "ns": "SDASHREDDER",
        "active":true
    }

}

If I try to use the defined "iris" server in my connection I get the Error: no auth mechanism defined. As soon as I remove the "server" setting in the connection, I connect fine. I am on InterSystems ObjectScript 0.8.7 and InterSystems Server Manager 0.0.4.

I've tried multiple versions of this with various settings. Can't seem to get the "server" to work for me.

**Comment by gjsjohnmurray** [comment]
This is a known issue, and there's a fixed VSIX available via https://github.com/intersystems-community/vscode-objectscript/issues/224#issuecomment-665495889

When you set the `server` property of `objectscript.conn` the `host`, `port`, `username` and `password` properties are ignored (intentionally). The bug is that the credentials aren't fetched from the `intersystems.servers` entry or the associated keychain entry, nor requested from the user when not found.

**Comment by DodgeDeBoulet** [comment]
So I guess this means that I need to figure out how to create a keychain entry, since username and password are not properties of the server object in Server Manager. I guess this makes sense, but it doesn't seem exactly intuitive.

**Comment by gjsjohnmurray** [comment]
0.8.8 is now published. Please update and verify this issue is fixed.

**Comment by gjsjohnmurray** [comment]
> 0.8.8 is now published. Please update and verify this issue is fixed.

pinging @JeffSemmens

**Comment by JeffSemmens** [comment]
Yes, this issue is fixed from my side, though I did change how I was doing things a bit in that I am using my keychain to hold my password now.

On Aug 13, 2020, at 10:42 AM, John Murray <notifications@github.com<mailto:notifications@github.com>> wrote:



0.8.8 is now published. Please update and verify this issue is fixed.

pinging @JeffSemmens<https://github.com/JeffSemmens>

**Comment by DodgeDeBoulet** [comment]
Using the keychain here too and have switched over to isfs:// access method. The only errors I get are the compilation kind, and that's **my** fault 😁

**Comment by gjsjohnmurray** [comment]
OK, closing this.
