### ISSUE TITLE
Saving local CSP file will cause file not found error on the server

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#230]

**Comment by bourette** [comment]
@daimor, does this mean that using client side source control there is no way to load CSP files to the server?  Ideally there would be a way to move local files to a csp application directory.

**Comment by daimor** [comment]
It's possible but needs some development and decisions how to make it better, and convenient for developers.

So, the main point is how to translate local physical path of csp files to CSP Application on the server.

**Comment by bourette** [comment]
Can we reopen this issue or do you want an enhancement request?

**Comment by daimor** [comment]
Better to have it separately as an enhancement request
