### ISSUE TITLE
Check if AfterUserAction method of server-side support class is called in the right circumstances

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#241]
Documentation of AfterUserAction method includes the following sentence:

> For the cases where Studio did not perform any interaction this method is not called.

I didn't spot any logic in studio.ts to make its AfterUserAction call equivalently conditional.

Investigate this, e.g. using a dummy server-side class that logs its calls. Check what we do matches what Studio does.

**Comment by gjsjohnmurray** [comment]
@ty-d are you willing to take this task?

**Comment by ty-d** [comment]
Yes, I can look into this.
