### ISSUE TITLE
SQL Highlighting Error

### ISSUE THREAD

**Issue by MakarovS96** [intersystems-community/vscode-objectscript#249]
Error with highlighting and bracers markup in SQL INSERT ... SELECT

![image](https://user-images.githubusercontent.com/19629483/89379947-12b2bc80-d73a-11ea-9db6-ceccc5516de7.png)

ObjectScript highlighting (error):
``` ObjectScript
&sql(INSERT INTO Tableau(Member, Enabled, Type, FollowDate, RelatedId) 
	SELECT Member, 1, 'Relation', NOW(), :relId
	FROM Tableau2
	WHERE (Type = 'Relation1' OR (Type = 'Relation2' AND RelatedId = :reltwoId))  AND Enabled = 1 
	GROUP BY Member)
```

SQL highlighting (right):
``` SQL
INSERT INTO Tableau(Member, Enabled, Type, FollowDate, RelatedId) 
SELECT Member, 1, 'Relation', NOW(), :relId
FROM Tableau2
WHERE (Type = 'Relation1' OR (Type = 'Relation2' AND RelatedId = :reltwoId))  AND Enabled = 1 
GROUP BY Member
```

**Comment by gjsjohnmurray** [comment]
Expect this to resolve when language server lands.

**Comment by gjsjohnmurray** [comment]
With Language Server 1.0.0 the coloring looks correct, but the bracket-matching is still wrong

![image](https://user-images.githubusercontent.com/6726799/96716442-f1f31e00-139c-11eb-8315-b39598cd7893.png)

**Comment by gjsjohnmurray** [comment]
Imperfect bracket matching is a current limitation of VS Code (see https://github.com/microsoft/vscode/issues/73864#issuecomment-514958338)

Closing here.
