### ISSUE TITLE
FileSystem Error

### ISSUE THREAD

**Issue by gbergeson** [intersystems-community/vscode-objectscript#258]
When I attempt to modify a file, I get a FileSystemError: Cannot read property 'code' of undefined. My setup worked until recently, when I started getting this error. It looks like there's something going on with the isfs virtual file system.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/intersystems-community/vscode-objectscript/issues/247#issuecomment-669492528 and try the beta build referenced there.

**Comment by gbergeson** [comment]
Okay, great. This specific error looks like it's fixed, but there's another: I can't check anything out of source control. I've disconnected the namespace from source control and I can do everything I need, but checking out is still having problems.

**Comment by gjsjohnmurray** [comment]
@gbergeson please open a fresh issue with details of the source control problem. I assume this is server-side source control, inplemented by a source control class. What isn't working? Did it previously work on an earlier version of this extension?
