### ISSUE TITLE
Server side source control with isfs not reloading if revert done in perforce

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#259]
I have a class that I reverted using the perforce client, but when I open the class using the isfs connection it is not reloaded from disk but instead shows the changed class prior to the revert.  If I go to studio and open the class it is reloaded from disk, and then switching back to VSCode it reloads the class in the editor.

I would expect that when I revert the class in the perforce client that opening the class or switching to the class in the editor would reload from disk (assuming of course it hasn't been changed).

0.8.9-beta.5

**Comment by gjsjohnmurray** [comment]
Does the perforce client revert correctly change the timestamp of the class? To investigate, use this REST request (suitably modified to your situation) before revert:

`/api/atelier/v1/USER/doc/YJM.Class1.cls`

and again after revert.

Did result.ts change?

**Comment by bourette** [comment]
Interesting, it appears to be an issue with the api.

**Comment by gjsjohnmurray** [comment]
@bourette if the Atelier API doesn't report a timestamp change after the perforce revert, it sounds like the perforce revert is at fault. Maybe @ty-d can look at this with you.

**Comment by gjsjohnmurray** [comment]
@bourette did you discover any more about this? I recently fixed some issues with isfs. Not sure they applied to your case, but you may like to try [this beta](https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.8.10-beta.4).

**Comment by bourette** [comment]
@gjsjohnmurray, no difference.  I thought we determined that the issue was in the API due to the timestamp not changing.  I reached out to @ty-d but have not heard anything back.

**Comment by gjsjohnmurray** [comment]
@bourette, when the perforce source control class reverts a class do you see a change occur to the last-modified date of the class as seen by Studio and by Portal's Explorer? Or at the lowest level, does this property change (substitute your full classname)?
```objectscript
w ##class(%Dictionary.ClassDefinition).%OpenId("YJM.Class1").TimeChanged
```

**Comment by ty-d** [comment]
@gjsjohnmurray  Just to let you know, my internship ended a couple of weeks ago, but I have started working part time this week.

The TimeChanged property seems to change on revert. The API uses the %RoutineMgr TS method to determine the timestamp, which does not seem to update on revert. When I access TimeChanged in the console, the TS method reports a different timestamp and the file attempts to revert in VSCode. This causes a couple of prompts to checkout the file, so I will see if there is a way to avoid those prompts and reload the file.

**Comment by gjsjohnmurray** [comment]
@ty-d glad to hear you're back.

The behaviour you reported doesn't smell right to me, and I think it needs more investigation rather than working around.

Is the following description true?

1. Before the perforce revert, the TimeChanged property of %Dictionary.ClassDefinition and the TS method of %Library.RoutineMgr both report the same (correct) last-modified time.

2. After revert, if you check TS() first, its value is unchanged. This is unexpected.

3. If you then check TimeChanged its value has changed correctly, which is an expected consequence of the revert.

4. Now if you check TS() once more, its value has changed. It matches the new result from TimeChanged. But why should an access to TimeChanged cause this effect?

**Comment by ty-d** [comment]
After trying it again, neither the TS() or TimeChanged values update after reverting from P4V. They both return the last time the class was edited in VSCode, not the time it was reverted. I am not sure what caused the time to update when I tried it before, but it must have been something other than the access to TimeChanged.

**Comment by timleavitt** [comment]
@ty-d check out the "reload" byref argument on the %Studio.SourceControl.Interface methods; this is a case where it being set to 1 should trigger a reload from the server. I think this is exposed in the "Atelier" APIs.

**Comment by timleavitt** [comment]
Discussed with @ty-d today; in addition to the "reload" argument I mentioned before, there's another challenge in that the Atelier APIs don't expose %Studio.SourceControl.Interface:OnBeforeTimestamp. This (in the example of %Studio.SourceControl.ISC) is what allow detection of changes on the filesystem that call for reloading a document from the associated file.

@rajrsingh do you have any insights into other places where server-side changes are needed to support VSCode? (I'm sure this won't be the last.)

**Comment by timleavitt** [comment]
It would be sufficient to somehow have VSCode automatically add a class like:
```
Class %zVSCode.Utils [ Owner = {%Developer} ]
{

ClassMethod GetClassTimestamp(classname As %Dictionary.CacheClassname) As %TimeStamp [ SqlProc ]
{
	Set classname=$piece(classname,";")
	$$$IsClassDefVersionMatched(ismatched) i ismatched=0 $$$ThrowStatus($$$ERROR($$$ClassDictionaryVersionMismatch))
	Set classname=$$$NormalizeClassname(classname)
	If $isobject($get(%SourceControl)) Do
	. Set tmp=%SourceControl New %SourceControl Do tmp.OnBeforeTimestamp(classname_".CLS")
	Quit $ZDateTime($$$defClassKeyGet(classname,$$$cCLASStimechanged),3)
}

}
```

**Comment by timleavitt** [comment]
We'd also need a wrapper for %Library.RoutineMgr:GetCurrentTimeStamp

**Comment by isc-jamien** [comment]
Guys, I'm not comfortable with injecting code unless we are backed into a corner with a sharp knife at our throat. - a very sharp knife -

Can we define a query that can do this? Brett has done wonders with the query interface

**Comment by timleavitt** [comment]
@isc-jamien the point is to define something that can be used through the query interface. Short of that it'd be an update to the Atelier APIs. We could always put something on the Open Exchange rather than automatically injecting it.

**Comment by gjsjohnmurray** [comment]
@timleavitt this specific case is only an issue for server-side source control classes that rely on getting the OnBeforeTimestamp call, right? And presumably the same issue existed when using Atelier with %Studio.SourceControl.ISC.

**Comment by timleavitt** [comment]
@gjsjohnmurray Yes, and yes.

**Comment by bspead** [comment]
Does this introduce risk into the source stream or is it merely an inconvenience to the developer?  Specifically:
1) Does VSCode make it clear that it is no longer checked out? (I assume the answer is yes)
2) What happens if you check out the class from VSCode after a prior session where changes are made but discarded?  Are you now editing the previously discarded version of the class or at time of check-out does it refresh and therefore you are editing the head revision?

If it allows you to resume editing the content which was discarded due to the revert, then I think that would represent risk to the source stream and this should be prioritized accordingly.  The developer could accidentally check in changes that were previously reverted (and in the common case of a shared development environment, these changes could have been written and discarded by someone else).  Unless caught by a careful pre-check-in diff (which all developers should always do but in reality this doesn't always happen) the check-in could include previously discarded changes and pollute the code stream.

**Comment by bourette** [comment]
Ben, 
For me this issue came up when I reverted some changes in perforce but the code remained untouched in VSCode.  I could imagine other scenarios where I pull in a shelved changelist or I resolve changes in perforce after a get latest, only to have those changes lost because VSCode didn't get the new version.

**Comment by gjsjohnmurray** [comment]
> 
> > this specific case is only an issue for server-side source control classes that rely on getting the OnBeforeTimestamp call, right? And presumably the same issue existed when using Atelier with %Studio.SourceControl.ISC.
> 
> @gjsjohnmurray Yes, and yes.

In which case I think this should be handled as a server-side bug in the Atelier API and fixed there. Sites that use a server-side source control class that relies on getting OnBeforeTimestamp would then either upgrade to a server version that contains the fix or else get an ad-hoc containing it.

**Comment by timleavitt** [comment]
@gjsjohnmurray I think this needs to be reopened - there's still an upstream issue that needs to be fixed to address @bourette 's original concern.

**Comment by gjsjohnmurray** [comment]
Reopening. GH closed it automatically when I merged the PR that mentioned it.

**Comment by isc-bsaviano** [comment]
This will be fixed in v4 of the Atelier APIs. No changes will need to be made in this extension to accommodate the fix.

**Comment by isc-bsaviano** [comment]
Closing because server-side work is done

**Comment by gjsjohnmurray** [comment]
https://github.com/intersystems-community/vscode-objectscript/releases/tag/v1.0.13-beta.3 contains #685 which might improve things in this area.
