### ISSUE TITLE
Customised exporting structure

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#261]
@daimor Ok thanks, as a test I have set my export as follows:

```
"objectscript.export": {
        "folder": {
            "*./abstract/*.cls": "abstract/abstract"
        },
        "addCategory": true
     }
```

This exports my file to ```[object Object]/cls/abstract```

Where I am hoping it to export to ```cls/abstract/abstract```

Is there any reason it is adding this ```[object Object]``` onto the front of the export?

_Originally posted by @howardbailey in https://github.com/intersystems-community/vscode-objectscript/issues/75#issuecomment-671850609_

**Comment by daimor** [comment]
@howardbailey

Ok, `[object object]` comes from folder, which is supposed to be as string only as a root folder for any of your sources in the repo. 
While your pattern should be in `addCategory`. I suppose that you have classes like `somepackage.abstract.someclass.cls` and you would like this.
```
    "objectscript.export": {
      "folder": "src",
      "addCategory": {
        ".*\\.Abstract\\..*\\.cls": "cls/Abstract",
        "cls": "cls",
        "mac": "mac"
      }
    },
```
And how it exports
```
export "User.Abstract.Person.cls" as "/Users/daimor/temp/src/cls/Abstract/User/Abstract/Person.cls" - Success 
Exported items: 1
export "User.Person.cls" as "/Users/daimor/temp/src/cls/User/Person.cls" - Success 
```
You should keep in mind, if you would still need separate folders for each type, e.g. cls, mac and so on, you will have to define it as I did above.

Or this
```
    "objectscript.export": {
      "folder": "src",
      "addCategory": {
        "Abstract\\..*\\.cls": "cls/Abstract",
        "cls": "cls",
        "mac": "mac"
      }
    },
```
to get 
```
export "Abstract.Test.cls" as "/Users/daimor/temp/src/cls/Abstract/Abstract/Test.cls" - Success 
```

**Comment by howardbailey** [comment]
Ok great thanks, let me try that.

**Comment by daimor** [comment]
I've found the issue in order of checking patterns, it would not allow more then one pattern to check, I'm going to fix it. As well as an issue with type of `folder` is not string, or if it's just empty.

**Comment by howardbailey** [comment]
Ok great thanks.

I've tried more or less what you have suggested above.

```
"objectscript.export": {
     "folder": "CLS",
     "addCategory": {
        ".*\\.abstract\\..*\\.cls": "CLS/abstract/abstract",
     }
    },
```

I have specified abstract twice in the pattern, but it still only exports it to ```cls/abstract``` and not ```cls/abstract/abstract``` (one level too high.

**Comment by howardbailey** [comment]
Actually I think I have it working, give me a second.

**Comment by howardbailey** [comment]
Ok it seems that if I specify this:

```
"objectscript.export": {
     "folder": "CLS",
     "addCategory": {
        ".*\\.abstract\\..*\\.cls": "abstract/abstract",
     }
    },
```
It will export to cls/abstract/disposable method (it seems to ignore the path I specify).


If I specify:

```
"objectscript.export": {
     "folder": "CLS",
     "addCategory": {
        ".*.cls": "abstract",
     }
    },
```

It will export to cls/abstract/abstract/disposable method (correctly).

So it looks like there's an issue with the pattern, is that what you're fix addresses?

**Comment by daimor** [comment]
My fix a bit different, your final pattern just exports any `cls` files to the `abstract` folder, not sure if it was you are tried to do.
`.*\\.abstract\\..*\\.cls` finally as a regular expression will look like `^.*\.abstract\..*\.cls$`, so, it should work only for files like
`somepackage.abstract.someclass.cls` or, `package1.package2.abstract.someclass.cls` or `package1.abstract.package2.someclass.cls` and so on.

```
"addCategory": {
        ".*.cls": "abstract",
     }
```
this is exactly the same as 
```
"addCategory": {
        ".*\\.cls": "abstract",
     }
```
or even, just only with type
```
"addCategory": {
        "cls": "abstract",
     }
```
and means, use abstract folder for any cls files

**Comment by daimor** [comment]
Could you check, how it works with [this build](https://github.com/intersystems-community/vscode-objectscript/suites/1035217835/artifacts/13748975)?

**Comment by howardbailey** [comment]
Ok I think I have it working. As you say, I did need to use the regex but I wasn't specifying the correct pattern.

I was specifying: ```^.*\.abstract\..*\.cls$``` trying to match ```\abstract\file.cls```

Whereas it seems I should have been trying to match ```abstract.file.cls```


I have changed my export settings to the following:

```
 "objectscript.export": {
     "folder": "CLS",
     "addCategory": {
        "^abstract.*cls$": "abstract"
     }
    }
```

And that exports it correctly.

**Comment by daimor** [comment]
You don't have to use ^ and $ in your pattern, if you need any abstrac.*.cls to go to abstract folder, you have to use this
`abstract\\..*\\.cls`

**Comment by daimor** [comment]
your pattern will work also for class like this `abstractextra.anyclass.cls` as well

**Comment by howardbailey** [comment]
Yes I see what you mean now.

I was confused by the \\, thinking it was escaping \ and not .

I've changed my pattern to what you have above and now it works correctly.


```
    "objectscript.export": {
     "folder": "CLS",
     "addCategory": {
        "abstract\\..*\\.cls": "abstract",
        "access\\..*\\.cls": "access",
        "EF\\..*\\.cls": "EF",
     }
    },
```

Thank you very much Dmitry! 

I have also now tried using the Go To Definition function and that works correctly.
