### ISSUE TITLE
Git Branch/Namespace Sync Issue

### ISSUE THREAD

**Issue by PaulSiml** [intersystems-community/vscode-objectscript#266]
In our environment, we have many Git branches in VS Code and each branch is associated to a namespace.

For example:

Branch                  Cache Instance
A                           C-1
B                           C-2
C                           C-3
Etc.

When we switch branches in VS Code, it is necessary to update the setting.json file to now point at the correct namespace to keep the Git branch and Cache namespace in sync.

So if I switch to Git branch B, I have to make sure I switch to namespace, C-2, at the same time in setting.json and save it – otherwise I am pointing at the wrong namespace.  Any changes I save will push/compile to the **incorrect** Cache instance.

Seem like we should have at least a warning prompt to change the namespace in settings.json, the capability to quickly change the server/namespace in a dialog, blank out the namespace in settings.json on a branch change, or perhaps a resource file.  I have already pushed and compiled code to the wrong namespace because I forgot to update the settings.json file since it is so easy to change branches in VS Code.

**Comment by daimor** [comment]
It's not a common case, and I would not do it in VSCode. As you are using git, you have to look at githooks. [post-checkout](https://schacon.github.io/git/githooks.html#_post_checkout) looks like what your really need, just add the code, which will change the namespace in settings.json according to the branch name.

If you have such way, maybe just store different settings.json in different branches?

**Comment by bourette** [comment]
You can just create a settings.json with the namespace defined in each branch.  You don't need the full connection just the namespace.

Such as
{
    "objectscript.conn": {
        "ns": "C-1"
    }
}

Root
A
.vscode
settings.json
cls
mac
...

B
.vscode
settings.json
cls
mac
...

On Aug 12, 2020, at 7:48 AM, PaulSiml <notifications@github.com<mailto:notifications@github.com>> wrote:



In our environment, we have many Git branches in VS Code and each branch is associated to a namespace.

For example:

Branch Cache Instance
A C-1
B C-2
C C-3
Etc.

When we switch branches in VS Code, it is necessary to update the setting.json file to now point at the correct namespace to keep the Git branch and Cache namespace in sync.

So if I switch to Git branch B, I have to make sure I switch to namespace, C-2, at the same time in setting.json and save it – otherwise I am pointing at the wrong namespace. Any changes I save will push/compile to the incorrect Cache instance.

Seem like we should have at least a warning prompt to change the namespace in settings.json, the capability to quickly change the server/namespace in a dialog, blank out the namespace in settings.json on a branch change, or perhaps a resource file. I have already pushed and compiled code to the wrong namespace because I forgot to update the settings.json file since it is so easy to change branches in VS Code.

**Comment by PaulSiml** [comment]
Hi,

Thanks for taking the time to respond to our issue.

In some cases, the namespaces are on the same servers but in other cases the namespaces are on different servers.
Here is an example with altered names in our settings.json file.

Here is what our single json file looks like today:

{
    "objectscript.conn": {
      "active": true,
      "label": "SRV2017",
      "host": "SRV2017",
      "port": 57772,
      "username": "PXS",
      "password": "",
      "ns": "C-1",
      "https": false,
    },

    "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\TF.exe",
    "objectscript.export.addCategory": true,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "git.suggestSmartCommit": false

}


If I understand you correctly, we could have a settings.json on each Git branch.  As we switch branches, it picks up the settings.json associated with the branch?  Does that need to be configured in VS Code/ObjectScript?  Or am I missing something?

-Paul

**Comment by bourette** [comment]
You could modify the settings directly in the folder or update using the UI and assign the settings on the folder, versus workspace or user.  Folder settings will override workspace settings.

James

On Aug 12, 2020, at 9:56 AM, PaulSiml <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

Thanks for taking the time to respond to our issue.

In some cases, the namespaces are on the same servers but in other cases the namespaces are on different servers.
Here is an example with altered names in our settings.json file.

Here is what our single json file looks like today:

{
"objectscript.conn": {
"active": true,
"label": "SRV2017",
"host": "SRV2017",
"port": 57772,
"username": "PXS",
"password": "",
"ns": "C-1",
"https": false,
},

"tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\IDE\\TF.exe",
"objectscript.export.addCategory": true,
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
"git.suggestSmartCommit": false

}


If I understand you correctly, we could have a settings.json on each Git branch. As we switch branches, it picks up the settings.json associated with the branch? Does that need to be configured in VS Code/ObjectScript? Or am I missing something?

-Paul

**Comment by PaulSiml** [comment]
Hi James,

Thanks for your help … we will try a separate settings file on each folder.

-Paul

**Comment by PaulSiml** [comment]
Hi Dmitry,

Thanks for your quick response.

Yes … several other people have suggested adding settings to the directory.
We were not aware that it had this capability.
We are going to try separate settings on each directory.

Thanks,

-Paul

**Comment by gjsjohnmurray** [comment]
@PaulSiml can this be closed?

**Comment by PaulSiml** [comment]
Hi Dmitry,

Does this mean I could remove all settings.json files (user, workspace) and simply have a json file on a git branch?

So far, I have not been able to make this work.  VS Code\ObjectScript cannot seem to find the settings file on the Git Branch.  What am I doing wrong?
(I am using the latest version 8.9)

-Paul

**Comment by PaulSiml** [comment]
Hi John,

Not yet …. I am following up with Dmitry.
So far, I have not been able to make the settings.json file on a Git branch work.
(I must be doing something wrong)

-Paul

**Comment by daimor** [comment]
It seems that you misunderstood something.
What doing you mean by git branch?

Basically it means, that different branches just may have some changes in the same files.

So, for instance, you should have ‘.vscode/settings.json’ in any of your branches, but it have different namespace value. Or it could be ‘code-workspace’ file.

**Comment by PaulSiml** [comment]
Hi James,

As a test, I deleted all settings.json files (user and workspace) and only put a single settings.json file, with all connection info, on the Git branch at the same level as the src folder/.vscode expecting it to find and use the connection information.  However it does not.

I also tried just a setting.json file on the workspace and a setting.json files on the Git branch with just the NS info.  It does not seem to honor the settings.json file on the git branch.

So it does not seem to over-ride any settings files nor does it seem to find the settings file on a Git branch.

I am running ObjectScript 8.9 on a TFS Git Repo.

Am I missing something?

-Paul

**Comment by PaulSiml** [comment]
Hi James,

After more experimentation, I was able to get the settings into the Git branch correctly.

Since we have many servers and namespaces, we are still attempting to work out how to handle the setting file when switching branches.

Thanks for your help.

I appreciate it.

-Paul

**Comment by PaulSiml** [comment]
Hi John,

This can be closed now.
We found a solution with help from James and Dmitry using cascading settings files.  We put the server connection information in a workspace settings.json file and store in a Git branch.  Then we put username/password connection information in the user settings.json file.

-Paul
