### ISSUE TITLE
Jump to Tag-Offset within a routine

### ISSUE THREAD

**Issue by JeffSemmens** [intersystems-community/vscode-objectscript#267]
While debugging ObjectScript classes/routines, many times errors are returned with line tag offsets. One thing I miss from studio is the ability to goto a tag line offset in a routine. Is there any way to add this capability?

**Comment by bourette** [comment]
Agree 100%

On Aug 13, 2020, at 1:21 PM, JeffSemmens <notifications@github.com<mailto:notifications@github.com>> wrote:



While debugging ObjectScript classes/routines, many times errors are returned with line tag offsets. One thing I miss from studio is the ability to goto a tag line offset in a routine. Is there any way to add this capability?

**Comment by gjsjohnmurray** [comment]
Once implemented this enhancement could be accessed by clicking on the _tag+offset^routine_ panel that already appears in the status bar of an INT.
