### ISSUE TITLE
Server-side search of isfs folder using proposed API failed when using Server Manager connection

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#269]
Despite their package.json containing the expected `"enableProposedApi": true` setting, the FileSearchProvider and TextSearchProvider implementations don't seem to activate.

I suspect this is caused by the build procedure not adding vscode.proposed.d.ts

I will submit a PR.

**Comment by daimor** [comment]
I see no reasons for this, `vscode.proposed.d.ts` should be downloaded just by `npm install`

**Comment by daimor** [comment]
![image](https://user-images.githubusercontent.com/1212251/90244148-dae1fe00-de38-11ea-8d4a-f25422dd38fe.png)

**Comment by gjsjohnmurray** [comment]
I have re-titled this issue and am using it to deal with a related problem that showed up once I worked out why proposed API wasn't working when I used a beta or snapshot VSIX in Insiders. I will also add notes to the linked PR (#270).
