### ISSUE TITLE
Publish of 0.8.9 to Marketplace failed

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#275]
@daimor please see https://github.com/intersystems-community/vscode-objectscript/runs/985631042?check_suite_focus=true

Has something changed about whose identity is being used for publication? I didn't get this problem when I [released 0.8.8](https://github.com/intersystems-community/vscode-objectscript/runs/940348421?check_suite_focus=true)

**Comment by daimor** [comment]
Ahh, yes.  Raj already updated token

**Comment by rajrsingh** [comment]
Oops sorry about that. @daimor you can put the old token in to get this version released.

**Comment by daimor** [comment]
Updated token, published manually.
