### ISSUE TITLE
Consider adding resolution command buttons to diff shown when import detects a server-side change

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#283]
Since PR #200 a server-side change produces this dialog during import of the local version:

![image](https://user-images.githubusercontent.com/6726799/90702825-230f7f00-e284-11ea-8bbd-be9fc18a0bd3.png)

Clicking "Compare" gives this:

![image](https://user-images.githubusercontent.com/6726799/90703088-bb0d6880-e284-11ea-9c93-3e9615282960.png)

Unlike the equivalent diff which appears if the **local** file is modified outside VS Code before being saved (and which also appears when the scenario arises for an isfs-type workspace root), the one shown above lacks command buttons to resolve the conflict.

Here is that other story:

![image](https://user-images.githubusercontent.com/6726799/90703384-8cdc5880-e285-11ea-9feb-d17b507e5457.png)

Click "Compare":

![image](https://user-images.githubusercontent.com/6726799/90703494-d7f66b80-e285-11ea-952b-d653d1c81329.png)

**Comment by isc-bsaviano** [comment]
I don't think this is possible to do. The "resolve save conflict" diff window isn't a command so we can't open it.
