### ISSUE TITLE
Add action to filter class in server explorer (Deployed files, Generated files, System files)

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/vscode-objectscript#29]
Is it possible to add filters in server explorer to see or unsee 

- Deployed files

- Generated files

- System files

As it is in atelier :

<img width="720" alt="atelierserverexplorerfilter" src="https://user-images.githubusercontent.com/47849411/53890458-8e31ab00-4028-11e9-8e8b-a1b5d2dd2b9e.png">

**Comment by daimor** [comment]
Show generated already implemented
