### ISSUE TITLE
Image links are broked in new markdown doc

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#293]
In PR #292 @rajrsingh added new docs, but the image links are broken.

I will prepare a PR.

**Comment by gjsjohnmurray** [comment]
This change was reverted in #298, as it seems the environment publishing the doc pages requires the previous paths. Previewing the markdown in VS Code will result in broken links and images.

**Comment by rajrsingh** [comment]
Yes to preview properly one must follow this guidance:
https://docs.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll
