### ISSUE TITLE
Support "find in files" in an ISFS folder

### ISSUE THREAD

**Issue by timleavitt** [intersystems-community/vscode-objectscript#296]
If I try to "find in folder" on an ISFS folder, I never get any results. Being able to use "find in files" against the server is a critical feature for server-centric development.

**Comment by gjsjohnmurray** [comment]
We can't provide this in the standard release of VS Code (aka Stable) until https://github.com/microsoft/vscode/issues/59921 gets resolved. I'm trying by best to make that happen.

Meanwhile please see https://github.com/intersystems-community/vscode-objectscript/issues/126#issuecomment-674089387 for a workaround.

Let us know how you get on with this. Maybe we should add it to the product documentation.

**Comment by gjsjohnmurray** [comment]
@timleavitt can this be closed as a duplicate?

**Comment by timleavitt** [comment]
@gjsjohnmurray yes.
