### ISSUE TITLE
Documentation for installation directly from source tree

### ISSUE THREAD

**Issue by woodfinisc** [intersystems-community/vscode-objectscript#297]
Having pulled the repository, I looked at README.md for instructions on how to build/install the plugin. I was surprised that there were no "Build" instructions and that the "Installation" instructions directed me to the VS marketplace.

As a developer interested in both using and contributing to this plugin, I'd appreciate if the repository included direction on how to do this "from source".

**Comment by daimor** [comment]
Tom, could you look at [CONTRIBUTING](https://github.com/intersystems-community/vscode-objectscript/blob/master/CONTRIBUTING.md).md file, would it be enough for you?

**Comment by woodfinisc** [comment]
Indeed, I think that's what I'm looking for. I'll review and close this issue if it provides all that I need.

**Comment by woodfinisc** [comment]
I was following along with the excellent [CONTRIBUTING.md](https://github.com/intersystems-community/vscode-objectscript/blob/master/CONTRIBUTING.md) directions, but once I started the extension development host, it recommended that I install an "InterSystems Server Manager" extension. Where is the source for this? Again, I'm trying to build from scratch.

**Comment by daimor** [comment]
https://github.com/intersystems-community/intersystems-servermanager

**Comment by woodfinisc** [comment]
Strange that a GitHub search for "intersystems server manager" does not find that!

**Comment by gjsjohnmurray** [comment]
@woodfinisc can this be closed, or do you think there are still things needing to be improved in the docs?
