### ISSUE TITLE
Intellisense Methods from #dim variables

### ISSUE THREAD

**Issue by keeypee** [intersystems-community/vscode-objectscript#30]
Hello,

when I declare a variable with #dim as a object, it won't show up the methods.

	#dim win As test.sample.Window
	set win = view.getScene().getPopupWindow("test.sample.Window")
	do win.clearArr(arr)

When I'm pressing F12 on .clearArr(arr) it tells me "No definition found for'clearArr'"

**Comment by evshvarov** [comment]
Also, completion doesn't work for object variables. e.g. for this constructions:
ClassMethod GetPropertyValueForID(sd As %Integer) As %String
{
    set obj=..%OpenId(sd)
    return obj.StringData
}
for obj. 
it doesn't show StringData property, or any properties and methods

**Comment by mat1990dj** [comment]
Yup, same as #73

**Comment by Krokador** [comment]
Is it normal that I also don't have the intellisense on a method argument? 

Say I have
`Method DoSomething(arg1 As EnsLib.SQL.Snapshot, arg2 As %String)`

then I'd assume typing **arg1.** would suggest me methods and/or properties of the type of the argument? Especially when this argument is an EnsLib type? Doesn't work either with custom types Package.MyObject (although Atelier can do it, so it must be doable?).

Being a complete newbie to ObjectScript, the lack of wizards and code completion makes it really hard to use VSCode. But I'm also not a fan of eclipse either (I love me dark mode and atelier is hard to style properly, for one thing), so... any ideas when this might be implemented?

**Comment by daimor** [comment]
@Krokador yep, this is not implemented, yet. Should arrive I hope, this summer.

**Comment by jtsalten** [comment]
I hoped this was going to work with Language Server but it doesn't work yet...

**Comment by daimor** [comment]
Yeah, with the first stage, it just replaces some of the functionality done previously, so such a new functionality going next.

**Comment by isc-bsaviano** [comment]
@jtsalten @Krokador This feature is implemented in the Language Server so any issues related to it should be posted in that repository. @daimor This should probably be closed because it's out of scope for this extension.
