### ISSUE TITLE
Several issues with server manager and multiple server connections

### ISSUE THREAD

**Issue by timleavitt** [intersystems-community/vscode-objectscript#302]
Use case:
In the user-level settings.json file I have several entries in intersystems.servers. In a workspace-level settings file I have one isfs folder definition using each of them.

If I don't specify the username for each in intersystems.servers:
I get prompted for username/password on one of them (the last one in the list, it happens), and after that connections succeed. Connections continually fail for the other with:
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on host:57772[NAMESPACE]
Presumably it's assumed I want to act as UnknownUser.

If I specify the username for each in intersystems.servers, I see this repeatedly:
Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on host:57772[NAMESPACE]
I am prompted for a password on each of the instances, but each time the prompt replaces the current prompt, removing any input I may have typed before I may have had time to submit it.

It would be great to have behavior around asking for credentials tightened a bit. I'm a fan of the secure storage of these credentials in the Server Manager, but as it stands this is a major barrier to connecting to multiple servers easily.

(@rajrsingh indicated that this is a vscode-objectscript issue rather than intersystems-servermanager)

**Comment by JeffSemmens** [comment]
I also have a situation where I set up User settings with full credentials for a number of instances, then I pulled down the community objectscript-template from the ISC community GitHub repository (used as template, did a git pull from my repository). It sets up a .vscode/settings.json with the following credentials:
{
    "files.associations": {
    
        "Dockerfile*": "dockerfile",
        "iris.script": "objectscript"
      },
    "objectscript.conn" :{
      
      "ns": "IRISAPP",
      "active": false,
      "username": "_SYSTEM",
      "password": "SYS",
      "docker-compose": {
        "service": "iris",
        "internalPort": 52773
      }
    }

}

Since the workspace settings are supposed to override the User settings, I expected this to work. Instead I get a notification that it is trying to connect with the username from my User settings for this workspace.

**Comment by timleavitt** [comment]
@JeffSemmens I think that's a separate issue.

**Comment by gjsjohnmurray** [comment]
> 
> 
> @gjsjohnmurray I'm going to have a PR up for this soon (hopefully)

@timleavitt thanks for letting me know. I was about to take a look at it, as I've seen it myself and already have a hunch about what's going on. I'll look out for your PR.

**Comment by gjsjohnmurray** [comment]
The fix by @timleavitt can now be tested by downloading and installing the beta VSIX from https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.9.1-beta.5
