### ISSUE TITLE
Editing code directly on server always detects server file as newer

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#303]
I'm editing a .INT file directly on the server, and every time I save it, I get a dialog saying "Failed to save X.int: The content of the file is newer.  Please compare your version with the file contents or overwrite the content of the file with your changes."

I don't want to turn off the conflict setting in order to detect valid changes, the plug-in keeps detecting a server change when there isn't one.

**Comment by gjsjohnmurray** [comment]
Possibly #276 so please download the latest 0.8.10-beta VSIX from https://github.com/intersystems-community/vscode-objectscript/releases and see if you still have the problem.

**Comment by gjsjohnmurray** [comment]
It turns out that 0.9.0 just came out, so please update the extension from within VSCode, then re-test and report back here.

**Comment by RyszardWithAZ** [comment]
I upgraded and it looks like it's still happening. But I do see it only when I do the following:
1. Open a .INT
2. Make a change and save it, for example add a space to a comment. It saves successfully.
3. Now remove that space and save it. This presents the conflict message.

**Comment by gjsjohnmurray** [comment]
@RyszardWithAZ please try the beta VSIX from https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.9.1-beta.4 and let us know if this resolves it for you.

**Comment by RyszardWithAZ** [comment]
It works much better, thank you!
