### ISSUE TITLE
View other opens int as read only

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#309]
I can see that generated int code from a class should generally not be changed, but sometimes it's necessary to debug the generated int code and when that int code is in a server background job it's easiest to set globals.  

When I attempt to view other on one of my classes and change the int code I'm told "Cannot edit in read-only editor"

Is there some way around this limitation?

**Comment by gjsjohnmurray** [comment]
I assume you started from a class opened from a local file, not an isfs folder in your workspace.

If you set `"objectscript.serverSideEditing": true` you will be able to edit the int that "View Other" gets you. But this setting will also mean that every document you open from ObjectScript Explorer will also be editable.

Do you think we should offer "Edit Other" as an extra context menu option alongside "View Other"?

**Comment by bourette** [comment]
I think edit other might be an excellent compromise.  IMO not a common case that you want to edit the generated code, but when you do, it would be nice to not have to change settings.

**Comment by isc-bsaviano** [comment]
I think it's reasonable to add an "Edit Other" menu option specifically for local files.
