### ISSUE TITLE
Workspace folder objectscript.conn setting being overridden by user-level one

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#312]
> I also have a situation where I set up User settings with full credentials for a number of instances, then I pulled down the community objectscript-template from the ISC community GitHub repository (used as template, did a git pull from my repository). It sets up a .vscode/settings.json with the following credentials:
```
{
    "files.associations": {
    
        "Dockerfile*": "dockerfile",
        "iris.script": "objectscript"
      },
    "objectscript.conn" :{
      
      "ns": "IRISAPP",
      "active": false,
      "username": "_SYSTEM",
      "password": "SYS",
      "docker-compose": {
        "service": "iris",
        "internalPort": 52773
      }
    }

}
```
> Since the workspace settings are supposed to override the User settings, I expected this to work. Instead I get a notification that it is trying to connect with the username from my User settings for this workspace.

_Originally posted by @JeffSemmens in https://github.com/intersystems-community/vscode-objectscript/issues/302#issuecomment-682110658_

**Comment by gjsjohnmurray** [comment]
@JeffSemmens is it an `intersystems.servers` entry that the credentials are being taken from? Does the name of that entry happen to match the lowercased name of the local folder you have opened in VS Code? I think I can see a code path that would cause the extension to use that connection definition (host and port as well as username and password if set) even though you'd be expecting it to connect to your local Docker instance.

**Comment by JeffSemmens** [comment]
@gjsjohnmurray yes it is. Here is the definition of the intersystems.servers for my User profile

    "intersystems.servers": {
      "iris": {
        "webServer": {
          "scheme": "http",
          "host": "127.0.0.1",
          "port": 52773
        },
        "description": "Connection to local InterSystems IRIS™ installed with default settings."
      },
      "cache": {
        "webServer": {
          "scheme": "http",
          "host": "127.0.0.1",
          "port": 57772
        },
        "description": "Connection to local InterSystems Caché® installed with default settings."
      },
      "ensemble": {
        "webServer": {
          "scheme": "http",
          "host": "127.0.0.1",
          "port": 57772
        },
        "description": "Connection to local InterSystems Ensemble® installed with default settings."
      },
      "/default": "iris"
    }

As you can see, my default service is "iris", same as the workspace definition...

**Comment by JeffSemmens** [comment]
@gjsjohnmurray This is actually my original User definition...:
{
    "workbench.startupEditor": "newUntitledFile",
     "intersystems.servers": {

        "iris": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 52773,
            },
            "username": "iscusr",
            "description": "Connection to local InterSystems IRIS™ installed with default settings.",
        },
         "irisapp": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 32769,
            },
            "username": "_SYSTEM",
            "description": "Connection to local InterSystems IRIS™ installed with default settings.",
        },       "irislocal": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 52773,
            },
            "username": "semmens",
            "description": "Connection to local InterSystems IRIS™ installed with default settings.",
        },
        "irisaa": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 52774,
            },
            "username": "iscusr",
            "description": "Connection to local InterSystems IRIS™ installed with default settings.",
        }
        ,
        "cache": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 57772
            },
            "description": "Connection to local InterSystems Caché® installed with default settings."
        },
        "ensemble": {
            "webServer": {
                "scheme": "http",
                "host": "127.0.0.1",
                "port": 57772
            },
            "description": "Connection to local InterSystems Ensemble® installed with default settings."
        },
        "/default": "iris"
    },
    "objectscript.conn": {
    
    
        "server": "iris",
         "ns": "SDASHREDDER",
        "active":true
    },
    "objectscript.export.addCategory": true,
    "fileTemplates.author": "Jeff Semmens",
    "fileTemplates.company": "InterSystems"

}

**Comment by JeffSemmens** [comment]
@gjsjohnmurray Perhaps this is just my understanding regarding how connection settings work between different workspaces in vscode. I expected the User settings to be more universal (the same for every workspace I create in different directories). And that they could be overwritten at the Workspace level of the current directory. However I am seeing different User settings for the extensions in each workspace I open up. If I open up a directory in SDAShredder (a demo instance I have defined), and another in the Template-Demo directory, I actually see different User level settings. This confuses me.

**Comment by gjsjohnmurray** [comment]
I'm not clear what you mean by "see different User level settings".

In the Settings editor in VS Code with a single folder open (i.e. not a .code-workspace file), mouse over the User tab to see which settings.json file this tab affects:

![image](https://user-images.githubusercontent.com/6726799/92146826-31c46d00-ee12-11ea-8f89-9a35808389af.png)

This is User level, and will be the same regardless of what you've opened.

In my example (one folder open) the tip for the second tab looks like this:

![image](https://user-images.githubusercontent.com/6726799/92147027-7819cc00-ee12-11ea-9bb3-178243b918b9.png)

So this tab shows/alters settings in the file I've pointed to in the .vscode subfolder of the folder I opened in VS Code.

I hope you're already aware of the button on the top right of the settings editor which will open in a new tab the file that the current sub-tab of the settings editor relates to:
![image](https://user-images.githubusercontent.com/6726799/92147356-f8d8c800-ee12-11ea-9dfc-5442e3f81314.png)

When a **workspace** is open (i.e. XYZ.code-workspace) you get three tabs:
![image](https://user-images.githubusercontent.com/6726799/92147805-83212c00-ee13-11ea-99d1-aed50ce9e379.png)

The middle one correlates to the `settings` object within the JSON of the .code-workspace file. The rightmost one is for the settings.json file in the .vscode folder of the folder in the workspace. If the workspace is multi-root then the dropdown selector of that rightmost tab lets you switch between the _rootX_\.vscode\settings.json files.

**Comment by gjsjohnmurray** [comment]
> 
> 
> @gjsjohnmurray yes it is. Here is the definition of the intersystems.servers for my User profile
> 
> ...
> 
> As you can see, my default service is "iris", same as the workspace definition...

Then I think this is where your user-level server definition named "iris" is trumping the `objectscript.conn` parameters in your `iris\.vscode\settings.json` file:

https://github.com/intersystems-community/vscode-objectscript/blob/06ff9b0324ff39471f62fdda5d1aa2a1d208d954/src/api/index.ts#L157-L169

Only the `ns` parameter will be applied from your `objectscript.conn`. Everything to do with connecting to the target server will come from `intersystems.servers`.

If you rename your "iris" folder to something that doesn't match any of your `intersystems.servers` entries I think you'll get what you want.

@daimor @rajrsingh this behaviour needs to be either documented or changed.

**Comment by JeffSemmens** [comment]
Yes, this was what I was talking about. Probably just not using the correct terminology for vscode as I am a bit of a newbie where using it is concerned. I'll modify my settings as you suggest.

**Comment by jtsalten** [comment]
Behavior is determined by how we named a folder compared with "something" within a workspace settings definition? That's a bug isn't it?

**Comment by rajrsingh** [comment]
@gjsjohnmurray it seems to me that re-using the same server name is bound to create confusion no matter how the code is trying to handle the situation. Would it make the most sense to document that server names should be unique, and unexpected behavior may occur if they are not?

**Comment by gjsjohnmurray** [comment]
@jtsalten I think the situation probably exists because of how the isfs:// notation got expanded when `intersystems.servers` was subsequently added.

@rajrsingh I like the idea of recommending a naming strategy for entries in `intersystems.servers` that would minimize the chance of collisions with the names of local folders a developer might put their client-side-editing files in. Server names can contain -._~ punctuation characters, some of which strike me a relatively uncommon in folder names. For example a server name `local.dev` is unlikely to collide with a folder name.

**Comment by gjsjohnmurray** [comment]
Mitigated by https://github.com/intersystems-community/intersystems-servermanager/pull/31

**Comment by jstetson10** [comment]
I will need some additional input on exactly what the documentation needs to say on this.

**Comment by gjsjohnmurray** [comment]
@jstetson10 here's some info for the documentation. Please verify it on your own setup first though:

1. Have a local folder named `foo` that you want to use for client-side editing.
2. Open that folder in VS Code .
3. In VS Code's settings editor switch to the folder-specific tab (as opposed to the user-level settings tab) and set an `objectscript.conn` entry to define which namespace on which server the code export/import operations are to use. This entry gets filed in `foo/.vscode/settings.json` and consists of a `ns` property, and `active` property, and either a `server` property or a set of other properties such as `host`, `port`, `username` and maybe even `password`.
4. Verify that export/import works as expected.
5. Now use Server Manager to define a server named `foo` in user-level `intersystems.servers`. Point this entry at a different IRIS server from the one you used in the previous steps.
6. Retry export/import and observe that the `foo` entry in `intersystems.servers` takes precedence over the `objectscript.conn` entry in `foo/.vscode/settings.json`

That is the behavior which needs documenting.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Do you think that this still needs to be documented? AFAIK this isn't covered anywhere and the issue hasn't come up again

**Comment by isc-rsingh** [comment]
I agree if it hasn't come up in 1 1/2 years it doesn't need to be documented.

**Comment by gjsjohnmurray** [comment]
OK. At least it's documented here.
