### ISSUE TITLE
Support "SASchema"-based code completion in XData blocks

### ISSUE THREAD

**Issue by timleavitt** [intersystems-community/vscode-objectscript#315]
The Atelier REST APIs include support for retrieving metadata about various formats used in XData blocks. This is particularly important for Zen development, but is also relevant for %CSP.REST, %JSON.Adaptor, and %Installer. (I've used %Studio.SASchema in a few of my projects too, including https://github.com/intersystems/apps-rest, and would really like to see support for it.)

For example:
GET http://localhost:52775/api/atelier/v2/%25SYS/saschema/http://www.intersystems.com/urlmap

Returns:
```
{
"status": {
"errors": [],
"summary": ""
},
"console": [],
"result": [
  "# start checksum section",
  "!checksum:65401,44038",
  "# This file defines the Rest UrlMap studio assist database",
  "# Define the prefix mapping",
  "!prefix-mapping:urlmap:http://www.intersystems.com/urlmap",
  "# Set the default namespace to urlmap",
  "!default-namespace:http://www.intersystems.com/urlmap",
  "# Set the default prefix for element definitions that follow",
  "!default-prefix:urlmap",
  "/#Routes",
  "Routes/#Map",
  "Routes/#Route",
  "Map|Prefix",
  "Map|Forward",
  "Route|Url",
  "Route|Method@enum:!,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT",
  "Route|Call",
  "Route|Cors@enum:!,true,false"
],
}
```

VSCode should be able to consume this from the server (based on the XMLNamespace attribute of any given XData block) to help with code completion within that XData block.

**Comment by bsaviano-intersystems** [comment]
The language server will include this feature upon its initial release.

**Comment by timleavitt** [comment]
@bsaviano-intersystems Excellent!!!

**Comment by gjsjohnmurray** [comment]
See also #85

**Comment by isc-bsaviano** [comment]
Code completion for SASchemas is implemented in the Language Server so any issues related to it should be posted in that repository. @daimor This should probably be closed because it's out of scope for this extension.
