### ISSUE TITLE
support working with remote static files (html, js, css, CSP, etc...) 

### ISSUE THREAD

**Issue by mariosanchez23** [intersystems-community/vscode-objectscript#32]
I think this is not possible yet. It would be great if you could work with remote static files. 
When the server is remote, you can't work with static files unless you do OS mappings, etc...

It would be great if in the server explorer tab we could also see static files and edit html, js, csp, etc...

**Comment by klauws** [comment]
This would be great.

**Comment by grongierisc** [comment]
BTW, great work daimor !

any plan to add this feature in a release ?

**Comment by daimor** [comment]
I have not planed it yet, not sure when I will manage to do it.

**Comment by daimor** [comment]
@mariosanchez23, @grongierisc  look at my the [latest beta release](https://github.com/daimor/vscode-objectscript/releases), where I've added support for remote editing CSP files. How to configure, you can find [here](https://github.com/daimor/vscode-objectscript/wiki/Server-side-editing#csp-support), could you try and give some feedback.

**Comment by grongierisc** [comment]
Hi Dmitriy,

I try your implementation on the 0.8.1 beta and it doesn't work for me.
I can't edit or create new files with this configuration : 

{
    "folders": [
      {
        "name": "main",
        "path": "."
      },
      {
        "name": "Backend",
        "path": "Backend"
      },{
        "uri": "isfs://main/csp/user?csp",
        "name": "CSP-Backend",
      },
    ],
    "extensions": {
      "recommendations": [
        "daimor.vscode-objectscript"
      ]
    },
    "settings": {
      "files.exclude": {
        "Backend": true
      },
    }
  }

vscode settings on main : 

{
    "objectscript.conn": {
        "active": false,
        "host": "localhost",
        "port": 52773,
        "username": "_SYSTEM",
        "password": "SYS",
        "ns": "USER",
        "https": false,
        "docker-compose": {}
    }
}

<img width="660" alt="image" src="https://user-images.githubusercontent.com/47849411/73161178-3641de00-40eb-11ea-97ae-73f86fd9853f.png">

**Comment by daimor** [comment]
Hi Guillaume,

I see, that you got an error when creating a file, unfortunately I did not finish this part yet, but I'll add it quite soon.
While editing files should work.
Do you have any errors when edit existing files?
Does it show any errors?
Sometimes it can show error for an existing file but open it correctly when opening it a second time.

**Comment by grongierisc** [comment]
I can see and delete files
But, i can't edit files, no errors show in vscode, but modification are not reported to the server side.

**Comment by daimor** [comment]
Look at [wiki](https://github.com/daimor/vscode-objectscript/wiki/Server-side-editing)
you need this setting as well
"objectscript.serverSideEditing": true
