### ISSUE TITLE
Server name in settings.json requires lower case

### ISSUE THREAD

**Issue by marykerins** [intersystems-community/vscode-objectscript#323]
When adding a new server under "intersystems.servers", the arbitrary server name selected accepts only all lower case entries.  For example, if I enter "IRIS20201", the entry is underlined indicating an error, and Alt+F8 (Peek Problem) reports this:  "Property IRIS20201 is not allowed."   Changing the server name to "iris20201" fixes the problem

**Comment by daimor** [comment]
Yes, lowercase is required, due to limitations of using it as part of URI
