### ISSUE TITLE
Documentation link reports "404 Page not found :("

### ISSUE THREAD

**Issue by marykerins** [intersystems-community/vscode-objectscript#324]
Open documentation at https://intersystems-community.github.io/vscode-objectscript/.  From VSCode Workspaces page, click Server-side Editing link at bottom, then click Configuration link at end of second paragraph.  The Configuration link gives the page-not-found error.

**Comment by gjsjohnmurray** [comment]
Thanks for the report. The fix for this will land as part of #321. Meanwhile, use the site index on the left.
