### ISSUE TITLE
SOAP Wizard

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/vscode-objectscript#325]
Is there any plan to add support of Soap wizard like in Atelier/Studio ?

**Comment by isc-jamien** [comment]
Yes. Planned

**Comment by nickmitchko** [comment]
+1

**Comment by grongierisc** [comment]
Temporary workaround : 

http://localhost:32883/isc/studio/templates/%25ZEN.Template.AddInWizard.SOAPWizard.cls

**Comment by gjsjohnmurray** [comment]
@grongierisc this looks like a good use case for the `links` property of `objectscript.conn`, which already supports some variable substitution:

```json
	"objectscript.conn": {
		"links": {
			"SOAP Wizard": "http://${host}:${port}/isc/studio/templates/%25ZEN.Template.AddInWizard.SOAPWizard.cls?$NAMESPACE=${namespace}"
		},
...
```

And when #444 arrives in 1.0.4 there will be some more variables available.

Links you specify here will appear in the Server Commands menu. One way to launch that menu is to click on the ObjectScript connection panel in the status bar. If you're editing server-side (isfs) there's also a button in the top right of an open document:

![image](https://user-images.githubusercontent.com/6726799/97423516-40596d00-1907-11eb-98ea-e98579c42be5.png)

**Comment by grongierisc** [comment]
FYI : http://${host}:${port}/isc/studio/templates/%25ZEN.Template.AddInWizard.SOAPWizard.cls?$NAMESPACE=${namespace}

Is working but the generated classes aren't in ${namespace} but in %SYS.

How can i report this bug ?

**Comment by ondrejhoferek** [comment]
+1, it would be great to have all the Add-In/Template links provided out of the box.

Also, I investigated the direct browser access to the wizard and the appropriate URL Query parameter seems to be (case-sensitive) Namespace, not $NAMESPACE, so there is no bug and the URL used for the link definition should be:

http://${host}:${port}/isc/studio/templates/%25ZEN.Template.AddInWizard.SOAPWizard.cls?Namespace=${namespace}

or better now with [#444](https://github.com/intersystems-community/vscode-objectscript/pull/444) in place:

${serverUrl}/isc/studio/templates/%25ZEN.Template.AddInWizard.SOAPWizard.cls?Namespace=${namespace}

**Comment by jstetson10** [comment]
This is related to Doc about links in ObjecScript.conn #667
