### ISSUE TITLE
editor.formatOnSave is line breaking condition statements

### ISSUE THREAD

**Issue by rfns** [intersystems-community/vscode-objectscript#326]
Some of our developers have noticed an undesired behavior while using the extension's built-in formatter.

It changes from this:

```objectscript
if condition {
   // code
} else {
  // code
}
```

To this:

```objectscript
if condition {
  // code
}
else {
  // code
}
```

Same applies to `elseif`. This is causing us some overwork when reviewing the code.

Is that behavior intended? We even had to fully disable the formatter to workaround this issue.

**Comment by daimor** [comment]
Yes, at the moment formatter does not have so many options, and this particular behavior can’t be changed at the moment, but it with upcoming language server support, it will get more possibilities and options

**Comment by isc-rsingh** [comment]
@rfns now that language server is released, please use that extension, and if your issue still persists, file a new issue in the language server repo.
