### ISSUE TITLE
'Overwrite on Server' for all changed files

### ISSUE THREAD

**Issue by AxisClinical** [intersystems-community/vscode-objectscript#336]
Currently when 'Importing and Compiling' multiple files I have to click 'Overwrite on Server' for each file.  I need an option to 'Overwrite on Server' for all files I have selected.  This is very import for companies with many developers altering lots of different files together.

**Comment by gjsjohnmurray** [comment]
See #464 for a request for a setting to get unconditional server overwrite of all imports from local files.

**Comment by gjsjohnmurray** [comment]
@AxisClinical does the extra setting documented in https://github.com/intersystems-community/vscode-objectscript/pull/465 meet your need?

**Comment by AxisClinical** [comment]
Yes, thanks for this addition!


Matthew C. Lowry

IT Manager

Axis Clinical Software, Inc.<http://AxisClinical.com>

________________________________
