### ISSUE TITLE
Support additional characters in classnames

### ISSUE THREAD

**Issue by copperschnack** [intersystems-community/vscode-objectscript#337]
The classname `tmp.BigBäng` is supported in Studio. In VS Code, I get the following error when I save my changes, see Screenshot.

`ERROR #5001: Couldn't get text for tmp.BigB.cls`
`ERROR #16000: Line: 'Line: 0 Offset: 0 ERROR #5351: Class 'tmp.BigB' does not exist.' Offset: '%2'`

![image](https://user-images.githubusercontent.com/14861913/93192852-67d4eb80-f746-11ea-98c6-ff43142481aa.png)

**Comment by gjsjohnmurray** [comment]
> @copperschnack please download 1.0.5-beta.10 ...

Nevermind. 1.0.5 has been published.

**Comment by copperschnack** [comment]
@gjsjohnmurray sorry for being late: 1.0.5 works like a charm - THANK YOU!
