### ISSUE TITLE
Brackets in comments don't allow a file to compile

### ISSUE THREAD

**Issue by KyleShelton** [intersystems-community/vscode-objectscript#339]
A very common occurrence in our code base is a comment that is styled like this 
![Screenshot 2020-09-17 100532](https://user-images.githubusercontent.com/17133195/93482123-5833df00-f8cd-11ea-98fe-09b61c6fa991.png)
When I compile this file, the comment looks like this
![image](https://user-images.githubusercontent.com/17133195/93482214-7568ad80-f8cd-11ea-88e8-727ec546490d.png)
and produces this error message
![image](https://user-images.githubusercontent.com/17133195/93482250-7e597f00-f8cd-11ea-84de-113c42d1f368.png)
removing the bracket from the comment isn't an option as it is used for formatting help documentation

**Comment by daimor** [comment]
Just to clarify, is it happens when you have format on save activated, or when you format code by command manually, or just compile it as is and this change occurs?

**Comment by KyleShelton** [comment]
This happens when I save and compile the file. Here are my current settings
![image](https://user-images.githubusercontent.com/17133195/93483152-84039480-f8ce-11ea-8d2f-1e4e8a6a06a8.png)

**Comment by daimor** [comment]
I have not managed to reproduce the issue. 
Could you disable any other extensions, to see if maybe some other extension could do this?

**Comment by KyleShelton** [comment]
I do not have any other extensions installed right now

**Comment by daimor** [comment]
So, maybe you can insert here a minimal reproducible piece of code?

**Comment by gjsjohnmurray** [comment]
@KyleShelton do you still see this issue with the latest released version? Also, I see that you have set `"objectscript.autoPreviewXML": true`. Are you working with classes in XML format rather than UDL?

**Comment by gjsjohnmurray** [comment]
pinging @KyleShelton for status update

**Comment by gjsjohnmurray** [comment]
Closing - no response from @KyleShelton
