### ISSUE TITLE
Auto-Compile and Auto-Save Breaks Classes

### ISSUE THREAD

**Issue by nickmitchko** [intersystems-community/vscode-objectscript#340]
When writing a class, the auto-compile and auto-save break the formatting. It'll put the extends block above the classname, create unwanted classes on the server, and I can't even finish properties before it destroys my code.

How do I disable this so I only compile and import when I physically click ctrl+F7 or crtl+S?

![vscode fail2](https://user-images.githubusercontent.com/7769991/93497536-82da6380-f8de-11ea-9673-37b3622ca098.gif)

**Comment by nickmitchko** [comment]
As you can see in the screenshot, this formatting just seems to move everything around, If I make a typo the code changes all around it including the cursor position, the extends block moves all around.

And this movement and malformatting happens with the following:

- Properties and Parameters
- Methods, ClassMethods, XData Blocks
- Classes, Inheritance, Includes, Extends

**Comment by daimor** [comment]
Did you catch that your code is not correct?
But anyway, this behavior comes from IRIS, when we send this code to the server, and compile it, then we update it from the server, due to the possible changes on server side.

**Comment by nickmitchko** [comment]
@daimor **I am typing, this happens as I type, this isn't like I forgot to include an extension class**

1. I am extending a class
2. I look over to my project to remind myself which class to extend
3. In the 5 seconds that takes I come back to a mess in my class.

Is there a way to disable the autocompile / autoimport? I don't see an apparent way in documentation.

**Comment by isc-jamien** [comment]
Yes, this auto compile/auto import will lead to all sorts of problems. It should be completely disabled in my opinion.

**Comment by daimor** [comment]
I did not use auto compile for ObjectScript and even don’t know to configure it, you should look at VSCode settings, we don’t have it in this extension

**Comment by daimor** [comment]
```
  "files.autoSave": "off",
```

**Comment by nickmitchko** [comment]
That worked. I think that the auto-save gets reverted when vscode updates.
