### ISSUE TITLE
Server Side Source Control - how to add Studio project equivalent?

### ISSUE THREAD

**Issue by dkutac** [intersystems-community/vscode-objectscript#345]
Hi, In Studio, serve side source control hooks allow to leverage current project name and put it into the local workspace path (e.g. with SVN hooks). How can the project name be passed into the server side hooks?
Can settings be enhanced so on Workplace level this can be defined?

**Comment by timleavitt** [comment]
@dkutac how does your extension use the studio project name? The challenge is that there's a server-side %Studio.Project object for a legacy Studio project, but there isn't a similar concept where the server would know what's part of a VSCode workspace.

**Comment by dkutac** [comment]
@timleavitt , it uses project name to construct a path in both local workspace and repository. e.g. for local svn sandbox it forms the path this way: c:\sandbox\{username}\{namespace}\{projectname}\ followed by item name serialized in such way that it replaces dots with underscores.
There are partners who use my SVN hook for long timer. 
I think an reasonably easy solution could be to put project name into folder specific settings of the VSCode, but I have no clue how difficult it would be to implement in such way.
Anyway, this is not a high priority and there are some workarounds available without need to change VSCode plugin.

**Comment by gjsjohnmurray** [comment]
@dkutac if you saved your workspace as XYZ.code-workspace maybe we could pass "XYZ" as the Studio project name. Would that work?

**Comment by dkutac** [comment]
@gjsjohnmurray , if you show me how to pass this information to the server so %Studio.SourceControl class can use it, then yes. I checked %request object and there is no such information there and I have no clue how else it could be passed.

**Comment by timleavitt** [comment]
@dkutac where's the source for your SVN hooks?

**Comment by dkutac** [comment]
@timleavitt, I never published it , I'm going to send you email with archive and instructions.

**Comment by dkutac** [comment]
@timleavitt , what is your email?

**Comment by pisani** [comment]
hi Daniel, I think a sample %Studio.SourceControl subclass implementing server-side source control to GitHub for developers doing server-side development, would be a great addition to the product. is this something you are playing with ?

**Comment by dkutac** [comment]
HI Steve, no, I do not do anything in this direction.

**Comment by timleavitt** [comment]
@pisani see https://github.com/intersystems-ib/cache-git-studio

**Comment by pisani** [comment]
thanks Tim.  I've looked at cache-git-studio again.
My target state is - however, to be at a point where users can choose their own (preferred) IDE (VSCode or IRIS Studio), and switch accordingly as one product catches up in maturity to the other.   Ideally - I'd like to have a version of cache-git-studio (iris-git-studio ?) that honors vscode export settings and categories, as well as format (UDL vs ODL) - but that is not the case.  This would not be hard to do.
I do realise that this discussion probably does not belong here, but perhaps in a different forum.

**Comment by timleavitt** [comment]
@pisani agreed all around. I don't think this would be too difficult to accomplish via a subclass of `%Studio.SourceControl.File` or a fork of cache-git-studio. Let's take this discussion to a different venue - I'll reach out via e-mail.

**Comment by isc-rsingh** [comment]
@dkutac can this be closed?

**Comment by dkutac** [comment]
yes, thought the discussion diverted from the orgiginal issue, but I believe Tim knows what to do.
