### ISSUE TITLE
Server Side Hooks - Target as CSP page not working as expected

### ISSUE THREAD

**Issue by dkutac** [intersystems-community/vscode-objectscript#346]
when a server side hook specifies target in the menu handler as a CSP page, it won't close as it does in Studio, nor it performs action specified. see pictures illustrating the issue.

![Screenshot 2020-09-21 154011](https://user-images.githubusercontent.com/10270607/93774560-ade7ee80-fc21-11ea-9140-460a9fa0c096.jpg)

![Screenshot 2020-09-21 154412](https://user-images.githubusercontent.com/10270607/93774580-b2140c00-fc21-11ea-89c3-d4155c4730bd.jpg)

**Comment by timleavitt** [comment]
@dkutac - @ty-d may be able to chime in on this as well. My understanding is that VSCode's web view support doesn't have access to the DOM from within the IDE code, in the same way that Studio's IE shell does. We've added a separate API for this using window.parent.postMessage - i.e.:

```
	If (%request.Get("EndTemplate") = 1) {
		If (%request.UserAgent [ " Code/") {
			// For VSCode only:
			Set %response.ContentType="text/html",%response.CharSet="UTF-8"
			Write "<html>",!
			Write "<script type=""text/javascript"">",!
			&js<if (window.parent) {
				window.parent.postMessage({"result":"done"},'*')
			}>
			Write "</script>",!
			Write "</html>",!
		} Else {
			Set %response.ContentType="text/xml",%response.CharSet="UTF-8"
			Set delim = ##class(%CSP.StudioTemplateError).#DELIM
			Write "<?xml version=""1.0""?>",!
			Write "<template><![CDATA[BODY",delim
			Write delim,"]]]]><![CDATA[></template>",!
		}
		Quit $$$OK
	}
```

**Comment by timleavitt** [comment]
@gjsjohnmurray I think this is in OnPreHTTP in a class extending %CSP.Page.

For the typical template inheritance hierarchy it'll probably look a little different. Would be happy to connect to look at an example if you'd like. (I'm assuming you've hit the same thing on one of George James' products?)

**Comment by gjsjohnmurray** [comment]
Where file-based CSP templates or add-ins are being used, here's how I changed the contents of the page which ends the sequence.

Before:
```
<csp:StudioGenerateTemplate>
```

After:
```
<csp:StudioGenerateTemplate>
<script language="Cache" method="OnHTTPHeader" arguments="OutputBody:%Boolean" returntype="%Status"> 
	If (" "_%request.UserAgent[" Code/") {
		// For VSCode only:
		Set %response.ContentType="text/html",%response.CharSet="UTF-8"
		Write "<html>",!
		Write "<script type=""text/javascript"">",!
		&js<if (window.parent) {
			window.parent.postMessage({"result":"done"},'*')
		}>
		Write "</","script>",!
		Write "</html>",!
		Quit $$$OK
	} else {
		Quit ##super(.OutputBody)
	}
</script>
<script language="Cache" method="OnPostHTTP" arguments="" returntype=""> 
	If (" "_%request.UserAgent'[" Code/") {
		// For non-VSCode only:
		Do ##super()
	}
</script>
```

**Comment by gjsjohnmurray** [comment]
Also note that on IRIS 2021.1 or later it's necessary to change the session-handling setting for the /isc/studio/usertemplates web application from its default (Always) to Autodetect, otherwise the Close button of the dialog results in an authentication dialog instead of closing the tab.

This is because the security constraints of the webview tab prevent cookies from being planted.

**Comment by isc-bsaviano** [comment]
@timleavitt Is there anything that needs to be changed in this extension to fix this issue? Or has this already been addressed somewhere else?

**Comment by isc-tleavitt** [comment]
@isc-bsaviano it's a matter of changing extension/addin/template code as @gjsjohnmurray said earlier. (VSCode web views have different constraints than Studio's embdded IE, so it can't just work the same way.)

Another option would be to update <csp:StudioGenerateTemplate> upstream to have behavior dependent on user agent.

**Comment by isc-bsaviano** [comment]
@isc-tleavitt Ok, I'm going to close this then since there's nothing for us to change
