### ISSUE TITLE
Fail more descriptively if user is unprivileged

### ISSUE THREAD

**Issue by timleavitt** [intersystems-community/vscode-objectscript#352]
Ran into an issue using isfs with a user that didn't have the %Developer role - everything looks fine with the connection up until the user runs the query to list folder items (via StudioOpenDialog, which requires %Developer). This fails with
`ERROR #5540: SQLCODE: -99 Message: User Admin is not privileged for the operation` but there isn't an indication of any connection error.

It took a lot of debugging to figure out what was going on - and now that I know what I'm looking for it'll be much easier to diagnose such issues in the future. Still, it would be good to provide a better indicator than a message in ObjectScript output (which I didn't see until after diagnosing the issue); e.g., setting the connection status to errored or putting some kind of warning flag on the isfs folder. I'm not sure what the right solution is but it was too difficult to figure out what was going on in this case.

**Comment by daimor** [comment]
https://github.com/intersystems-community/vscode-objectscript#notes

I would say, that, this is mostly IRIS issue. When even having %Developer role, it needs some changes in the security, to get it working.

**Comment by isc-jamien** [comment]
Can you describe what else is needed apart from the %Developer role?

**Comment by daimor** [comment]
Security is in fact quite a complicated question. It should by default have access to call `%Library.RoutineMgr_StudioOpenDialog` function. But it may not enough if it does not have access to a particular database which contain developing application. And anyway developers should have access to any system class.

**Comment by gjsjohnmurray** [comment]
PR #681 improves the notification messages
