### ISSUE TITLE
ERROR #16005: Document 'Ens.Queue.1.int' does NOT exist

### ISSUE THREAD

**Issue by nablagodel** [intersystems-community/vscode-objectscript#359]
Hello!

When I am trying to debug then I get error. User has all permissions and roles.

```
Unable to open 'Ens.Queue.1.int': 404 - {"status":{"errors":[],"summary":""},"console":[],"result":{"name":"Ens.Queue.1.int","db":"","ts":"","cat":"RTN","enc":false,"content":"","status":"ERROR #16005: Document 'Ens.Queue.1.int' does NOT exist"}}.
```

**Comment by gjsjohnmurray** [comment]
Ens.Queue is a system class, and IIRC it isn't compiled in such a way as to retain INTs.

At a terminal prompt in the namespace what happens when you `zl Ens.Queue.1` ?

**Comment by nablagodel** [comment]
I recorded a video with visual description of the problem https://youtu.be/BjGa7a-v5ww.

**Comment by gjsjohnmurray** [comment]
@nablagodel thanks for the video.

@daimor it looks like when Attach to Process is used as the way of starting debugging, if there is no INT code for the routine in which the target process gets interrupted then the extension doesn't handle this well.

In the example given here it's an Ensemble/IRIS Interoperability background process that the OP is attaching to. AFAIK there's no INT code shipped for the Ens.Queue class.

**Comment by daimor** [comment]
Yeah, but what would your expected behavior? If I remember correctly, Studio's debugger does not work with this case as well. 
I think the best way would be if the debugger, on the IRIS side, just skipped steps with no open code and stop right when it will be able to show the executed place in code.

**Comment by nablagodel** [comment]
In general, I'm trying to debug my service, operation and process in IRIS Community Edition with yours Visual Studio ObjectScript extension. But I cannot do it.

For example, 
1. I set a breakpoint in a self-written business service,
2. then I attach the debugger of the extension to the job (by ID) of business service,
3. call the business service via HTTP request,
4. but debugger don't stop on breakpoint.

**Comment by daimor** [comment]
@nablagodel could you send me some, reproducible example, and how you test it, so I could try it

**Comment by daimor** [comment]
https://github.com/intersystems-community/vscode-objectscript/suites/1297293399/artifacts/20307273

Please download this build of this extension, and install it in VSCode with command Install from vsix...

There the issue with not existing files should be solved, it should be able to debug, and it will show the correct stack trace, but with no ability to dive to not existing place, debugger cursor will keep on the latest available position

**Comment by nablagodel** [comment]
@daimor thank you. The error has gone. But I still have no way to debug. Another video https://youtu.be/Cexpl8fxobU. :) I was trying to follow an instruction https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=EGDV_testing#EGDV_testing_debugging, but probably a foreground mode doesn't work.

**Comment by nablagodel** [comment]
@daimor suggested resolution of the problems in another issue #370.
