### ISSUE TITLE
Source control application from Multiple namespaces

### ISSUE THREAD

**Issue by pisani** [intersystems-community/vscode-objectscript#364]
Hi,

Typically, applications could be made of code residing in multiple databases.  For example, myAppLIB database may contains library object script classes/functions, and, myAppCode may contain my application code.   I'm trying to figure out what is the best approach to setup a git repository and VSCode with local editing for these sort of multi-database solutions.

my 'MyApp' namespace takes care of class/routine mapping.  My application is distributed with 2 databases (myAppLib and myAppCode), and appropriatley configured MyApp Namespace 

I want to export code to my PC, and edit it locally, before staging this in Git, and pushing to GitHub. 

How does one setup a workspace where there are two IRIS sources, and, two different Export folders ? (eg, I want classes, etc,  from the myAppLib database to be exported to /myApp/src/myAppLib and and from the myAppCode database to be exported to /myApp/src/myAppCode)

I know about the multi-root feature, but I could not see how I could pull code from separate databases into, separate local source folders. 

I'm open to suggestion here - but essentially I have a solution made up of multiple databases of code, which together, constitute a single solution.

Steve

**Comment by daimor** [comment]
So, I suppose, you have one namespace, and you connect to all of those code from one place. And you have to use package mapping to be able to use code from different databases. If, so, I see only one issue, is how to split your code by different folders in the same project. As VSCode and even Studio, does not care about their location in the database, it's enough to be available in the desired namespace. I can offer only one option is to export it by filters.
```
"objectscript.export": {
  "folder": {
    "MyAppLib.*": "MyAppLib/src",
    "*": "MyApp/src"
  }
}
```
I did not check it, but I hope it should work. It will place Classes from package MyAppLib to a defined folder MyAppLib/src, and anything else, to MyApp/src. You may define as many filters as needed and remember about the order.

**Comment by pisani** [comment]
thanks.  ok I think that will work. essentially - it will be like Package 'Un-Mapping' by VSCode end to 'un-map' source code of a namespace back into database-specific /src paths.

**Comment by gjsjohnmurray** [comment]
> I know about the multi-root feature, but I could not see how I could pull code from separate databases into, separate local source folders.

@pisani if you give each database its own namespace (MYAPPLIB, MYAPPCODE) in addition to pointing the app namespace (MYAPP) at them via package mappings, I think you could use a multiroot workspace that connects to MYAPPLIB and MYAPPCODE.

**Comment by gjsjohnmurray** [comment]
@pisani do you need more on this or can it be closed?
