### ISSUE TITLE
Make 'Jump to Tag + Offset' use DocumentSymbolProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#368]
Instead of doing its own scan for labels in the text of MAC and INT documents it could invoke [`vscode.executeDocumentSymbolProvider`](https://code.visualstudio.com/api/references/commands#commands) and filter to get only those whose `kind` is `SymbolKind.Method`.

See #367 for a reason to do this.

**Comment by gjsjohnmurray** [comment]
@ty-d you implemented this technique recently as part of https://github.com/intersystems-community/vscode-objectscript/pull/609. Would you be willing to update 'Jump to Tag + Offset' to do the same?

**Comment by ty-d** [comment]
Yes, I can update it
