### ISSUE TITLE
Create Exported API for Docker-Compose Configuration Changes

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#369]
The language server extension caches the server connection info for each opened document and relies on notifications from the client to invalidate that cache (document is closed, configuration in settings.json changes, password stored in keychain via server manager changes). Since the configuration information when using the docker-compose configuration may change during runtime without triggering any of those 3 notifications, I propose adding an event to the exported API that the language server can consume so its cache is properly invalidated. Please see server-manager PR #13 for how that extension creates the event API. Thanks.

**Comment by daimor** [comment]
implemented in PR #360 
can be tested, added `onDidChangeConnection`
