### ISSUE TITLE
Debugging with attach to Ensemble process

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#370]
@daimor thank you. The error has gone. But I still have no way to debug. Another video https://youtu.be/Cexpl8fxobU. :) I was trying to follow an instruction [Debugging Production Code](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=EGDV_testing#EGDV_testing_debugging), but probably a foreground mode doesn't work. I don't know how the foreground mode should work in real.

I'm using Ubuntu Linux.

_Originally posted by @nablagodel in https://github.com/intersystems-community/vscode-objectscript/issues/359#issuecomment-704871925_

**Comment by daimor** [comment]
It does not look like it's possible to do it this way. The documentation says, to use foreground instead of background.
The job started to serve the service, and you attached with the debugger is just a control process and it starts a new process to do a real work, where do you expect it with the breakpoint.

**Comment by daimor** [comment]
Well, I found how to debug it.
You have to untick 'Job per connection' option. And in this way, the process you attached will do everything.
But, Just after attach, the process is on pause, and you have to start it.

Breakpoint or break command will do the same, so, if you have break command in your code, the debugger will stop there anyway.

**Comment by nablagodel** [comment]
@daimor thank you very much! Everything works good now. Perhaps this experience will be useful for others https://youtu.be/JnPNNrakSvM.
