### ISSUE TITLE
Treat deployed classes as read-only

### ISSUE THREAD

**Issue by isc-apino** [intersystems-community/vscode-objectscript#382]
Expected behavior: a deployed class should be treated as read-only by VS Code, similar to how they are treated by Studio. 
Developers should be able to open class with method bodies removed and delete the class, but should not be able to edit or save the class.

Actual behavior: deployed classes are treated as read-write by VS Code. Developers are able to open the class with method bodies removed and can delete the class as expected, but can also edit and save the class. This is a major issue since saving the class will save it as each method not having a body. An accidental save can therefore wipe out an entire class, which if the developer doesn't have access to the source can be difficult to get back.

**Comment by gjsjohnmurray** [comment]
@ajpino good catch. Are you using isfs and editing directly in the server namespace?

**Comment by ajpino** [comment]
I've observed this behavior with server side editing turned on using both isfs and the objectscript explorer.

**Comment by gjsjohnmurray** [comment]
My understanding is, server side editing from ObjectScript Explorer actually uses isfs under the covers. @daimor can confirm.

**Comment by daimor** [comment]
Right, if server editing is enabled, but ServerExplorer have ability to delete classes in any case. 

And perhaps, this issue have to be fixed in Atelier API as well, preventing any such changes for deployed code.

**Comment by gjsjohnmurray** [comment]
@daimor could importFile use the /action/index API endpoint when handing a class, to get result.content.content.depl and throw if it is true?

**Comment by daimor** [comment]
Yes, and isfs can also use it, to mark file as read-only.

**Comment by gjsjohnmurray** [comment]
> isfs can also use it, to mark file as read-only.

@daimor I'm not clear what you mean. A FileSystemProvider can only supply read-only documents by registering itself with that characteristic. That's what `isfs-readonly` does. VS Code doesn't yet allow individual documents to be toggled read-only or read-write.
