### ISSUE TITLE
Document how to enable VS Code's proposed APIs for server-side searching

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#385]
See https://github.com/intersystems-community/vscode-objectscript/issues/126#issuecomment-674089387

We currently implement `FileSearchProvider` and `TextSearchProvider` when `--enable-proposed-api` is set as a launch argument.

**Comment by gjsjohnmurray** [comment]
Added to 1.0.5 README in PR #475 

Still needs to be added to main docs.

**Comment by copperschnack** [comment]
@gjsjohnmurray maybe, you want to add a hint to the docs that "enable-proposed-api" is available in beta versions of the extension only?

**Comment by gjsjohnmurray** [comment]
@copperschnack see #478

**Comment by jstetson10** [comment]
Questions in my mind include: what exactly is a 'proposed' api, and what's going on with "maybe, you want to add a hint to the docs that "enable-proposed-api" is available in beta versions of the extension only?" If this is a pre-release feature, it should probably be discussed in the README until it has achieved released status.

**Comment by isc-rsingh** [comment]
@gjsjohnmurray I tend to agree with @jstetson10 that it may be confusing to cover features not available in the Marketplace version in the main documentation. How about a separate document -- something like BETAFEATURES.md -- and a reference to it from the README?

**Comment by isc-bsaviano** [comment]
I think the README is the right place for this, and since #1140 we link to it in the extension.
