### ISSUE TITLE
Debugger fails to start when using multi-root workspace with isfs

### ISSUE THREAD

**Issue by pravinb1** [intersystems-community/vscode-objectscript#387]
I get an error pop-up with "Debugger can not start" when I try to launch the objectscript debugger. It looks like the extension doesn't know what namespace I'm in so it's throwing an error from the serverInfo() method in AtelierAPI.
Here is my workspace configuration:
```
{
	"folders": [
		{
			"name": "cls",
			"uri": "isfs://pbarton_local/?ns=CCR&type=cls"
		},
		{
			"name": "rtn",
			"uri": "isfs://pbarton_local/?ns=CCR&type=rtn"
		}
	],
	"settings": {
		"objectscript.showExplorer": false,
		"intersystems.servers": {
			"pbarton_local": {
				"webServer": {
					"scheme": "http",
					"host": "localhost",
					"port": 57772
				},
				"description": "Connection to my local Cache environment",
			},
			"/default": "pbarton_local"
		}
	},
	"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"type": "objectscript",
				"request": "launch",
				"name": "cosdebug",
				"program": "##class(UnitTest.CCR.AppSight.Task.CCRScanner).RunMe()"
			}
		]
	}
}
```

**Comment by gjsjohnmurray** [comment]
@pravinb1 I was able to reproduce this, though my error message was different.

Until it is fixed you can probably work around it by adding the following to your .code-workspace file's settings section:
```
		"objectscript.conn": {
			"active": true,
			"ns": "CCR"
		}
```

This should force debugging to target the CCR namespace.

**Comment by pravinb1** [comment]
Thank you, adding the objectscript.conn property got it to work for me.

**Comment by daimor** [comment]
@pravinb1 could you check if it's fixed, with this build https://github.com/intersystems-community/vscode-objectscript/actions/runs/386842599
