### ISSUE TITLE
Issue with syntax highlighting of comments

### ISSUE THREAD

**Issue by isc-aray** [intersystems-community/vscode-objectscript#406]
It is often not permitted to begin a comment immediately after ObjectScript code without intervening whitespace. However, there are some circumstances where comments are permitted without intervening whitespace. All of the following comments are legal:

``` objectscript
    Set myvar="test",;; Legal comment
        var2=; another comment
            "string to concatenate"_// here's a comment
            "with another",
        var3=..LocalMethod(; And one more legal comment
            "argument"
        )
```

However, the language server reports them as syntax errors:
![image](https://user-images.githubusercontent.com/43610734/96718449-0a037700-1376-11eb-8c3a-701f00fa3cb7.png)

Note that this does not apply to `/* inline comments */` or `##; macro comments`, which are both marked correctly marked as legal in these locations.

**Comment by gjsjohnmurray** [comment]
Studio does the same:

![image](https://user-images.githubusercontent.com/6726799/96732765-9c287100-13b0-11eb-9b8d-ec2a22724353.png)

Language Server leverages the same parser. @isc-aray are you willing to raise this upstream issue internally?

**Comment by isc-aray** [comment]
@gjsjohnmurray That's unexpected. I'll see if I can find out who's responsible for the Studio syntax parser.

**Comment by isc-aray** [comment]
@gjsjohnmurray I have reported the issue to the Studio team. I'm not sure how they want to track any progress on that work.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano does this have a tracking issue in your repo it could be pointed to?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray No but it was filed internally as a Prodlog and is on Andy's todo list. I'll create a LS issue for this and point it to this so you can close this version.
