### ISSUE TITLE
Suggested doc improvements

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#409]
A task list to collect/track improvements to what is published at https://intersystems-community.github.io/vscode-objectscript/

(checkmarks updated to reflect #441 changes)
### Installation.md
- [x] Refresh Marketplace screenshot so it shows icons and more recent version & publisher information.
- [x] Once https://github.com/intersystems-community/vscode-objectscript-pack publishes, suggest install of the extension pack instead of the individual extensions. A search for 'intersystems' returns more than just the extensions needed.
- [x] ObjectScript Explorer icon only appears on the activity bar when a folder or workspace has been opened.

### workspace.md
- [x] It is not true that a .code-workspace file is always in the root folder.

### Configuration.md
- [x] An 'Add Server' user story that begins from the '+' button of a Server Manager quickpick is significantly simpler for newcomers than the current one which requires opening a JSON file and editing that. In which case, relegate the details of the JSON structure to a later section about editing an existing connection spec.
- [x] PR #408 reinstated references to three `InterSystems Server Manager: Test ...` commands that no longer exist. Remove these references.
- [x] The need to add an `objectscript.conn` to JSON settings can also be avoided. Open the folder you want to put client-side files in. Click on the ObjectScript Explorer icon on the activity bar. Use the 'Choose Server and Namespace' button. Pick a server (or add a new one). Pick the namespace on the server. That's it. The required `objectscript.conn` will get created in the .vscode\settings.json file of your folder.
- [x] The info under 'Configuring Export from Server' is really for advanced users in the situation where the default export behaviour doesn't meet their needs. Don't alarm newcomers with it.

### ServerSide.md
- [x] Fix the `=======` string that appears above the step-by-step list.
- [x] In step 4 add a note that a new server definition can be added using the '+' button.
- [x] Expand step 7 to cover how this part of the process now has four options (two each for code and webapps).
- [x] 'Web Application (CSP) Files' section is advanced info now that the above step 7 supports adding of a webapp-type folder to the workspace.

**Comment by jstetson10** [comment]
I'll need some input regarding what the current status of Web Application (CSP) Files is and how they should be handled in the documentation.
