### ISSUE TITLE
Save As issue

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#410]
1. Work server-side using isfs
2. Have a simple class in your namespace, e.g.
```objectscript
Class YJM.BeforeSaveAs
{

Property before As %String;

}
```
3. Use `File\Save As...` and enter a new name e.g. `AfterSaveAs.cls` 
![image](https://user-images.githubusercontent.com/6726799/96769715-6480ef80-13d7-11eb-8bae-30faff6b4d76.png)

4. Add another property but forget to change the name of the class on the top line:

![image](https://user-images.githubusercontent.com/6726799/96769874-a3af4080-13d7-11eb-878f-66be195a2a92.png)

5. Close your class and reopen it from Explorer. It is only the stub one.

6. Open the original class. It has the changes you thought you made in the new one.

Maybe export to server should cross-check filename against embedded class name.

**Comment by isc-rsingh** [comment]
Suggested fix: fail the save until user fixes the name.
