### ISSUE TITLE
Issue with syntax coloring when Japanese(UTF8) letters are included

### ISSUE THREAD

**Issue by IRISMeister** [intersystems-community/vscode-objectscript#411]
I just start using brandnew VSCode Language Server and found it excellent! except that it generates tons of syntax errors when Japanese letters are included (as comment line, literal, variable names...).
As an example, you can pull the following repo and open wsdemo/project/Common/ProductMaster.cls (or anything).
https://github.com/IRISMeister/whdemo-wsdemo.git
It compiles successfully.
Studio syntax coloring works file. 
![syntax](https://user-images.githubusercontent.com/12710874/96838120-69e74400-1482-11eb-96b6-4794e36492a2.JPG)

**Comment by gjsjohnmurray** [comment]
Thanks for your report. I have opened an issue at https://github.com/intersystems/language-server/issues/31 for the Language Server team to deal with.
