### ISSUE TITLE
Change file names during export

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#412]
Needs the ability to transform file names during export.
for instance any % classes, should use underscore instead of the percent sign
%ZPM.PackageManager.cls have to be stored on the disk as _ZPM/PackageManager.cls

**Comment by isc-jamien** [comment]
I suggest that this is implemented with a pair of user-modifiable javascript functions that take the file name, direction and transformed value. The _ vs % thing is an artifact of support for Perforce source control and the requirement may well be different for other situations.

**Comment by daimor** [comment]
This extension uses export settings to associate a physical file with a remote one. Mostly one side, just to get the physical place for a logical name. The logical name from the physical file is getting just from parsing.

And what I did in PR, is an array of regular expressions, pattern and replacement
