### ISSUE TITLE
Multiple CSP-Sessions

### ISSUE THREAD

**Issue by Erich11** [intersystems-community/vscode-objectscript#416]
Since updating to v1.0 each change in VS Code will spawn one CSP-Session on my system, until the maximum number of licences is reached.
I tried to restrict /api/atelier/ to password authentication only, didn't help.
Only solution for me as of now is to reduce the timeout of /api/atelier/ to 5 seconds.

WRC could replicate the issue, but directed me to report the bug here.
"Yes, I see the same behavior.
Looks like some component of the extension does not send cookie with the session back to the Caché server.
As VS Code extension is driven by community, please report this bug to the VSCode-objectscript issues board:"

![apiatelier2](https://user-images.githubusercontent.com/22928859/96871224-43211180-1472-11eb-83da-c10b64a525ae.PNG)

**Comment by daimor** [comment]
That's interesting, I thought, I've already solved it. Since that I'm mostly using Community Edition version, I would catch it faster.
Do you using Debugging, or just edit code, could you explain how you use it most? Can you catch, when it adds a new session?

**Comment by daimor** [comment]
Well, I think, I know how it's happening, it's another extension

**Comment by gjsjohnmurray** [comment]
Believed to be resolved in Language Server 1.0.1 which is now published. @Erich11 please verify and close / update this issue.

**Comment by Erich11** [comment]
I just checked with Language Server 1.0.1.
After typing three lines of code, I already have 18 /api/atelier/ CSP-Sessions consuming 18 licenses.

As for your first question, I mostly edit code. Some debugging with classes, but I don't think that this is relevant, as pure typing inside any routine is enough to trigger this bug.

**Comment by daimor** [comment]
Just to be sure, that the issue really in Language server, could you install the [latest beta version](https://github.com/intersystems-community/vscode-objectscript/releases) of this extension and disable the language server extension temporarily

**Comment by Erich11** [comment]
I updated VS Code to 1.50.1 and vscode-objectscript to v1.0.2-beta.5.
When I disable the Language Server extension, only one or two Sessions are created.
Enabling it will again create many sessions, although I've yet to find a pattern on when a new session will be created. Sometimes editing code is enough to create two or three new sessions, sometimes none are created.

Creating a new file on the server (with extension enabled) resulted in 4 new sessions (I ended all sessions in management studio prior to this), editing and saving the file resulted in no new sessions.
Creating another new file without deleting the 4 sessions prior only created 1 new session.
Opening and editing an existing file afterwards created 3 new sessions.

Another observation:
When I newly open VS Code, up to 34 new CSP session will be created, whether language server extension is enabeld or disabled. I don't know if this happened before updating to the latest beta.

**Comment by daimor** [comment]
Beta version just contains a fix, to keep extension working well when language server have not enabled.

Thanks, it means that we need some more work on language server extension with sessions

**Comment by BoBo3991** [comment]
At the version 1.0.2 of the Language Server, it's opening one CSP-Session per opened file now. 
This still leads to a lot of opened CSP-Sessions.

**Comment by daimor** [comment]
Could you also install the [latest beta](https://github.com/intersystems-community/vscode-objectscript/releases) for the main extension

**Comment by BoBo3991** [comment]
I installed the latest beta (1.0.4-beta.5) and restarted VS Code. The behaviour does'nt change.

**Comment by gjsjohnmurray** [comment]
Looks like this is https://github.com/intersystems/language-server/issues/41

**Comment by gjsjohnmurray** [comment]
Closing it here. The issue will be followed up on the LS repo.
