### ISSUE TITLE
Is it possible to switch off (or fine tune) absent classes detection?

### ISSUE THREAD

**Issue by AlexeyM64** [intersystems-community/vscode-objectscript#420]
False positives that are being detected are associated with non-% system classes, e.g.:

 set sc=##Class(Config.Databases).Get(pDB, .prop)

It's virtually impossible to recognize that the current namespace was preliminarily switched to "%SYS", so maybe it worth introducing a setting whether to consider "absent classes" problematic or not.
By the way, you already have a similar setting for MACs and INCs.

**Comment by daimor** [comment]
Hi Alexey, please fill it as an enhancement request in [language-server extension repo](https://github.com/intersystems/language-server/issues)

**Comment by gjsjohnmurray** [comment]
https://github.com/intersystems/language-server/issues/36
