### ISSUE TITLE
Multiple connection issues when using server-side editing.

### ISSUE THREAD

**Issue by pisani** [intersystems-community/vscode-objectscript#424]
Several issues when you try to use VSCode to do server-side  editing. (start with no open folder, or workspace - then Select explorer, and 'Choose Server and Namespace).

1. I choose server from the list, enter username and password - then- VSCode re-prompts me for username (?) again. before giving me the namespace list. - that's the first problem.

2. Then I add a second server and namespace - VSCode prompts me for a username - but not a password... This is a second issue.
Since the password is the same on both servers, I now see two servers:namespace connections in my workspace, and I can swtich between the two.

3. If I go to Extension Settings for Objectscript, I see that, apart from User and Workspace, I also see a third tab, with a drop down I can use to select either of my server side connections. When on this tab, trying to invoke 'edit in settings.json' brings up nothing.

4. Back in Explorer, I remove my 1st server:namespace using 'Remove folder from workspace'. This breaks my second (I think we know somehow from problem #2, that they share the same credentials). When I do remove the 1st entry, VSCode prompts me for username again. - and then password - and then I'm back in business.

I have also found myself in the situation many times, which I cannot re-produce now for some reason - sometimes, when working with connecting to namespaces VSCode is prompting me:

_Authorization error: Check your credentials in Settings, and that you have sufficient privileges on the /api/atelier web application on 127.0.0.1:52777[TRAINING]__

with the top input box saying _"Not Authorised, Enter password to connect as user 'undefined' ..."_ 
as it tries repeatedly to connect as an Unauthenticated user. On IRIS in the security log I see repeated login failures to /api/atelier.

Steve

**Comment by gjsjohnmurray** [comment]
@pisani thanks for your feedback. I know you'll understand it's a busy time for the team right now, but here are some initial responses from me.

> 3. If I go to Extension Settings for Objectscript, I see that, apart from User and Workspace, I also see a third tab, with a drop down I can use to select either of my server side connections. When on this tab, trying to invoke 'edit in settings.json' brings up nothing.

See the first screenshot on https://github.com/intersystems-community/vscode-objectscript/pull/384 for how to set up the webapp that will provide the required server-side support for this level of VS Code settings storage.

We need to investigate why you don't get a notification if you try to use this level without the necessary config on the server.

> 4. Back in Explorer, I remove my 1st server:namespace using 'Remove folder from workspace'. This breaks my second (I think we know somehow from problem #2, that they share the same credentials). When I do remove the 1st entry, VSCode prompts me for username again. - and then password - and then I'm back in business.

For legacy reasons VS Code performs a full reload of your environment if you add or remove the first root folder of a multiroot workspace, or if you resequence your roots in such a way as to affect which is first.


Re the overprompting for password(s), a workaround while we work on the glitches here may be to use the command that lets you store your password in your keystore.

Related issues: #417 #255

**Comment by gjsjohnmurray** [comment]
@pisani please install https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.4-beta.4/vscode-objectscript-1.0.4-beta.4.vsix and re-test.

**Comment by pisani** [comment]
@gjsjohnmurray version 1.04-beta.4 seems to have fixed the issues #1 and #2 highlighted above - Thanks !

thanks for the input on #3, - will look into that, and re #4 - ok I can live with that.
thanks

**Comment by gjsjohnmurray** [comment]
Resolved by 1.0.4

**Comment by pisani** [comment]
Thanks John

-------- Original message --------From: John Murray <notifications@github.com> Date: 3/11/20  11:09 am  (GMT+10:00) To: intersystems-community/vscode-objectscript <vscode-objectscript@noreply.github.com> Cc: pisani <pisani.stephen@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [intersystems-community/vscode-objectscript] Multiple connection issues when using server-side editing. (#424) 
Closed #424.
