### ISSUE TITLE
Unexplained conflict when importing to Experience Lab 2020 server namespace

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#442]
When using the lab server provisioned by the course ["ObjectScript Development in Visual Studio Code"](https://learning.intersystems.com/course/view.php?id=1536), each time a local .cls file is saved the automatic import into the linked server namespace reports a conflict. The course PDF even notes this, though without justifying it.

For example, open src/FirstLook/Person.cls and save it (Ctrl+S). This dialog appears:

![image](https://user-images.githubusercontent.com/6726799/97246179-9c7f9c80-17f4-11eb-93c5-4439e3b47099.png)

Choose "Overwrite". Then save the file a second time without making any changes. The same dialog appears.

Using the same VS Code instance (thus the same extension versions) I do not get this behaviour when working on my local servers.

**Comment by gjsjohnmurray** [comment]
My deep dive indicates that something in the path between my local VS Code and the remote IRIS hosted at labs.learning.intersystems.com is stripping the `IF_NONE_MATCH` http header from the PUT request sent to the /api/atelier/v2/<namespace>/doc/foo.bar.cls endpoint.

Without the `IF_NONE_MATCH` header the endpoint fails the request with a 409 unless the request specified `ignoreConflict=1`

@isc-rsingh please forward this internally in the hope of discovering what part of the labs.learning.intersystems.com infrastructure is causing this. I'm seeing `X_FORWARDED_FOR` and `X_REAL_IP` headers arrive into IRIS on the request, which some brief Googling suggests is indicative of some kind of proxy or load balancer.

**Comment by isc-rsingh** [comment]
Thanks @gjsjohnmurray we'll look into it.

**Comment by gjsjohnmurray** [comment]
@isc-rsingh the new setting arising from #464 will provide a workaround for this issue. We still need to understand what is causing Experience Lab not to get the `IF_NONE_MATCH` header, in case users get the same problem within their own infrastructure. Fortunately we fail safe in this situation, warning of an overwrite unnecessarily.

**Comment by isc-rsingh** [comment]
no longer testable.
