### ISSUE TITLE
Add ability to load csp or other files to server csp application from client side save or import

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#449]
Using client side source control is difficult for my application that uses /csp/xslt directory with files that should be uploaded to the server /csp/xslt csp application when changes are made.  Certainly this would include various types of files that when imported would be placed in the csp application directory tree.

**Comment by mcronin117** [comment]
I am also interested in this, mostly for CSPs, which are objectscript based, but it would be a nice to have for other file types as well if they synced with the server from the client side

**Comment by gjsjohnmurray** [comment]
See also #147
