### ISSUE TITLE
Request support for method arguments listed on separate lines

### ISSUE THREAD

**Issue by UltraMed** [intersystems-community/vscode-objectscript#457]
Issue Type: <b>Feature Request</b>

Add an option that when selected will list method arguments on separate lines. So instead of

Method MyFunction(X As %String = "", Y As %String = "", Z As %String = "")
{
...
}

you would have
Method MyFunction(X As %String = "", 
                                  Y As %String = "", 
                                  Z As %String = "")
{
...
}

This is very important for readability of methods with a lot of arguments.

Extension version: 1.0.4
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 10.0.14393

**Comment by gjsjohnmurray** [comment]
Arose from #194

**Comment by isc-bsaviano** [comment]
This will be fixed in v4 of the Atelier APIs. From the devkey description:

Passing ?format=udl-multiline for the GET /doc/ endpoint will return the document with method arguments formatted on multiple lines.
