### ISSUE TITLE
Add Feedback instructions to README

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/vscode-objectscript#462]
Get content from https://community.intersystems.com/post/using-intersystems-objectscript-vs-code-how-report-issues

**Comment by gjsjohnmurray** [comment]
Link to DC article added to 1.0.6 README

**Comment by gjsjohnmurray** [comment]
Done in https://github.com/intersystems-community/vscode-objectscript/pull/650 for 1.0.11
