### ISSUE TITLE
For server-side editing, show server in Ctrl-P list for artifact

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#466]
If I add multiple servers to my workspace, and I perform a Ctrl-P to open (for example) a routine, both servers get searched. If the same routine is in both namespaces, I can't tell which is which (see screenshot).
![image](https://user-images.githubusercontent.com/63731219/97876852-6194d180-1cea-11eb-94d5-8c4e94b8ec95.png)

Could the server name be added to the artifact name so we can tell them apart?

**Comment by gjsjohnmurray** [comment]
@RyszardWithAZ what version of the ObjectScript extension are you using?

**Comment by gjsjohnmurray** [comment]
@RyszardWithAZ are you willing to try the latest beta? If so please download [1.0.5-beta.5](https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.5-beta.5/vscode-objectscript-1.0.5-beta.5.vsix)

**Comment by RyszardWithAZ** [comment]
Hah, I've been installing all your betas, but I haven't gotten to this last one yet! I just installed it, excellent!!

**Comment by gjsjohnmurray** [comment]
That's good. The change for #455 made this happen. Closing.
