### ISSUE TITLE
error while connecting

### ISSUE THREAD

**Issue by rizmaan** [intersystems-community/vscode-objectscript#47]
my status bar in the bottom says connected

i am getting the following errror;

Failed to load page "/api/atelier/v2/TRAK/Region/MEXX/docnames/CLS/*", status code: 404

![image](https://user-images.githubusercontent.com/29242059/62700224-71900980-b9f2-11e9-9941-e937ed8a6044.png)
![image](https://user-images.githubusercontent.com/29242059/62700244-7e146200-b9f2-11e9-9982-09e244050838.png)

**Comment by daimor** [comment]
Hi, sorry for the delay, could you check how it works now with the latest version?
