### ISSUE TITLE
Changes in IRIS Interoperability Production does not reflect on Object Script Explorer

### ISSUE THREAD

**Issue by vmrcastro** [intersystems-community/vscode-objectscript#477]
I don't know if I'm missing something, but if I edit an IRIS Interoperability Production setting through web browser (let's say the "Enabled" flag for a Business Host), and view the respective Production class through Object Script Explorer in VS Code, this change doesn't appear even after hitting the refresh button (more specifically, it doesn't change the "Enabled" XML property inside the XData block that resides inside the Production class).

**Steps to reproduce:**

1. Clone this project:
`git clone https://github.com/intersystems-community/iris-interoperability-template.git`

2. Open the just cloned project's folder in VS Code

3. Edit .vscode/settings.json to include the following key-value pair:
`"objectscript.export.folder": "src"`

4. Build and run the container

5. Open IRIS' Management Portal in your browser and open the dc.Demo.Production

6. Click on "dc.Demo.EmailOperation", uncheck the "Enabled" box and click "Apply"

7. Verify in Object Script Explorer, inside VS Code, that the class dc.Demo.Production still has the property "Enabled=true" in the XData XML for the item name "dc.Demo.EmailOperation" 

Is there any alternative to pull the changes made in the production through web browser into my local project files?

**Comment by gjsjohnmurray** [comment]
@vmrcastro I think what you are seeing is expected. When you use Portal to change something in the XData of the dc.Demo.Production class on the server, the only way this change will reach the local file on your workstation (src\dc\Demo\Production.cls) is if you use the Export option on the context menu of this class in ObjectScript Explorer (OE).

When you open a file from OE, if there is a locally-exported copy of the entity in your workspace this local copy gets opened. If there is no local copy (e.g. a class in a utility package that you aren't changing), the item in the OE tree doesn't have an icon, and when you open it from OE it is pulled from the server namespace and is read-only by default.

For another way to view server-side classes and see server-side changes in near real time, look at the [Server-side Editing](https://intersystems-community.github.io/vscode-objectscript/serverside/) documentation. With this you could add a second root folder to your VS Code workspace. I recommend using the read-only mode unless you also want to be changing stuff server-sdie (like Portal does). The documented steps add a folder with a uri that begins `isfs-readonly://`

**Comment by daimor** [comment]
@vmrcastro At the moment it's expected behavior. When you did your changes on the server through SMP, these changes saved only on the server, VSCode does not check any changes on the server. You can do it manually, by going to Server Explorer, find a node with a package or class, and press Export in the context menu. It will update your local copy with server's version.

**Comment by vmrcastro** [comment]
Thanks for the answers @gjsjohnmurray and @daimor .
Indeed, if I export the class from OE I get the latest version in my local file. 
Somehow, I thought OE would always display the classes as they are in the server, independently of my local files, even if I was using "client side editing".
I found a little weird to export a "different version" of the class that OE is displaying...
Anyway, thanks once again for your answers!
