### ISSUE TITLE
"Class without super" snippet produces an error

### ISSUE THREAD

**Issue by joelsolon** [intersystems-community/vscode-objectscript#481]
With a new empty cls document open, type "cla" and choose the "class without super" snippet. It expands correctly but immediately produces this error:

[Error - 11:22:56 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Cannot read property 'p' of undefined
  Code: -32603 

Note that the "class with super" **does not** produce the error.

**Comment by isc-bsaviano** [comment]
@joelsolon DocumentSymbols come from the LS. I will create an issue there and link it to this. Please follow that issue for updates.
