### ISSUE TITLE
Change headings in Variables section of the Debugger view

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#482]
In the Variables section of the debugging view, the current variables are shown in groupings that use the headings “local” and “global.” Since obviously “global” means something special to us, it would be great if the headings could be changed to “private” and “public”.

**Comment by isc-solon** [comment]
What does "Validate in triage" mean?

**Comment by isc-rsingh** [comment]
Triage is the GitHub Project board we use to discuss and prioritize issues in our weekly project management committee meetings.

**Comment by isc-bsaviano** [comment]
This would need to be changed in the Atelier API debugger

**Comment by isc-solon** [comment]
@isc-bsaviano Do you mean that the Atelier API uses/returns those terms for the groupings and VS Code merely displays them?

**Comment by isc-bsaviano** [comment]
@isc-solon Yes, VSCode asks the debugger for the context scopes and just shows whatever it receives.

**Comment by gjsjohnmurray** [comment]
This could be changed here:

https://github.com/intersystems-community/vscode-objectscript/blob/567fe1de026b4e497cfa7c42ebbd421206235933/src/debug/debugSession.ts#L390

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray We're considering making some changes to the debugger anyways so we can make the change on that end

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano presumably that will require a new version of the API, and if it's not backported everywhere the context labels users see will depend on the server version. I think we should do our own mapping of context.id (currently 0, 1 and 2) to labels (Private, Public and Class). See [`%Atelier.v2.XDebugAgent`](https://docs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?&LIBRARY=%25SYS&PRIVATE=1&CLASSNAME=%25Atelier.v2.XDebugAgent#anchor_parameters)

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Makes sense

**Comment by gjsjohnmurray** [comment]
@isc-solon will you submit a PR for this?

**Comment by isc-solon** [comment]
@isc-bsaviano When you say "I think we should do our own mapping..." I don't know if the "we" is "InterSystems development" or "the people contributing to the ObjectScript extensions." If it's "InterSystems development" then I assume @gjsjohnmurray means I should submit an internal enhancement request. If it's "the people..." then I don't know what I need to submit other than this issue itself.

**Comment by isc-bsaviano** [comment]
@isc-solon John thinks the change should be made in this extension and I think that makes sense. John was asking if you could submit a pull request here to fix this issue.

**Comment by isc-solon** [comment]
Unfortunately, I don't know TypeScript so it will have to be someone else.
