### ISSUE TITLE
Display values of class parameters during debugging

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#484]
While debugging, when hovering over a class parameter (..#PARAMETER), display its value if possible

**Comment by isc-bsaviano** [comment]
@joelsolon Can you provide a specific example? The LS supports this

**Comment by gjsjohnmurray** [comment]
@joelsolon is this in the context of debugging?

**Comment by gjsjohnmurray** [comment]
https://github.com/intersystems/language-server/issues/74 may be relevant

**Comment by isc-bsaviano** [comment]
Fixed in Language Server version 1.1.4
