### ISSUE TITLE
Exception "Request textDocument/hover failed" in &sql with line-breaks

### ISSUE THREAD

**Issue by copperschnack** [intersystems-community/vscode-objectscript#487]
When hovering over &sql sections with line-breaks, VS Code throws the following error to output channel "InterSystems Language Server" 

	[Error - 11:33:31] Request textDocument/hover failed.
	  Message: Request textDocument/hover failed with message: Cannot read property 'l' of undefined
	  Code: -32603 
	  
  
**Environment:**

* intersystems-community.vscode-objectscript v1.0.6-beta.1
* intersystems.language-server v1.0.4  

**Example:**

Maybe aliasing the tables contributes to the effect.
  
```
ClassMethod SqlTest()
{
				 // hovering [tmp.test] below -- OK
	&sql( select tmp.test into :test from (select current_timestamp test) tmp )

	&sql( select 
				 tmp.test into :test from (select current_timestamp test) tmp  )
				 // hovering [tmp.test] above - ERR
}
```

**Comment by isc-bsaviano** [comment]
@copperschnack This is a bug in the Language Server. I will create an issue there and link it to this one. Please follow that issue for updates.
