### ISSUE TITLE
Atelier API v4 candidates

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/vscode-objectscript#488]
Issues requiring changes to the Atelier API that can be addressed in a version 4

- [x] #259 
- [x] #363 
- [x] #457 
- [x] intersystems-community/sqltools-intersystems-driver#9

Not coming in v4

- [ ] #136

**Comment by isc-rsingh** [comment]
assign to @isc-bsaviano

**Comment by isc-bsaviano** [comment]
@isc-rsingh #363 is the Atelier API issue, not 353.
@daimor Do you have a real example for the sqltools issue? I'm not familiar with that SQL syntax and want to test it myself with a real query

**Comment by daimor** [comment]
It's anyway working example.
`FROM table` is optional
![image](https://user-images.githubusercontent.com/1212251/99112417-b3006300-25fe-11eb-95bb-fecfc33e2295.png)

**Comment by gjsjohnmurray** [comment]
> @isc-rsingh #363 is the Atelier API issue, not 353.

Fixed

**Comment by isc-bsaviano** [comment]
I can't edit the checklist in this issue but I updated the 4 issues that were fixed by the upcoming Atelier API v4. v4 will be in 2021.1 and I requested ports to 2019.1.x and 2020.1.x

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I have updated the checklist

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Is there a way to put an "X" or strikethrough for the other issue? It won't be making it into v4.

**Comment by isc-bsaviano** [comment]
Internal devkeys for the above changes:

- #259 BES046
- #363 BES045
- #457 BES044
- intersystems-community/sqltools-intersystems-driver#9 BES047

**Comment by eduard93** [comment]
Any chance for https://github.com/intersystems-community/vscode-objectscript/issues/272 to make it into the next Atelier API?

**Comment by isc-bsaviano** [comment]
@eduard93 No debugger changes will be included in v4. The four issues checked off above are the only changes included in v4.

**Comment by gjsjohnmurray** [comment]
> 
> 
> I can't edit the checklist in this issue but I updated the 4 issues that were fixed by the upcoming Atelier API v4. v4 will be in 2021.1 and I requested ports to 2019.1.x and 2020.1.x

@isc-bsaviano can these be backported to Cache 2018.1 ?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray That's a PM decision so it's a question for @isc-rsingh

**Comment by isc-rsingh** [comment]
I'm on it

**Comment by isc-bsaviano** [comment]
FYI Atelier API v4 made it into 2019.1.2 and 2020.1.1 but missed the boat for CE 2018.1.5

**Comment by isc-jamien** [comment]
No worries. It’s a PM decision, not ours.

De: Brett Saviano ***@***.***>
Responder a: intersystems-community/vscode-objectscript ***@***.***>
Fecha: lunes, 29 de marzo de 2021, 8:17 a. m.
Para: intersystems-community/vscode-objectscript ***@***.***>
CC: Subscribed ***@***.***>
Asunto: Re: [intersystems-community/vscode-objectscript] Atelier API v4 candidates (#488)


FYI Atelier API v4 made it into 2019.1.2 and 2020.1.1 but missed the boat for CE 2018.1.5

**Comment by isc-bsaviano** [comment]
Closing because server-side work is done
