### ISSUE TITLE
Upgrading from .98 to 1.01 Error

### ISSUE THREAD

**Issue by JeffSemmens** [intersystems-community/vscode-objectscript#489]
I tried to move my environment to the latest version of vscode-objectscript, server manager, and language server. Now whenever I try to connect I get the following: command 'vscode-objectscript.explorer.refresh' not found. I've tried clearing out my connection information but I'm basically shooting in the dark at this point. Any ideas what I can do to reset my connections and get this workin?

**Comment by daimor** [comment]
Could you check it with the latest version? At the moment it is 1.0.5

**Comment by JeffSemmens** [comment]
Yes, I will do that. Just discovered I had another issue with my container not starting correctly so which may be the entire issue. I'm debugging that now.

**Comment by JeffSemmens** [comment]
OK, something in my extension settings was messed up. I simplified my User settings and removed the Workspace settings completely and I am now connected with now issues.
