### ISSUE TITLE
Document the server actions menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#492]
> ...and thanks to this fix, I am now aware of the "server action menu!" I was right-clicking the connection instead of clicking. Is this menu documented anywhere?

_Originally posted by @isc-solon in https://github.com/intersystems-community/vscode-objectscript/pull/491#issuecomment-724156120_

Documentation should also cover how to add extra entries to this menu.

**Comment by GendronAC** [comment]
This is indeed needed, also I miss the "open as a webpage" for unit tests and ZenPages.
