### ISSUE TITLE
Explorer view should always show what is on the server

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/vscode-objectscript#494]
Relocating here from https://github.com/intersystems/language-server/issues/78

When browsing the class tree from the Objectscript Explorer VS Code will always show the local exported copy of the file. This leaves no way to see what is actually on the server.  I expected the explorer to be analogous to the Atelier server tab.

Steps to reproduce:

1. export a file
2. modify the file outside VS code (e.g. a `git pull` or fake it using `vi`)
3. browse to the file in the explorer, notice the tooltip is pointing to the working copy and the change is show even though it was never imported and compiled.

**Comment by gjsjohnmurray** [comment]
To see what is actually on the server you could add an isfs-readonly root to your workspace. This has the added benefit of bringing you server-side search capabilities, provided you have installed a beta VSIX from GitHub and have gone through the README steps to enable proposed APIs.

**Comment by mvhenderson** [comment]
Thanks John - this works, and the README instructions were clear.

However, is this a workaround or the solution?   The README also states that client-side editing is usually configured in `.vscode/settings.json` while server-side projects use the `.code-workspace` file.  Is the best practice now using a `.code-workspace` to enable server-side search and quick-open for both types of projects?

If so, where does this leave the objectscript explorer? I'm somewhat bothered by having two pointers in my project to the same thing that provide different feature sets (explorer to export, compile, delete; isfs for server search and quick open).  Are there plans for merging these proposed API features into the explorer for client-side oriented projects?

**Comment by pjsulin** [comment]
Why would I want to see my local file, which I do from the File Explorer, in the ObjectScript Explorer instead of what is on the server?

This seems like a bug or an oversight. If not, let us know the rationale.

**Comment by isc-bsaviano** [comment]
@isc-rsingh Let's review this at the next PMC meeting

**Comment by isc-bsaviano** [comment]
@mvhenderson Can you download the vsix found [here](https://github.com/intersystems-community/vscode-objectscript/suites/5506601713/artifacts/176297062) and confirm that this is the behavior you were looking for?
