### ISSUE TITLE
Unable to see "other" files unless a folder is defined

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#500]
Issue Type: <b>Bug</b>

If in my workspace I only have isfs definitions for folders an no local paths it's not possible to see the explorer and therefore not possible to see "other" files.  I can see a need for the folder definition to export, but why can't i just view in the explorer?

Extension version: 1.0.6-beta.3
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:14:40.758Z)
OS version: Darwin x64 19.6.0

**Comment by gjsjohnmurray** [comment]
On your isfs folder definition try adding this to the query string:
```
&filter=*
```

In the absence of a filter it behaves as though you specified `filter=*.cls,*.inc,*.mac,*.int`
