### ISSUE TITLE
Regression between 1.0.5-beta.7 and 1.0.5-beta.8

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#503]
From #458:
> 1.0.5-beta.7 works …. 1.0.5-beta.8 fails

> So the problem is back in beta.8 with a slight variation … we don’t receive the password prompt at all.  In the previous failure we were presented the prompt but it would not accept the input.

_Originally posted by @PaulSiml in https://github.com/intersystems-community/vscode-objectscript/issues/458#issuecomment-725541188_

**Comment by gjsjohnmurray** [comment]
@PaulSiml please download and install [1.0.6-beta.6](https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.6-beta.6/vscode-objectscript-1.0.6-beta.6.vsix) and let us know if this resolves the issue.

**Comment by PaulSiml** [comment]
Beta.6 resolved the connection issue.

However, we have noticed one issue while testing this fix.  I believe it was already present prior to our connect issues.

We can connect to all namespaces.  However, on namespaces USER, DOCBOOK, and %SYS – we throw the error:

ERROR #5540: SQLCODE:-99 Message: User PXS is not privileged for the operation

when we attempt to open the ObjectScript Explorer tree.

To this end, I went into Studio for these namespace and was able to create, compile and run routines in these namespaces.
So I am convinced that Dean has our user accounts & privileges configured correctly.

-Paul

**Comment by gjsjohnmurray** [comment]
Thanks for confirming the fix in beta.6.

Re that SQLCODE error, there's info near the end of the extension's README that I think will help.

**Comment by PaulSiml** [comment]
Where is the README file located?

**Comment by gjsjohnmurray** [comment]
> 
> Where is the README file located?

1. Go to the Extensions view in VS Code
2. Select the "InterSystems ObjectScript" extension from your list of installed extensions.
3. The information shown on the right is the README (aka "Details").
