### ISSUE TITLE
Unable to connect to docker instance on Windows 10

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/vscode-objectscript#516]
https://github.com/intersystems-community/vscode-objectscript/blob/dbfc345a2ad2ce4901e6390c92f14ef8f1ed1c6e/src/utils/index.ts#L292

This command fails with message in ObjectScript output window:

```
Command failed: docker-compose -f docker-compose.yml   ps --services --filter 'status=running'
Invalid filter: 'status
```

Which prevents connection to the server with `objectscript.conn.docker-compose` configured.  Removing that and fully configuring server works fine.

The single quotes fail under CMD, but work without them:

![image](https://user-images.githubusercontent.com/669176/99350927-1ab7e780-2865-11eb-8cc1-798ff9034950.png)

Either works fine with PowerShell v7.1.0:

![image](https://user-images.githubusercontent.com/669176/99350989-41761e00-2865-11eb-8023-9ea71c8ed14a.png)

Detail
```
Windows 10 build 2004
VSCode: 1.51.1 (user setup)
intersystems-community.vscode-objectscript v1.0.6
```

**Comment by mvhenderson** [comment]
Forgot to mention can reproduce using clone from git@github.com:intersystems-community/objectscript-docker-template.git

**Comment by daimor** [comment]
I don't have windows, so, did not check how it works there.
I'll try to fix it

**Comment by mvhenderson** [comment]
No worries - I will submit a pull request tomorrow if you can't, just wanted to get it logged.

**Comment by daimor** [comment]
It would be great
