### ISSUE TITLE
CSP Runtime Expressions cause colour issue when used on tag attribute

### ISSUE THREAD

**Issue by Taulim** [intersystems-community/vscode-objectscript#517]
I'm not sure if this is an issue with the objectscript extension or the language-server extension.  
When using a CSP Runtine Expression (`#()#`) within a tag attribute the colouring gets weird (on the attribute and in anything after it):

![image](https://user-images.githubusercontent.com/7851440/99400793-52637580-28df-11eb-8a89-808d8eff88c3.png)

![image](https://user-images.githubusercontent.com/7851440/99400818-5abbb080-28df-11eb-9f85-5656d40e1dfc.png)

![image](https://user-images.githubusercontent.com/7851440/99400837-5f806480-28df-11eb-91dc-d9df1e79ba4e.png)

![image](https://user-images.githubusercontent.com/7851440/99400848-6313eb80-28df-11eb-8726-3daae792b7e9.png)

It does not cause compilation error, it is just annoying depending how crazy the code gets after that point :smile:  
It is also not consistent, if you close and reopen the file a few times or redo the changes you may get different results, but it always after the attribute.

**Comment by isc-bsaviano** [comment]
@Taulim Coloring issues should be posted on the Language Server repo, so I'm going to create an issue there and like it to this.
