### ISSUE TITLE
Objectscript debugger hangs

### ISSUE THREAD

**Issue by pjamieso** [intersystems-community/vscode-objectscript#518]
Issue Type: <b>Bug</b>

I am finding a number of problems when using the Objectscript Debugger: (1) When stepping on a particular line of code , the debugger hangs (see screenshot)

![image](https://user-images.githubusercontent.com/6224023/99548735-f522ff00-2986-11eb-818d-8b87231ba5f3.png)

When setting a breakpoint, the line of code may take a long time to finally be reached, or in some cases may not be reached, even when it is the first line in a method (see screenshot).

![image](https://user-images.githubusercontent.com/6224023/99548765-fd7b3a00-2986-11eb-911c-43b60872ca54.png)

Extension version: 1.0.6
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 6, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id b47d7fd5-8259-407e-91e5-402ab7c6c479|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by daimor** [comment]
Would it be possible, to make some simple sharable example, with steps for reproducing?

**Comment by pjamieso** [comment]
The example I shared in not completely reproducible on each execution. I have found the debugger hangs on different lines or does not hit a breakpoint even when it did on the last execution. I am not sure how to create a simple example that is "reproducible".

**Comment by isc-rsingh** [comment]
@bourette can you test this with the Studio debugger?

**Comment by isc-bsaviano** [comment]
Pinging @pjamieso again. Version 1.0.10 might fix this issue
