### ISSUE TITLE
Debug REST service classes in Visual Studio Code

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/vscode-objectscript#521]
Is there anything planned for debugging REST service classes in Visual Studio Code like what is done with Serenji : 

![img](https://community.intersystems.com/sites/default/files/inline/images/images/RESTdebugDC-20190906.gif)

**Comment by ondrejhoferek** [comment]
+1

**Comment by isc-bsaviano** [comment]
Implementing this would almost certainly require server side work.

**Comment by grongierisc** [comment]
That's for this great features, but it's seems to me it's only works with isfs. Is it possible to make it works with local source file ?

<img width="949" alt="image" src="https://user-images.githubusercontent.com/47849411/211986551-69a01a95-5295-437c-a06c-e9c185b4a83e.png">

error message : No file system provider found for resource 'objectscript://XXX.cls'

**Comment by isc-bsaviano** [comment]
@grongierisc This is caused by #1042. Since the `objectscript` URI scheme isn't a full FileSystemProvider, `vscode.workspace.fs.readFile()` can't read the file. I will open a new issue. Turning on `objectscript.serverSideEditing` should solve the problem until a fix is released.
