### ISSUE TITLE
Compile Option "c" for "Compile Dependent Classes" is not working properly

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#528]
Make sure Compile Dependent Classes option "c" is set. 
Class A is superclass for classes B and C. Add a property to class A and compile. B and C should also be compiled, and messages about that should appear in the console.

**Comment by gjsjohnmurray** [comment]
What results do you get if you do the same test from Studio?

What is your server's $zversion string?

**Comment by isc-solon** [comment]
I'm using IRIS for UNIX (Ubuntu Server LTS for x86-64 Containers) 2020.1 (Build 217_1U) Tue May 26 2020 20:59:20 EDT

Studio and Atelier compile all 3 classes.

**Comment by daimor** [comment]
VSCode just compiles with flags set by default. And all compilation is on the server-side. I don't see if anything can be done on this side.
You can change the setting `objectscript.compileFlags`, with the value `cuk` by default.

**Comment by isc-solon** [comment]
I have the flags set to `cuk`. To me it appears that those flags are **not** being sent correctly over to the server.

**Comment by daimor** [comment]
Just open ObjectScript in Output, and you will see, exactly the same output as in Studio, which will show the line like
`Compilation started on 12/16/2020 18:52:38 with qualifiers 'cuk'`

**Comment by isc-solon** [comment]
My mistake, sorry! I forgot that it's the "b" flag that means "compile dependent classes" and not the "c" flag.
