### ISSUE TITLE
Invalid filter: 'status error when using docker compose

### ISSUE THREAD

**Issue by isc-sshutov** [intersystems-community/vscode-objectscript#530]
When using docker-compose with 

      "docker-compose": {
        "service": "iris",
        "internalPort": 52773
      },

on Windows, extension reports error 

       Invalid filter: 'status 

Apparently filter should not contain single quotes

![photo_2020-12-16_13-52-53](https://user-images.githubusercontent.com/50501768/102298943-34546800-3fa6-11eb-8df0-dea697007c09.jpg)

**Comment by daimor** [comment]
fix already available with the latest beta
