### ISSUE TITLE
Object what imported by base class doesn't be linked.

### ISSUE THREAD

**Issue by yuji-ohata** [intersystems-community/vscode-objectscript#538]
Hi,

I have a problem on VisualStudioCode.

I understand ObjectScript can import other packages.
https://irisdocs.intersystems.com/iris20191/csp/docbook/DocBook.UI.Page.cls?KEY=GOBJ_packages#GOBJ_packages_in_classname

And we can use package imported by base class, too,
when created class extend this base class.
But on VisualStudioCode, it's not linked, and shown error.
(It doesn't occered compile error, of course.)

![test](https://user-images.githubusercontent.com/76474248/102876468-93274f00-4488-11eb-8743-c76edef81d28.png)

In this picture, ResultSet was imported by DAOBase class.
Can you fix it?

Best Regards
Yuji

**Comment by isc-bsaviano** [comment]
@yuji-ohata The InterSystems Language Server extension creates the error diagnostics so this issue should be posted in that repository. I will create a issue there, link it here, and close this one. If the false error diagnostic is distracting, you can turn them off by going to Settings -> Extensions -> InterSystems Language Server and unchecking the classes diagnostics setting.
