### ISSUE TITLE
Better commenting for Cache'

### ISSUE THREAD

**Issue by neils-s** [intersystems-community/vscode-objectscript#541]
The one feature I miss from Cache' Studio is the automagic indenting and commenting.  It's very nice to not have to retype the comment character when I'm writing a long series of full-line comments (e.g. a tag header).  When setting up a new Cache' Studio instance, I always make a point to set the User Defined indentation options in
          Tools -> Options -> Editor -> Indentation 

I tried using the "Auto Comment Next Line" extension (https://github.com/ctf0/vscode-auto-comment-next-line) to duplicate this Cache' Studio functionality, but it didn't work correctly.  The problem was that the code in vscode-objectscript/src/languageConfiguration.ts  contains a lineComment setting that doesn't support raw MUMPS.  Instead of a ";" character, the lineComment setting only contains "#;" token.  This means that when I try to use something like the , I keep getting "#;" tokens blown in as my leading characters.

It might be nice to put in some kind of OnEnterRules that can carry over the leading characters of the previous line, based on a user-defined list.  This would exactly duplicate the Cache' Studio functionality.

**Comment by daimor** [comment]
It's already done for `///` descriptions in class. This feature worth to be implemented as well.
