### ISSUE TITLE
isfs filter/generated combo to see certain files

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#544]
Hello,

This is more a question than an issue, though you can see that if this isn't possible, it would turn into a use-case for maybe a future enhancement... 

In the navigator, I'd like to be able to see the following:

1. All classes, generated or not,
2. All routines, generated or not, EXCEPT for routines (INTs or MACs) that are generated from classes.

Is there any way to set up a filter that does this?

**Comment by daimor** [comment]
Look here https://github.com/intersystems-community/vscode-objectscript/wiki/Server-side-editing#filters

**Comment by RyszardWithAZ** [comment]
Thank you @daimor, I did read that earlier, it looks like it's not possible to do this in one view. I don't see a way of excluding INT from CLS specifically, while allowing other generated INT and all CLS files.

**Comment by daimor** [comment]
I'm personally see no reason to have generated INT's for MAC's, while do not see it for classes. Even see generated items persistently. You always can do View Others, to see generated code. Could you explain tour reasons, to having this?

**Comment by RyszardWithAZ** [comment]
We regularly debug all of our hand-build & generated classes & routines, so we need to see all of them. We don't want to see IRIS-generated code though (so routines generated from any class), unless we finally see there's an IRIS compilation issue. But these filter options don't let us filter against IRIS-generated code.

Here's one example: We have thousands of generated classes for our UIs. When debugging our UI, we iterate by fixing that specific generated class and then transferring the change to our generator and regenerate, keeping both side-by-side. So that's why we want to see all generated classes at the same time. 

With the IRIS-compiled artifacts sharing the same view, they get in the way very quickly, so I was trying to not see them.

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ You could try adding `'*.1.int` to your filter if you can be sure that none of the routines that you care about end with that suffix

**Comment by RyszardWithAZ** [comment]
> @RyszardWithAZ You could try adding `'*.1.int` to your filter if you can be sure that none of the routines that you care about end with that suffix

That doesn't seem to work, it just makes nothing appear. And the doc on the filter doesn't have a not operator.

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ The extension uses [%Library.RoutineMgr::StudioOpenDialog()](https://docs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?&LIBRARY=%25SYS&CLASSNAME=%25Library.RoutineMgr#StudioOpenDialog) to get the list of documents to show. The isfs `filter` URI parameter corresponds to the StudioOpenDialog `Spec` parameter. Please see the linked docs for the allowed values for `Spec`.

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ Were you able to write a filter that meets your needs?

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ I'm glad you found something that works!
