### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [intersystems-community/vscode-objectscript#545]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by daimor** [comment]
@rajrsingh could you do it?

**Comment by isc-rsingh** [comment]
@daimor yes I'm working on this and having the publisher agreement reviewed internally.

**Comment by isc-rsingh** [comment]
@spoenemann is the Open VSX publisher agreement different than the one for Eclipse IDE extensions? My organization already publishes to that registry, and it would facilitate review of this agreement if we knew they were similar.

**Comment by spoenemann** [comment]
I am not aware of any legal document for the Eclipse Marketplace. I found only these guidelines: https://marketplace.eclipse.org/content/eclipse-marketplace-publishing-guidelines

**Comment by gjsjohnmurray** [comment]
@daimor what still needs to be done to close this? The v1.0.9 release just now didn't publish to Open VSX:
![image](https://user-images.githubusercontent.com/6726799/112279418-cfcb3800-8c7b-11eb-8d67-4b97033b0737.png)

**Comment by daimor** [comment]
Published manually, and fixed token in CI, for the next releases
https://open-vsx.org/extension/intersystems-community/vscode-objectscript
