### ISSUE TITLE
When debugging, the Globals listing in the VARIABLES section lists local (private) variables

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#549]
When debugging, in the VARIABLES section, the Global grouping shows the values of method arguments and the Local grouping shows other variables in the method. **All** of these variables should be in the Local grouping.

The Global grouping should **only** show:
- variables declared in the method's `publiclist`
- all variables if the method has `ProcedureBlock = 0`

These grouping names will hopefully be changed by #482.

**Comment by daimor** [comment]
This issue and the issue with group name is not issue of this extension. It's how Atelier API respond. So, you may would like to post these issues internally.

**Comment by isc-solon** [comment]
I discovered that the reason that the local variables are listed as global variables is that they are used as host variables in an Embedded SQL statement. So this is correct after all. Closing.
