### ISSUE TITLE
Hover documentation needs more linebreaks

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#557]
Issue Type: <b>Bug</b>

For example, the list of arguments for the WRITE command:
![image](https://user-images.githubusercontent.com/6726799/105028755-53349700-5a49-11eb-9f39-b0a26c80d22a.png)

Notice the horizontal scrollbar.

Extension version: 1.0.9-beta.1
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray All hover suggestions are provided by LS. I'll create an issue there and reference this one
