### ISSUE TITLE
Add Globals viewer on Server view

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#558]
With the option to have the option to Export in XML on a right-click

**Comment by isc-rsingh** [comment]
The PMC has discussed and thinks this is a very interesting, useful idea but would be best executed as a different extension.

**Comment by evshvarov** [comment]
It’s a pity to hear cause Globals could be a part of the IRIS solution and
repository and thus should be viewed and imported/exported.


Пт, 22 янв. 2021 г. в 18:14, Raj Singh <notifications@github.com>:
