### ISSUE TITLE
Serverside editing setup docs

### ISSUE THREAD

**Issue by pjsulin** [intersystems-community/vscode-objectscript#559]
From https://intersystems-community.github.io/vscode-objectscript/serverside/#server-side-source-control

2 Open the Explorer view (Ctrl/Cmd+Shift+E) if it is not already visible.

3 When the button labeled "Choose Server and Namespace" appears, click it.

This is accessed from Object Exporer, not the File Explorer

**Comment by gjsjohnmurray** [comment]
> This is accessed from Object Exporer, not the File Explorer

@pjsulin I think you missed the part of the instruction in step 1 that says "If a folder or workspace is already open, close it, ..."

The Object Explorer will only be visible if a folder or a workspace is already open.

The instructions in steps 2 and 3 are specifically for the case where neither a folder nor a workspace is open. In this case the "Choose Server and Namespace" button does appear on the File Explorer (Ctrl/Cmd+Shift+E).
