### ISSUE TITLE
When formatting the code, the method becomes full spelling 

### ISSUE THREAD

**Issue by Sunxiaomo311** [intersystems-community/vscode-objectscript#563]
When I use **‘Alt+Shift+F’** to format the ‘cls’ file, the built-in method will change from abbreviation to full spelling. Can this question be changed to configuration? I hope that the built-in method remains the same when formatting  : )

**Comment by isc-bsaviano** [comment]
@Sunxiaomo311 Code formatting is handled by the Language Server extension. The LS provides 4 configuration settings for formatting: 2 for commands and 2 for system functions and variables. For each one you get to choose the case (upper, lower or word) and length (short or long form). It is possible to set your configuration to use the long form for commands and short form for system variables and functions. Please see the Language Server README or go to VSCode settings -> Extensions -> InterSystems Language Server to see all configuration options.

**Comment by Sunxiaomo311** [comment]
Thanks for the answer!
