### ISSUE TITLE
'Server Source Control' and 'Server Command Menu' menus

### ISSUE THREAD

**Issue by pisani** [intersystems-community/vscode-objectscript#564]
I'm setup use VS-Code for server-side editing.. - I attached the basic %Atelier.SourceControl subclass of %Studio.SourceControl.base to USER.   When I right click on a server item (eg a class):
1.  'Server Source Control... ' prompts me 'Add to Source Control'.. and 
2.  Choosing 'Server Command Menu...' gives me nothing. 

I'm guessing I can invoke server-side source control hooks - but - I need to know exactly how the source control server-side class needs to be developed. For example, how it knows that to offer 'Add to Source Control' versus 'Remove from Source Control'.  What is going on here ?

I have a dummy, other, incomplete source control hooks subclass of Studio.SourceContro.base, and this, one does something different. 
1. does not prompt me for anything and
2. displays the item context menu (the Studio Source control <Menu> flagged with attribute Type="1" 

I'm confused on the usage of these commands, and if they are supported at all ?  IT seems like something that needs to be implemented if implementing server-side editing (because that needs server-side source control). 

Steve

**Comment by daimor** [comment]
First of all, it better to compare how it works with Studio. VSCode implementation supposed to behave the same way, with some differences.

> how it knows that to offer 'Add to Source Control' versus 'Remove from Source Control'
It should work depends on the result from method `GetStatus`

**Comment by gjsjohnmurray** [comment]
@pisani any chance of you posting (XML export file) a simple source control class that illustrates the differences between Studio and VS Code that you have observed?

**Comment by pisani** [comment]
Hi John, 
I did a bit more work - a fresh look, at this.. I took a look at the sample %Atelier.SourceControl.cls class and created something identical, except for a different set of <menu> items map.

I was able to reproduce the appearance of items for 'Server Source Control" and "Server Command Menu" menu option invoked from VS Code.  If seem both these must invoke an Atelier api to get menu items, which, in turn must invoke the OnMenuItem() and subsequent methods of an StudioSourceControl class assigned to that namespace.

What I found is with this menu map:

<MenuBase>
<Menu Name="%SourceMenu" Type="0">
  <MenuItem Name="%CheckOut"/>
  <MenuItem Name="%UndoCheckout"/>
  <MenuItem Name="%CheckIn" Save="100"/>
  <MenuItem Name="%GetLatest"/>
  <MenuItem Name="%AddToSourceControl" Save="100"/>
</Menu>
<Menu Name="OtherTopMenu" Type="0">
  <MenuItem Name="OtherTopMenu-A" Save="100"/>
  <MenuItem Name="OtherTopMenu-B"/>
</Menu>
<Menu Name="%SourceContext" Type="1">
  <MenuItem Name="%CheckOut"/>
  <MenuItem Name="%UndoCheckout"/>
  <MenuItem Name="%CheckIn" Save="100"/>
  <MenuItem Name="%GetLatest"/>
  <MenuItem Name="%AddToSourceControl" Save="100"/>
</Menu>
<Menu Name="OtherCommands1" Type="1">
 <MenuItem Name="OtherContextMenu-A" Save="100"/>
 <MenuItem Name="OtherContextMenu-B"/>
</Menu>
<Menu Name="OtherCommands2" Type="1">
 <MenuItem Name="OtherContext2Menu-A" Save="100"/>
 <MenuItem Name="OtherContext2Menu-B"/>
</Menu> 
</MenuBase> 

- the Type=0 menu option appear on the Studio top menu (I guess we knew that), and nowhere do they appear in VSCode.

- the last menu specified with Name starting with a "%", and Type=1, is shown as the context, source-control menu and, the menu items appear in Studio as a context menu items. Additionally these menu items will come up in VSCode when you select and item and click 'Server Source Control...' - 

- All other non-% named, Type=1 menus behave differently between Studio and VSCode. In Studio the last appearing menu group is offered as another context-menu list, and in VSCode all the subsequent non-% named, Type=1 menus are bundled together, and in VS Code,  show up shown if in VS Code the menu "Server Command Menu..." .

The above, at least, shows me how to provide 'Server Command Menu...' options in VS Code. However, I've not been able to find a way to hide Server Command Menu items from Studio entirely. It's likely that these menu options would not make sense to a studio user.

What can I expect moving forward though ?  Can I expect that in VSCode, the menu options "Server Source Control..", and "Server Command Menu..." would still be available ?

**Comment by ty-d** [comment]
Due to some limitations of VSCode extensions, we cannot use the Type=0 top menus defined by the user in the same way as Studio. Instead, they appear as a description next to each menu item. The Server Source Control and Server Command Menu are used instead to try to maintain some organization of menu items by sorting them into one or the other. 

You can expect the Server Command Menu and Server Source Control options to stay the same. The goal is to display the same menu items in both VSCode and Studio, so there is no simple way of hiding menu items in just one of the platforms.

**Comment by pisani** [comment]
ok thanks,
In this thread we have established where Source Control Menu.. and Server Command Menu.. options need to be defined server-side, in order to expose functionality to VS Code.
