### ISSUE TITLE
No template when creating .cls with client side source control

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#566]
When I create a new class Test.MyClass1.cls with an isfs connection I get a template of a class ie
Class Test.MyClass1
{

}
When I create a class when using client side sources I get an empty document.

**Comment by gjsjohnmurray** [comment]
I don't think there's a way to make VS Code add boilerplate text to a new local (i.e. client-side) file. But the extension provides some snippets that help you:

![image](https://user-images.githubusercontent.com/6726799/107071862-451e9e80-67dd-11eb-9e5b-9ea0cce450cb.png)

**Comment by bourette** [comment]
I was able to resolve this by installing Auto Snippet, defining
	"autoSnippet.snippets": [ { "pattern": "**/*.cls", "snippet":"template"}]
and adding the following to my ObjectScript-class.json preferences snippet
	"template": {
		"body": "Class ${TM_DIRECTORY/(.*cls[\\\\\\/])?([^\\/\\\\]*)([\\/\\\\])?/$2${3:+.}/g}.$TM_FILENAME_BASE\n{\n\n}"
	}
