### ISSUE TITLE
Empty explorer

### ISSUE THREAD

**Issue by AchrafSoltani** [intersystems-community/vscode-objectscript#57]
Hello,

I managed to set a connection to the local Caché server, but the explorer doesn't show anything and I cannot create a class or routine, basically it's unusable.

**Comment by david2278** [comment]
Did you export sources?

**Comment by AchrafSoltani** [comment]
what do you mean by export sources ?

**Comment by david2278** [comment]
Click on the intersystems logo and you should be able to see all the files in the namespace.

Hit ctrl-shift-p and choose "Export Sources"

That will export the namespace files into the explorer. Saving them in the explorer will compile them and reimport them back into the namespace.

![yeSZ9KZINS](https://user-images.githubusercontent.com/6810903/65621825-79037600-df92-11e9-9f86-6d1efcbc8c9c.png)

**Comment by AchrafSoltani** [comment]
That's my point, I am on the explorer and I don't see any files (I am on the SAMPLES namespace)

Clicking on export sources doesn't change anything 

PS: I am on OSX

**Comment by daimor** [comment]
Hi,
Could you post your settings?
in your `.vscode/settings.json` you should have, at least
```
"objectscript.conn.active": true,
```
But you may also have to configure other connection settings
```
"objectscript.conn.port": 52772,
"objectscript.conn.ns": "SAMPLES",
"objectscript.conn.host": "localhost",
"objectscript.conn.username": "_SYSTEM",
"objectscript.conn.password": "SYS",
```
You can check connection status, in status bar of VSCode
![image](https://user-images.githubusercontent.com/1212251/65778439-e7bc0d00-e113-11e9-86bb-6251733a61d7.png)
And in Output view for ObjectScript in dropdown
![image](https://user-images.githubusercontent.com/1212251/65778477-f99db000-e113-11e9-8f48-831ef1ede3b9.png)

**Comment by a-boertien** [comment]
I had the same problem: it was because I didn't have a open folder / workspace in VSCode

I created a new folder & opened it, and Explorer then showed the classes/routines

**Comment by daimor** [comment]
Yes, actually it is important part, it does not work if you did not open any folder at all.

**Comment by AchrafSoltani** [comment]
I opened a folder and it worked, but it doesn't seem to allow creating routines or classes, just editing existing code right ?

**Comment by daimor** [comment]
It is supposed to be as just an explorer of server's code. To create classes and routines, you should use local files.

**Comment by daimor** [comment]
So, with the next release, added a check, to show Explorer View only if any folder opened
