### ISSUE TITLE
Compile options

### ISSUE THREAD

**Issue by marceldenouden** [intersystems-community/vscode-objectscript#571]
Issue Type: <b>Bug</b>

I have set the compiler options in VSCode to crkf. If I compile a class I am working on, it seems to respect those settings. However, if I do a "Import & Compile" on a package I am not sure if it also uses these settings? 

Thanks

Extension version: 1.0.8
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:45:54.515Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 3.10.0-1160.6.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 192d1db4-8a9f-4c19-9b28-dccf3a85438f|
|Screen Reader|no|
|VM|25%|

|Item|Value|
|---|---|
|Remote|SSH: Palga-Mercurius|
|OS|Linux x64 3.10.0-1160.6.1.el7.x86_64|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (4 x 2207)|
|Memory (System)|3.70GB (0.26GB free)|
|VM|45%|
</details>

**Comment by gjsjohnmurray** [comment]
Based on my reading of the code it looks like the `objectscript.compileFlags` flags **do** get used when a folder is imported and compiled. Closing, but if you have evidence it's not working that way please post it and reopen the issue.

**Comment by marceldenouden** [comment]
Thanks John,

Regards Macel
________________________________
Van: John Murray ***@***.***>
Verzonden: donderdag 25 maart 2021 19:38
Aan: intersystems-community/vscode-objectscript ***@***.***>
CC: marceldenouden ***@***.***>; Author ***@***.***>
Onderwerp: Re: [intersystems-community/vscode-objectscript] Compile options (#571)


Based on my reading of the code it looks like the objectscript.compileFlags flags do get used when a folder is imported and compiled. Closing, but if you have evidence it's not working that way please post it and reopen the issue.
