### ISSUE TITLE
Syntanx highlighting can go haywire

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#574]
When I'm editing a legacy .INT file, syntax highlighting tends to get messed up easily, even though I have no syntax issues in my file.
For example:
![image](https://user-images.githubusercontent.com/63731219/109019330-e5523f80-7686-11eb-8d3d-ad72e31a3931.png)

**Comment by gjsjohnmurray** [comment]
What are your version numbers for VS Code and for the Language Server extension?

cc @isc-bsaviano

**Comment by RyszardWithAZ** [comment]
The Language Server extension is 1.1.2, and VSCode version 1.53.2.


Ryszard Kilarski
Principal Software Engineer, athenaIDX Development
(he, him, his)
[cid:image001.jpg@01D70A96.3194B380]
311 Arsenal Street • Watertown, MA 02472
o 360.317.9957

**Comment by isc-bsaviano** [comment]
This is a known issue: https://github.com/intersystems/language-server/issues/29

Certain edits can cause the client to not color the text correctly but the underlying tokens are correct. AFAIK this is an issue with VSCode and not us

**Comment by isc-bsaviano** [comment]
Closing in favor of https://github.com/intersystems/language-server/issues/29
