### ISSUE TITLE
Upgrade xmldom to patch XXE security vulnerability

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/vscode-objectscript#580]
from https://snyk.io/test/github/intersystems-community/vscode-objectscript

Introduced through: vscode-objectscript@intersystems-community/vscode-objectscript › xmldom@0.3.0
Remediation: Upgrade to xmldom@0.5.0
More: https://snyk.io/vuln/SNYK-JS-XMLDOM-1084960

**Comment by gjsjohnmurray** [comment]
Resolved by dependabot in #582
