### ISSUE TITLE
Quick Open of isfs files slow

### ISSUE THREAD

**Issue by LogMull** [intersystems-community/vscode-objectscript#581]
I am using version 1.0.9-beta.1 of the plugin and have it configured to edit files on the server.  I've enabled the proposed API and am able to properly edit files on the server.  However, attempting to find a file via quick open is very slow.  It takes ~30 seconds for results to populate.  This appears to be the only wait to open files by typing the class name, while editing on the server, so it is difficult to make full use of this feature.  It does not seem to be effected by the parameters I append to the uri for the folder. StudioOpenDialog in %RoutineMgr appears to be what populates this list and the size of our project is likely what slows down this process.

**Comment by gjsjohnmurray** [comment]
Your Quick Open is being populated by a REST call serviced by the GetDocNames method of %Api.Atelier.v1 which then uses the StudioOpenDialog query in %Library.RoutineMgr

Each time you add a character in the Quick Open field a fresh REST call gets run with the new filter, which is applied as a 'LIKE %yourtext%' clause. Are you observing that happening?

You make a good point about this lookup not being confined to the subtree that your isfs uri may have specified. Maybe we can do something about that.

**Comment by LogMull** [comment]
I did not notice that it was sending a fresh request on each character, but that makes sense, as I do see a difference in return time when I type out a value vs paste it in.  I am exploring the possibility of setting the dispatch class for the /api/atlier end point to a custom class that will effectively let us define our own lookup method.  I'm hoping that since the vast majority of what we will want to open will either follow predictable naming conventions or be in a few specific packages that it may a reasonable alternative for the time being.

**Comment by gjsjohnmurray** [comment]
@LogMull are you willing to try the VSIX just built from the PR I have submitted? You can download it from https://github.com/intersystems-community/vscode-objectscript/suites/2317319885/artifacts/48696711

**Comment by LogMull** [comment]
I am not seeing a difference with this version of the plugin.  Just to verify, the intent would be for this to work with something along the lines 
`	"folders": [
		{
			"name": "server:namespace",
			"uri": "isfs://server:namespace/?filter=*.cls,ST*.mac",
		}
	`, correct?

**Comment by gjsjohnmurray** [comment]
No, the change was only to deal with a path prefix in your root URI, e.g. `isfs-readonly://server:%sys/%Dictionary`

I have now enhanced it to respect a `type=cls` or `type=rtn` queryparam, but unfortunately the Atelier REST API endpoint it's using  (/docnames) doesn't seem to cater for the 'filter=XXX` one. Getting round this would probably require switching to use /action/query in the way the isfs FileSystemProvider already does. That code should be refactored so it can be shared between the FileSystemProvider and the FileSearchProvider.

**Comment by gjsjohnmurray** [comment]
Latest build is at https://github.com/intersystems-community/vscode-objectscript/suites/2323619521/artifacts/48890894

**Comment by LogMull** [comment]
That would definitely explain why I did not see a difference in my use case then hah.  I appreciate your work on this.  Do you think that the switch and refactoring is likely to happen in the near future?

**Comment by gjsjohnmurray** [comment]
>  Do you think that the switch and refactoring is likely to happen in the near future?

I think it's unlikely to happen soon. FileSearchProvider is still only proposed API in VS Code. You've jumped through the hoops to be able to use it, and will continue having to download the 1.0.x-beta.1 after each release we publish to Marketplace.

How are your TypeScript skills?

**Comment by LogMull** [comment]
I work frequently with JavaScript, but I have not done much with TypeScript specifically, just a few side projects here and there.

**Comment by gjsjohnmurray** [comment]
@LogMull I created #593 to capture the outstanding item. If you feel like having a go at the work I'll be happy to support you getting to the point where you submit a PR. If so please follow up on that issue.
