### ISSUE TITLE
Unable to refactor classes definitions within hierarchy 

### ISSUE THREAD

**Issue by isc-pchung** [intersystems-community/vscode-objectscript#585]
Unable to refactor classes in a hierarchy. 

Load attached XML file, in the base class "ClassA", refactor property "baseConfig" doesn't reflect change in "ClassC" that inherits "ClassA".

Seems ObjectScript refactoring in VSCode is text base search/replace in single file.

[test_class_hierarchy.zip](https://github.com/intersystems-community/vscode-objectscript/files/6152042/test_class_hierarchy.zip)

**Comment by isc-bsaviano** [comment]
@isc-pchung You need to recompile ClassA after renaming the property. The language server queries the server to provide intellisense so if the class hasn't been compiled, then thee server won't know that the name of the property has changed.

**Comment by isc-pchung** [comment]
@isc-bsaviano Thanks. Guess I was drawing a parallel to behavior of IRIS Studio, which does support concept of refactoring. Rename thru refactor would highlight the impacted classes. This might be VSCode specific & how it is suppose to work.

So in the current scheme, if I had class hierarchy of 5 class, which all use a variable in the base class, the workflow to refactor would be 

1. enable recursive compile
2. refactor target in class / recompile
3. see which child classes fail to compile & repeat step #2

To confirm, this is the intended behavior of how refactoring will work in VSCode?

**Comment by isc-bsaviano** [comment]
@isc-pchung Ok, now I understand what you're asking about. By "refactoring", you mean [Studio's "refactor->rename" feature](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GSTD_Commands#GSTD_Commands_Class). This doesn't exist in VSCode so you'd have to manually update all classes involved. If this is something you'd like us to consider adding to the Language Server, please post an issue on [that repo](https://github.com/intersystems/language-server/issues). Be sure to check out the [readme](https://github.com/intersystems/language-server/blob/master/README.md) for a full list of features that already exist, including renaming for local variables within methods and method arguments.
