### ISSUE TITLE
isfs 'filter' queryparam is not respected by QuickOpen

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#593]
> I am not seeing a difference with this version of the plugin.  Just to verify, the intent would be for this to work with something along the lines 
> `	"folders": [
		{
			"name": "server:namespace",
			"uri": "isfs://server:namespace/?filter=*.cls,ST*.mac",
		}
	`, correct?

_Originally posted by @LogMull in https://github.com/intersystems-community/vscode-objectscript/issues/581#issuecomment-804300830_

The QuickOpen (Ctrl+p) list may include files that are filtered out of what the Explorer tree shows.

Our FileSearchProvider uses the /docnames API endpoint which only offers LIKE %xxx% server-side filtering.

We should probably refactor the readDirectory method of FileSystemProvider, extracting most of its logic so it can be shared with the provideFileSearchResults method of our FileSearchProvider.

**Comment by LogMull** [comment]
@gjsjohnmurray I'd be happy to try my hand at this.  I can get this forked and set up locally to work on. However, I'm not sure what kind of project this is, so once I have a local copy, I am unsure what I need to get set up to build a VISIX once I make changes.

**Comment by gjsjohnmurray** [comment]
@LogMull please start by following the instructions in [CONTRIBUTING.md](https://github.com/intersystems-community/vscode-objectscript/blob/master/CONTRIBUTING.md) to get a runnable locally-built copy of the extension.

Then create a local branch, perhaps named `fix-593`, and start making changes and testing them.

If you want to discuss the changes you plan to make, please do that on this issue. Alternatively you could push your branch, create a draft PR here, and I'll be able to review what you've done and make suggestions.

And while you're doing this, if you feel CONTRIBUTING.md needs improving please create another branch for doing that on.

**Comment by LogMull** [comment]
Thank you for this information.  I have the FileSearchProvider working well by emulating what the FileSystemProvider does, but the code is still not shared between them.  Where would you suggest placing this shared code?  It will effectively be running the SQL query %Library.RoutineMgr_StudioOpenDialog via AtelierAPI.actionQuery based on information from a given URI.

**Comment by gjsjohnmurray** [comment]
@LogMull sorry for my slow response. I suggest you create a new .ts file in src/utils for the shared code.

**Comment by LogMull** [comment]
@gjsjohnmurray I have submitted a pull request with my changes.  I am not experienced with doing so, so I am unsure if I have done it all correctly.
