### ISSUE TITLE
Save a class/routine without compile

### ISSUE THREAD

**Issue by davevdg** [intersystems-community/vscode-objectscript#594]
Using server-side editing...
I can't figure out how to save a class definition (or .mac routine) without compiling it.
We definitely need the ability to Save without Compiling.
Am I missing something or is this not currently supported?

**Comment by gjsjohnmurray** [comment]
This is not currently supported.

Please tell us about why you need this, and how you want it to behave. For instance, a user/workspace/folder setting to skip the post-save compile. Or maybe a separate command that saves but doesn't compile.

**Comment by davevdg** [comment]
Every InterSystems editor going back to the old CHUI _do ^%_ editor in the M/SQL product has had separate Save and Save & Compile functions, why stop now :)

There are times when you are editing code (MAC or CLS) that you want to simply save your changes without compiling and making the changes active.
The work today that made me realize this is not currently an option is I want to delete the storage of a class and save the class, then compile from the command line to have the class compiler re-generate the default storage so I can debug from the command line (I'm working on enhancements to class storage and the class compiler).

As to how it is implemented, I would prefer separate _Save_ and _Save & Compile options_ that I can map to keystrokes.

Thanks.

**Comment by isc-rsingh** [comment]
Proposal for ISFS save/compile:
1. add a preference to set whether save compiles automatically or not
1. add a command to compile current class (so that if the preference has been set to NOT compile on save, this allows you to compile)

**Comment by davevdg** [comment]
Somewhat related to this is editing/saving an include file.  .INC files are not compiled, only saved, yet when I save an include file I see messages about it being compiled.  This should not happen, it should only save the file
(I see this with server-side editing).

**Comment by isc-bsaviano** [comment]
@davevdg The extra compile step happens automatically for all InterSystems files currently. Since that step is effectively just a no-op for non-compilable files this should be harmless. If you'd like us to make this change anyways, please open a separate issue for it.
