### ISSUE TITLE
Should not need to check-out a class to compile it

### ISSUE THREAD

**Issue by davevdg** [intersystems-community/vscode-objectscript#595]
I'm, using server-side editing.
If I open a class that is in source control and attempt to compile it, I get an error:

ERROR #5865: Item '%Library.Decimal.CLS' is not checked out of source control [zConstructEditError+3^%Library.RoutineMgr.1:%SYS]

There is no reason to need the file checked out in order to compile it!  I'm not editing the class, only compiling it.

**Comment by isc-bsaviano** [comment]
@davevdg Are you just asking for a `Compile Current File` command like the already existing `Import And Compile Current File`, or do you also want the ability to right-click on an isfs file/folder and compile it from there?

**Comment by davevdg** [comment]
I think so.  I'm not sure why it is called "Import And Compile Current File".  I am doing server-side editing.  I'm not importing anything.  I have the class/routine open in the editor.  I simply want to compile it.  I don't want to edit it or check it out (if source control is enabled).  Right now I get an error that I can't compile because the file is not checked out, but there is no need to check it out to compile.  Studio allows this.

**Comment by isc-bsaviano** [comment]
@davevdg The language is imperfect but what the command actually does is update the document's contents on the server, and the compiles it. In the Atelier API, these are 2 separate REST calls. I can add a command that only compiles the current file (if it's not dirty) that you can assign a keybind to if you want.
