### ISSUE TITLE
Which server is routine/class from?

### ISSUE THREAD

**Issue by davevdg** [intersystems-community/vscode-objectscript#599]
I'm using server-side editing with multiple server connections.
Editing a routine or class of the same name from multiple servers at the same time is difficult, if not impossible, to tell which routine or class we are editing.

Can we get some kind of label or breadcrumbs or something that gives us the location of the routine/class?

**Comment by daimor** [comment]
Could you check, if enabling breadcrumbs help to you?
`"breadcrumbs.enabled": true`

**Comment by bourette** [comment]
@davevdg, down in the lower left it shows the server:port[namespace] you are connected to doesn't it?

**Comment by davevdg** [comment]
@daimor, I can't see any difference with the "breadcrumbs.enabled": true setting:
![image](https://user-images.githubusercontent.com/35857691/113336800-e9602580-92f4-11eb-8424-0462473c1a62.png)

@bourette, yes, I do see the port in the lower-left corner. 
   localhost:57773[%SYS]
Now I have to remember which of my 6 localhost port numbers are which...  ;-)
(And remember to look down in the corner...)

**Comment by bourette** [comment]
@daimor, if I hover over the breadcrumb for my local data it tells me the base path in p4, though if I do the same for isfs it gives me /firstpackage ie /%Archive when opening %Archive.Content.  Perhaps hovering over something server based should give server:[namespace]?

**Comment by gjsjohnmurray** [comment]
@davevdg please download [this beta VSIX](https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.10-beta.6/vscode-objectscript-1.0.10-beta.6.vsix) and install it, e.g. by dropping it onto the side bar when in Extensions view. Then reopen your workspace. You should now see extra information alongside each item in Open Editors.

Prior to #602 this extra info was only shown when running with proposed APIs enabled. See the extension's README for how that is done. As an isfs user you may like to leverage the server-side searching and quick open features that also need proposed API.

**Comment by davevdg** [comment]
@gjsjohnmurray Thank you.  Looks good!
