### ISSUE TITLE
Server side changes to class .INT routines not recognized/loaded in editor window

### ISSUE THREAD

**Issue by davevdg** [intersystems-community/vscode-objectscript#600]
I am using server-side editing...
Compile a class (say User.abc.cls) and then _View Other_, you see the INT code for the compiled class's .1 routine (User.abc.1.int) - great.
Now compile the class from the command line in an IRIS session.  The User.abc.1.int is not updated in the editor window.  Even if I close the editor window and re-open it, the INT routine is not updated.  It onl;y seems to be updated if I Save[/Compile] the class from the Editor window again.  Here is an example of the mismatch in the editor window and the source on the server:
![image](https://user-images.githubusercontent.com/35857691/113348550-b887ec80-9304-11eb-8f78-737d74a6005d.png)

The IDE needs to re-load the source of the routine/class from the server if the source on the server changes.

**Comment by isc-jamien** [comment]
The IDE is not connected to the server in the way you are used to in Studio. There is NO persistent connection (except when you are doing debugging). When you compile from the command line the IDE has no clue what you have done. All it has is the timestamp of what it last pulled got from the server on the last IDE compile. If you force a reload from the server then you will see your changes. Really this is not a supported way of development, you really should compile and edit from the IDE to maintain consistency.

**Comment by davevdg** [comment]
How do I force a reload?  <Right-click>Reload... would be nice.

**Comment by gjsjohnmurray** [comment]
> 
> 
> How do I force a reload? _Right-click_ Reload... would be nice.

You can use `Revert File` from the `File` menu.

**Comment by davevdg** [comment]
> > How do I force a reload? _Right-click_ Reload... would be nice.
> 
> You can use `Revert File` from the `File` menu.

Ok, thanks.  That was not obvious to me :)

**Comment by gjsjohnmurray** [comment]
@davevdg you may like to try the VSIX at https://github.com/intersystems-community/vscode-objectscript/suites/2991455243/artifacts/67570330 which PR #685 has built. It ought to make isfs files reload upon focus if the server-side code changed.

**Comment by gjsjohnmurray** [comment]
@davevdg now available in beta build at https://github.com/intersystems-community/vscode-objectscript/releases/tag/v1.0.13-beta.3
