### ISSUE TITLE
http/https setting does not change after initial definition unless you restart VSCode

### ISSUE THREAD

**Issue by isc-zkrowiak** [intersystems-community/vscode-objectscript#608]
In server definition, the "scheme" setting will not change after initial definition without restarting VSCode. Even if you toggle/refresh connection.

**Comment by gjsjohnmurray** [comment]
@isc-zkrowiak since you refer to toggle/refresh connection I assume your `objectscript.conn` setting has a `server` property that points to an entry in `intersystems.servers`, right?
