### ISSUE TITLE
Replicate Studio Add-Ins

### ISSUE THREAD

**Issue by davidpeterunderhill** [intersystems-community/vscode-objectscript#61]
We make extensive use of the SOAP Wizard in the Studio Add-Ins so it would be good for these to be replicated in VSCode
![image](https://user-images.githubusercontent.com/36628548/68019671-5e5ca500-fc94-11e9-9fb7-7949e84d155d.png)

**Comment by mvhenderson** [comment]
Another option is to just move these wizards into the management portal

**Comment by gjsjohnmurray** [comment]
Add-ins should now be working in 0.8.7. Please test, and open new issues for any problems you find.
