### ISSUE TITLE
Document export folder

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/vscode-objectscript#612]
objectscript.export.folder does not show up in documentation

e.g.
```
  "objectscript.export.folder": "src", 
```

**Comment by isc-bsaviano** [comment]
@isc-rsingh I don't think this setting is actually used by anything. I checked the export commands and I don't see it being checked. @daimor am I missing something?

**Comment by jstetson10** [comment]
What is it? What does it do? Is it described anywhere?

From: Raj Singh ***@***.***>
Sent: Tuesday, April 20, 2021 3:30 PM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Jan Stetson ***@***.***>; Assign ***@***.***>
Subject: [intersystems-community/vscode-objectscript] Document export folder (#612)


objectscript.export.folder does not show up in documentation

e.g.

  "objectscript.export.folder": "src",

**Comment by isc-rsingh** [comment]
I thought it's required for client side setup. The extension needs to know where to download code. If not required at least it's best practice, even if the default is "src"

**Comment by isc-bsaviano** [comment]
Deleted my previous comment, I was incorrect. This setting is used to determine which folder to put exported documents in.

**Comment by isc-rsingh** [comment]
The wiki has a small write up on this @jstetson10

**Comment by isc-bsaviano** [comment]
@isc-rsingh What change do you want to see for this? If all you want is a doc string in the package.json I can do that.

**Comment by isc-rsingh** [comment]
@isc-bsaviano No code changes needed. This is just documentation.

**Comment by jstetson10** [comment]
This will be handled along with other settings when Document all possible settings #565 is fixed. I don't think this setting need to be called out elsewhere in the documentation as the default value of **src** is acceptable in many cases.
