### ISSUE TITLE
Leading whitespace before Class keyword prevents import

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/vscode-objectscript#613]
Saving a `cls` file with leading space before the class keyword will not import on save or via "Import and Compile" menu option.

Example `src/Leading/Space.cls`:

```
 Class Leading.Space
{
}
```

The extension should either report an error that the file didn't import or not prevent import/compile since `$SYSTEM.OBJ.Load` will import and compile the file without issue.

**Comment by daimor** [comment]
Yeah, the issue is in the way how it works. Before import it should recognize what's really inside, how to get the class name from some plain text file. So, if it did not decide that the file is have to be imported, it just ignore it.

Atelier API, requires the name of document for import.
