### ISSUE TITLE
Add documentation for pertinent compiler settings

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#614]
Studio (Tools > Options) and Atelier (Preferences > Atelier) describe pertinent compiler options (b, u, k) directly in the interface. For VS Code - ObjectScript, rather than adding descriptions to the Settings doc itself, the Settings should link to descriptions in the VS Code doc on GitHub. This information could perhaps be added to the Configuration page. @jstetson10 and I have discussed this already.

The link from the Settings doc added by https://github.com/intersystems-community/vscode-objectscript/pull/611 contains the b, u, k information mixed in with many other flags that don't apply to IDE compilation. Once the new doc is complete, that link should be updated to point to the new doc instead.

**Comment by jstetson10** [comment]
This will be handled along with other settings when Document all possible settings #565 is fixed. I don't think the compiler setting need to be called out elsewhere in the documentation as the default value is fine for most users.
