### ISSUE TITLE
Server side source control integration save failure

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#62]
When classes are in server side source control, a save of the class updates the class in the database but is unable to export it if it's not checked out.  It seems that this failure to export is not reported, am I just missing something?  If the class is checked out, the changes are properly exported.

**Comment by daimor** [comment]
it is an expected an issue, when you have own Source Control class with some kind of manual action for Check Out, suppose for such SCM as Perforce or SVN.

You can manually install the latest release from [the releases page](https://github.com/daimor/vscode-objectscript/releases). Which will add the ability to execute some commands from your Source Control Class as it was available in Studio. Could you try this feature, and give me some feedback about using it.
Not every actions from Studio's Source Control class is available to execute, by now is that actions which can be executed only on the server side.

**Comment by bourette** [comment]
I'm confused how to setup isfs:// is there a document you could point me to?

**Comment by daimor** [comment]
I've just added [this page](https://github.com/daimor/vscode-objectscript/wiki/Server-side-editing). Hope it will help you.

**Comment by mat1990dj** [comment]
For me it's working to execute the studio command check out and then editing

**Comment by daimor** [comment]
@bourette can we close it?
