### ISSUE TITLE
Merging a PR while another PR merge is still completing CI causes CI of second merge to fail

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#625]
The second merge tries to assign the same beta label as the first one.

Perhaps main.yml can serialize its processing in the case of a 'push' event (and for consistency, a 'release'), so that while one CI process is running a second one will wait before beginning its work.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano please be aware of this issue. Until it gets resolved I recommend only merging one PR at a time, then waiting for the beta release to get built before you merge the next one.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I'm aware of it, I thought I waited long enough.

**Comment by gjsjohnmurray** [comment]
Workaround is to wait until no CI run is in progress, then rerun all jobs in the failed CI run, even the successful ones.
