### ISSUE TITLE
Save / Compile error goes silently unreported

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#633]
Issue Type: <b>Bug</b>

I accidentally made my database read only and then when saving changes to a class the fact that it was failing was unreported / no feedback.

**Comment by isc-bsaviano** [comment]
@bourette Is this a duplicate of #391?

**Comment by bourette** [comment]
Yes, it is a duplicate.  I thought I had logged it, but when I did a quick search I couldn't find it.  It's a serious issue that needs to get addressed.
