### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#64]
Code text
	Set tIdx=$o(pArray("$XDSDocumentEntryPatientId",""))
Reports error:
Unrecognized system function/variable
System function or variable '$XDSDocumentEntryPatientId' not recognized

**Comment by daimor** [comment]
Yes, this kind of issue is known. And don't have a good fix, yet.

**Comment by bourette** [comment]
This did not resolve all of the issues
Set tIdx = $O(pAry("$MetadataLevel","")) Set:tIdx]"" tM=$o(pAry("$MetadataLevel",tIdx,""))
System function or variable '$MetadataLevel' not recognized
If ($O(pQueryParams(""))="") && (..info("$MetadataLevel")'=1)  && (..QueryReturnType="ObjectRef") {
System function or variable '$MetadataLevel' not recognized
Set tIsValue=($p(tItem,"||",1)="V"),tNode=$p(tItem,"||",2),tField=$p(tItem,"||",3) Set:tField="" tField=$p(tNode,"$XDSDocumentEntry",2)
System function or variable '$XDSDocumentEntry' not recognized
