### ISSUE TITLE
ObjectScript - View Other, fails if cursor is in a method with language other than ObjectScript

### ISSUE THREAD

**Issue by davevdg** [intersystems-community/vscode-objectscript#645]
I've already spoken to @isc-bsaviano about this, just documenting it here.
I have a class with a method with language = python (a new IRIS feature in progress, but the same might be true for other languages).  If the cursor is anywhere in this method, View Other simply reports:
"There are no other documents to open."

If the method does not exist in the class INT code, perhaps it should just open the class INT routine and place the cursor at the top of the routine?  Or maybe the error should mention the method code does not exist in the INT routine?
I was mainly just trying to quickly get the class's INT routine open.  I appreciate trying to go to the proper location in the INT routine, but if the location does not exist, I still want to see the INT routine.

**Comment by isc-bsaviano** [comment]
This was caused by #632. I need to add a check that only supplies the label+offset if the method language keyword is objectscript or not present
