### ISSUE TITLE
I can't view classes, routines,... from server

### ISSUE THREAD

**Issue by jtsalten** [intersystems-community/vscode-objectscript#649]
Issue Type: <b>Bug</b>

I can't visualize classes from server... I got the mssage:
Unable to open 'User.clientes.mac' (read-only): Not Found.
Unable to open 'valor.cls' (read-only): Not Found.

Those classes and routines exist and are editable using Studio. Also I can edit them in my local repository and compile against the server that is giving me those messages... Has it anything changed in the extension settings? Can't we view elements in the server?

Extension version: 1.0.10
VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (0.91GB free)|
|Process Argv|--crash-reporter-id 358469c0-fdbf-4ba7-9019-19e4937e55fb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
bridgeflight:30299254

```

</details>

**Comment by jtsalten** [comment]
![image](https://user-images.githubusercontent.com/6997495/117956274-30403280-b319-11eb-93d8-ab77cd20fe47.png)

**Comment by gjsjohnmurray** [comment]
Nothing has changed on 1.0.10 since it was released two weeks ago. Since then there have been two VS Code releases (1.56 and 1.56.1), and Language Server updated to 1.1.5.

Is this a workspace you used to be able to open read-only copies of classes and routines from previously? Has anything changed on the target server? Your screenshot shows ObjectScript Explorer is able to enumerate the namespace contents OK.

Please try the latest beta VSIX from https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.11-beta.20/vscode-objectscript-1.0.11-beta.20.vsix, which is likely to be released later today.

**Comment by gjsjohnmurray** [comment]
1.0.11 is now on Marketplace. If you are taking advantage of the proposed API features remember remember to fetch the 1.0.12-beta.1 VSIX from the Releases section here and install that manually.

**Comment by jtsalten** [comment]
This error is happening with the instance and namespace that I normally use to implement small samples... Normally I just develop the sample and compile it... and that works.
I don't know if it has passed more than 2 weeks since last time I went to the server to view something... but of course I did it before and it worked. Nevertheless I'll install new 1.0.11 and check again.

**Comment by jtsalten** [comment]
Tested with 1.0.11 and it seems to work now.

**Comment by gjsjohnmurray** [comment]
That's good to hear. Closing.
