### ISSUE TITLE
Routines failing to load

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#65]
I have a routine in my project and even though I update it, it's failing to load after a change.  An import and compile is also failing.

**Comment by evshvarov** [comment]
Maybe the folder structure is different? The proposed folder structure is the following: https://community.intersystems.com/post/setting-folder-structure-objectscript-code-intersystems-package-manager

**Comment by daimor** [comment]
@bourette is it still actual for you?
Is the status bar have a Connected status?
Could you give some more details, is there any errors you got. Look at Output panel, and find there logs from ObjectScript in dropdown. If nothing there, some other logs from VSCode itself.

**Comment by bourette** [comment]
It is an issue still, I'm working around it.  Basically it's an odd PackageManager package where I have some tools in %ZLANGC00 and %ZSTART in a package called MyTools which has dependencies
  <Resources>
    <Resource Name="%ZSTART.MAC"/>
    <Resource Name="%ZLANGC00.MAC"/>
Which tries to load files from
ERROR #5005: Cannot open file '/Volumes/P4/Users/bourette/MyTools/latest/rtn/_ZSTART.rtn'
ERROR #5005: Cannot open file '/Volumes/P4/Users/bourette/MyTools/latest/rtn/_ZLANGC00.rtn'

I have updated the files to be /mac/%ZSTART.mac and %ZLANGC00.mac and they now load with VSCode, but they don't work with the package manager.

**Comment by daimor** [comment]
Such errors do not look like it goes from VSCode-ObjectScript. It mostly looks like it happens from the configured Source Control Class. So, I'm sure you should check it there.

**Comment by daimor** [comment]
@bourette do you still need help, or we can close it already?
