### ISSUE TITLE
Change to Explorer automatically when select whatever element (class,routine,...)

### ISSUE THREAD

**Issue by jtsalten** [intersystems-community/vscode-objectscript#651]
Issue Type: <b>Bug</b>

From ObjectScript view, when select one file (class, routine, etc.) for viewing, it automatically changes to Explorer view again... so if I didn't finish and I want to view any other element, I have to go back to ObjectScript explorer and look for it again...
Not sure if this is intended behavior... I think it's a bug... but if it's by design, it is annoying.

Extension version: 1.0.11
VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:05.141Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (1.26GB free)|
|Process Argv|--crash-reporter-id 358469c0-fdbf-4ba7-9019-19e4937e55fb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553
bridgeflight:30299254

```

</details>

**Comment by jtsalten** [comment]
![VSCodeError](https://user-images.githubusercontent.com/6997495/117993248-d9018880-b33f-11eb-9361-c7f4961d88dc.gif)

**Comment by gjsjohnmurray** [comment]
No, that's not intentional. 1.0.11 included some changes to handle the case where a user changes connection details and the existing connections used not to refresh. Perhaps this is causing your issue. I can repro it, and am investigating now.

**Comment by gjsjohnmurray** [comment]
@jtsalten please download the zip from https://github.com/intersystems-community/vscode-objectscript/suites/2726455476/artifacts/60143151 and extract the VSIX. Install that manually and verify it fixes your issue. Assuming it does, I will merge PR #652 to create a beta VSIX, and we will schedule a Marketplace release.
