### ISSUE TITLE
Colour background on View Other

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#655]
Is there a way to colour the background differently when in View Other?  I want server side editing on because there are times I want to change the code, but I'd also like to be reminded that I'm in the int and not the cls file.

**Comment by isc-bsaviano** [comment]
I think you can either create your own theme or edit your settings.json to change the editor background color for a specific language. The language ID for mac and int routines is just "objectscript". Here's a link to the VSCode theming documentation: https://code.visualstudio.com/api/extension-guides/color-theme

**Comment by bourette** [comment]
Hmm, that is less than optimal.  We know that the int code for a class is generated as it has the keyword, is there some way to use that in the theme to have a different background colour?  It really seems like we should do this as a default.

**Comment by isc-bsaviano** [comment]
AFAIK there's no way to set theme colors based on the text contents of a file (i.e. the words within, not the semantic tokens or language ID). Extensions can't control editor colors besides providing themes that users can activate so there's nothing to be done on our part.

**Comment by isc-bsaviano** [comment]
Closing this issue because this isn't possible AFAIK
