### ISSUE TITLE
snippets not working in clientmethod

### ISSUE THREAD

**Issue by spotashn** [intersystems-community/vscode-objectscript#656]
Issue Type: <b>Feature Request</b>

I have a class that extends %ZEN.Component.page and have defined a ClientMethod

ClientMethod JSContent() [ Language = javascript ]
{
{

within a clientmethod the objectscript snippets do not auto complete when typing.

Can ClientMethod be added so that snippets in objectscript.json auto complete when typing.

Extension version: 1.0.11
VS Code version: Code 1.56.1 (e713fe9b05fc24facbec8f34fb1017133858842b, 2021-05-06T10:08:24.325Z)
OS version: Darwin x64 19.6.0
Remote OS version: Linux x64 4.18.0-193.el8.x86_64
Remote OS version: Linux x64 4.18.0-193.el8.x86_64

**Comment by daimor** [comment]
Snippets for ClientMethod should use language `objectscript-class` not `objectscript`
![image](https://user-images.githubusercontent.com/1212251/118237009-74f5d600-b49f-11eb-83bb-aeb39d2a2966.png)

**Comment by isc-solon** [comment]
Why should ObectScript snippets work in a JavaScript ClientMethod?

**Comment by spotashn** [comment]
My mistake. Thanks working as expected
