### ISSUE TITLE
Within VSC how to use the debug function with Object script

### ISSUE THREAD

**Issue by tomb54** [intersystems-community/vscode-objectscript#659]
Hi all, how do you use the debug function within VSC to debug Objectscript?

Any pointers much appreciated.

I have already installed Serenji extension! 

![image](https://user-images.githubusercontent.com/44673339/118413879-67a43b80-b699-11eb-8a72-ed13018e9a79.png)

**Comment by isc-bsaviano** [comment]
@tomb54 I'm not sure how Serenji debugging works. @gjsjohnmurray can help with that. The documentation for debugging using this extension is found [here](https://intersystems-community.github.io/vscode-objectscript/rundebug/). You will need to install the [ObjectScript extension pack](https://marketplace.visualstudio.com/items?itemName=intersystems-community.objectscript-pack) before you can use this extension for debugging.

**Comment by tomb54** [comment]
Thanks isc-bsaviano, 

The issue I'm having is that the launch.json does not open or appear on the file Explorer and I do not have the .vscode 

I am trying to debug a macro that I created under the name space Ensembles.SAMPLES

**Comment by isc-bsaviano** [comment]
@tomb54 The documentation page I linked in my initial response shows you how to create an ObjectScript debugging configuration (using this extension, not Serenji). If you follow those steps, the file should be created automatically. I'm not sure what you mean by "debugging a macro". You generally want to be debugging routines or ClassMethods.

**Comment by isc-rsingh** [comment]
ping @gjsjohnmurray

**Comment by gjsjohnmurray** [comment]
@tomb54 having both the InterSystems ObjectScript extension and the Serenji extension enabled at the same time can in some cases lead to complications and confusion. An upcoming release of Serenji (3.1.4) should improve the situation. Meanwhile I suggest you disable the Serenji extension for the workspace in which you are attempting to use the debug capabilities of the InterSystems ObjectScript extension (for which this is the GitHub repo).

Please also tell us if you are using the [Server-side Editing](https://intersystems-community.github.io/vscode-objectscript/serverside/) mode of the client-side one. One way of clarifying this is to share the contents of your xxx.code-workspace file.

**Comment by tomb54** [comment]
When I try to add the workspace from the InterSystem ObjectScript settings I receive the following error:

![image](https://user-images.githubusercontent.com/44673339/118548995-d1345080-b752-11eb-95cf-5987b0b52781.png)

[image](https://user-images.githubusercontent.com/44673339/118548359-1d32c580-b752-11eb-93cd-10ccad2f51d5.png)

**Comment by tomb54** [comment]
Thanks gjsjohnmurray,
I am not using Server-side Editing.
Basically I have..
1. Downloaded VSC and installed ObjectScript Extension Pack
2. Set my local Ensemble as the default
3. Completing the following tutorial by using VSC instead of Studio
https://docs.intersystems.com/latest/csp/docbook/Doc.View.cls?KEY=TCOS_StepByStep1

4. I created a file called mydatent and saved it as a Macro within the in the SAMPLES namespace.

But I cannot run debug on my code, I receive the following error when I try to add ObjectScrip to my workspace

![image](https://user-images.githubusercontent.com/44673339/118552569-0642a200-b757-11eb-8717-0cd11da02312.png)

**Comment by isc-solon** [comment]
1. By "debugging a macro" @tomb54 means "debugging a macro routine."
2. @tomb54 The version of the ObjectScript Tutorial you're using applies to an earlier version of our products. You can still use it, and debugging should work for you no matter what. If you want to switch to the latest version of the tutorial, it's here: https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=TOS

**Comment by tomb54** [comment]
Thanks isc-solon

**Comment by tomb54** [comment]
Ok I found the issue; you need to create a folder first :)

**Comment by tomb54** [comment]
Ok I found the issue; you need to create a folder first :)

**Comment by gjsjohnmurray** [comment]
@tomb54 the screenshots you posted indicate that you **were** using the server-side mode of operation. Particular clues are that your workspace folder label reads 'default~ensemble:SAMPLES' and the "Unable to write file" error message refers to 'isfs://..."

Documentation currently lacks key information about server-side setup that enables server-side mode to store folder-specific debug configurations. See #425 for the doc issue.

Anyway, good to know that @tomb54 is now able to debug. Thanks for having closed this issue.
