### ISSUE TITLE
How to use gitlab for version control

### ISSUE THREAD

**Issue by yidongyi** [intersystems-community/vscode-objectscript#660]
Issue Type: <b>Feature Request</b>

We have a small development team, I don't want everyone to be able to update the program directly. So ,I want to use gitlab or github for version control . Do you have any relevant documentation or suggestions?

Extension version: 1.0.11
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.15063

**Comment by gjsjohnmurray** [comment]
I suggest you search Developer Community (https://community.intersystems.com/) and maybe post your questions there.

**Comment by yidongyi** [comment]
thanks for your reply.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John ***@***.***&gt;; 
发送时间: 2021年5月17日(星期一) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [intersystems-community/vscode-objectscript] How to use gitlab for version control (#660)





 
I suggest you search Developer Community (https://community.intersystems.com/) and maybe post your questions there.
