### ISSUE TITLE
Issue exporting classes to local (1.int files)

### ISSUE THREAD

**Issue by saulper** [intersystems-community/vscode-objectscript#663]
Issue Type: <b>Bug</b>

I don't know if this is an issue or if I have to configure something, because I am quite newbie in IS. 
I have used the InterSytems Portal to build some DT. 
I have my Visual Studio Intersystems extensions connected, so I can see all the transformation classes in the ObjectScript Extension, in the explorer.

If I right-click on one of the individual files I can select export and everything is fine. The class is now updated in my local explorer.
But if I do the same with a folder (the DT folder or any other) and I export it, 
<img width="253" alt="exporting" src="https://user-images.githubusercontent.com/6555497/118649007-4e0f0b00-b7e3-11eb-83e2-a784f49a8d35.png">
I get the folder with all the files and also additional folders with the name of each class and in every one of these folders a file named 1.int (which I think its the intermediate InterSystems code).

<img width="232" alt="localfiles" src="https://user-images.githubusercontent.com/6555497/118649054-5bc49080-b7e3-11eb-8546-2a331b74935d.png">

Extension version: 1.0.11
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19041

**Comment by isc-bsaviano** [comment]
@saulper You probably have the configuration setting `objectscript.export.generated` set to `true`

**Comment by saulper** [comment]
> @saulper You probably have the configuration setting `objectscript.export.generated` set to `true`

Thank you for your answer, I think it is set to false. I haven't changed anything, at least not consciously.
These are my settings:

![image](https://user-images.githubusercontent.com/6555497/118699310-abba4c00-b811-11eb-8e48-48d485b99d19.png)

**Comment by isc-bsaviano** [comment]
@saulper Delete your local `src` folder and try again with those settings. Do the generated INTs reappear?

**Comment by saulper** [comment]
> @saulper Delete your local `src` folder and try again with those settings. Do the generated INTs reappear?

Yes, the same thing has happened. Every .cls file has a corresponding folder with a file 1.int inside.
I can live with it, I delete all of them, but it would be nice if this didn't happen.
I have restarted the docker, the PC and nothing changes.

**Comment by isc-bsaviano** [comment]
@saulper You're exporting from the ObjectScript Explorer, right? It's the view with the InterSystems logo

**Comment by saulper** [comment]
> @saulper You're exporting from the ObjectScript Explorer, right? It's the view with the InterSystems logo

Yes, it is the ObjectScript Explorer.

**Comment by isc-bsaviano** [comment]
@saulper Hover over the root node of your explorer tree and click on the little "window with gears" icon to show or hide generated documents. Please change that setting and try again with an empty source folder and let me know what gets exported. Hovering over that icon should say `Show Generated Items` if the generated documents are hidden.

![Screen Shot 2021-05-18 at 3 44 10 PM](https://user-images.githubusercontent.com/44776135/118713423-e90de200-b7ef-11eb-8416-ee71fc08d23d.png)
