### ISSUE TITLE
Document that current open file wins for debugging

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/vscode-objectscript#666]
When debugging, `launch.json` only specifies the file name. This is unclear if you have a multi-root workspace, and the same class exists in multiple roots (e.g. src/MyPackage/MyClass.cls). Debugging resolves this by using a currently open file with the name specified in `launch.json`. 

It needs to be documented that when debugging, make sure the class you want to debug is currently open, and no other class with the same name is open at the same time.

**Comment by isc-bsaviano** [comment]
To be clear, VS Code will start a debug session with the server of the file in the active editor (the tab that the user is focused on). The new documentation can be as simple as this:

> When starting a "launch" debug session, make sure that the file that you are debugging is open in your editor and is the active tab.
