### ISSUE TITLE
Document ObjectScript.conn links feature

### ISSUE THREAD

**Issue by jtsalten** [intersystems-community/vscode-objectscript#667]
Issue Type: <b>Feature Request</b>

Hi, 
trying to look for documentation about how to define new links to external pages in objectscript.conn.links... I couldn't find any doc

Extension version: 1.0.11
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isc-bsaviano** [comment]
@jstetson10 These comments contain some information about this feature:

https://github.com/intersystems-community/vscode-objectscript/issues/325#issuecomment-717838543
https://github.com/intersystems-community/vscode-objectscript/issues/325#issuecomment-733920836
