### ISSUE TITLE
Extra OK popup and extra OK

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#673]
When a class compiles with an error, the error message appears in the Output window, but it's followed by an "OK" on the next line. The "OK" doesn't appear for successful compilation. I think this could be confusing.

The error compilation also pops up an "OK" dialog. It has a gear icon. Hover over the icon and it says "Manage Extension" but clicking it does nothing. Clicking "Show Details" dismisses the popup, just like clicking X.

I think this is new behavior.

**Comment by isc-bsaviano** [comment]
Probably related to #637
