### ISSUE TITLE
Default grant of procedure permissions for all namespaces for %Developer role

### ISSUE THREAD

**Issue by isc-ryoung** [intersystems-community/vscode-objectscript#688]
Could these permissions be granted by default in future versions, so that users do not need to run this for every namespace to be accessed?

`GRANT EXECUTE ON %Library.RoutineMgr_StudioOpenDialog TO %Developer`

I am guessing this would require a change within IRIS rather than VSCode?

**Comment by g3mGoddess** [comment]
visual code community was made by me.. im currently dealing with a hacker(s) and they have made things VERY dificult for me :(. but i did manage get vs

**Comment by gjsjohnmurray** [comment]
@isc-ryoung this would need to change upstream on IRIS. Please open a request through the relevant internal channel and add a reference to it here.

**Comment by isc-ryoung** [comment]
@gjsjohnmurray Thanks.
I have submitted Jira DP-406308 for this issue.

**Comment by isc-bsaviano** [comment]
Fixed internally by DP-413625
