### ISSUE TITLE
 intersystems-community 

### ISSUE THREAD

**Issue by g3mGoddess** [intersystems-community/vscode-objectscript#689]
vs community

**Comment by gjsjohnmurray** [comment]
@g3mGoddess please explain what this issue is about.

**Comment by g3mGoddess** [comment]
im still learning but i believe i just got over whelmed with all the open folders and programs i had running.. i then got confused and forgot what it was i was trying to do. ive cleaned things up and back tracked and will focus on the next step. thank you for the quick response
