### ISSUE TITLE
Permissions issue: Language Server fails when hovering over class names

### ISSUE THREAD

**Issue by S-Hahne** [intersystems-community/vscode-objectscript#690]
Dear Developer community,

Following [Issue#678](https://github.com/intersystems-community/vscode-objectscript/issues/678) I think there is another rights issue.
When hovering over class names with a %Developer user, the following error displays in the InterSystems Language Server extension:
![2021-06-15 21_52_18-VSCode Language Server error](https://user-images.githubusercontent.com/75479680/122348455-76596900-cf4b-11eb-9b1a-9189da76c950.png)
 With a user who has %All permissions, the expected popup appears:
![grafik](https://user-images.githubusercontent.com/75479680/122348946-fc75af80-cf4b-11eb-8cfe-57211034e09d.png)

Which permission am I missing?

Thanks in advance, 
Sebastian

**Comment by isc-bsaviano** [comment]
@S-Hahne [Here's](https://github.com/intersystems/language-server#setup-notes) the relevant section of the LS readme

**Comment by S-Hahne** [comment]
Many thanks @isc-bsaviano !!

I've already mentioned this in the WRC ticket: wouldn't it be useful to have this built into the %Developer role? As developers shouldn't have the %All rights.

Have a nice weekend.

**Comment by gjsjohnmurray** [comment]
Similar to #688

**Comment by isc-bsaviano** [comment]
@S-Hahne This has been reported internally. See https://github.com/intersystems-community/vscode-objectscript/issues/688#issuecomment-863248043
