### ISSUE TITLE
isfs workspace expansion fails silently if server definition is missing

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#695]
Issue Type: <b>Bug</b>

1. Create an isfs workspace.
2. Edit the code-workspace JSON, changing the server name to one that doesn't exist in your settings.json
3. Close and reopen the workspace, then try to expand the folder. The expanded tree node has no descendants but no explanation is given.

Extension version: 1.0.13-beta.3
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by RyszardWithAZ** [comment]
I'm getting the same result often (but not always!), except my workspace has the correct server name. When I click on the Refresh Explorer icon, I briefly see my subpackages and then they disappear again.

Usually after I restart VSCode, it starts working again for a little while, until it stops. Of course, today it's not even recovering after a restart, I'm very frustrated I can't reach any of my code on the server.

**Comment by gjsjohnmurray** [comment]
@RyszardWithAZ if you install the pre-beta build from https://github.com/intersystems-community/vscode-objectscript/suites/3032303382/artifacts/68794426 does the workspace folder change color when this happens during a refresh?

Is your server running out of licenses?

**Comment by RyszardWithAZ** [comment]
I'm on the latest beta build (vscode-objectscript-1.0.13-beta.3), the workspace folder doesn't seem to be changing color, and I have PLENTY of licenses.

I'm also seeing save/compile operations in my output when I haven't saved anything. It looks like VSCode is CONSTANTLY saving to IRIS, even when I haven't saved the class. I'm also getting plenty of "Failed to save file on the server" messages, even if I'm not doing anything!

**Comment by gjsjohnmurray** [comment]
Have you enabled autosave in VS Code?

**Comment by RyszardWithAZ** [comment]
My workspace autosave is set to Off (though my User-level autosave is set to afterDelay)... I think my workspace one should win since I'm in my IRIS workspace?
