### ISSUE TITLE
Support watchpoints in debugger

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#697]
The command line and Studio debuggers support watchpoints. I'm posting this issue to see if there are any plans to add this as an enhancement for VS Code - ObjectScript.

**Comment by isc-bsaviano** [comment]
@isc-solon This is supported already. You can watch the values of variables and expressions in the [Watch window](https://code.visualstudio.com/Docs/editor/debugging#_data-inspection)

**Comment by isc-solon** [comment]
No, it's not supported yet. A **watchpoint** in InterSystems Studio is a variable that will trigger a break whenever the variable is set or killed. I just checked the regular Studio docs (https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSTD_DEBUGGER) and that doc uses "watchpoint" to mean "a variable in the watch window." But that's not what a watchpoint is (a doc JIRA is forthcoming for that!) Here's some doc on watchpoints:
* from an old version of the ObjectScript tutorial that used Studio (https://docs.intersystems.com/latest/csp/docbook/Doc.View.cls?KEY=TCOS_Debug)
* from the current glossary (https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=RGOT_complete#RGOT_Watchpoint)

**Comment by isc-bsaviano** [comment]
@isc-solon I read through the docs and this is possible in [VS Code](https://github.com/Microsoft/vscode/issues/58304), but it will require work in this extension and on the server. Unfortunately I don't have any free time to work on this so it may not get considered in time for the next IRIS release.

**Comment by isc-bsaviano** [comment]
I just checked and the server already supports setting watchpoints (`breakpoint_set -t watch` in the XDebug DBGP protocol that we use). Doing this enhancement would only require VS Code work. We'd need to set `supportsDataBreakpoints: true` here:

https://github.com/intersystems-community/vscode-objectscript/blob/6793e168bec1ddee649002b9e1c52b8967d5f173/src/debug/debugSession.ts#L103-L115

and then implement the data breakpoint methods.
