### ISSUE TITLE
FR: Formatting/Indentation of XML

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#699]
This is more of a "nice to have" rather than "required" feature, but it would be great if XML embedded in ObjectScript (XData sections primarily) were indented and collapsible. Thoughts?

**Comment by isc-bsaviano** [comment]
@DodgeDeBoulet The [Language Server extension](https://github.com/intersystems/language-server#features) provides Folding Ranges for XML tags in XData blocks. The mini-indenting that Studio does isn't possible to replicate in VS Code.

**Comment by isc-bsaviano** [comment]
@DodgeDeBoulet Is the current behavior with the LS installed sufficient?

**Comment by DodgeDeBoulet** [comment]
If it's not supported by VS Code, I suppose it has to be sufficient 😉 Closing
