### ISSUE TITLE
Not recognised commands between &SQL() 

### ISSUE THREAD

**Issue by Patresko** [intersystems-community/vscode-objectscript#70]
Syntax higlighting does not know any of SQL commands between &SQL() and its marking as Unrecognized command

**Comment by daimor** [comment]
It's ok at the moment it's not a syntax highlighting issue, it a parsing issue.
syntax highlighting should work well. 
error as `unrecognized command`, is a part of diagnostic errors and works quite dumb for now.

**Comment by david2278** [comment]
Will this fix things like a multiline SET statement?

```set a = 0,
b = 1
c = 2```

**Comment by daimor** [comment]
Multiline SET should be already fixed in the latest [beta version](https://github.com/daimor/vscode-objectscript/releases)

**Comment by Dudelmoser** [comment]
Could you mark the whole SQL block as comment until the actual parsing is implemented? Getting errors for perfectly valid code is a major pain :-/

**Comment by daimor** [comment]
@Dudelmoser I think I already fixed it, could you give some example, please

**Comment by Dudelmoser** [comment]
Oh pardon, I just realized it's already fixed in the beta version. When will you push it to the vscode market place?

**Comment by daimor** [comment]
This beta, already released as public

**Comment by Dudelmoser** [comment]
By the way, THANK YOU so much! Developing in COS would be barely an option for me without your extension.

**Comment by daimor** [comment]
Thanks, for such feedback ))

**Comment by daimor** [comment]
Actually, just checked, it may not work if you have `&sql` not in lowercase.

**Comment by daimor** [comment]
I'll add ignore case a bit later

**Comment by Dudelmoser** [comment]
Correct, that's what I realized aswell after you said the change is already live. Thank you :) I also noticed an issue with recognizing matching parentheses which in turn screws up the syntax highlighting.

![image](https://user-images.githubusercontent.com/16316772/73657779-49c4ea00-4693-11ea-8362-149371cbaf39.png)

```sql
    SELECT a
    FROM s
    WHERE b LIKE '%' || (
      SELECT TOP 1 b
      FROM t
    ) || '%'
```

The second '%' is not recognized as string because the previous parenthesis seems to close the &sql block. I hope there's a quick fix for that aswell :)

**Comment by aray-isc** [comment]
`&sql` and `&SQL` seem to both work now, but `##SQL` doesn't.

**Comment by daimor** [comment]
Thanks, for reporting, I'll check it later

**Comment by daimor** [comment]
should be fixed now, closing

**Comment by aray-isc** [comment]
@daimor is there an estimate for when this gets into a released version?

**Comment by daimor** [comment]
week or so
