### ISSUE TITLE
Server side source control fails but no error in VS Code

### ISSUE THREAD

**Issue by hansonmark** [intersystems-community/vscode-objectscript#701]
Using server side source control hooks I open a routine and make an edit and the dialog comes up asking if I wish to check this item out. I select 'Yes' but as my VPN is down the 'p4 edit' command that is being run on the IRIS server fails. The bug is that there is no error message in VS code indicating this failure. The dialog asking if I wish to checkout the document is closed and no error is show but if I attempt to make another edit to the routine the dialog comes up again and the situation repeats.

Adding logging to the %Studio.SourceControl.ISC.cls in the 'CheckOut' method I can see the attempt to run the 'p4 edit' is reporting the correct failure %Status code so something higher in the plumbing is dropping the error:

^IRIS.Temp.YMH(1)=$lb(2,"edit","/Users/markh/perforce/projects/sql/databases/sys/rtn/obj/_apiDDL.rtn","0 "_$lb($lb(5001,"Error: Perforce client error:"_$c(10,9)_"Connect to server failed; check $P4PORT."_$c(10,9)_"TCP connect to perforce.iscinternal.com:1666 failed."_$c(10,9)_"nodename nor servname provided, or not known"_$c(10),,,,,,,,$lb(,"%SYS",$lb("e^zSecureRunCmd+33^%Studio.SourceControl.ISC.1^1","e^zCheckOut+18^%Studio.SourceControl.ISC.1^1","e^zAfterUserAction+19^%Studio.SourceControl.ISC.1^2","e^zAfterUserAction+7^%Studio.SourceControl.Interface.1^1","e^zAfterUserActionExecute+11^%Atelier.v1.Utils.Extension.1^1","e^zAfterUserActionFunc+2^%Atelier.v1.Utils.Extension.1^1","e^%0AmBm2l1t+1^%sqlcq.pSYS.cls10.1^1","d^%0AmBk1^%sqlcq.pSYS.cls10.1^1","d^%Next+5^%sqlcq.pSYS.cls10.1^1","e^zAppendResultSet+22^%Api.Atelier.v4.1^1","e^zQuery+43^%Api.Atelier.v1.1^1","e^zDispatchRequest+42^%CSP.REST.1^1","e^zDispatchRequest+56^%CSP.REST.1^1","e^zPage+26^%CSP.REST.1^1","e^zPage+2^%Atelier.REST.1^1","e^CSPDispatch+484^%SYS.cspServer^2","d^CSPDispatch+274^%SYS.cspServer^1","d^zProcessRequest+1^%CSP.Session.1^1","d^Request+665^%SYS.cspServer2^1","d^Request+25^%SYS.cspServer2^1","d^zProcessRequest+1^%CSP.Request.1^1","d^css+51^%SYS.cspServer2^1","d^SuperServer+56^%SYS.SERVER^3","d^^^0")))))

This log entry contains:

		Set sc=..SecureRunCmd("p4",.args) Set ^IRIS.Temp.YMH($I(^IRIS.Temp.YMH))=$lb(args,args(1),args(2),sc)

**Comment by isc-bsaviano** [comment]
@timleavitt can you or @ty-d take a look at this when you have a minute? I'm not familiar with this part of the extension at all.

**Comment by timleavitt** [comment]
@ty-d I think this would be your area; the VSCode client is ignoring the error reported.
