### ISSUE TITLE
Server side source control 'check out' then prompts for same action you just selected

### ISSUE THREAD

**Issue by hansonmark** [intersystems-community/vscode-objectscript#702]
Open a document that is part of the server side source control and from the 'server source control' icon pick the 'Check Out' option to check the current document out. This brings up a dialog asking 'Do you wish to check item 'XYZ' out from Source Control?'. 

This dialog is redundant as the user just selected the option to check out the item from source control, so this dialog should not appear in this situation (it obviously should still appear if the user starts editing the document and the document is not currently checked out).

**Comment by timleavitt** [comment]
This is an issue with the source control class, not VSCode itself. (Internal reference: APPS-6717)

**Comment by isc-bsaviano** [comment]
Closing this because it's an issue with ISC's internal source control class
