### ISSUE TITLE
Server side source control edit prompts to checkout document but loses the edit just made

### ISSUE THREAD

**Issue by hansonmark** [intersystems-community/vscode-objectscript#703]
Open a document under server side source control that is not currently checked out. Select a chunk of text from this document and hit 'delete' to remove this from the document. VS code prompts to checkout the document so the edit can be made (which is correct), on selecting 'Yes' and the server side checkout being performed correctly the edit i.e. deleting the chunk of text is not applied to the current document so you need to perform the edit a second time to make it work.

The edit should be applied once the document is successfully checked out.

**Comment by timleavitt** [comment]
This is an issue with the source control class, not VSCode itself. (Internal reference: APPS-6717)

**Comment by timleavitt** [comment]
@ty-d please see if we can improve this.

**Comment by isc-bsaviano** [comment]
Fixed by #725
