### ISSUE TITLE
Server side 'Undo checkout' option should recompile the reverted routine/class

### ISSUE THREAD

**Issue by hansonmark** [intersystems-community/vscode-objectscript#704]
With server side source control make an edit to a file under source control and save it which recompiles this item. Now you decide that you do not like this change and wish to go back to the previous head revision under your source control. Select the 'Undo checkout' option from the source control menu which reverts the file. The problem is the reverted file is not compiled so any attempt to run this results in the code that is run being the version you had edited.

If you try to recompile this reverted file with command+S you get an error:

ERROR #5865: Item 'User.Class.CLS' is not checked out of source control

So the save part of the command+S fails which prevents it from running the compile phase.

It seems the simplest solution is to make the 'undo checkout' also recompile the document as this keeps the saved version in sync with the compiled version.

**Comment by timleavitt** [comment]
@hansonmark %Studio.SourceControl.ISC already does this (see TSL875)

**Comment by hansonmark** [comment]
Apologies, you are right it does recompile the reverted file. I was confused with another revert behavior I am about to report.
