### ISSUE TITLE
Revert of document in source control not picked up if this document open in VS Code

### ISSUE THREAD

**Issue by hansonmark** [intersystems-community/vscode-objectscript#705]
Open a document under server side source control in VS Code. Edit this document which asks to checkout the document, select 'yes' and save/compile it. Under your separate source control tool e.g. P4V you can see the file associated with this document is now checked out and modified. In P4V revert this file. 

In VS Code there is no indication the file on disk associated with this document was changed. In IRIS Studio the timestamp check it performs on a regular basis and when the document gets focus will trigger a source control call that detects the associated file is modified and if the document is not modified in Studio will cause the document to be reloaded from the file automatically and the view inside Studio will be refreshed. Additionally if the file in Studio was modified you will be prompted if you wish to revert your edits back to the version of the file on disk.

**Comment by gjsjohnmurray** [comment]
@hansonmark are you using the Marketplace version of the extension, or the latest beta from https://github.com/intersystems-community/vscode-objectscript/releases ?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I got Mark set up with Insiders and the beta. He's using 1.0.13-beta.6, which has #685

**Comment by gjsjohnmurray** [comment]
> 
> 
> @gjsjohnmurray I got Mark set up with Insiders and the beta. He's using 1.0.13-beta.6, which has #685

@isc-bsaviano thanks for confirming that.

@hansonmark if you focus to another part of VS Code (or to another app) after the P4V revert, then when you focus back to the document in VS Code does it reload?

**Comment by gjsjohnmurray** [comment]
Update: looks like the focus change needs to be to another app and back again.

**Comment by timleavitt** [comment]
This resembles #259 which I'd thought was resolved... maybe need some more timestamp check triggers?

**Comment by isc-bsaviano** [comment]
Fixed internally by DP-409553
