### ISSUE TITLE
Debugger disconnects when debug method loads itself

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems-community/vscode-objectscript#706]
We have a unit test manager that loads all classes from the unit test directory before running the specific test. If we try to debug a test in VS Code, the debugger seems to disconnect at the point we load that test. A simple way to reproduce is by loading this class:
```
Class Test.pbarton.debug
{

ClassMethod Check()
{
    break
    do $System.OBJ.Load("somedirectory\debug.xml","ck")
    break
}

}
```
Export it to "somedirectory\debug.xml". Then run the debugger with this option:
```
	"launch": {
		"version": "0.2.0",
		"configurations": [
			{
				"type": "objectscript",
				"request": "launch",
				"name": "XDebug",
				"program": "##class(Test.pbarton.debug).Check()"
			}
		]
	}
```
The VS Code debugger will stop at the first break statement, but never reach the second. The Studio debugger on the other hand will stop at both breakpoints.

InterSystems ObjectScript version: v1.0.13-beta.6
VS Code version: 1.57.1
Caché instance version: Cache for Windows (x86-64) 2018.1 (Build 184U) Wed Sep 19 2018 09:09:22 EDT

**Comment by isc-bsaviano** [comment]
@isc-pbarton I did a quick test with server side debug logging on, and the issue appears to be with the stack info for the target process getting messed up. Here's the log for when the first `break` statement is hit:

```
^IRIS.Temp.Atelier("debug",3813,1,25)="Hit A BreakPoint"
^IRIS.Temp.Atelier("debug",3813,1,26)="Event:status|<response command='run' status='break' reason='ok' transaction_id='6'/>"
^IRIS.Temp.Atelier("debug",3813,1,27)="Received:stack_get -i 7"
^IRIS.Temp.Atelier("debug",3813,1,28)="Calling state stack_get"
^IRIS.Temp.Atelier("debug",3813,1,29)="stack: 3^zDebugStub+40^%Debugger.System.1:5^zt+1^User.short.1"
^IRIS.Temp.Atelier("debug",3813,1,30)="mapping:zt+1^User.short.1 -> USER:User.short.cls:t:1"
^IRIS.Temp.Atelier("debug",3813,1,31)="Event:stack_get|<response command='stack_get' transaction_id='7'><stack level='1' type='file' filename='dbgp://%7CUSER%7CUser.short.cls' method='t' methodoffset='1' lineno='1'/></response>"
```

And here's the log for when the second `break` is hit:

```
^IRIS.Temp.Atelier("debug",3813,1,77)="Hit A BreakPoint"
^IRIS.Temp.Atelier("debug",3813,1,78)="Event:status|<response command='run' status='break' reason='ok' transaction_id='10'/>"
^IRIS.Temp.Atelier("debug",3813,1,79)="Received:stack_get -i 11"
^IRIS.Temp.Atelier("debug",3813,1,80)="Calling state stack_get"
^IRIS.Temp.Atelier("debug",3813,1,81)="stack: 3^zDebugStub+40^%Debugger.System.1:5^^User.short.1"
^IRIS.Temp.Atelier("debug",3813,1,82)="mapping:^User.short.1 -> No Location: Not Mapped"
^IRIS.Temp.Atelier("debug",3813,1,83)="Event:stack_get|<response command='stack_get' transaction_id='11'></response>"
```

The difference is that the stack string in the first example contains the `label+offset` in the generated INT routine, but that's not present in the second example. This means that the server doesn't have a line that they can tell the client that we stopped on, so the client (VS Code) doesn't highlight that line when execution stops. I'm not sure exactly why this is happening, but I bet that recompiling the class while it's being debugged is the cause. I'll discuss this with Jamie when he returns from PTO next week and see if there's anything we can do.

**Comment by isc-bsaviano** [comment]
@isc-pbarton I spoke with Jamie and there's nothing we can do about this

**Comment by isc-pbarton** [comment]
@isc-bsaviano Understood, thank you for looking into this.
