### ISSUE TITLE
 An error occurs when importing many routines. [Import Without Compilation]

### ISSUE THREAD

**Issue by k-murata** [intersystems-community/vscode-objectscript#708]
Issue Type: <b>Bug</b>

When trying to import all at once due to the reflection of assets from the workspace to the Cache server, it fails.
* Command [Import and compile] or [Import without Compilation])
(Message)
Failed to save file 'xxxxxxxxx.mac' on the server

Extension version: 1.0.12
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
vspre833:30267464
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2:30301612
vscorehovct:30302760
bridgeflight:30302069
vscod805cf:30301675

```

</details>

**Comment by isc-bsaviano** [comment]
@k-murata Can you provide more details please? How many files are you importing, what's the folder structure, do you get the error on the same file every time, are you seeing more info in the ObjectScript output window at the bottom of your screen?

**Comment by k-murata** [comment]
Thank you for your reply. 
It occurred in about 400 mac files. The place where the error occurs is different every time.
OBJECTSCRIPT: EXPLORE brings all classes in the SAMPLES namespace to the local workspace
The same error is displayed when you export and then [Import without Compilation].confirmed.

**Comment by isc-bsaviano** [comment]
@k-murata Ok, so you're exporting all MAC files from the SAMPLES namespace using the explorer, and now you want to re-import all of them? If you click on `Output` in the bottom pane and select `ObjectScript` from the dropdown menu on the right side of the pane, do you get any messages when you try your import? If so, can you paste that here?

**Comment by k-murata** [comment]
samples namespace I have created all the classes in the USER namespace workspace.
After that, I selected [import and compile]. 

![image](https://user-images.githubusercontent.com/11677016/124612305-2ec06000-dead-11eb-872c-6792985ec83c.png)

**Comment by isc-bsaviano** [comment]
@k-murata It looks like you're working server side (using virtual ISFS files). In that workflow, you don't need to export and re-import files. You're already seeing what's on the server like in Studio. The files are don't exist on your file system. Can you describe what exactly you're trying to do? Just edit files in your USER namespace?

**Comment by k-murata** [comment]
I did the following steps:
1. Delete all classes in the USER namespace using CacheStudio

2. Execute [Import and compile] in VS Code
・ An error has occurred, but the file still exists.
![image](https://user-images.githubusercontent.com/11677016/124694269-df654880-df1b-11eb-94db-54415ec33a38.png)
![image](https://user-images.githubusercontent.com/11677016/124694305-f6a43600-df1b-11eb-87fc-fc46960cc84c.png)

3. After a while The text color of Explorer is now all green.
![image](https://user-images.githubusercontent.com/11677016/124694328-028ff800-df1c-11eb-9c80-41b9a868f024.png)

**Comment by isc-bsaviano** [comment]
@k-murata Thanks for the extra information. I know the operation that you’re trying to perform. I don’t know why you’re seeing that error, but I think you can avoid doing the large import operation that produces it. Are you using client side source control like GitHub for these 440+ files? If not, I suggest that you follow our [server side editing documentation](https://intersystems-community.github.io/vscode-objectscript/serverside/) and adopt that workflow. You’ll be able to edit code directly on your server without having to export it to your local file system and import it again. It’s also fully integrated with Studio’s server side source control hooks. From your screenshots, it looks like you’ve already experimented with this feature so if you have any questions about it I can answer them.

**Comment by k-murata** [comment]
I've understood the situation. I'm using Git source control, but it's a problem only for the first time, so I'll try it with a source control hooks.
Thank you very much.

**Comment by isc-bsaviano** [comment]
@k-murata Since you're using GitHub, exporting the files and working client side is a good workflow. I'm still not sure why you need to import 400+ files simultaneously though. Did you edit all of them? If not, you should only re-import ones that you've changed. I will look into this but I suspect that the server is getting overloaded because of all the requests in quick succession.

**Comment by k-murata** [comment]
I had to install Cache in my new environment and create an empty namespace. I had this problem when trying to import a source that was pulled from Git.
I first contacted Intersystems Support. The error was reproduced with VSCode, but it was said that no error occurred on the server side.

**Comment by isc-bsaviano** [comment]
@k-murata VS Code is a development tool, not a deployment tool. If you need to deploy a large number of files, please use the Management Portal or [`$SYSTEM.OBJ.LoadDir()`](https://irisdocs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?&LIBRARY=%25SYS&CLASSNAME=%25SYSTEM.OBJ#LoadDir)

**Comment by daimor** [comment]
VSCode should not be used this way at all. You may import a few changed files, but not all. This task for the build process on the server, even just simple $system.OBJ.LoadDir, would be enough.

**Comment by k-murata** [comment]
Thank you. I understand how to use it. I would like to use $system.OBJ.LoadDir.
