### ISSUE TITLE
isfs with system=1 and filter doesn't show expected classes

### ISSUE THREAD

**Issue by timleavitt** [intersystems-community/vscode-objectscript#709]
Issue type: Bug

I have the following isfs folder defined:
```
    {
      "name": "IRISHealth-ZHSLIB",
      "uri": "isfs://IRISHealth:USER/?system=1&filter=%Z*"
    }
```
I see routines and include files, but not classes matching the filter. (I've tried a few variations on the filter and none seem to work.)

It seems likely to me that this is an upstream issue.

Server version: IRIS for Windows (x86-64) 2019.1.1 (Build 612U) Mon Oct 28 2019 11:29:24 EDT
VSCode version: 1.57.1
Extension version: 1.0.12 (language server 1.2.2, server manager 2.0.5)

**Comment by isc-bsaviano** [comment]
@timleavitt The ISFS `filter` query param corresponds to the `Spec` argument to the `%Library.RoutineMgr_StudioOpenDialog()` query. I tried running that query in my user namespace using your `filter` (with the `,'*.prj` addition from the extension) and `system` values and I saw classes in the result set. Would it be possible for you to get Wireshark running and see the exact request and response packets?

**Comment by isc-bsaviano** [comment]
@timleavitt I added an ISFS folder using your filters and captured the packets using Wireshark. This does appear to be a server issue. This is the query that was sent to my server:

```json
{
  "parameters": [
    "%Z*,'*.prj",
    "1",
    "1",
    "1",
    "0",
    "0",
    "0"
  ],
  "query": "CALL %Library.RoutineMgr_StudioOpenDialog(?,?,?,?,?,?,?)"
}
```

This is correct based on your query params. The response was:

```json
{
  "status": {
    "errors": [],
    "summary": ""
  },
  "console": [],
  "result": {
    "content": [
      {
        "Name": "csp/apiexplorer",
        "IsDirectory": "/",
        "Type": "10",
        "Size": "",
        "Date": "",
        "Description": "",
        "IconType": "0"
      },
      {
        "Name": "csp/user",
        "IsDirectory": "/",
        "Type": "10",
        "Size": "",
        "Date": "",
        "Description": "",
        "IconType": "0"
      },
      {
        "Name": "%ZHSLIB.inc",
        "IsDirectory": "",
        "Type": "2",
        "Size": "11025",
        "Date": "2021-06-03 10:48:21.7852613",
        "Description": "",
        "IconType": "0"
      }
    ]
  }
}
```

This is obviously incorrect. We would expect to see entries for `%ZEN` and `%ZHSLIB` only. The issue appears to be with having text before the `*` wildcard.

**Comment by isc-bsaviano** [comment]
@timleavitt I reported this internally. JIRA is DP-406867

**Comment by timleavitt** [comment]
@isc-bsaviano thank you for chasing this down!!

**Comment by isc-bsaviano** [comment]
@timleavitt Mark looked at your issue and determined that it's not a bug. From the JIRA:

> The behavior is by design as before we include a subdirectory we look to see if there are any items that match the pattern the user input in this directory, so we see the %ZEN package for example and then look if there are any items matching '%ZEN/%Z*' which there are not so we exclude the %ZEN directory etc.
> 
> So the pattern input is expected to match the name of an item when you have moved to this directory rather than the full name of each item which is the case when Flat=1 is passed in.

There's no way to filter on the full name of an item when `Flat = 0`, which is always the case when the ISFS FileSystemProvider builds its file explorer tree. There is a `Filter` argument that can be passed to `%Library.RoutineMgr_StudioOpenDialog()` which functions like a SQL WHERE clause. Passing `Name %STARTSWITH '%Z'`
for that argument may do what you want, but VS Code doesn't have a query parameter for that argument.

**Comment by timleavitt** [comment]
@isc-bsaviano thank you. So I think this is really just a matter of an enhancement to vscode-objectscript, being able to provide more advanced filters; in lieu of a "studio project" concept this will certainly be desirable, I'd imagine especially for DBP dev.

**Comment by isc-bsaviano** [comment]
@timleavitt Yes, we should consider adding in a query parameter for the `Filter` argument.

**Comment by isc-bsaviano** [comment]
@timleavitt We brought this up at the PMC meeting today and we think that using the existing VS Code configuration setting `files.exclude` should be sufficient for your use case. Can you try that and get back to me?

**Comment by isc-kiyer** [comment]
@isc-bsaviano I tried `files.exclude` but VS code's glob pattern isn't rich enough (it doesn't support negation: https://github.com/microsoft/vscode/issues/27051) so we cannot do something like "exclude all but %Z* classes". Would need to manually list every single % package in `files.exclude` other than the one we want to see which seems like an unreasonable solution.

**Comment by isc-bsaviano** [comment]
@isc-kiyer I'm glad you found a method that works.
