### ISSUE TITLE
Server side search has a default max of ~200 results. This should be configurable

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems-community/vscode-objectscript#713]
When using server side search using the proposed APIs, search results are limited to just over 200. This setting should be configurable so more results can be returned if desired:

Extension version: v1.0.13-beta3
VS code version: 1.57.1

Per @isc-bsaviano this is due to the REST request using a default value of 200. A setting should be exposed to override this default.

**Comment by isc-bsaviano** [comment]
We don't need a custom setting for this. The `options` argument to `provideTextSearchResults()`  has key `maxResults`, which is configurable via VS Code setting `search.maxResults`. All we need to do is pass that value to the server.
