### ISSUE TITLE
More than 1 space between "class" and the classname disables autocompile on Save

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#717]
Issue Type: <b>Bug</b>

Create a class definition and save it. It saves, saves to IRIS, and compiles. Now add additional spaces on the top line between "Class" and the classname, and save. The file saves locally, but there's no save to the server or compilation. Remove the extra spaces and everything works again.

Extension version: 1.0.12
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

**Comment by isc-bsaviano** [comment]
The save isn't happening because the multiple spaces between `Class` and the class name fail this regex on line 116:

https://github.com/intersystems-community/vscode-objectscript/blob/c2cc7a67b3731f7140582445c42c766efce9470e/src/utils/index.ts#L114-L119

**Comment by gjsjohnmurray** [comment]
Similar to #613
