### ISSUE TITLE
Open class by name from server

### ISSUE THREAD

**Issue by mat1990dj** [intersystems-community/vscode-objectscript#72]
When using "Edit on server" (not having source code locally) the open class functionality is lost.
A ObjectScript: Open server class... inputing the classname would be great

**Comment by daimor** [comment]
In any case you can use `Go to symbol in file` which at the moment used to search any classes and method names on a server. So, just use cmd+T on macOS enter any classname, and it will show you the list where you can go. It will work as well in case if used virtual fs for server editing.

**Comment by RyszardWithAZ** [comment]
An ObjectScript: Open to open a specific routine or class would be supremely useful. We are forced to be server-based and have tens of thousands of routines and classes, and navigating to them via the explorer, while possible, is prohibitive.

Atelier had the same issue for a long while, it was basically unusable for us (b/c navigating via its explorer was VERY slow) until the Open Atelier Resource utility was added.

**Comment by daimor** [comment]
Feature I mentioned earlier, go to symbol in file, should work for routines too. Could you check it?

**Comment by RyszardWithAZ** [comment]
Oh, interesting... when I have a separate unrelated git directory open, and I can use the navigator to browse my IRIS server, this doesn't work.

But when I open VSCode in an empty directory, where there's no other project loaded, then this does work.

I also noticed that the ObjectScript explorer icon doesn't even show up when I open a workspace, I have to open a directory instead. I wonder if that's related to the above.

**Comment by daimor** [comment]
Yeah, you have to open folder or code-workspace file to be able to work with it

**Comment by mvhenderson** [comment]
One place this would be handy is jumping straight to the line referenced in errors, e.g.

     ERROR <Ens>ErrException: <UNDEFINED>zSignalAllJobs+11 ^Ens.Queue.1

**Comment by gjsjohnmurray** [comment]
If you follow the steps in https://github.com/intersystems-community/vscode-objectscript/issues/126#issuecomment-674089387 to install the latest beta and enable proposed APIs, you should now find that VS Code's QuickOpen (Ctrl/Cmd+p) let's you find files on the server.

**Comment by ajpino** [comment]
Perhaps would be better as a separate issue, but are there any plans for a "Go to Error" functionality that parses error messages like @mvhenderson noted?

**Comment by gjsjohnmurray** [comment]
"Go to Error" suggestion is now #386.

@mat1990dj @RyszardWithAZ for the original issue, does QuickOpen meet the need (see my previous comment)?

**Comment by gjsjohnmurray** [comment]
QuickOpen plus enabling use of proposed APIs meets this need.
