### ISSUE TITLE
Language Server Indicates Data Type on Parameter as Invalid Parameter Type

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#724]
Just a cosmetic issue, since the code actually compiles. I don't think it should be indicated as an error, though:

![image](https://user-images.githubusercontent.com/4532366/125855534-f1127f3f-bd07-4ff6-be19-a756c429342a.png)

**Comment by isc-jamien** [comment]
Yes, it compiles but that doesn't change the fact that it is an invalid parameter type.

**Comment by DodgeDeBoulet** [comment]
How so? ISC's documentation seems to disagree.

https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GOBJ_classes#GOBJ_classes_basics_parms

**Comment by isc-jamien** [comment]
See here, allowed parameter definitions

https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=ROBJ_classdef_parameter

From: DodgeDeBoulet ***@***.***>
Reply-To: intersystems-community/vscode-objectscript ***@***.***>
Date: Thursday, July 15, 2021 at 5:18 PM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Jamie Newton ***@***.***>, State change ***@***.***>
Subject: Re: [intersystems-community/vscode-objectscript] Language Server Indicates Data Type on Parameter as Invalid Parameter Type (#724)

How so? ISC's documentation seems to disagree.

https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GOBJ_classes#GOBJ_classes_basics_parms

**Comment by DodgeDeBoulet** [comment]
Thank you for the clarification.
