### ISSUE TITLE
Language server doesn't recognise postconditional

### ISSUE THREAD

**Issue by S-Hahne** [intersystems-community/vscode-objectscript#726]
Dear community,

I thought post-conditionals would be a very common pattern in ObjectScript, so I was quite surprised that my first use of a postconditional in a set command did fail (whereas the same written as if statement has been recognised properly):
![grafik](https://user-images.githubusercontent.com/75479680/126752124-95b61fa7-aa3e-4545-acff-60f8da644651.png)

Is there something I forgot to configure or could this even be a real issue?

Best regards,
Sebastian

**Comment by gjsjohnmurray** [comment]
You have forgotten the `()` after the first occurrence of `SystemMode`

**Comment by S-Hahne** [comment]
Sorry, my bad.
