### ISSUE TITLE
Introduce ObjectScript highlighting support for script files

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#729]
Sometimes we need to feed IRIS with the list of ObjectScript commands that are not within Routine or Class.
E.g. this is [the script file](https://github.com/intersystems-community/iris-analytics-template/blob/master/iris.script), and here is [the place it is being used](https://github.com/intersystems-community/iris-analytics-template/blob/277a08432ef116a0d6ecda80960ea717b9210b05/Dockerfile#L28).

Practically all the IRIS+Docker cases demand some ObjectScript files for initialization that look with highlighting like this:
<img width="578" alt="Screenshot 2021-08-05 at 09 51 06" src="https://user-images.githubusercontent.com/2781759/128304639-d00330db-16f7-4beb-a24c-a499557ee1f5.png">
Could we please add at least minimum highlighting support for script-files?

**Comment by isc-bsaviano** [comment]
@evshvarov Why not just turn your `.script` file into a `.mac` or `.int` routine and load it the `Do` it in your Dockerfile? That file is basically a routine without the `ROUTINE` header line and with a different file extension.

**Comment by evshvarov** [comment]
Because the idea is to feed it into IRIS terminal. Sometimes you don’t need
a class or routine but a line of Objectsript to adjust something.
I found already a workaround, never mind.

Чт, 5 авг. 2021 г. в 14:46, Brett Saviano ***@***.***>:
