### ISSUE TITLE
Can't goto method definition of class instance despite #Dim declaration

### ISSUE THREAD

**Issue by mat1990dj** [intersystems-community/vscode-objectscript#73]
Having an instance of a class, cant navigate to a method definition.

```objectscript
#Dim instance As serumIndex.interface.GarbageCollector = ##class(serumIndex.interface.GarbageCollector).%New()
Do instance.DeleteEndOfDayIT()
```

In fact, intellisense is also lost as the method is not proposed

**Comment by isc-bsaviano** [comment]
@mat1990dj This feature is implemented in the Language Server so any issues related to it should be posted in that repository. @daimor This should probably be closed because it's out of scope for this extension.
