### ISSUE TITLE
Request initialize failed with message: Dynamic Linking Error

### ISSUE THREAD

**Issue by amirsamary** [intersystems-community/vscode-objectscript#733]
After I upgraded my Mac to Big Sur, I keep getting this error when I try to use VSCode with IRIS:

```
Request initialize failed with message: Dynamic Linking Error:
dlopen(/Users/asamary/.vscode/extensions/intersystems.language-server-1.2.2/server/lib/mac/libCOMBridge.dylib, 2): 
no suitable image found. 
Did find: /Users/asamary/.vscode/extensions/intersystems.language-server-1.2.2/server/lib/mac/libCOMBridge.dylib: code signing blocked mmap() of '/Users/asamary/.vscode/extensions/intersystems.language-server-1.2.2/server/lib/mac/libCOMBridge.dylib'
```

It happens just after I open VSCode for the first time on the folder where my IRIS source is. I will click on one of my IRIS source files and VSCode will ask me for my IRIS username and password. Then I will see the error above:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/6372644/130528157-17e3d9a4-2b11-4f1c-8dbb-35f5e3868199.png">

I can still save and compile my code on IRIS and "view other" when I right-click the source. But some feature like jumping to the definition of a method are disabled now. It seems that all the features that the language server would provide me are not working anymore and that is very annoying.

I have tried to:
- Uninstall the extensions and re-install them
- Uninstall the extensions and remove the intersystems folders under "/Users/asamary/.vscode/extensions/" 
- Uninstalled VSCode and installed it again. 

Has anyone faced this issue? What else would you suggest me doing?

**Comment by isc-bsaviano** [comment]
@amirsamary See https://github.com/intersystems/language-server/issues/182
