### ISSUE TITLE
Open Terminal in Docker fails on Windows with latest docker

### ISSUE THREAD

**Issue by mvhenderson** [intersystems-community/vscode-objectscript#734]
Running "Open Terminal in Docker" results in this error:

> The terminal process failed to launch: A native exception occurred during launch (Cannot create process, error code: 193).

I've confirmed it is related to this issue: https://github.com/microsoft/vscode/issues/104343 where docker now installs a `docker-compose` shell script and `docker-compose.exe`. I believe the fix is to use `docker-compose.exe` if it exists else use `docker-compose` which avoids doing OS or docker version checks. Then update these two locations:

1. portFromDockerCompose https://github.com/intersystems-community/vscode-objectscript/blob/26df9f018331b9b8835f31b85acca4ce3d233c2d/src/utils/index.ts#L344
2. terminalWithDocker https://github.com/intersystems-community/vscode-objectscript/blob/26df9f018331b9b8835f31b85acca4ce3d233c2d/src/utils/index.ts#L377

Current workaround is to open normal terminal and run `docker compose exec service iris session iris` manually.

Versions 

    Windows 10 build 19042
    Docker Engine 20.10.8
    VS Code 1.60.0
    intersystems-community.vscode-objectscript 1.0.13

**Comment by isc-bsaviano** [comment]
@mvhenderson A PR for this would be much appreciated
