### ISSUE TITLE
Go To Definition opening read-only file

### ISSUE THREAD

**Issue by howardbailey** [intersystems-community/vscode-objectscript#75]
Hi Dmitry,

I love your extension. 

There is one issue that I have been having, which is that when I use "Go to Definition"  on a method or classname it opens the file in a read-only mode.

I see that this problem has been raised before in #14, but I wasn't sure whether it has been resolved or not.

Here are a couple of screenshots illustrating the issue I'm getting:

![image](https://user-images.githubusercontent.com/40768432/69876105-a92f0400-12b6-11ea-91c7-c76c96b2a1c8.png)

![image](https://user-images.githubusercontent.com/40768432/69875977-55bcb600-12b6-11ea-9712-daca2b9e9662.png)

Perhaps I have setup my connection incorrectly?

My settings are 
```
"objectscript.conn": {
        "compileFlags": "cbk",
        "active": true,
        "ns": "LOCALDEV"
    }
```

Editing and compiling both work correctly.

Thanks in advance,

Howard

**Comment by daimor** [comment]
Look here #71

**Comment by howardbailey** [comment]
> Look here #71

Yes, I had looked at this one too, but I'm not sure how it applies.

We aren't using serverSideEditing.

Do I need to map my folder structure in some way?

**Comment by daimor** [comment]
Yes, you have to configure `objectscript.export` correctly, in case if you don't use serverSideEditing. This would be needed for server-side editing.

`objectscript.export`, used to map ClassNames from server to folder/file structure on your machine.

**Comment by howardbailey** [comment]
> Yes, you have to configure `objectscript.export` correctly, in case if you don't use serverSideEditing. This would be needed for server-side editing.
> 
> `objectscript.export`, used to map ClassNames from server to folder/file structure on your machine.

Do you have an example of how to do this?

**Comment by daimor** [comment]
It depends on if you already have some source code structure, used to store sources in your SCM
So, you have to configure `objectscript.export` to follow your structure.
If you don't have any strict structure, yet. You can just make it now. By default it uses `src` folder as root folder for sources, without folders by category of file. Just splitted by package name.

**Comment by evshvarov** [comment]
@howardbailey, the folder structure for VSCode follows recommendations for folder structure for Atelier cause it exports the ObjectScript this way. The basics are: every folder is a package, class is a file.
Check [this article](https://community.intersystems.com/post/setting-folder-structure-objectscript-code-intersystems-package-manager) about folder structure suitable for ObjectScript Package Manager - it's same for Ateiler and VSCode ObjectScript as well.
[Another useful conversation](https://community.intersystems.com/post/intersystems-cach%C3%A9-project-files-and-folders)

Examples could be found in Open Exchange: [One](https://openexchange.intersystems.com/package/objectscript-package-template), [two](https://openexchange.intersystems.com/package/iris-datatransform-unittest), [three](https://github.com/intersystems-community/msgpack), [four](https://github.com/azenkov1991/DocumentTemplate) and many more.

**Comment by howardbailey** [comment]
@daimor @evshvarov 

Ok thanks for your examples.

We do have an established file structure, locally it is as follows:
```
project-name/
 cache/
   CLS/
     package1/
       package1/
         fileA.cls
     package2/
      package2/
         fileB.cls
   INC/
   MAC/
```

The problem that I have is that I do not know how to define the objectscript.export setting, and I don't actually know what it does.

I'm I supposed to do this?

```
objectscript.export: {
 [
 {
 "local": "my/local/path"
 "server": "my/remote/path"
 }
 ]
}
```
I can't find any examples of how to define this export object.

**Comment by daimor** [comment]
Look [here](https://github.com/daimor/vscode-objectscript/wiki/Export-settings), some description for `objectscript.export` settings.
It looks like, your settings should be something like this.
```JSON
  "objectscript.export": {
    "folder": "cache",
    "addCategory": true,
  }
```

**Comment by howardbailey** [comment]
Hi Dmitry,

Thanks for creating that wiki page with more information on the export object.

I have tried setting it up as you have suggested, but the problem is still the same.

There are a couple of other factors that might be causing a problem.

1. The folder that I open in VS code - my workspace did have the CLS, INT and CSP folders added separately. I have tried instead adding the cache folder, but again this seemed to make no difference. Does the folder you open from affect the translation logic?

2. Each package has a folder within it with the same name.

 i.e. our structure is 
 CLS/packageName/packageName/fileName.cls
 not CLS/packageName/fileName.cls

 I'm not sure if this could cause classname to filename translation code problems?

**Comment by daimor** [comment]
To check how export settings work, you can do export action from Server explorer. So, you should manage to get it exported to the same folder. 
If you have CLS,INT folders just in the root of your project, you should set folder as empty
`"objectscript.export.folder": ""`

**Comment by howardbailey** [comment]
Hi Dmitry,

I've been experimenting with this a bit, exporting some files and seeing where they are placed.

It seems that they are always placed one level too high.

For example, let's say I have fileA here:
```
 cache/CLS/packageA/packageA/fileA.cls
```

I export fileA, and it is placed here instead:
```
 cache/CLS/packageA/fileA.cls
```

Is there a way to tell the extension that my all of my packages have a subfolder with the same name within it?

My config was as follows:
```
"objectscript.export": {
    "folder": "cache",
    "addCategory": true
 }
```

**Comment by gjsjohnmurray** [comment]
>  our structure is
> CLS/packageName/packageName/fileName.cls
> not CLS/packageName/fileName.cls

@howardbailey I'm interested to know why you double the package directories. AFAIK that isn't a convention handled by this extension.

**Comment by howardbailey** [comment]
@gjsjohnmurray As far as I know, the decision was made to more efficiently work with eclipse, each package being defined as a separate eclipse project - it was a little before my time at the company.

**Comment by howardbailey** [comment]
@daimor Is it possible to define a different export for each package? So that I could tell each one to export to a specified directory under ```CLS/package/``` ?

**Comment by daimor** [comment]
Look at ‘objectscript.export.addCategory’ here https://github.com/intersystems-community/vscode-objectscript/wiki/Export-settings

**Comment by howardbailey** [comment]
@daimor Ok thanks, as a test I have set my export as follows:

```
"objectscript.export": {
        "folder": {
            "*./abstract/*.cls": "abstract/abstract"
        },
        "addCategory": true
     }
```

This exports my file to ```[object Object]/cls/abstract```

Where I am hoping it to export to ```cls/abstract/abstract```

Is there any reason it is adding this ```[object Object]``` onto the front of the export?

**Comment by daimor** [comment]
interesting, let me check

**Comment by gjsjohnmurray** [comment]
@howardbailey do you still have this problem? If not, please close the issue here.

**Comment by howardbailey** [comment]
@gjsjohnmurray Thanks John, closing the issue now.
