### ISSUE TITLE
Locking problem with server side source control hooks and auto-reload of routine

### ISSUE THREAD

**Issue by hansonmark** [intersystems-community/vscode-objectscript#763]
This is with server side source control hooks enabled for VS Code.

To reproduce I had a.inc open in VS Code but not with focus. I undid a shelve of this file so the file in my workspace that is linked to the INC via the source control hooks changed from read only to a different contents and writable. I swap in VS code to this tab and this appears in output window:

ERROR #5864: User 'CSP Gateway' in process '63671' has 'a.INC' open for editing. [zLock+33^%SYS.GlobalQuery.1:%SYS]

Imported 'a.INC' from file '/Users/username/perforce/projects/sql/databases/sys/inc/a.inc'

I suspect this is because VS code is using two server jobs at the same time. In one it is importing the modified INC file from the filesystem, and in the other it was trying to read this document to display it in VS Code but because the other job already had a lock on this we get this locking failure message and the VS code window shows:

The editor could not be opened because the file was not found. <try again>

If I click 'Try Again' then it works as there is no lock conflict anymore.

**Comment by isc-bsaviano** [comment]
Mark and I determined that this is an issue with the Atelier APIs and ISC's source control hooks and is probably related to #705

**Comment by isc-bsaviano** [comment]
Fixed internally by DP-409553
