### ISSUE TITLE
Debugger stops working in new release

### ISSUE THREAD

**Issue by isc-rsingh** [intersystems-community/vscode-objectscript#768]
User report on Marketplace https://marketplace.visualstudio.com/items?itemName=intersystems-community.vscode-objectscript&ssr=false#review-details

"PS: It seems there is a bug for yesterday's release as after updating it the debugger stops running with an error: cannot read property trim of undefined."

**Comment by isc-bsaviano** [comment]
@isc-rsingh I fixed this already in #767. Version `1.1.1-beta.2` contains the fix
