### ISSUE TITLE
Warning when calling a function that throws an exception

### ISSUE THREAD

**Issue by david2278** [intersystems-community/vscode-objectscript#77]
Is there a way we could get a warning that we might want to use a try-catch when calling a function that throws an exception and perhaps recursively checks if that function calls another one which throws? Java implements this in its language through the "throws" keyword on the method declaration so idk if it's possible, but it would be really nice if we could at least get a warning even if it still compiles.

**Comment by daimor** [comment]
In the future, we can try to implement such feature as well. But at the moment, not so easy to add it, due to some reasons.

**Comment by david2278** [comment]
Cool. We're running into some issues because people are calling things and don't immediately realize they need to handle exceptions so this would be a big help!

**Comment by isc-bsaviano** [comment]
@david2278 This isn't feasible, but the Language Server extension version 1.2.0 added a code refactoring feature that allows you to wrap a block of ObjectScript code in a Try/Catch, so you'll be able to easily add Try/Catch blocks to existing methods/routines. See the [LS README](https://github.com/intersystems/language-server/blob/master/README.md) for details
