### ISSUE TITLE
Debugger can not start 

### ISSUE THREAD

**Issue by a807875765** [intersystems-community/vscode-objectscript#773]
Hello. I use extension pack the  version is 1.0.3
I use debug to debug one method from my cls file the launch.json like
![image](https://user-images.githubusercontent.com/58621768/142139552-aaf4fc6c-c38f-4f8d-a613-fd6610b3b2b9.png)

when I  Press debug this method
![image](https://user-images.githubusercontent.com/58621768/142120619-cd47ec67-95bb-4ea2-a093-11dbe60da1e7.png)
![image](https://user-images.githubusercontent.com/58621768/142091175-48f450bd-5537-45a5-9bf0-6373d3319729.png)
I want know what am i missing in launch.json file

Pleause answer my simple question ,I want to know how to deal with .thanks a lot!

**Comment by isc-bsaviano** [comment]
@a807875765 Thanks for the images. When you click `Debug this method`, a debug configuration is created for you automatically.  The `Xdebug` debug configuration in your launch.json isn't used. Are you sure that your server connection info is correct and that the server is running?

**Comment by a807875765** [comment]
@isc-bsaviano Yes,I am sure  the server runing,when I edit comment and save will ask me whether overwrite on server 
![image](https://user-images.githubusercontent.com/58621768/142318566-86b537f2-85dd-4c12-bf25-2415b3e53465.png)
 and I click overwrite will tell me copmile success and sync to remote 
![image](https://user-images.githubusercontent.com/58621768/142321202-928453a6-7e56-4cbc-a312-67757fd2b0a6.png)
 when i click dubug this method the console have not any message and tell me open launch.json 
so I don't konw what  should I  do  , Please help me.Thanks a lot!

**Comment by a807875765** [comment]
when i was use terminal do this method has response 
![image](https://user-images.githubusercontent.com/58621768/142329967-26b8f8b1-07c5-44a7-ae54-e50c6125ca3c.png)
I think l miss some config but not connection config.I'm looking forward to your reply.Thanks!

**Comment by a807875765** [comment]
I use sqltools always can get data, I think maybe not connection problem
![image](https://user-images.githubusercontent.com/58621768/142331989-da2de371-30fa-466b-8bcd-42f1c7f81625.png)

**Comment by a807875765** [comment]
I saw https://code.visualstudio.com/docs/editor/debugging#_launch-configurations 
and put js file debug success.that mean  the studio has not problem  
I want know display debugguer not start reason whether not find class because i don't understand ##class method 
because i have export  cls.file in my local from remote.and Itry  add argument in launch.json  just like this 
![image](https://user-images.githubusercontent.com/58621768/142398232-40acf16b-9f2f-47bc-8c9c-2213106fa4c2.png)
but no use .the cls relative path is src\src\Doctor\reg.cls  and i try change class method argument like this 
![image](https://user-images.githubusercontent.com/58621768/142398789-6ea382fc-a44a-48d3-a6b1-fc5319034796.png)
also did not solve problem .could you try to delete proagrm argument in launch.json and tell me what display .I want know the debug whether need authorization or other configuration.Thanks a lot!

**Comment by isc-bsaviano** [comment]
@a807875765 Thanks for the extra information. You don't need the `"cwd"` key in the launch configuration. What you originally had looked good to me. The class name inside the `##class()` needs to be the same as the name at the top of your file (after the `Class` keyword). Can you try starting a debug session using your `XDebug` configuration instead of clicking `Debug this method`? To do that, make sure the class you want to debug is open, navigate to the [run view](https://code.visualstudio.com/docs/editor/debugging#_run-view), select `XDebug` in the dropdown and press the green play button next to it. Does that work or do you see the same error as with `Debug this method`?

**Comment by a807875765** [comment]
Yes,I find if  i exoprt  class  will creat director src， I use Xdebug instead of Debug this method and see the same error.

**Comment by a807875765** [comment]
@isc-bsaviano  I think it maybe not connection question because  I use F12 to jump the method  effective. thanks for your answer

**Comment by isc-bsaviano** [comment]
@a807875765 Would it be possible for you to use Wireshark or turn on the [HTTP Trace for your server](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GCGI_oper_config#GCGI_viewtrace) in the Web Gateway portal to see the communication between VS Code and the server? I would do that myself but I still haven't been able to reproduce your issue. After you click `Debug this method`, you should see this HTTP request: `GET /api/atelier/v5/%25SYS/debug` and the response should be `101 Switching Protocols`.

**Comment by a807875765** [comment]
Thanks for your answer.I will try use Wireshark to look up my debug request.I can't operate remote Server because I don't have permission.And I need some time to leran skilled use Wireshark.I'll reply to you when I catch the request.Thanks a lot!

**Comment by a807875765** [comment]
At present, I only know that using studiol to connect to the server is a different port. I use the vscode to connect to the last port. Is this correct?
![image](https://user-images.githubusercontent.com/58621768/142726420-e8cea65a-a92d-4ce8-bbdd-c45e09e44024.png)

**Comment by a807875765** [comment]
@isc-bsaviano  Yes.I  use wireshark find this  debug request 
![image](https://user-images.githubusercontent.com/58621768/142793935-5ed5f7c1-4374-4256-9f5b-54aa7bae2084.png)
but it's still showing error.so does the server need to configured!
Thanks a lot！

**Comment by a807875765** [comment]
do I need to Install local language environment of object script?

**Comment by isc-bsaviano** [comment]
@a807875765 Yes, you use the Web Server Port when connecting from VS Code. Thanks for finding that the debug HTTP request got sent. Can you check that the response is `101 Switching Protocols`? I'm not sure what you mean by "local language environment" but the extension pack (which you have installed) is sufficient for working with ObjectScript in VS Code.

**Comment by a807875765** [comment]
@isc-bsaviano  Sry.my english is poor.local language environment mean  I need to install jdk in my computer just like java.I do not have permission to find response in remote server.I think it's not have response.because after port mapping for nginx.the port is map to another port.
![image](https://user-images.githubusercontent.com/58621768/142955324-c3aefda7-3b41-406e-a863-15a0515f0b3f.png)
just like this image.I use 3399 port to export code.but when I use terminal for IRIS for Health it's request telnet port 3398.but i just can revise setting.json .but in objectscript.conn just have one port property. how can i use another port in debug? cause Security considerations the remote web server only open some port .

**Comment by a807875765** [comment]
Thanks a lot  for your answer .I'm looking for your reply.

**Comment by a807875765** [comment]
@isc-bsaviano I want ask another question when I exoprt  class file diffrent enviourment in one workspace (have same class).I can not find go to definition.
![image](https://user-images.githubusercontent.com/58621768/143001695-ce6030e3-ed60-43ad-84c4-6a2c1501eb64.png)
what should I do？I use F12 useless.

**Comment by isc-bsaviano** [comment]
@a807875765 I understand now. There isn't a local language environment like JDK for ObjectScript. All you need is the VS Code with the ObjectScript Extension Pack and an InterSystems server to connect it to. Debugging doesn't use a terminal. A debugging session is started by making a REST request (the one you saw in Wireshark earlier) which is then upgraded to a WebSocket. It's likely that your nginx configuration is preventing the connection upgrade, which is why the debugger can't start. Unfortunately, I'm not an nginx expert so I can't help you with that. 

In response to your second question, you need to check your [export settings](https://intersystems-community.github.io/vscode-objectscript/settings/#vscode-objectscript) to see where an exported class will be located in your local workspace. In the future, please create a new issue for any unrelated questions. It makes the conversation more organized and easier to follow.

**Comment by a807875765** [comment]
@isc-bsaviano Thanks for your answer。if i have another question i will creat a new issue.Thanks

**Comment by a807875765** [comment]
@isc-bsaviano Hello.I use Wireshark find debug error response 
![image](https://user-images.githubusercontent.com/58621768/143205536-4ee907c5-bf40-4601-9676-2ea7f2293015.png)
maybe reson is nginx need add config 
![image](https://user-images.githubusercontent.com/58621768/143205833-a9175f51-c80a-4d4b-ae69-7688555247d9.png)
to make support websocket
If i have permission to add config i will be try .Thanks a lot!

**Comment by isc-bsaviano** [comment]
@a807875765 Does everything work once you configured nginx to allow websockets?

**Comment by a807875765** [comment]
yes,it's useful，Thanks.

**Comment by S-Hahne** [comment]
Hi @a807875765,

I'm currently also struggling to get this configured and neither of these location configurations let me start the WebSocket session:

## VS Code access
location /api/atelier {
    CSP On;
    CSPNSD_pass 127.0.0.1:7038;
    CSPNSD_response_headers_maxsize 8k;
    #proxy_http_version 1.1;
    #proxy_set_header Upgrade $http_upgrade;
    #proxy_set_header Connection "upgrade" ;
}

#location /api/atelier/v5/%SYS/debug {
#    ## 2023-07-17 SeH Test for WebSocket support
#    proxy_pass http://127.0.0.1:7038;
#    proxy_http_version 1.1;
#    proxy_set_header Upgrade $http_upgrade;
#    proxy_set_header Connection "upgrade";
#} 

In the meantime I also tried to vary this as "CSPNSD_set_header" as well but that's not allowed in the configuration and let the NGINX fail to start.

Could you share the updated configuration that works for you?

Many thanks for any useful hint in advance!

Best regards,
Sebastian
