### ISSUE TITLE
Package names passed to source control / server command extensions are missing `.pkg` extension

### ISSUE THREAD

**Issue by isc-svelury** [intersystems-community/vscode-objectscript#774]
Unlike Studio, names of packages selected by users in the explorer view are not passed with the `.pkg` extension in VS Code. This creates inconsistencies and failures in VS Code. Our current workaround for this is to check if the package has any classes and explicitly add the extension if it does. This will not work if the package has no classes. 

Also see: [this git-source-control hooks issue](https://github.com/intersystems/git-source-control/issues/71) 

@timleavitt

**Comment by isc-bsaviano** [comment]
@isc-svelury Do you mean the ObjectScript Explorer or the regular file explorer set up to use `isfs`? I verified that when clicking on a package node in the ObjectScript Explorer, `.PKG` is added to the end of the name:

https://github.com/intersystems-community/vscode-objectscript/blob/421ea58c17b2be64c34b98409415b624b75a9cbe/src/commands/studio.ts#L76-L80

**Comment by isc-tleavitt** [comment]
@isc-bsaviano good question - this would be the regular file explorer set up to use isfs.
