### ISSUE TITLE
Error thrown when undoing checkout

### ISSUE THREAD

**Issue by ryanhenn** [intersystems-community/vscode-objectscript#775]
I have a set of files checked out in Perforce that have no changes since the last revision, and all I want to do with them is revert them or undo their checkouts. In VSCode, when I go to "Server Source Control..." and click "Undo Check Out", I get an error like this:

"ERROR: Item {file I'm trying to revert} has been modified in the database outside of source control.
The copy in IRIS no longer matches the version in the file {path to file in my Perforce folder}.
If you are sure the version in IRIS is the copy you want to keep, make a dummy modification and
save it to force an export to the external file. Otherwise you must do an import from the external file."

I don't think it is true that the two files are out of sync--I believe they are identical. And even when I make a dummy change in the file in my Perforce folder and see that VSCode has imported the new change, when I check out the file and then undo the checkout, I just get the same error again. 

I believe that the set of files this happens for are files that I once tried to revert in the Perforce p4v UI (which I know sometimes messes stuff up). Is there something I'm doing wrong or is this just a phony error? I know other TrakCare devs experience this same error in the course of normal development. Thanks!

**Comment by isc-bsaviano** [comment]
Sounds like a duplicate of #705

**Comment by ryanhenn** [comment]
Yes--and it actually is working now with that one's fix. Thanks!
