### ISSUE TITLE
CSP and JS cannot be synchronized to the server

### ISSUE THREAD

**Issue by buxinshou** [intersystems-community/vscode-objectscript#777]
When the code is checked out locally, the compiled CSP and JS cannot be synchronized to the server

**Comment by isc-bsaviano** [comment]
@buxinshou What's the path of the web app that you're editing files for? Since #622, only non-ObjectScript local files with `csp` in the path are synced with the server.

**Comment by isc-bsaviano** [comment]
@buxinshou Are you still experiencing this issue?

**Comment by buxinshou** [comment]
> @buxinshou What's the path of the web app that you're editing files for? Since #622, only non-ObjectScript local files with `csp` in the path are synced with the server.

`web app` path : localws\src\imedical\web\csp
![image](https://user-images.githubusercontent.com/31057024/159202431-0ed06aa8-2a54-434f-8496-10c2ff0d155b.png)

**Comment by isc-bsaviano** [comment]
@buxinshou Please try this again with the latest version (`1.4.4` or `1.4.5-beta.1`). It contains a bug fix in this area

**Comment by buxinshou** [comment]
> @buxinshou Please try this again with the latest version (`1.4.4` or `1.4.5-beta.1`). It contains a bug fix in this area

I tried 1.4.4 and 1.4.5 and still reported CSP does not exist when saving
![{SQ_084WYYHX4}UTS0(P36Y](https://user-images.githubusercontent.com/31057024/159415376-12dbb1ed-03d5-40df-92ad-2c765f15df3a.png)
---
---
![UU9R8M%)E@TYC_EUGR4T~OM](https://user-images.githubusercontent.com/31057024/159415446-a2c0391d-adfe-4841-a773-ec50071892fb.png)

**Comment by isc-bsaviano** [comment]
@buxinshou Is `/csp/ct.ipmr.bt.config.csp` the correct file path? If not, can I see your `objectscript.export` settings if you exported the file using the extension?

**Comment by buxinshou** [comment]
> @buxinshou Is `/csp/ct.ipmr.bt.config.csp` the correct file path? If not, can I see your `objectscript.export` settings if you exported the file using the extension?

When saving `csp`, an error of `error #5912:page /csp/xx.csp does not exist` will be reported.
---
The `/csp/ct.ipmr.bt.config.csp` path should be correct. 
The steps I take to export 'csp' are shown below. 
![`6Z_PT1O9BXW6MP@{G` P_7](https://user-images.githubusercontent.com/31057024/159673452-65645e7d-4201-457f-b6d1-95733ed7d68a.png)
---
Local file structure after export:
![P%PU)83T_LX`GD)MRRY3~1M](https://user-images.githubusercontent.com/31057024/159674102-1ce32780-ddd4-4dc2-bfad-7943379a94ac.png)
---
`objectscript.export` uses the default value and I have not changed its value. I copied the value of `objectscript.export` from Settings as follows:
```json
"objectscript.export": {
  "folder": "src",
  "addCategory": false,
  "map": {},
  "atelier": true,
  "generated": false,
  "filter": "",
  "category": "*",
  "noStorage": false,
  "dontExportIfNoChanges": false,
  "maxConcurrentConnections": 0
}
```

**Comment by isc-bsaviano** [comment]
@buxinshou Thanks for the extra info. I think this is a bug in the code that maps local files to their server path. I will add this  to my to-do list.
