### ISSUE TITLE
Formatting code is using long form of commands

### ISSUE THREAD

**Issue by kazamatzuri** [intersystems-community/vscode-objectscript#78]
How can I configure the code formatting to not use the long forms of commands?

**Comment by daimor** [comment]
At the moment, it only offers full form of commands and functions.
Not even sure if we even need it.
Any Commands should be in full notations, but I accept that some of functions can be written short.
So, I may add some way to add an exception list.

**Comment by kazamatzuri** [comment]
```Any Commands should be in full notations```
That's a personal preference and the editor shouldn't prescribe that ;)

**Comment by gjsjohnmurray** [comment]
@kazamatzuri now 1.0 has released with Language Server please review the settings it offers, report back here, and close the issue if resolved.

**Comment by gjsjohnmurray** [comment]
Closing here. @kazamatzuri if necessary please open a new issue at https://github.com/intersystems/language-server/issues
