### ISSUE TITLE
Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by RathLee** [intersystems-community/vscode-objectscript#780]
When trying to configure VS Code to connect via public webserver, instead of private Apache.
After entering password and clicking the drop down next to Namespaces shows:
 Cannot read property 'content' of undefined

System Management Portal works via the public webserver. 
VS Code works via the private webserver.

**Comment by XRB900** [comment]
Here is the clients configuration file with sensitive data adjusted
[settings-hidden_TEST.txt](https://github.com/intersystems-community/vscode-objectscript/files/7596376/settings-hidden_TEST.txt)

**Comment by isc-bsaviano** [comment]
@RathLee What are the exact steps that I need to perform to reproduce this? Also, does your public web server use HTTPS?

**Comment by RathLee** [comment]
@isc-bsaviano
1)Setup a public webserver (in this case IIS) to handle request for multiple instances (Registry,Viewer, Edge, etc)
    Usually the steps for that are:
   - Configure the Web Gateway so that there is a Server Access definition pointing to the super server port for each 
          instance.
   - Add a unique Application Access definition in the Web Gateway that will point to each instance.
   - Add applications to your web site in IIS that match the Application Access prefixes previously defined.
   -  (If necessary) add the needed handler mappings (.cls,.csp,.cxw,.zen) for CSP to the newly created applications in IIS.
   - Test public Webserver by bring up SMP for different instances. 

2)We edited the setting.json file and added the new servers to with the public webserver example:
...
"intersystems.servers": {
        "dev1-cv-hsweb": {
            "webServer": {
                "scheme": "http",
                "host": "test.server.com",
                "port": 52773
            },
            "description": "Viewer connection to Private webserver",
            "username": "hsadmin"
        },
        "dev1-cv-iis-http": {
            "webServer": {
                "scheme": "http",
                "host": "test.server.com/viewer",
                "port": 80
            },  
            "description": "Viewer connection to Public webserver",
            "username": "hsadmin"
        },

3) From VS Code when connecting to the dev1-cv-iis-http it prompts for the password and then when you expand the Namespace menu it throws "Cannot read property 'content' of undefined"

Nothing is trapped in the Web Gateway log. 

We changed the host in the setting.json file to be: host= "test.server.com/viewer/" (forward slash at the end), we see the request in the Web Gateway log but it's appending the port incorrectly.

C:\InterSystms\HealthShare\Viewer\:80\api\atelier


Let me know if you have any questions.

Thanks,
Rath

**Comment by gjsjohnmurray** [comment]
@RathLee are you interacting with the Server Manager extension at this point rather than the ObjectScript one? Pasting a screenshot here may help clarify.

**Comment by gjsjohnmurray** [comment]
> "host": "test.server.com/viewer",

I dont thing this will work. Instead please try:

```json
"host": "test.server.com",
"pathPrefix": "/viewer",
```

**Comment by gjsjohnmurray** [comment]
For the record, VS Code currently doesn't enforce the `format` definitions for the `host` property in Server Manager's package.json

https://github.com/intersystems-community/intersystems-servermanager/blob/0b77debab8437832a87945e9d68a5db68330b722/package.json#L156-L171

**Comment by XRB900** [comment]
The client response to suggested review/changes to configurations - following:

[Connection_errors.txt](https://github.com/intersystems-community/vscode-objectscript/files/7619476/Connection_errors.txt)
[Connection_errors.txt](https://github.com/intersystems-community/vscode-objectscript/files/7619478/Connection_errors.txt)
We checked the Handler Mappings in IIS.  Under applications named csp, viewer, and healtshareucr, we found entries named CSPGateway_wildcard. For each, the path was set to *

That looked correct to us, so no settings were changed and the webserver was not restarted.

As you suggested, I changed the viewer connection to use "pathPrefix" of "/viewer".  And, I was able to connect and see my HealthShare code.  But, there were errors in the output window.  I'm not sure if these errors are an issue. I've attached them in a text file.

On a whim, I changed the ucr connection settings in vscode to use a "pathPrefix" of "/healthshareucr".  Again, I was able to connect and see my HealthShare code.  Again, there were connection errors that are reported in the attached text file.

**Comment by isc-bsaviano** [comment]
@XRB900 Where are these error messages coming from? Are these from your web server or the `ObjectScript` Output channel? If the former, what errors are you seeing in your Output channel?

**Comment by XRB900** [comment]
Here are screen shots from the client:

Screen Shot 2021-11-29 at 1.55.04 PM
Shows /csp Handler Mappings

Screen Shot 2021-11-29 at 1.56.05 PM
Shows /healthshareucr Handler Mappings
 
Screen Shot 2021-11-29 at 1.56.45 PM
Shows /viewer Handler Mappings
 
Screen Shot 2021-11-29 at 2.00.44 PM
Shows the error message I get when the /viewer prefix is in the host property of the dev1-cv-iis-https settings JSON and I click on the dropdown next to Namespaces
 
Screen Shot 2021-11-29 at 2.02.43 PM
Shows that /viewer has been moved to the pathPrefix property and that there are no errors generated when looking at the Namespaces.
 
Screen Shot 2021-11-29 at 2.01.53 PM
Shows that when the read-only option is selected from the previous screenshot, errors are generated upon loading the server into the explorer view

![Screen Shot 2021-11-29 at 1 55 04 PM](https://user-images.githubusercontent.com/94975932/143948138-10f2aa41-bb44-4f6b-8fdf-1671fbc03d47.png)
![Screen Shot 2021-11-29 at 1 56 05 PM](https://user-images.githubusercontent.com/94975932/143948144-21a473eb-1c87-479b-9c6e-7c696dc8539c.png)
![Screen Shot 2021-11-29 at 1 56 45 PM](https://user-images.githubusercontent.com/94975932/143948146-0d8461cb-7854-4075-afc9-f11cc589cc86.png)
![Screen Shot 2021-11-29 at 2 00 44 PM](https://user-images.githubusercontent.com/94975932/143948151-4cb4a4ea-3da4-410d-8e57-bc8537079449.png)
![Screen Shot 2021-11-29 at 2 01 53 PM](https://user-images.githubusercontent.com/94975932/143948154-0cf22eee-cb75-4211-b4e1-4e78fbd2b04e.png)
![Screen Shot 2021-11-29 at 2 02 43 PM](https://user-images.githubusercontent.com/94975932/143948159-cccab0f9-808e-492a-b9d1-41c139fff2e3.png)

**Comment by isc-bsaviano** [comment]
@XRB900 Thanks for the screenshots. We've addressed the original error already so there isn't much else to say about that one. The "Non-JSON response" errors seem to be caused by your web server returning an HTML page with the 40X errors (this is visible in your connection_errors.txt). The extension expects to get a JSON packet back in response from the Atelier APIs (except for 401 errors).

**Comment by XRB900** [comment]
Could this be an issue that the version of the extensions is not correct (to low) that the client is using?
If so what version should they be using?

**Comment by isc-bsaviano** [comment]
@XRB900 I don't think so, but regardless it's a good idea to keep VS Code and your extensions up to date if possible. Would it be possible for you to configure your web server to not send those HTML pages for 40X errors? It's important for error handling that the extension gets the Atelier JSON packet back with the reason for the error.

**Comment by isc-bsaviano** [comment]
@RathLee @XRB900 Does the error still appear after you modified your web server to pass through the response packets from IRIS?

**Comment by XRB900** [comment]
The error do not occur since they made the change to do pass through.
Thanks for your assistance
Roger
