### ISSUE TITLE
Intersystems Language Server crashed

### ISSUE THREAD

**Issue by AndreaSchecker** [intersystems-community/vscode-objectscript#783]
Using 'Import and Compile' I received the following message.

![image](https://user-images.githubusercontent.com/94963324/143866834-3a4328f9-3cec-4b84-b113-c3aca845af1b.png)

The command was correctly processed. What's wrong?

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I suggest you move this to the LS repo.

**Comment by isc-bsaviano** [comment]
@AndreaSchecker What OS are you on? Can you send me the error(s) reported in the `InterSystems Language Server` Output channel?

**Comment by AndreaSchecker** [comment]
OS = Microsoft Windows 10 Enterprise Version 10.0.19042 Build 19042
Cache for Windows (x86-64) 2018.1.2 (Build 309_5_19250U) Tue Sep 10 2019 10:49:14 EDT
[InterSystems Language Server Output.pdf](https://github.com/intersystems-community/vscode-objectscript/files/7618784/InterSystems.Language.Server.Output.pdf)

**Comment by isc-bsaviano** [comment]
@AndreaSchecker Thanks for that info. You're using the latest version of VS Code and the extensions, correct? If you restart VS Code do you see an error popup like https://github.com/intersystems/language-server/issues/197? Unfortunately that Output channel text doesn't identify the cause of the crash.

**Comment by AndreaSchecker** [comment]
I didn't see an error popup after starting VSCode

**Comment by AndreaSchecker** [comment]
VSCode-Version 
<img width="183" alt="image" src="https://user-images.githubusercontent.com/94963324/144440717-21ea2b9b-9022-4f06-a367-97d35d25c119.png">
Intersystems Language Server 1.2.6 (current)
Intersystems Objectscript 1.1.2 (beta.8)
 Intersystems Servermanager 2.0.6 (current)

**Comment by gjsjohnmurray** [comment]
I wonder if it's relevant that @AndreaSchecker 's VS Code installation on Windows is a [system setup rather than a user setup](https://code.visualstudio.com/docs/setup/windows#_user-setup-versus-system-setup). Mine is user.

**Comment by isc-bsaviano** [comment]
@AndreaSchecker Do you still see this issue with Language Server version 2.0.0?

**Comment by isc-bsaviano** [comment]
Closing this issue because it's for an outdated version of the Language Server
