### ISSUE TITLE
Class tree does not open, Login worked and Namespaces are visible (Windows User Kontext)

### ISSUE THREAD

**Issue by Kosock** [intersystems-community/vscode-objectscript#796]
I can't open the class tree for a Namespace while in Windows user context.
I can connect to IRIS (UCR server) and the log in is successful. I can see all Namespaces but I can't open the class tree (nighter edit or just view).
If I do the same when I run Visual Code as Administrator it works. The settings are the same setting.json.

**Comment by isc-bsaviano** [comment]
@Kosock Are you seeing any errors in the `ObjectScript` Output channel? Can you give me more information about the exact steps you're following so I can try to reproduce your error? Extensions and OS version would be useful too, as well as your settings.json with sensitive information removed.

**Comment by Kosock** [comment]
@isc-bsaviano hope these are alle the versions you need:
InterSystems Language Server v1.2.6
InterSystems ObjectScript v1.2.1
InterSystems ObjectScript Extension Pack v1.0.3
InterSystems Server Manager v2.0.6
Serenji v3.2.1
I go to InterSystems Tools -> All Servers klick on hs-base and enter my password. No error, I see the Namespaces and try to doulbe click to open it in workspace or try the Edit or View icon next to an selected namespace "hs-base". Nothing happens, and there are no Connection errors but it says "here are no connections yet"

Here is the settings content:
{
    "intersystems.servers": {
    

        "hs-base": {
            "webServer": {
                "scheme": "https",
                "host": "hs-base-web.mh-hannover.local",
                "port": 443
            },
            "description": "Healthshare Base (Entwicklung)",
            "username": "****"
        }
    }
}

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Can you give this a look? Sounds like a server manager issue to me.

**Comment by gjsjohnmurray** [comment]
@Kosock does your user account have the %All role? If not, can you grant it that and retry? Or use an account that already has %All?

**Comment by Kosock** [comment]
@gjsjohnmurray Strangely my user had the role but I just "reapplyed" it and now I can get the full access. Thanks for the quick help.
