### ISSUE TITLE
Exporting not working with new version 1.2.1

### ISSUE THREAD

**Issue by jospalau** [intersystems-community/vscode-objectscript#799]
Hi,

I exported 2 new tables (classes) from the Object Script Explorer after creating them with DDL syntax and they were not appearing as usual. This is my configuration:
"objectscript.export": {
"folder": "",
"addCategory": false,
},

I realized then than instead of exporting the class inside the folder tree of its package (namespace), it was exporting it to the root using the whole package in its name. I rolledback the extension to the previous version, 1.1.1, and it worked like always during last year. I use this functionality nearly every week. Thanks for the extension.

Best,
Jose

**Comment by OneLastTry** [comment]
Same here, I'm downgrading till a fix comes out.

**Comment by elvquant** [comment]
Got the bug, too! Loading last version and waiting. Kills me one hour of live.

**Comment by elvquant** [comment]
to fix it on 1.2.1

objectscript.export.atelier: Export source code as Atelier did it, with packages as subfolders.

"objectscript.export": {
"atelier": true
}

**Comment by daimor** [comment]
Yeah, thanks, forgot to say about it. And the latest beta version, has a fix, for this default value.
