### ISSUE TITLE
Classname and filename mapping option?

### ISSUE THREAD

**Issue by tsfu** [intersystems-community/vscode-objectscript#803]
I am wondering if vscode extension has the functionality to match filename and classname for ObjectScript? We are doing a branch mapping and renaming now, and I know java IDEs can do this, not sure for ObjectScript.
 
So if we update class name like this in code: “Class patientRecord” becomes “Class patientUnifiedRecord”, the filename can be automatically updated from “patientRecord.cls” to “patientUnifiedRecord.cls” under some configuration? I feel like this would be useful for branching mapping or code refactoring work.

**Comment by isc-bsaviano** [comment]
This isn't supported. For local files, the class name in the file is used to identify the class when syncing it to the server and if you change that, the file path won't change. If you're using server-side editing (virtual `isfs` files), you will get an error if you try to save a class that has a class name that's different than the file path.

**Comment by isc-solon** [comment]
But **could** it be supported? Change the classname inside the file and it updates the filename correctly? Do you know if VS Code does this for other languages? Do any other IDEs do this?

**Comment by daimor** [comment]
I did not see something like this in VSCode for other languages. I know that IntelliJ IDEA has this for Java. But any way, it looks good to have.

**Comment by tsfu** [comment]
Thanks for your reply. I only know some Java IDEs (like Eclipse, IntelliJ) let you do this. Maybe there aren't many situations where you want filenames to change with class names in ObjectScript, but if we do branch mapping, refactoring, renaming, it could potentially save a lot of time. That's what I'm doing right now so I'm asking out of curiosity.

**Comment by isc-solon** [comment]
Config setting ("Keep classname and filename in sync") or prompt when saving ("You've changed the classname. Update filename to match?") or some other way?

**Comment by tsfu** [comment]
> Config setting ("Keep classname and filename in sync") or prompt when saving ("You've changed the classname. Update filename to match?") or some other way?

Yes. The prompt is how java IDEs do this.

**Comment by GendronAC** [comment]
👍 Love this proposition

**Comment by isc-bsaviano** [comment]
@tsfu The upcoming version 1.8.0 includes #923, which allows you to rename `isfs` files. The ROUTINE header or Class name will be automatically updated for you, but do note that no other code in the document will be changed.

**Comment by tsfu** [comment]
> @tsfu The upcoming version 1.8.0 includes #923, which allows you to rename `isfs` files. The ROUTINE header or Class name will be automatically updated for you, but do note that no other code in the document will be changed.

Thanks for the update. It would be great to try it out.

**Comment by gjsjohnmurray** [comment]
@tsfu version 1.8 has been out for a while so I am closing this. Please reopen with more information if you need to.
