### ISSUE TITLE
Code Completion for keyword 'MultiDimensional' missing

### ISSUE THREAD

**Issue by kazamatzuri** [intersystems-community/vscode-objectscript#81]
For example when adding a classproperty like 
```
Property code As %Integer [ MultiDimensional ];
```
It's not offering code completion.

**Comment by gjsjohnmurray** [comment]
This will resolve when the language server lands.

**Comment by gjsjohnmurray** [comment]
See also #82 

@kazamatzuri now 1.0 has released with Language Server please re-test, report back here, and close the issue if resolved.

**Comment by gjsjohnmurray** [comment]
Closing here. @kazamatzuri if the problem remains please open an issue at https://github.com/intersystems/language-server/issues
