### ISSUE TITLE
`Server Command Menu` is enabled for `isfs-readonly` files but doesn't return a list of options

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#811]
`Server Command Menu` is enabled for `isfs-readonly` in the `package.json`:

https://github.com/intersystems-community/vscode-objectscript/blob/756f27e10bd2d4ad24a7ce715e61a2058abfd3a6/package.json#L327-L331

https://github.com/intersystems-community/vscode-objectscript/blob/756f27e10bd2d4ad24a7ce715e61a2058abfd3a6/package.json#L395-L399

but the command that's run when the menu is clicked on intentionally doesn't return menu options:

https://github.com/intersystems-community/vscode-objectscript/blob/756f27e10bd2d4ad24a7ce715e61a2058abfd3a6/src/commands/studio.ts#L457-L459

https://github.com/intersystems-community/vscode-objectscript/blob/756f27e10bd2d4ad24a7ce715e61a2058abfd3a6/src/commands/studio.ts#L474-L476

We should either disable the `Server Command Menu` or actually return menu options for it. I propose the latter @daimor @gjsjohnmurray

**Comment by gjsjohnmurray** [comment]
> I propose the latter

Makes sense to me.
