### ISSUE TITLE
Question: What's the difference between CTRL+P and CTRL+T?

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#819]
I'm trying to understand the difference between CTRL+P and CTRL+T to open an artifact.

All I can suss out is that CTRL+P is more reliable and will perform a lookup on the server for my artifact. (BTW, I'm using server-side editing). It also lets me search for a specific type (for example item.int versus item.class) of artifact. Once in a while, it doesn't do anything, but I haven't been able to reliably understand when yet.

While CTRL+T... sometimes works, but you can't specify extension? To be honest, it's kind of stopped working for me, though my coworkers say it sometimes works and sometimes doesn't. 

Anyway, any help on these? Ultimately, all I'm looking for is a keyboard-centric way of opening my artifacts that works.

I'm also trying to teach others in my org on using VSCode and I've written internal doc on this, and the best I can do right now is "if one doesn't work, try the other one". Just looking for clarity.

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ If you’re editing server side and want to open a file by name then CTRL-P is what you’re looking for. It uses the same StudioOpenDialog query as the isfs file explorer and will filter the results based on what you type. You need to enable the VS Code proposed API using [these directions](https://github.com/intersystems-community/vscode-objectscript#enable-proposed-apis) for it to work, however.

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ Did that answer your question?
