### ISSUE TITLE
Code completion for 'InitialExpression' is missing

### ISSUE THREAD

**Issue by kazamatzuri** [intersystems-community/vscode-objectscript#82]
For example when using a class property like this:
```

Property stopped As %Boolean [ InitialExpression = 0 ];
```
InitialExpression doesn't get offered as code completion.

**Comment by daimor** [comment]
Yes, I don't have completion for members parameters at all right now. Just have to be added.

**Comment by gjsjohnmurray** [comment]
This will resolve when the language server lands.

**Comment by gjsjohnmurray** [comment]
@kazamatzuri now 1.0 has released with Language Server please re-test, report back here, and close the issue if resolved.

**Comment by gjsjohnmurray** [comment]
Closing. @kazamatzuri if you still see the problem please open a new issue at https://github.com/intersystems/language-server/issues
