### ISSUE TITLE
Call sql query within a class

### ISSUE THREAD

**Issue by tomb54** [intersystems-community/vscode-objectscript#821]
Hi, can you call sql query within a class like this?

set sql="SELECT TOP 10 * FROM Data_Assets.Asset"

**Comment by gjsjohnmurray** [comment]
This question isn't specific to the VS Code extension whose repository you have posted it on.

Please see the InterSystems documentation at https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSQL_esql

Another good resource is the InterSystems Developer Community (DC) at https://community.intersystems.com/
