### ISSUE TITLE
MAC syntax is allowed in INTs

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#823]
At the moment we treat INTs and MACs as the same language. IMO this is a mistake, because it means I can write in my INTs code which is only valid in MACs (e.g. #-directives, embedded SQL etc) and only find out when I try to save/import them into a namespace.

To fix this I think we should add a new language `objectscript-int` and associate the .int extension with this rather than with `objectscript`.

_Originally posted by @gjsjohnmurray in https://github.com/intersystems-community/vscode-objectscript/issues/822#issuecomment-1012949887_

@isc-bsaviano - Work will also be needed in the [Language Server](https://github.com/intersystems/language-server).

**Comment by isc-bsaviano** [comment]
I can look into modifying the LS's diagnostics provider so it raises error diagnostics when macro preprocessor stuff is present in a `.int` routine but that probably could be done regardless of if we split the `"objectscript"` language into  `"objectscript-mac`" and `"objectscript-int"`

**Comment by daimor** [comment]
Yes, there is a difference. But I'm not sure that worth spending time on it, as soon as MAC is supposed to be as a replacement of INT. The only place where it should appear now, only as other files, which are mostly read-only.

**Comment by isc-bsaviano** [comment]
I just checked and the LS already shows syntax errors when using things like `#Dim` or `&sql()` in a `.int` routine
