### ISSUE TITLE
Request textDocument/hover failed when landing on an objectscript class

### ISSUE THREAD

**Issue by Beiming-Zhang** [intersystems-community/vscode-objectscript#824]
Hi, I encountered this issue this morning on a new instance:

`[Error - 9:44:10 AM] Request textDocument/hover failed.
  Message: Request intersystems/server/resolveFromUri failed unexpectedly without providing any details.
  Code: -32603 `

It keeps popping up when Ianding on an objscript class and try to hover my mouse on a class definition. Also when I try to access it by right click "go to definition", a similar error happens and it cannot open the target class file:
`[Error - 9:46:38 AM] Request textDocument/definition failed.
  Message: Request intersystems/server/resolveFromUri failed unexpectedly without providing any details.
  Code: -32603 `
![image](https://user-images.githubusercontent.com/94547358/149535382-e94e61e9-44b3-4090-85cc-fc07992e859b.png)

This issue has never happened before, and I'm sure that my class, the target classes I'm trying to access, the instance and its server definition are all valid. Everything works fine on Studio.

I tried to restart & reload vscode but does not fix the problem. Also tried to revert to an earlier version (v1.2.7 and v1.2.6), but the error still presented, though I've never encountered it before. Notice that when I used an earlier version of the extension and reload vscode, this error shows up on my other previously-fine instances as well.

My environment: Windows. InterSystems Language Server v1.2.8. vscode 1.63.2.

Thank you in advance for investigating!

**Comment by isc-bsaviano** [comment]
See https://github.com/intersystems/language-server/issues/212. You'll need to roll back to main extension version 1.2.2 until 1.4.0 is released. 1.3.2021011401 was meant to be a pre-release version but it made it into the release channel by accident.

**Comment by Beiming-Zhang** [comment]
@isc-bsaviano Ah sorry for missing that open issue. Thanks for the workaround!

**Comment by gjsjohnmurray** [comment]
@Beiming-Zhang 1.4.0 has now been published. This means that if your 1.2.2 updates it will skip the bad release and go direct to 1.4.0.

Sorry for the inconvenience caused by the bad release I did.

**Comment by Beiming-Zhang** [comment]
@gjsjohnmurray  No worries and thanks for the quick response!
