### ISSUE TITLE
Version 1.4.0 is failing to activate

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#827]

**Comment by isc-bsaviano** [comment]
I believe this is due to the code that checks for the proposed API because version 1.4.1-beta.1 works

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano it looks like #814 didn't account for the way our publish CI removes the `enabledApiProposals` key entirely from package.json

Well done for fixing this so quickly.

**Comment by isc-bsaviano** [comment]
Yup, that's exactly what happened. I needed an extra check to make sure the array was actually present.
