### ISSUE TITLE
Debugger will not start!

### ISSUE THREAD

**Issue by tomb54** [intersystems-community/vscode-objectscript#830]
I created simple class to start playing with the VSCode and the debugger tool, but every time I start the debugger an alert box popup stating, “Debugger cannot start, open launch.json” 
My launch.json has the following;

``{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "objectscript",
            "request": "launch",
            "name": "ObjectScript Run current routine",
            "program": "##class(Test.MyOtherClass).Test()",
        }
    ]
}``

**Comment by isc-bsaviano** [comment]
@tomb54 Does your web server allow websocket connections? The debugger works by making an HTTP request that  upgrades to a websocket. Also, do you have `Test.MyOtherClass` open in your editor when you start the debugging session? From [our documentation](https://intersystems-community.github.io/vscode-objectscript/rundebug/):

> When starting objectscript launch debug session, make sure that the file containing the program that you are debugging is open in your editor and is the active tab. VS Code will start a debug session with the server of the file in the active editor (the tab that the user is focused on).

**Comment by tomb54** [comment]
I created a custom class file within VSCode; the custom file is not on my local instance of Ensemble, but if I!
1.	Start my instance of Ensemble
2.	Create a production
3.	Create my custom class
4.
Woohoo I can then debug my custom class!

It would be helpful if we could just create a custom class within VSCode and start playing with the code and the debugger, why so much overhead just to test some code?

And how do you debug a Method like this OnProcessInput(pInput As %Stream.Object, pOutput As %RegisteredObject) As %Status

I have tried this 

` {
            "type": "objectscript",
            "request": "launch",
            "name": "debug Test",
            "program": "##class(Test.DBS.FilePassthroughService).OnProcessInput(pInput As %Stream.Object, pOutput As %RegisteredObject)",
        },`

But I can't get the debugger to work, I think Intersystem should have some online training specifically on how to use the debugger with VSCode, it’s so frustrating compared to Visual Studio where you can write code and just debug it no hassle :(

**Comment by isc-bsaviano** [comment]
@tomb54 The class need to exist and be compiled on the server for it to be debugged. We have [a page in our documentation](https://intersystems-community.github.io/vscode-objectscript/rundebug/) that covers debugging and InterSystems Learning Services produced [a video](https://learning.intersystems.com/course/view.php?name=VSCodeDebugging) that demonstrates the debugging features of this extension. I suggest you check out those resources if you're confused. To debug a ClassMethod that takes arguments you can open that class and click the `Debug this method` CodeLens that appears above its definition and you will be prompted for a comma-separated list of arguments. You can also supply the argument values directly in the value for the `program` key of your debug  configuration like this:

```json
{
  "type": "objectscript",
  "request": "launch",
  "name": "debug Test",
  "program": "##class(Test.DBS.FilePassthroughService).OnProcessInput(\"abc\", 2)"
}
```

**Comment by tomb54** [comment]
@isc-bsaviano all good now, thanks for your response.
