### ISSUE TITLE
Connections Not Closing

### ISSUE THREAD

**Issue by ebromberg** [intersystems-community/vscode-objectscript#845]
Issue Type: <b>Bug</b>

It seems like anytime I compile or export source using this extension, a new connection is created on the server and not released. As a result I wind up exceeding my license usage and get to the point where I have to goto the Management Portal and clear the CSP sessions. Is there a way to prevent this? Am I just missing a setting?

Extension version: 1.4.1
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.72GB (13.51GB free)|
|Process Argv|--crash-reporter-id d315149c-0cd6-48b9-8593-e8475b9f60c2|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isc-bsaviano** [comment]
@ebromberg Are you able to confirm that VS Code is the process that's using all the licenses?

**Comment by ebromberg** [comment]
Yes it is these. When I look in the management portal I see many CSP sessions tied to /api/atelier for my user.

**Comment by isc-bsaviano** [comment]
Can you tell which agent is making the REST requests that open new sessions? This extension uses node-fetch and the Language Server uses axios so if we know that we can identify the offending extension. Both of them should send cookies instead of basic auth though so this is surprising.

**Comment by ebromberg** [comment]
How would I be able to tell that?

**Comment by isc-bsaviano** [comment]
You can use the HTTP trace in the web gateway portal. Look for requests that aren't using cookies. I just checked the license usage on my IRIS and I didn't see anything out of the ordinary.

**Comment by isc-bsaviano** [comment]
@ebromberg Are you still experiencing this issue?
