### ISSUE TITLE
Connection configuration changes automatically

### ISSUE THREAD

**Issue by baasvancodeza** [intersystems-community/vscode-objectscript#846]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by baasvancodeza** [comment]
Issue Type: <b>Bug</b>

Not exactly sure how this happens.
I have a workspace with 4 ObjectScript folders open, each linking to the same IRIS server.
Each folder has its own settings file containing the connection information.
The "active" setting changes to false on all connections by itself.
{
    "objectscript.conn": {
        "server": "default~iris",
        "ns": "LIBSDEPO",
        "active": false
    }
}

I edit all the files and make it true. It then works again for a few VSCode runs, At some poknt all of them go false again.

Extension version: 1.4.1
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|27.87GB (11.40GB free)|
|Process Argv|--crash-reporter-id fc42bdfa-0e74-4b7b-a3d0-136602da30cb|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop940:30404999
vsrem710:30416614

```

</details>

**Comment by daimor** [comment]
When the extension has not managed to connect to the server, for some reason, after a few attempts, it may switch off the active flag. So, you have to check that your settings are correct and you have access to it and activate it again.

**Comment by baasvancodeza** [comment]
Thank you.
Sometimes I run out of licenses, then when some free up, I continue. I
think it relates to this.
