### ISSUE TITLE
XData display and editing

### ISSUE THREAD

**Issue by eduard93** [intersystems-community/vscode-objectscript#85]
There are many special XDatas:
- BPL
- DTL
- Storage (not XData but XML)
- DeepSee stuff
- %Installer manifest
- ...

In Studio they are:
- available for autocomplete on edit
- autoindented
- collapsible (useful, but I think less important)
- color coded (xpos, ypos - gray, request type - blue) 

![image](https://user-images.githubusercontent.com/5127457/72158372-21670a00-33cb-11ea-9605-69365ce5e172.png)

Not so in VSCode:
![image](https://user-images.githubusercontent.com/5127457/72158414-3d6aab80-33cb-11ea-89a5-6744ecbc2e76.png)

**Comment by daimor** [comment]
Unfortunately, such behavior about fake indention, as in Studio, is not possible and will not be possible in any editor.

Autocomplete, yet, quite hard to implement, but in plans.

color coded - I'm not sure how it was implemented and don't know what does this color means.

**Comment by isc-bsaviano** [comment]
@eduard93 Code completion for SASchemas is implemented in the Language Server so any issues related to it should be posted in that repository. @daimor This should probably be closed because it's out of scope for this extension.
