### ISSUE TITLE
Export incompatible with ExportUDL

### ISSUE THREAD

**Issue by gertjanklein** [intersystems-community/vscode-objectscript#850]
The files created by "Download" are different than those created by $System.OBJ.ExportUDL. The former are missing a final newline. 

The difference is not syntactically relevant, but does show up as a change in source control systems. This is inconvenient if developers use different programs for getting their files in source control.

I believe that vscode-objectscript is wrong here. The API returns an array of lines. These are joined [here](https://github.com/intersystems-community/vscode-objectscript/blob/c75b3931b11ce191fdd8b46ed1f99be24226fdbe/src/commands/export.ts#L118); that code causes the final line to be removed (if empty).

I'd like to know if this is something deemed worth fixing. If so, I'm willing to take a stab at it.

**Comment by isc-bsaviano** [comment]
@gertjanklein This would be a backwards-incompatible change that may cause issues for users who prefer the current behavior so we're unlikely to change it. You should set your source control to ignore whitespace diffs if possible

**Comment by gertjanklein** [comment]
I realize it is a backwards incompatible change, it would need a setting to turn it on or off. I asked because the current behaviour is wrong, and it seemed reasonable to want to fix. :-)  I'll close and change my other tooling.
