### ISSUE TITLE
add support for project (.prj) files

### ISSUE THREAD

**Issue by isc-lindensc** [intersystems-community/vscode-objectscript#851]
Hi,
can you please look into adding project support? refer to https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GSTD_Intro#GSTD_Int_Projects

Projects allow an easy method of grouping relavant files.
The project view would only show files added to the project instead of all avalable e.g. classes in a namespace.
Project export would only export whatever is referenced in the project.

Best Regards

**Comment by daimor** [comment]
I see no reasons of implementing this. It's studio's feature. In VSCode you can construct your project as you wish, it's just your local files.

**Comment by isc-lindensc** [comment]
not if you work in a shared development environment using serverside editing

**Comment by isc-bsaviano** [comment]
@isc-lindensc You can filter out unwanted file server-side by adding a `filter` query parameter to your `isfs` folder URI in your `.code-workspace` file (documented [here](https://intersystems-community.github.io/vscode-objectscript/serverside/#filters-and-display-options)). You can also use the VS Code `files.exclude` setting:

```
  // Configure glob patterns for excluding files and folders. For example, the File Explorer decides which files and folders to show or hide based on this setting. Refer to the `search.exclude` setting to define search-specific excludes.
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/Thumbs.db": true
  },
```

**Comment by gjsjohnmurray** [comment]
I think there could still be a role for PRJ support for isfs users.

Meanwhile @isc-lindensc you may like to try this extension, to which I have contributed:

https://marketplace.visualstudio.com/items?itemName=howardzuo.vscode-favorites

With it you can tag files (e.g. server-side classes) as favorites. They get recorded in your XYZ.code-workspace file, which becomes a client-side equivalent of your server-side PRJ.
