### ISSUE TITLE
/api/atelier/v4 endpoint issue with UCR 2021.2 SSO?

### ISSUE THREAD

**Issue by CraigRegester** [intersystems-community/vscode-objectscript#853]
Generally, extension works fine with latest UCR release 2021.2 that has SSO implemented using ISC's OAuth 2.0 model. There's no explicit instructions provided in ISC Docs (or here) on how to adjust the /api/atelier web application to properly work with the new SSO model but interpreting from other areas but haven't run into any issues until today.

When trying to modify an existing class and then compiling (ISFS is off), it is trying to suggest the Server Side copy is newer and normally would see a prompt to override this. Instead, in the output window I see:

```
Non-JSON response to /api/atelier/v4/MYNS/doc/My.Modified.cls?ignoreConflict=0
The page was not displayed because there was a conflict.
```

Audit log in IRIS shows the following

```
Error message: ERROR #862: User UnknownUser is restricted from running application /api/atelier, %Development:U required -- cannot execute.Web Application: /api/atelier
```

So clear it's attempting to execute the original API call without context of the user I'm currently running as is but unclear why this is since all other functionality works as my user (has %All) including the language server extension pieces. 

If I add objectscript.overwriteServerChanges = true to my VSC config, I can bypass this issue and successfully compile but I'd prefer not to leave in this state, especially for my other users. Any guidance on adjusting /api/atelier web app settings to work kindly with UCR 2021.2 SSO OAuth2 model?

**Comment by isc-bsaviano** [comment]
Are you using the private web server or a different one? Based on the error message in your output, I think your web server is seeing that the request returned a 409 Conflict HTTP status and instead of passing along the JSON body it substituted that string of text on the second line.

**Comment by CraigRegester** [comment]
Fronted by IIS w/ Web Gateway 2021.2.

But good question as I wonder if this is a case where the path prefix isn't be respected as I ran into that once before w/ the Language Server API where it didn't always pay attn to the path prefix we use in Web Gateway.

**Comment by isc-bsaviano** [comment]
Can you make the request using Postman or curl and verify that the response is JSON?

**Comment by CraigRegester** [comment]
Definitely using HTTPS but I will try to reproduce and check IIS logs to see if I can tell where it might not be respecting the prefix (just identified a similar issue with ISC git-source-control that the gentlemen over there are assisting me with! pinpointed it with the IIS logs as well)

**Comment by isc-bsaviano** [comment]
Ok, let me know what you find out. You can also check the HTTP trace in the web gateway portal.

**Comment by CraigRegester** [comment]
> Ok, let me know what you find out. You can also check the HTTP trace in the web gateway portal.

I have not been able to reproduce yet - I set my settings I adjusted in both UCR (in the Web App area) and VS Code workspace to what they were but interestingly, error hasn't returned. @isc-bsaviano We can close this off for now if you need to keep the issue list clean - your call - and I can reopen if I'm able to start reproducing.

**Comment by CraigRegester** [comment]
Apologies @isc-bsaviano as I'm unclear if this is the same issue but still with UCR so I'm taking a guess at 'Yes'

When using isfs w/ UCR/ODS instances, we see a bunch of these messages in the ObjectScript Output window upon opening VS Code.

```
Non-JSON response to /ucr/api/atelier/v4/HSCUSTOM/doc/pom.xml
Bad Request

Non-JSON response to /ucr/api/atelier/v4/HSCUSTOM/doc/pom.xml
Bad Request

Non-JSON response to /ucr/api/atelier/v4/HSCUSTOM/doc/build.gradle
Bad Request

Non-JSON response to /ucr/api/atelier/v4/HSCUSTOM/doc/build.gradle
Bad Request

Non-JSON response to /ucr/api/atelier/v4/HSREGISTRY/doc/pom.xml
Bad Request

Non-JSON response to /ucr/api/atelier/v4/HSREGISTRY/doc/pom.xml
Bad Request
```

To try and absolve authentication issues (make the problem easier), I even switched the atelier web app to unauthenticated to test with curl, etc. and I get the same response regardless. It is indeed NOT a JSON response and instead a 404 - File or directory not found error being returned.

Note we can see the namespaces just fine in VSCode so doesn't appear to be a blocking issue, more just an annoyance at startup. Unclear however what these files are and what its trying to do though so not sure if the issue is something to be concerned about or not.

**Comment by isc-bsaviano** [comment]
@CraigRegester I'm not sure what those files are. I assume that the "Bad Request" would mean that the response status was 400, not 404 but that could be a small bug in our error logging.

@gjsjohnmurray Do you know what these files are or where they could be coming from?

**Comment by gjsjohnmurray** [comment]
I think these requests probably arise from VS Code trying to gather telemetry about the kinds of workspaces it is being used on:

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/tags/electron-sandbox/workspaceTagsService.ts

@CraigRegester if you set `telemetry.telemetryLevel` to anything other than `all` (the default) do the messages stop?

**Comment by CraigRegester** [comment]
@gjsjohnmurray I already have "telemetry.telemetryLevel": "off" in my (and all my users, who also see this) settings.json (the one in AppData/Roaming/code/user) so yes.

Doublechecked my workspace file and it doesn't make any changes to this setting either (don't believe it even works there but checked just the same!)

But yes, I see what you mean and think you're on the right path. Hmm can ObjectScript Extension gracefully ignore these requests or prevent them from being sent to /api/atelier?

**Comment by gjsjohnmurray** [comment]
@CraigRegester does setting `"workbench.enableExperiments": false` make any difference?

**Comment by CraigRegester** [comment]
Unfortunately no:

![image](https://user-images.githubusercontent.com/65192819/156420260-691c3773-7b6a-4984-93c7-bd7e18a67e8d.png)

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano it seems the /api/atelier/v4/_namespace_/doc/_filename.extension_ endpoint returns a 400 if the extension isn't a known document type, e.g.

`GET http://localhost:57772/api/atelier/v4/USER/doc/pom.xml`

I haven't worked out what about @CraigRegester's config makes VS Code's WorkspaceTagService profile workspaces upon opening, in a way that doesn't happen for me.

Maybe we should handle 400 as a special case in AtelierAPI.request()

**Comment by isc-bsaviano** [comment]
Why is the `GET /doc` endpoint being called for those files though? That's the real bug IMO.

**Comment by CraigRegester** [comment]
Here's the extension set I use generally if it helps. But otherwise don't see any other related settings. All are up to date (no pre-releases active). GitLens (GitKraken formerly) recently updated with some new stuff but wouldn't think it'd trigger something like this. All of them however I've used for quite some time and have only recently seen this particular issue - maybe around the time we got 1.4.3 of the extension? Not sure/positive, but I know I didnt see this last week (100% certain.)

"github.vscode-pull-request-github",
"eamodio.gitlens",
"intersystems-community.objectscript-pack",
"robholme.hl7tools",
"humao.rest-client",
"kelvin.vscode-sshfs",
"deltaxml.xslt-xpath"

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray Since this is `isfs`, maybe our `readFile()` method needs to proactively throw `FileNotFound` errors when it's called on files that will never exist in an `isfs` folder.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I don't think it's wise to hardcode the isfs FSP to treat specific filenames and/or file-extensions in particular ways. Sites might be leveraging %Studio.AbstractDocument to implement other document types, for example.

@CraigRegester I'm interested that you only started getting these messages recently. If you use `Install Another Version...` from the extension's gearwheel menu in Extensions view, can you confirm it doesn't happen with 1.4.2? Then bisect through the 1.4.3 betas at https://github.com/intersystems-community/vscode-objectscript/releases to pinpoint when it started?

Please also post your VS Code version info from Help\About.

**Comment by CraigRegester** [comment]
Certainly will give it a shot but sitting and thinking about it - the other thing is the switch to isfs. For awhile, I was the only 'engineer' using VSC with UCR for a variety of reasons. With others joining the fray, it made sense to normalize to using ISFS for all since it matches what we do in our I4H environment/workspaces.

So very quickly I can see in my old non-ISFS based workspace, none of these messages show up. But soon as I launch the ISFS-based workspace file, bam, there they are. Not sure if that's helpful or not to solving this but a definite cause and effect. The switch to 1.4.3 just happened to be this week I was onboarding some new members and using the new ISFS workspace (so correlation != causation and all that to be considered.)

![image](https://user-images.githubusercontent.com/65192819/156467097-b5976763-aa38-433b-9bca-a6f897712d19.png)

**Comment by isc-bsaviano** [comment]
Good point John, I forgot about custom Studio documents

**Comment by gjsjohnmurray** [comment]
@CraigRegester VS Code's workspace-probing mechanism (pom.xml, build.gradle etc) will only result in /api/atelier calls to your UCR server (via your web server) if the workspace uses isfs. So I'm not surprised you didn't see it before you started using isfs.

I see you're using the REST Client extension. If you use that to submit one of the requests reporting as returning a non-JSON response, what does the response look like? When I do this through the IRIS-bundled private Apache web server I get:

![image](https://user-images.githubusercontent.com/6726799/156473470-7203d35b-c60f-4393-8dd6-d5ba8d8d0278.png)

**Comment by CraigRegester** [comment]
I get the same as you it seems:

```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Transfer-Encoding: chunked
Content-Type: text/html
Expires: Thu, 29 Oct 1998 17:04:19 GMT
Server: Microsoft-IIS/10.0
Set-Cookie: CSPSESSIONID-SP-443-UP-ucr-api-atelier-=001001030000GRBw7NydSVgYJSKJpfIyniNJn2lzzOljZwVsz0; path=/ucr/api/atelier/;  secure; httpOnly; sameSite=strict;,IRISLoginToken=UkzXG3JTtQyyt/RDMVroKw==; expires=Thursday, 03-Mar-2022 01:25:12 GMT; path=/; secure; httpOnly; sameSite=strict;,CSPWSERVERID=C22FVHAj; path=/; httpOnly; secure;,NSC_itvs-uftu.GB.psh_wt=ffffffff0956013545525d5f4f58455e445a4a42378b;path=/;secure;httponly
Date: Thu, 03 Mar 2022 00:55:12 GMT

Bad Request
```

What does that tell us exactly? (genuinely curious!)

**Comment by gjsjohnmurray** [comment]
Yours is different from mine. Mine has JSON after the headers, and yours has a single line of text stating "Bad Request".

https://docs.microsoft.com/en-us/iis/troubleshoot/diagnosing-http-errors/how-to-use-http-detailed-errors-in-iis has info about how by default IIS sends custom error pages. We need detailed errors.

**Comment by CraigRegester** [comment]
> Yours is different from mine. Mine has JSON after the headers, and yours has a single line of text stating "Bad Request".
> 
> https://docs.microsoft.com/en-us/iis/troubleshoot/diagnosing-http-errors/how-to-use-http-detailed-errors-in-iis has info about how by default IIS sends custom error pages. We need detailed errors.

Ah apologies, multitasking this late at night. Of course, I know how to turn on the detailed errors. Will do!

**Comment by CraigRegester** [comment]
```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 191
Content-Type: application/json; charset=utf-8
Expires: Thu, 29 Oct 1998 17:04:19 GMT
Server: Microsoft-IIS/10.0
Set-Cookie: CSPSESSIONID-SP-443-UP-ucr-api-atelier-=001001030000GRBw7NydSVBvicC66Sihh0gn2u8rb4dMUz0KLH; path=/ucr/api/atelier/;  secure; httpOnly; sameSite=strict;,IRISLoginToken=w1HK7eOUhvDr+pQWnKX7IA==; expires=Thursday, 03-Mar-2022 02:29:40 GMT; path=/; secure; httpOnly; sameSite=strict;,CSPWSERVERID=C22FVHAj; path=/; httpOnly; secure;
Date: Thu, 03 Mar 2022 01:59:40 GMT

{
  "status": {
    "errors": [],
    "summary": ""
  },
  "console": [],
  "result": {
    "name": "pom.xml",
    "db": "",
    "ts": "",
    "cat": "OTH",
    "enc": false,
    "content": "",
    "status": "ERROR #16006: Document 'pom.xml' name is invalid"
  }
}
```

Ok now they're the same :) Or at least both show the same JSON

**Comment by gjsjohnmurray** [comment]
Has that stopped the  `Non-JSON Response` messages?

**Comment by CraigRegester** [comment]
@gjsjohnmurray It did - duh on my part, sorry, 13 hr day yesterday and that was at the end and just didn't make the connection! But makes sense.

I don't see a note in the docs however that says to ensure detailed errors are turned on for VS Code ObjectScript at the web gateway (but will double check) and if I had the world, I would prefer these requests don't even get made if they're being triggered by unnecessary things from VS Code as that's just unnecessary traffic to the web server - and it's not insignificant - seemed to probe with every little change in the UI. But that might be out of your/our/ISC's hands, I understand.

Gonna adjust the detailed settings errors on my other IIS sites but much appreciated for your help!

**Comment by isc-bsaviano** [comment]
@CraigRegester I opened a PR that will stop the `Non-JSON response` errors from being automatically logged to the Output channel. They will be handled the same as any other error that occurs during a REST request.

@gjsjohnmurray Is there anything we can do on our end to stop that probing? It adds unnecessary stress on the server and pollutes the Wireshark log whenever I need to debug something `isfs` related.

**Comment by gjsjohnmurray** [comment]
> I don't see a note in the docs however that says to ensure detailed errors are turned on for VS Code ObjectScript at the web gateway

@CraigRegester I don't think it's documented anywhere. Something new I learned yesterday when trying to work out why I wasn't seeing what you were seeing.

@isc-bsaviano do you still see isfs requests for these special files even when you reduce `telemetry.telemetryLevel` to a setting less than `all` (the default)?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I have telemetry level set to `crash` and I'm stilll seeing the pom.xml and build.gradle requests, as well as a huge number of calls to `doc//_vscode/USER/xx.json`. I only have 2 `isfs` folders in my workspace but there are many iof these requests. I'm not using the folder level settings feature.

**Comment by CraigRegester** [comment]
ty both - much appreciated. @gjsjohnmurray  Reminder though - my telemetry levels were set to off and was still seeing these requests.

Understood re: documentation - definitely something to add in the isfs area if it can't be addressed otherwise.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano I'm puzzled about why I don't seem to get those pom.xml or build.gradle requests when working with my isfs workspaces. I should probably re-check.

Have you done the setup described in https://intersystems-community.github.io/vscode-objectscript/serverside/#configuring-storage-for-folder-specific-settings ?

If not, maybe add it and see if it changes the number of calls to `doc//_vscode/USER/xx.json`

Perhaps adding stub files (e.g. workspace-level settings.json) makes a difference.

**Comment by isc-bsaviano** [comment]
No, I didn't do that setup because I don't intend to use folder-specific settings. I do have some settings in my code-workspace file. I assume that those REST requests are caused by VS Code (probably when one of our extensions checks a setting value) so they can't be turned off, but it would be nice if we had a `objectscript.serverSideFolderSettings` setting that defaults to `false` so we don't have to ping the server. Since there's already a lot of effort required to get this to work, I don't see that additional step being excessive.
