### ISSUE TITLE
Enhancement Request - Import/Upload for Server-Side Editing

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#854]
Precipitated by [this post on the Developer Community](https://community.intersystems.com/post/vs-code-moving-classes-between-namespaces).

As described in the link above, there is no workflow in VS Code that allows one to move a class from one namespace to another. Such a feature would go a log way in reducing my dependence on Studio for simple, ad-hoc code fixes in small applications..

Thanks!

**Comment by isc-bsaviano** [comment]
What exactly would you like to see? An option to right click on a file/directory, choose another namespace and have the classes copied there with the option to overwrite and delete from the source namespace?

**Comment by DodgeDeBoulet** [comment]
That's one option, and certainly would be useful. But I was thinking more along the lines of having an "Import" or "Upload" option in the Server Explorer view when right-clicking on a namespace. Perhaps adjacent to the "Download" option :)
![image](https://user-images.githubusercontent.com/4532366/153079043-1101e775-798a-4f5d-a236-60947182b240.png)

**Comment by isc-bsaviano** [comment]
That "Download..." menu option is not contributed by any of our extensions. For server-side editing, "upload" doesn't make much sense because the source files don't actually exist on the file system. I will think more about the best way to do this

**Comment by gjsjohnmurray** [comment]
Maybe implement the copy method in FileSystemProvider.ts, even if only for the specific case where the path element of source and destination uris are the same, scheme of destination is isfs, and the authority elements differ.

Then it should be possible to Ctrl+drag a class from one isfs root folder (i.e. one namespace) to another.

**Comment by DodgeDeBoulet** [comment]
Ooooh, I like that!

**Comment by DodgeDeBoulet** [comment]
> That "Download..." menu option is not contributed by any of our extensions. For server-side editing, "upload" doesn't make much sense because the source files don't actually exist on the file system. I will think more about the best way to do this

The instance of VS Code on which I first discovered it has only InterSystems/ObjectScript extensions installed:

![image](https://user-images.githubusercontent.com/4532366/153112261-7e6c6d81-dfa8-4145-871d-f20b68c9a385.png)

So not sure where it would have come from?

**Comment by daimor** [comment]
> Maybe implement the copy method in FileSystemProvider.ts, even if only for the specific case where the path element of source and destination uris are the same, scheme of destination is isfs, and the authority elements differ.
> 
> Then it should be possible to Ctrl+drag a class from one isfs root folder (i.e. one namespace) to another.

This should work already, as I remember I've implemented it a while ago

**Comment by DodgeDeBoulet** [comment]
> > Maybe implement the copy method in FileSystemProvider.ts, even if only for the specific case where the path element of source and destination uris are the same, scheme of destination is isfs, and the authority elements differ.
> > Then it should be possible to Ctrl+drag a class from one isfs root folder (i.e. one namespace) to another.
> 
> This should work already, as I remember I've implemented it a while ago

If I attempt to left-click/drag a package from one namespace to another, I get an error that the package already exists at the destination even though it doesn't.

I'm assuming that by referencing the isfs "root" that this move/copy operation would (if working) only support entire packages rather than individual classes within a package? If that's the case, I downgrade my "Oooh I like it!" to "Well, it's a start." 😉

**Comment by daimor** [comment]
At least it should work for files(classes/routines), not folders(packages)

**Comment by DodgeDeBoulet** [comment]
> At least it should work for files(classes/routines), not folders(packages)

Hi @daimor, dragging a class to another workspace generates a "not implemented" error. Attempting to create the package "tree" in the destination using the "create directory" option fails silently. If I create the package in the target namespace by using the "create file" option and specifying the source package as the directory portion and a temporary class name as the filename, the package appears to be created but I get a "not implemented" error when I attempt to copy a class into that package as well.

**Comment by isc-bsaviano** [comment]
I will explore the copy method.

**Comment by DodgeDeBoulet** [comment]
Well, you're getting there ... what's happening though is that the class is copied to the target namespace, but is created in a "User" package.

For example, the class Abc.DBGen.Extract.FormatColumns is copied to User.FormatColumns ...

**Comment by DodgeDeBoulet** [comment]
> @gjsjohnmurray Well, you're getting there ... what's happening though is that the class is copied to the target namespace, but is created in a "User" package.
> 
> For example, the class Abc.DBGen.Extract.FormatColumns is copied to User.FormatColumns ...

Actually, that may have been a result of me pasting the class at the "root" of the isfs folder/namespace. When I selected the corresponding package in the target namespace, it worked. So it appears my copy method needs more experimentation ...

**Comment by gjsjohnmurray** [comment]
@DodgeDeBoulet there's a new vsix in the zip at https://github.com/intersystems-community/vscode-objectscript/suites/5242702542/artifacts/161315807

**Comment by DodgeDeBoulet** [comment]
> @DodgeDeBoulet there's a new vsix in the zip at https://github.com/intersystems-community/vscode-objectscript/suites/5242702542/artifacts/161315807

Looking promising so far. I'll be testing it more extensively in the morning.

**Comment by gjsjohnmurray** [comment]
@DodgeDeBoulet any update on this? Unless I hear from you by Monday that it needs more work I plan to merge the PR so we can ship a new release.

**Comment by DodgeDeBoulet** [comment]
Ok, so still a significant improvement but not without some problems.

Copying at any level below the base package name and pasting at the "root" of the target namespace will create a package using the relative path of the source. I guess that makes sense, but it's something the user will need to watch out for. The user will need to create the package/"folder" structure for pasting the "sub" package into a corresponding location in the target name space.

Copying a base package into a namespace that already has a base package of the same name generates an error and nothing is copied:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/4532366/153615984-387eeb11-2924-41f7-982a-24aafc09c65b.png">

Cleaning up after a paste mistake is a little arduous if there were many classes or sub-packages in the paste operation since folder/package deletion is not yet implemented:

<img width="271" alt="image" src="https://user-images.githubusercontent.com/4532366/153616856-ad8fb415-a890-498b-978c-b5dd56287c0d.png">

The user needs to traverse the package tree and delete the classes in each sub-package (is there another name for this?).

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray @DodgeDeBoulet I think this issue can be closed now that package deletion is implemented.

**Comment by DodgeDeBoulet** [comment]
I'm happy with the way it works. Closing!
