### ISSUE TITLE
Server side search does not adhere to filters present in the workspace configuration

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems-community/vscode-objectscript#856]
I have the following workspace configuration:

```
{
	"name": "wip22v1:HSLIB",
	"uri": "isfs://wip22v1:hslib/?filter=*.cls,*.inc,*.MODULE,*.LOC&system=1"
}
```

Although I see % classes in my search (looks like the system flag is adhered to), I do not see MODULE or LOC custom documents.

I have proposed APIs enabled as I see the following in my output channel:
intersystems-community.vscode-objectscript version 1.4.2-beta.3 activating with proposed APIs available.

VS Code version:
Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:26:08.977Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by isc-bsaviano** [comment]
This is included in #852
