### ISSUE TITLE
Documentation enhancement request: Routine creation and compilation

### ISSUE THREAD

**Issue by isc-ConnieGao** [intersystems-community/vscode-objectscript#864]
When creating routine files and add .mac/.int in the file name under **Explorer view** and **ObjectScript view** via "New File" utility, it generates an empty file without "ROUTINE <routine name>" declaration on top. Users need to manually add this header otherwise compiling the routine would fail. Creating routine files in a **workspace** gives different behavior, where the ROUTINE <routine name> header is auto generated when adding .mac/.int in the file name. A number of members in InterSystems WRC Support team have noticed this inconsistency and we feel this can bring confusion. We believe this should be documented anywhere, or we may want to change the behavior to be consistent where the ROUTINE header is always generated under all views.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray @daimor I think this might be possible using the `onDidCreateFiles` event

**Comment by gjsjohnmurray** [comment]
Upstream issue https://github.com/microsoft/vscode/issues/143557 means this feature does not always trigger.
