### ISSUE TITLE
Optionally fold all ranges when class is opened

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#876]
> In studio there was the option to "Open class in contracted view"
In vs code, for each class I open, I have to click in the class and ctrl+k ctrl+1 to get the same effect.
Can it be made a setting and auto-applied?

This is possible using the `editor.foldAll` built  in command, which  s what gets called when you use the `ctrl-k-0` keybinding.

*Moved from https://github.com/intersystems/language-server/issues/218*

**Comment by kolaval** [comment]
The setting has been added but it folds all ranges.
It needs to only fold the first range i.e Methods and ClassMethods to allow quicker class navigation

**Comment by isc-bsaviano** [comment]
@kolaval Please try [this VSIX](https://github.com/intersystems-community/vscode-objectscript/suites/5784395951/artifacts/192907615) and let me know if this still isn't what you'd expect.

**Comment by kolaval** [comment]
Yes this is great!
The methods are folded but not the code inside

**Comment by isc-bsaviano** [comment]
Yes, that is by design. If you open a method to edit it, look away, and then focus back on the original class, your work shouldn't be folded back up.
