### ISSUE TITLE
1.4.2 release - publish to OpenVSX stalled

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#878]
See https://github.com/intersystems-community/vscode-objectscript/runs/5304710409?check_suite_focus=true

![image](https://user-images.githubusercontent.com/6726799/155347497-d4131e6d-b3fa-41c2-835c-910b5befe11f.png)

@daimor - any ideas?

**Comment by daimor** [comment]
it looks like open-vsx just not so stable, and we probably would need to set some timeout, and retry

**Comment by daimor** [comment]
and it was released successfully in fact, so, probably just timeout will be enough

**Comment by daimor** [comment]
set it to 15 minutes
https://github.com/intersystems-community/vscode-objectscript/blob/05f43ba9f3e0dcd6306682124b76011a78f31ffa/.github/workflows/main.yml#L174
