### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by PeterUK3** [intersystems-community/vscode-objectscript#89]
- Issue Type: `Performance`
- Extension Name: `vscode-objectscript`
- Extension Version: `0.8.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Peter\daimor.vscode-objectscript-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rajrsingh** [comment]
@PeterUK3 are you still seeing this problem in the latest version?
