### ISSUE TITLE
request to http://serverIP:57772/api/atelier/ failed

### ISSUE THREAD

**Issue by buxinshou** [intersystems-community/vscode-objectscript#901]
When opening vscode for the first time, there is a high probability that the connection to the server will fail. But clicking on the link returns a value.
Open VScode `Settings` -> save (do not change Settings)- > sometimes you can connect to the server successfully. Or open and close `vscode` several times can also connect to the server successfully.

"objectscript.conn": {
    "server": "locallib",
    "ns": "dhc-app",
    "active": true,
    "links": {}
},
"intersystems.servers": {
    "/default": "locallib",
    "locallib": {
        "webServer": {
            "scheme": "http",
            "host": "192.168.127.130",
            "port": 57772
        },
        "username": "_system",
        "description": "本地库"
    }
}
![vscode-output](https://user-images.githubusercontent.com/31057024/159197396-b6af0104-8690-46eb-9996-ca9bcab6571d.png)
![Snipaste_2022-03-21_10-17-09](https://user-images.githubusercontent.com/31057024/159197399-77cac9e5-339f-44b0-8b42-6cd88522c0f8.png)

**Comment by gjsjohnmurray** [comment]
Have you installed the Server Manager extension? If so, have you used it to store the password for username _system?

Or are you being prompted for the password each time you open your VS Code workspace?

**Comment by buxinshou** [comment]
> Have you installed the Server Manager extension? If so, have you used it to store the password for username _system?
> 
> Or are you being prompted for the password each time you open your VS Code workspace?

I installed `InterSystems Server Manager v2.0.7` through the `InterSystems Server Manager Pack, and used it to store the password with the username `_ system`.Every time I open the vscode workspace, I am not prompted for a password.

![image](https://user-images.githubusercontent.com/31057024/159416820-39b0fae7-b67d-4630-b000-05f49030f7c1.png)

**Comment by buxinshou** [comment]
> Have you installed the Server Manager extension? If so, have you used it to store the password for username _system?
> 
> Or are you being prompted for the password each time you open your VS Code workspace?

I installed `InterSystems Server Manager v2.0.7` through the `InterSystems Server Manager Pack`, and used it to store the password with the username `_ system`.Every time I open the vscode workspace, I am not prompted for a password.

![image](https://user-images.githubusercontent.com/31057024/159416820-39b0fae7-b67d-4630-b000-05f49030f7c1.png)

**Comment by isc-bsaviano** [comment]
@buxinshou Ar you still experiencing this issue? If so, could you turn on [HTTP Trace](https://cedocs.intersystems.com/ens20162/csp/docbook/DocBook.UI.Page.cls?KEY=GCGI_oper_config#GCGI_viewtrace) for your Cache instance before you start up VS Code then paste the trace result here after you start VS Code and observe the error?

**Comment by isc-bsaviano** [comment]
@buxinshou I'm going to close this issue since it's getting stale. Please comment and re-open it if you are still experiencing it.
