### ISSUE TITLE
Some Configuration Settings for Export Not Working

### ISSUE THREAD

**Issue by CH-HaroldShort** [intersystems-community/vscode-objectscript#909]
I am able to control the export folder using this setting (the default folder is "src" which I did not want):
```
    "objectscript.export.folder": "",
```
That works as expected.

However, these settings seem to have no effect:
```
    "objectscript.export.category": "CLS",
    "objectscript.export.generated": false
```
When I right click on a folder in Objectscript Explorer and select Export, like this on a folder with just `*.cls` files 
<img width="303" alt="image" src="https://user-images.githubusercontent.com/33648346/160950119-49777995-621b-4eee-af0a-514a3bb45619.png">
Despite the settings to not export generated files and to only export CLS files, I end up with collection of subfolders each containing a `1.int` file on my local file system in addition to the desired .cls files in the local folder.
<img width="278" alt="image" src="https://user-images.githubusercontent.com/33648346/160950217-c7ca9247-cffd-45bb-8f76-b9b611f7acd7.png">

I've tried restarting VS Code after changing the settings to ensure the extension is using them, but to no avail.

**Comment by CH-HaroldShort** [comment]
@isc-bsaviano Thanks, I had not realized that. As you suggested, toggling "Show Generated Items" in explorer stops the extra folders and INT files from being exported.
<img width="167" alt="image" src="https://user-images.githubusercontent.com/33648346/161119243-2fabc9c9-0de5-4f23-8ab1-67f0062bf6d4.png">

However, it sounds like there is another way to do an export that would respect the configured settings, how would I do that?

**Comment by isc-bsaviano** [comment]
@CH-HaroldShort Those settings control the behavior of the `vscode-objectscript.export` command, which you can invoke by opening the command palette (cmd/ctrl-shift-p) and typing in `Export Code from Server`

**Comment by CH-HaroldShort** [comment]
@isc-bsaviano Thank you again! That export from the command palette is working for me.
