### ISSUE TITLE
Export Filter Enhancement

### ISSUE THREAD

**Issue by CH-HaroldShort** [intersystems-community/vscode-objectscript#913]
I am using the `"objectscript.export.filter"` setting in my settings.json
```
    "objectscript.export.filter": "CH.%.cls",
```
This works similar to the filter in the export UI, but is rather limited. I would like to limit the export to just the names that start with `CH.` using a filter value of `CH.%.cls`, but per the documentation there is an implicit wildcard before and after the filter criteria:
> The filter is applied to document names using the [LIKE predicate](https://irisdocs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=RSQL_like) (i.e. Name LIKE '%filter%').

This results in hundreds of matches for us where "ch.%.cls" is found somewhere else after the beginning of the name. 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/33648346/161149611-07680f89-7edd-4040-afc7-aa2123225f51.png">

I am working around this by manually filtering the returned results and unselecting the undesired results, but it would be ideal if we could just get the results we are looking for with configuration.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray How do you feel about this? The change would be backwards-incompatible but i think it's a reasonable request.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano how about adding a new `objectscript.export.exactFilter` setting which would take priority over `objectscript.export.filter`?

Another idea for achieving back-compatibility would be to say that a `objectscript.export.filter` string which begins with `^` would drop that character and would not add a `%` prefix to the value used in LIKE. Similarly a `$` suffix would indicate that no trailing `%` should be added. Those signal characters are chosen to match regex syntax, but might mislead folk into thinking we support regexes.

My preference is for the extra setting.

**Comment by isc-bsaviano** [comment]
@CH-HaroldShort Please download the vsix found [here](https://github.com/intersystems-community/vscode-objectscript/suites/5922777542/artifacts/202416812) and let me know if the exactFilter setting works for you.

**Comment by CH-HaroldShort** [comment]
@isc-bsaviano I downloaded it and ran another export using the new setting. It works great, thank you!
