### ISSUE TITLE
modified header when storing on local disc

### ISSUE THREAD

**Issue by MartinJakubowski** [intersystems-community/vscode-objectscript#924]
Exporting a routine or a class to a local folder, modifies the header of the file. 

We have 2 maschines with the the same software level. Only one maschine has this problem since the last week.

The routine header is modified like this:

'''
ROUTINE Cache-APO.src.FiveRxTest [ type = mac]
'''

Normaly the exported Header looks like this:
'''
ROUTINE FiveRxTest
'''
***Cache-APO*** is the name of the repository and ***src*** is the name of the local folder 

If a class is exported, the hole informationen of the class is lost:

'''
Class AdvKasse.Rezeptdruck Extends %Persistent [ ClassType = persistent, Owner = {ADV}, ProcedureBlock ]
'''

'''
Class Cache-APO.src.AdvKasse.Rezeptdruck
'''

I'm not sure with parameter causes the problem. I played around with objectscript.format.atelier, after the change to false it looks like this:

'''
ROUTINE c:.Users.MJ.Desktop.JAKU [ type = mac]
'''

Setting it back to default (True) doesen't make any changes. 

Do you have any ideas for an other troubleshooting? 

thankful regards

Martin

Extension version: 1.6.0
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.26GB free)|
|Process Argv|C:\\Users\\MJ\\Desktop\\JAKU.mac --crash-reporter-id 8b73076d-076c-47c1-b56e-98443a389461|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

blage geschrieben, da sie zu groß zum Senden waren. Fügen Sie sie ein.

**Comment by isc-bsaviano** [comment]
@MartinJakubowski That header is used by the Atelier API and this extension to identify a routine. It should NOT be modified. You also shouldn't change the name of a class in it's definition unless you want to change the class's name on the server. The server doesn't know or care about the folder structure that you use to modify the files on the client so I'm not sure why you're trying to put that info in the file's header.

**Comment by MartinJakubowski** [comment]
Thank you for your reply. Right, it should not be modified and I know this. I changed the titel and the text to have more clear.

The "modifikation" happens when saving the routing/class to the local disc. It's not in the database.

**Comment by isc-bsaviano** [comment]
@MartinJakubowski Can you please provide exact steps to reproduce this issue?

**Comment by MartinJakubowski** [comment]
@isc-bsaviano After compile -> Finde Routine in Workspace -> Right-Click -> Download...

**Comment by isc-bsaviano** [comment]
The download menu option is not provided by our extensions so I'm not sure how to works exactly. However, I just did a few tests using it with a workspace folder configured for server-side editing and the downloaded files looks good to me.

**Comment by isc-bsaviano** [comment]
If you're editing files on the server then there's no need to save them locally. The server can be configured to handle your source control. The extension supports a client-side workflow as well where you export files and handle the source control yourself. For more information on the server-side editing feature that you're currently using, see [this documentation page](https://intersystems-community.github.io/vscode-objectscript/serverside/). To edit client-side, you can use the [ObjectScript Explorer](https://intersystems-community.github.io/vscode-objectscript/extensionui/#objectscript-view) to export files. You can also use the `Export Code From Server`, which uses the `objectscript.export` [configuration settings](https://intersystems-community.github.io/vscode-objectscript/settings/#vscode-objectscript) to determine what to export.

**Comment by MartinJakubowski** [comment]
I know, but for some reasons we decided to use sourcecontrol outside from Caché. Here we have an mixed environment that will need to support both server- and client-side editing to fit all needs. 

Anyway, if I work with your suggested way the header of the exported files are correct. I tested both ways exports Command Menü and Server-Explorer.  The export will stored in a wrong folder, so it will not show up in the changend files in the sourcecontrol automaticly, but that is a secondary issue.

I never used one of these ways before.

I always download the routine/class in the view of server-tree over the context menü of the file (File -> right-click -> download -> choose folder dialog and store it). 

If this way will not work anymore on my maschine, I will use one of the other ways and it's ok to close the case.

**Comment by isc-bsaviano** [comment]
@MartinJakubowski You should be able to open your local folder that's hooked up to source control and edit classes and routines and have them be automatically synced with the server if you have a server connection enabled. Once the file exists in your file system you shouldn't have to keep exporting it if you just edit that file. As for the download menu option, I don't see any reason why it wouldn't work but because it's provided by VS Code and not our extension it is much harder for me to help you if it breaks for whatever reason.

**Comment by MartinJakubowski** [comment]
I appreciate your time an efford for helping and understandig this problem. 

Its also not understandble for me, why the download option is working differntly to the other options. I'm with you. New to me was the fact that this feature will not interact with the extension.

I will see this as an oppertunity to overwork my lokal setup inkl. my workflows. I know that VSCode syncs the edited local files  directly into the database. We set this up on an other maschine, but this doesn't feed my needs on a daily basis.

Thanks again and all the best!
