### ISSUE TITLE
OpenVMS and Cache 2017.2

### ISSUE THREAD

**Issue by samalaut** [intersystems-community/vscode-objectscript#926]
Has anyone tried to use VSC/ObjectScript plug-in with an OpenVMS and Cache 2017.2 system?  If so, is there anything special as far as setting up the connection?

Thanks!!

**Comment by isc-bsaviano** [comment]
@samalaut All of the extensions in the [InterSystems Extension Pack](https://marketplace.visualstudio.com/items?itemName=intersystems-community.objectscript-pack) support Cache 2017.2. You can have VS Code with our extensions installed on another machine and you can set up a connection to your VMS Cache as long as the machines are on the same network.

**Comment by samalaut** [comment]
Thanks for the Response!!  I misstated the version, we have version 2017.1.3 (last version for OpenVMS).   Should the extension pack work for this version?

**Comment by isc-bsaviano** [comment]
Yes, that version is supported. Some features will not be available because that version only contains the the first version of the server-side Atelier API (latest kits are up to v5) but the core features such as editing, saving and deleting documents and debugging will work fine.

**Comment by samalaut** [comment]
That's what I thought.     But our Infrastructure team is having issues with connectivity to that version.   Is there anything "special" what would need to be done for OpenVMS and Cache 2017.1.3? 

Again, thanks for you help, it is much appreciated!!

**Comment by isc-bsaviano** [comment]
Nope, not that I can think of. VS Code will need to be installed on another machine though because AFAIK it doesn't support VMS. I suggest you try pinging your server from the command line/terminal of the machine that VS Code is installed on to make sure that it's actually reachable.

**Comment by isc-bsaviano** [comment]
@samalaut I'm closing this issue since there's nothing for me to fix. If you're still running into trouble let me know and I will re-open it.

**Comment by samalaut** [comment]
Thanks Brett!   Will do

**Comment by gmanii** [comment]
Hi @isc-bsaviano  and @benn,

For the above scenario , I've pinged the VMS cache server in command line/terminal at specified machine where VS Code is installed  and yes I got the response. 
Further what next to be done to connect VSCode with VMS cache ?

**Comment by isc-bsaviano** [comment]
@gmanii You can follow the configuration steps outlined in [our documentation](https://intersystems-community.github.io/vscode-objectscript/configuration/). The steps are the same regardless of the OS that Cache is installed on or the OS that VS Code is running on. If you don't have VS Code installed already, you should start with our [installation instructions.](https://intersystems-community.github.io/vscode-objectscript/installation/)
