### ISSUE TITLE
intellisense completion for 'words' 

### ISSUE THREAD

**Issue by MaxAbrahams** [intersystems-community/vscode-objectscript#93]
![image](https://user-images.githubusercontent.com/11665665/73597088-71328000-44f6-11ea-9cd3-9dcd8d38b159.png)

This example is very challenging, it would be quite difficult to get intellisense to understand `db` is an oref to an object of `%DocDB.Database` . If you could solve that, that would be great, but in the short term, there's a simpler workflow that could be enable that would cover many cases

i have these enabled
![image](https://user-images.githubusercontent.com/11665665/73597054-36c8e300-44f6-11ea-8e6d-7b9ece7eabbe.png)

so in theory, this should suggest a completion 
![image](https://user-images.githubusercontent.com/11665665/73597122-de461580-44f6-11ea-95f3-db6f3be268b7.png)

or perhaps a more real example
![image](https://user-images.githubusercontent.com/11665665/73597150-0afa2d00-44f7-11ea-81eb-c45149a83940.png)

this could also work within a string thats repeated:
![image](https://user-images.githubusercontent.com/11665665/73597164-37ae4480-44f7-11ea-98b7-248bee83de5b.png)

let me know what you think, @daimor ! keep up the good work.

**Comment by gjsjohnmurray** [comment]
@isc-rsingh do you have the requisite permissions (write on both repos) to transfer this to https://github.com/intersystems/language-server/ ?

**Comment by isc-rsingh** [comment]
According to https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/transferring-an-issue-to-another-repository issues can't be moved across organizations, so another option is to open a new issue referencing this one.

**Comment by gjsjohnmurray** [comment]
@MaxAbrahams if you still want this considered please open a new issue at https://github.com/intersystems/language-server/issues and close this one with a link to it.

**Comment by isc-bsaviano** [comment]
Closing because the first request is for type inferencing, which the LS doesn't plan to add anytime soon and the second is part of VSCode itself, not this extension.
