### ISSUE TITLE
Suggestion: option to do notifications.clearAll before compile

### ISSUE THREAD

**Issue by MaxAbrahams** [intersystems-community/vscode-objectscript#94]
If I have a syntax error, and do ctrl+S, i get an error notification. this is great.

if i fix the error and re-submit the compilation, the error stays but is no longer useful.

![image](https://user-images.githubusercontent.com/11665665/73597580-5d3d4d00-44fb-11ea-9aa2-5634250fdcaa.png)

**Comment by daimor** [comment]
Alex, thanks for the feedback, unfortunately, I did not find a way how close it automatically, yet.

**Comment by daimor** [comment]
Your suggestion to use command `notifications.clearAll`, does not look like a good way as it will clear any other notifications, which supposed to stay visible anyway.
Another solution would be, is do not use such kind of notifications anymore, just keep focusing Output where any errors showed already.

**Comment by MaxAbrahams** [comment]
I like that idea; it would be familiar to those used to atelier/studio as well.

**Comment by MaxAbrahams** [comment]
this has been done for a while, right? thanks alot @daimor

**Comment by daimor** [comment]
Yes
