### ISSUE TITLE
Server-side editing: Cannot select project 

### ISSUE THREAD

**Issue by S-Hahne** [intersystems-community/vscode-objectscript#944]
Dear InterSystems community,

I have found the new option to open a namespace's project in VS Code rather than the complete namespace.
When I tried this with my local IRIS instance and an %All user, I am presented the list of projects but when I try this with our locked-down dev server (where I mainly have %Developer rights), the prompt disappears after
![grafik](https://user-images.githubusercontent.com/75479680/168286781-58a492d4-1fbc-47dc-af95-9555216e1f31.png)

I remember we had a similar issue with the display of routines and classes before (#678), so I assume it is related to a missing right in the %Developer role again.

Does someone know which ressource I need to add to the %Developer role?

Thanks in advance,
Sebastian

**Comment by isc-bsaviano** [comment]
@S-Hahne Everything you need is in the `Notes` section at the bottom of the [`Working with Projects` documentation page](https://intersystems-community.github.io/vscode-objectscript/projects/#notes).

**Comment by S-Hahne** [comment]
Thanks for the information. That works!
