### ISSUE TITLE
Extension does not recognize references to class parameters escaped with quotes

### ISSUE THREAD

**Issue by mfortuna-isc** [intersystems-community/vscode-objectscript#946]
In ObjectScript, you can define a class parameter with non-alphanumeric characters so long as you escape its name in double quotes.
You can then reference the parameter using the syntax `..#"<parameter-name>"`
For example
```objectscript
Class Example
{

Parameter "ESCAPED_PARAMETER" = "Value";

ClassMethod Test()
{
 return ..#"ESCAPED_PARAMETER"
}

}

```

However, neither Studio nor the VSCode extension recognizes this syntax, even though such code compiles and executes as expected.

The regonizer for these IDEs should be updated to detect this usage.

**Comment by isc-bsaviano** [comment]
@mfortuna-isc This appears to be a parser bug specially with quoted parameters. I will create a JIRA for this.
