### ISSUE TITLE
export to UNC file share fails

### ISSUE THREAD

**Issue by isc-lindensc** [intersystems-community/vscode-objectscript#952]
Hi,

i got an issue with exporting source.
I am running Win10 and my local user folers like documents are windows redirected to a fileserver by it admins.
If i try to export to local src as usual using default config i get an error:
Custom.Test.cls - Error: EEXIST: file already exists, mkdir '\\server.local\users\'
export "Custom.Test.cls" as "\\server.local\users\timol\Documents\vscode_workspace\scr01\scratch2\src\Custom\Test.cls" - ERROR: Error: EEXIST: file already exists, mkdir '\\server.local\users\'
Exported items: 0
Items failed to export: 
Custom.AUNG.UDF.ListFilters.cls - Error: EEXIST: file already exists, mkdir '\\server.local\users'

Any ideas?

**Comment by isc-bsaviano** [comment]
@isc-lindensc Is that export path correct?

**Comment by isc-lindensc** [comment]
@isc-bsaviano this is the path as reported by vscode i just have removed the identifiable information.

I think the issue is when user folders are redirected via the use of MS group policies from the local disc to a remote server.

If i take the reported path and paste it into windows file explorer it opens the folder correctly.

**Comment by isc-bsaviano** [comment]
@isc-lindensc If the path that the extension generated is correct then the issue is probably in your environment.

**Comment by isc-lindensc** [comment]
Hi Brett,

The issue is with the plugin VSCode can access all files even on that path perfectly. Only the export fails when trying to create/access the remote path.

Best Regards

Timo

**Comment by isc-bsaviano** [comment]
Maybe it's an issue with our use of node's `fs`. I will replace it with calls to vscode's `workspace.fs` to see if that helps.

**Comment by isc-bsaviano** [comment]
@isc-lindensc Can you install the dev vsix found [here](https://github.com/intersystems-community/vscode-objectscript/suites/7890107842/artifacts/335234868) and let me know if this works for you

**Comment by isc-lindensc** [comment]
Hi Bred,

Looks like this s working now. Just got following error on export but file has been created.
***@***.***

Cheers
Timo
