### ISSUE TITLE
Word completion for macros like $$$TRACE() without $$$ prefix

### ISSUE THREAD

**Issue by Dudelmoser** [intersystems-community/vscode-objectscript#96]
Is it possible to activate macro word completion by typing the macro name without the dollar signs?  Having the option to type 'to' / 'toe' instead of  '$$$th' / '$$$toe' would be pretty slick in my opinion. I understand this is not really "necessary", but it should be really easy to implement and nice to have.

**Comment by daimor** [comment]
It's already there, even few versions ago
https://community.intersystems.com/post/vscode-objectscript-release-0711

**Comment by Dudelmoser** [comment]
I know you can already autocomplete macros, but it requires to type $$$ plus 1-2 more characters, which is a little bit tedious especially for common things like **$$$TH**rowOnError. Optionally suggesting those macros when typing just the beginning of the name itself would be awesome.

**Comment by daimor** [comment]
It's actually how it should work, and animation shows it. It is possible that your connection to the server not so fast, and it looks like you need some more letters. And it is also possible that not every available macro is shown, but I'm not sure that I can solve it, yet.

**Comment by rajrsingh** [comment]
I'm seeing the same behavior as @Dudelmoser
