### ISSUE TITLE
Add "Run Method in Terminal" feature

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#974]
There is a handy "Debug this method" feature above every class method.
Could we also add "Run Method in Terminal" or similar to copy the line suitable to execute classmethod in Terminal?

E.g. if the method is "
Class Foo {
classmethod Bar () As %Status {
}

The function will copy the following:
w ##class(Foo).Bar()

**Comment by isc-bsaviano** [comment]
@evshvarov I don't think this is worth doing. If a user sees "Run this method", they will expect the method to actually be run when they click the button, not have something copied to the clipboard. If you want to run a method and see any console output, you can just click "Debug this method" without any breakpoints and see the output in the Debug Console

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray @daimor Do either of you have a strong opinion about this request?

**Comment by daimor** [comment]
> @evshvarov I don't think this is worth doing. If a user sees "Run this method", they will expect the method to actually be run when they click the button, not have something copied to the clipboard. If you want to run a method and see any console output, you can just click "Debug this method" without any breakpoints and see the output in the Debug Console

There are many reasons, why I would like to have this feature. When actively working on some projects, it's faster to run it in terminal, but unfortunately the syntax for the command is so stupid, so, I have to print `do ##class` copy classname from the top of the class, past it in terminal, then copy classmethod and past it again, too many actions. Debugger is too slow, and may not work as I need, and most developers prefer the way they can control is to run it in terminal.

**Comment by isc-bsaviano** [comment]
Calling this feature "run this method" is confusing. It doesn't actually run anything. A user is going to click this, see that nothing happened, and report a bug or become frustrated.

**Comment by daimor** [comment]
Offer another name, which will be quite short

**Comment by daimor** [comment]
`Pass Invocation Command to Terminal` ?

**Comment by daimor** [comment]
No clipboard, actually at this moment, just inserts to active terminal

**Comment by isc-jamien** [comment]
No, it doesn’t do that, it doesn’t pass anything to the terminal.  I’ll support ‘copy invocation to clipboard’ because that is what it does.

From: Dmitry Maslennikov ***@***.***>
Reply-To: intersystems-community/vscode-objectscript ***@***.***>
Date: Monday, August 29, 2022 at 10:37 AM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [intersystems-community/vscode-objectscript] Add "Run Method in Terminal" feature (Issue #974)


Pass Invocation Command to Terminal ?

**Comment by isc-jamien** [comment]
Inserting directly into the terminal is too dangerous, what with people clicking around, anything could happen.

From: Dmitry Maslennikov ***@***.***>
Reply-To: intersystems-community/vscode-objectscript ***@***.***>
Date: Monday, August 29, 2022 at 10:38 AM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [intersystems-community/vscode-objectscript] Add "Run Method in Terminal" feature (Issue #974)


No clipboard, actually at this moment, just inserts to active terminal

**Comment by evshvarov** [comment]
It’s a developer environment- what dangerous could be there?

Let’s name it “Run in a terminal” ?

**Comment by isc-jamien** [comment]
What are you talking about, VSCode can be connected to any instance in any namespace. Respectfully I don’t think you are thinking this through. I won’t approve it as it stands.

From: Evgeny Shvarov ***@***.***>
Reply-To: intersystems-community/vscode-objectscript ***@***.***>
Date: Monday, August 29, 2022 at 10:43 AM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Jamie Newton ***@***.***>, Comment ***@***.***>
Subject: Re: [intersystems-community/vscode-objectscript] Add "Run Method in Terminal" feature (Issue #974)

It’s a developer environment- what dangerous could be there?

Let’s name it “Run in a terminal” ?

**Comment by isc-bsaviano** [comment]
Why would it insert the text into the active terminal? There's no guarantee that it's an IRIS terminal. What if the terminal is a separate window, like on windows? Or not in vscode's integrated terminal? In those cases copying to the clipboard is preferable and the user has to actually paste it somewhere so they can't run anything by accidentally pressing enter after the copy is done.

**Comment by evshvarov** [comment]
Anyway I’d prefer to have “Copy to clipboard” somewhere too or instead if
possible

**Comment by daimor** [comment]
Changed to clipboard

**Comment by daimor** [comment]
https://github.com/intersystems-community/vscode-objectscript/blob/3c76b3c86824bd99a2ff9f9dfc109cbbb9a9c47b/src/providers/ObjectScriptCodeLensProvider.ts#L110

**Comment by isc-solon** [comment]
Does anyone prefer this: "Copy ObjectScript invocation to clipboard"

And if [language = python]: "Copy Python invocation to clipboard"

…and the proper invocation is copied in each case?

On Aug 29, 2022, at 11:14 AM, Dmitry Maslennikov ***@***.******@***.***>> wrote:



https://github.com/intersystems-community/vscode-objectscript/blob/3c76b3c86824bd99a2ff9f9dfc109cbbb9a9c47b/src/providers/ObjectScriptCodeLensProvider.ts#L110

**Comment by daimor** [comment]
Different behavior for python makes no sense, since the call exactly the same

**Comment by isc-jamien** [comment]
It also should take into account if the method returns a value

From: Joel Solon ***@***.***>
Reply-To: intersystems-community/vscode-objectscript ***@***.***>
Date: Monday, August 29, 2022 at 11:26 AM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Jamie Newton ***@***.***>, Comment ***@***.***>
Subject: Re: [intersystems-community/vscode-objectscript] Add "Run Method in Terminal" feature (Issue #974)

Does anyone prefer this: "Copy ObjectScript invocation to clipboard"

And if [language = python]: "Copy Python invocation to clipboard"

…and the proper invocation is copied in each case?

On Aug 29, 2022, at 11:14 AM, Dmitry Maslennikov ***@***.******@***.***>> wrote:



https://github.com/intersystems-community/vscode-objectscript/blob/3c76b3c86824bd99a2ff9f9dfc109cbbb9a9c47b/src/providers/ObjectScriptCodeLensProvider.ts#L110

**Comment by daimor** [comment]
> It also should take into account if the method returns a value

No difference at all

**Comment by isc-solon** [comment]
Python invocation would work in Python shell (iris.cls)
ObjectScript invocation would work in ObjectScript shell (##class)

On Aug 29, 2022, at 11:27 AM, Dmitry Maslennikov ***@***.******@***.***>> wrote:



Different behavior for python makes no sense, since the call exactly the same

**Comment by daimor** [comment]
> Python invocation would work in Python shell (iris.cls) ObjectScript invocation would work in ObjectScript shell (##class) 
Nope, language = python does not change it
In python shell, supposed to work any method in any language

**Comment by isc-rsingh** [comment]
> Copy ObjectScript invocation to clipboard

How about simply `Copy invocation`? I think the "to clipboard" part is what people expect a copy command to do, unless some other behavior is specified.

**Comment by evshvarov** [comment]
Good day! What about a feature? Already want to use it!

**Comment by evshvarov** [comment]
> > Copy ObjectScript invocation to clipboard
> 
> How about simply `Copy invocation`? I think the "to clipboard" part is what people expect a copy command to do, unless some other behavior is specified.

Like it. Or Copy this method - pair to Debug this method

**Comment by daimor** [comment]
> Good day! What about a feature? Already want to use it!

Download archive with VSIX file, extract and install manually in VSCode with dedicated command
https://github.com/intersystems-community/vscode-objectscript/suites/8192958499/artifacts/356594965

**Comment by isc-solon** [comment]
I don’t understand…

USER>write ##class(%PopulateUtils).Mission()

>>> print(iris.cls(‘%PopulateUtils’).Mission())



On Aug 29, 2022, at 11:37 AM, Dmitry Maslennikov ***@***.******@***.***>> wrote:



Python invocation would work in Python shell (iris.cls) ObjectScript invocation would work in ObjectScript shell (##class)
Nope, language = python does not change it
In python shell, supposed to work any method in any language

**Comment by isc-jamien** [comment]
What do you mean.? If it returns a value the invocation should retrieve the value else it get’s lost

From: Dmitry Maslennikov ***@***.***>
Reply-To: intersystems-community/vscode-objectscript ***@***.***>
Date: Monday, August 29, 2022 at 11:32 AM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Jamie Newton ***@***.***>, Comment ***@***.***>
Subject: Re: [intersystems-community/vscode-objectscript] Add "Run Method in Terminal" feature (Issue #974)


It also should take into account if the method returns a value

No difference at all
