### ISSUE TITLE
Unable to debug Python methods : breakpoint are not taken into account 

### ISSUE THREAD

**Issue by SylvainGuilbaud** [intersystems-community/vscode-objectscript#975]
ie :
ClassMethod augmentationPython(sal1 As %Double, sal2 As %Double) As %String [ Language = python ]
{
pct = ""
if sal1 > 0 :
pct = str(round(((sal2 * 100 / sal1) - 100) , 2)) + "%"
return pct
}

with launch.json :
{
"version": "0.2.0",
"configurations": [
{
"type": "objectscript",
"request": "launch",
"name": "augmentation Python",
"program": "##class(common.functions).augmentationPython(1,2)"
}
]
}

**Comment by SylvainGuilbaud** [comment]
ie :
ClassMethod augmentationPython(sal1 As %Double, sal2 As %Double) As %String [ Language = python ]
{
       pct = ""
       if sal1 > 0 :
              pct = str(round(((sal2 * 100 / sal1) - 100) , 2)) + "%"
       return pct
}

with launch.json :
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "objectscript",
            "request": "launch",
            "name": "augmentation Python",
            "program": "##class(common.functions).augmentationPython(1,2)"
        }
    ]
}

**Comment by isc-bsaviano** [comment]
@SylvainGuilbaud The IRIS debugger does not support debugging python so there's nothing we can do to fix this

**Comment by SylvainGuilbaud** [comment]
Never mind ; thanks Brett
