### ISSUE TITLE
Feature Request: Add "import (upload) on save" setting

### ISSUE THREAD

**Issue by rohlem** [intersystems-community/vscode-objectscript#982]
I'm relatively new to using this extension, so I might be overlooking something obvious.

From what I can tell, an exported file is always imported (uploaded) to the server on saving.
To my surprise, this even happens when disabling the "compile on save" option.
This means I cannot easily save local changes privately - unless there happens to be a conflict with the server version and I discard/ignore the corresponding info window.

So basically I'd appreciate the option to deliberately decouple saving and importing (uploading) into separate steps:
Either a new flag, or expand the "compile on save" option to become a drop-down: "on save" -> {"do nothing", "import/upload", "import/upload and compile"}

For now there are probably workarounds, I can just remember never to save it until I want to re-import the code, or move the file out of the workspace (EDIT: renaming it didn't seem to work).
(On that topic, I'm not sure what benefits or use cases even exists for having a frequently-synced exported file over directly using server-side editing,
but if one exists then the current behavior can be kept; I'd just prefer the ability to work locally without overwriting server-side code.)

If the idea sounds good I might find the time to implement it myself within the next month if no-one else is up for it until then.

**Comment by gjsjohnmurray** [comment]
If you click on the ObjectScript panel in the status bar you can toggle the connection to "Disabled". Now your saves won't affect the server namespace.

But bear in mind that some of the features provided by the InterSystems Language Server extension depend on it communicating with the server and having an up-to-date copy of the code there.

**Comment by gjsjohnmurray** [comment]
> Interesting, I assume "Go-To-Definition" of a only-locally introduced function wouldn't work correctly?

@isc-bsaviano can answer definitively about what isn't available when the server is offline, and what could be misleading if the server's copy is out-of-date.

**Comment by isc-bsaviano** [comment]
@rohlem I think your best bet is to turn on the `objectscript.overwriteServerChanges` setting. The local copy will still be saved on the server but you won';t get any more version conflict notifications. Since you're working client-side and use your local copy as the source of truth then you shouldn't care about what the server version looks like.

**Comment by rohlem** [comment]
@isc-bsaviano Sorry if I wasn't clear, I want the server-side version to be retained until I explicitly upload/import my own version to the server - at which point I _do_ value a conflict notification.

**Comment by isc-bsaviano** [comment]
In that case I think that adding a `importOnSave` setting is the best way to support your workflow. Turning off the server connection is a workaround but like John said, the Language Server won't be able to provide as much intellisense as it does with a server connection. 
@gjsjohnmurray Do you agree?

**Comment by isc-bsaviano** [comment]
@rohlem I opened a PR that adds a new `objectscript.importOnSave` setting. Can you please download the vsix found [here](https://github.com/intersystems-community/vscode-objectscript/suites/8417723775/artifacts/372488048) and let me know if the new setting that I added improves your experience?

**Comment by rohlem** [comment]
Sorry for the late reply, the version from PR #985 worked as expected, thank you!
