### ISSUE TITLE
Prerelease: Use Server Manager auth provider's credentials immediately after consent is given

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript#990]
When using the auth provider to store the password, things work well once the password is stored but that initial attempt when users need to create the server credentials wasn't flawless IMO. After giving the main extension permission and saving a password for the credentials, the main extension appeared to not use the credentials and still prompted me for a password using its own prompt.

**Comment by gjsjohnmurray** [comment]
Fixed in v2.0.0
