### ISSUE TITLE
Encountering issue while exporting code .ERROR [Object Object]

### ISSUE THREAD

**Issue by RathinakumarS** [intersystems-community/vscode-objectscript#997]
Type: <b>Bug</b>

Hi Team,
1. Connect to intersystem cache server and then export file from server to local.

While exporting the server code in cache 2018.1.7 .we are getting  Error [Object Object ].

Extension version: 2.0.0
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (18.23GB free)|
|Process Argv|--crash-reporter-id 82b82e51-fdf6-4571-8b11-779f93f8fd7e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by RathinakumarS** [comment]
![cache2018_1](https://user-images.githubusercontent.com/108020025/194122776-b1a4c86b-6cbd-45d3-97d6-da15c83b0d8e.jpg)

please find the attached screen shot for reference

**Comment by RathinakumarS** [comment]
![cache2018_1](https://user-images.githubusercontent.com/108020025/194123315-f4b5ee4f-53ff-4d8c-a78c-bfc52e186872.jpg)

please find the attached screen shot

**Comment by isc-bsaviano** [comment]
@RathinakumarS Can you please download and install the dev VSIX found [here](https://github.com/intersystems-community/vscode-objectscript/suites/8633789999/artifacts/387820779) and then try your export again? I've improved the logging so instead of seeing `[ object Object ]` you should see the actual reason for the failure in the Output channel.

**Comment by RathinakumarS** [comment]
@isc-bsaviano  I can't able to install that VSIX.
![image](https://user-images.githubusercontent.com/108020025/194317775-663f52da-7826-47e8-89d1-b81ab64afc31.png)

**Comment by isc-bsaviano** [comment]
@RathinakumarS You need to install it in VS Code. You can do that by following [these directions](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix) or dragging it into the extensions view. To open the extensions view, click on this icon, then drag the `.vsix` file into the wide panel that shows all of your installed extensions:

<img width="51" alt="Screen Shot 2022-10-06 at 9 00 28 AM" src="https://user-images.githubusercontent.com/44776135/194319237-4ce2cc47-2a24-4899-bcfd-60821ecc41e2.png">

You will need to reload your VS Code window the complete the install.

**Comment by RathinakumarS** [comment]
now am not seeing any error message but sometimes am getting an  below error right bottom 
![image](https://user-images.githubusercontent.com/108020025/194332755-826cc182-4186-4dc9-9b0c-e1912ed96c0a.png)

**Comment by isc-bsaviano** [comment]
@RathinakumarS I wasn't able to reproduce that error. How is your workspace configured? Do you just have a single local folder open?

**Comment by RathinakumarS** [comment]
This error occurred all the file types .mac,/.int /.cls

**Comment by isc-bsaviano** [comment]
@RathinakumarS Does it only happen with files that already exist in your local folder or only ones that don't exist? Sorry for all the questions, I'm trying to get more info that will help me reproduce your issue.

**Comment by RathinakumarS** [comment]
All the files new and existing . @isc-bsaviano

**Comment by RathinakumarS** [comment]
All the files new and existing . @isc-bsaviano

**Comment by RathinakumarS** [comment]
Occurred in all the files existing and new.

**Comment by isc-bsaviano** [comment]
Does it occur using the `ObjectScript: Export Code from Server` command? That command uses the values of your `objectscript.export` settings to export all files on the server that matches those settings. It's a more efficient way of exporting code than selecting one item at a time from the explorer. Are you only seeing the "Error running command" popup or do you see other error messages in the Output channel like before?

**Comment by RathinakumarS** [comment]
@isc-bsaviano 
please find below. [From output log]
![image](https://user-images.githubusercontent.com/108020025/194552704-7dd228b0-0662-42f5-947c-e5b3c88f5005.png)

**Comment by RathinakumarS** [comment]
It shows exported items 1 but not exported.

![image](https://user-images.githubusercontent.com/108020025/194563805-e01ed507-ee13-4055-9a2f-d5f4cf49879c.png)

**Comment by isc-bsaviano** [comment]
@RathinakumarS Ok, that is unexpected. It should also show the name and path of the file that was exported. Can you tell me the exact steps you did to export the file form the moment you started up VS Code? I will do those same steps to see if I can reproduce your issue.

**Comment by isc-bsaviano** [comment]
I will try to reproduce again and get back to you.

**Comment by isc-bsaviano** [comment]
@RathinakumarS Can you please install [this vsix](https://github.com/intersystems-community/vscode-objectscript/suites/8670408428/artifacts/390413219) in your VS Code and try exporting again? I was able to fix the bug where "Exported items: 1" would show even if the export failed. Now if it fails you should see the reason why printed in the ObjectScript Output channel following the name of the file.

**Comment by RathinakumarS** [comment]
Hi @isc-bsaviano  please find below 

![image](https://user-images.githubusercontent.com/108020025/194616576-672560a6-2d8d-4ec6-9c1a-092dd51c806b.png)

**Comment by isc-bsaviano** [comment]
Great, now we can see the cause of the failure! You have server-side source control enabled for the namespace that you're working in, but something is wrong with that class so an instance of it couldn't be created during the call to the Atelier API. You need to make sure that class exists and doesn't contain any bugs.

**Comment by RathinakumarS** [comment]
I saw the same error message when I opened the particular server cache studio.

![image](https://user-images.githubusercontent.com/108020025/194618450-ad5a3779-c2e3-4ed2-bbfe-6b3232a2ece2.png)

**Comment by isc-bsaviano** [comment]
It looks like that class doesn't exist on that server

**Comment by RathinakumarS** [comment]
@isc-bsaviano  Great thank you. I will check that class.

![image](https://user-images.githubusercontent.com/108020025/194619271-be59f9a3-7b84-444b-8142-6fdef57d6cc9.png)



I will select none and try it

**Comment by RathinakumarS** [comment]
Thank you very much @isc-bsaviano .
After selecting NONE in the source control class.
Now I try to export it and it is working fine. PFB

![image](https://user-images.githubusercontent.com/108020025/194619502-80034ccd-e8a9-4b26-bbec-f4513ba7eda6.png)

**Comment by isc-bsaviano** [comment]
@RathinakumarS Great, I'm glad that it is working for you now! Happy to help.
