### ISSUE TITLE
Import custom snippets from IRIS Studio

### ISSUE THREAD

**Issue by apobrt** [intersystems-community/vscode-objectscript#999]
It would be very convenient to have a tool to automatically import code snippets created in IRIS Studio (which are saved to a .txt file).
Currently, the only way is to recreate them by hand, but it is a long and inconvenient process

**Comment by isc-bsaviano** [comment]
@apobrt I will take a look at this

**Comment by isc-bsaviano** [comment]
@apobrt I opened a PR that adds this feature, among others. If you want to try it out, please download and install the VSIX found [here](https://github.com/intersystems-community/vscode-objectscript/suites/8951826593/artifacts/411117723). Here's an except from the new documentation that describes the command:
> The [InterSystems ObjectScript extension](https://marketplace.visualstudio.com/items?itemName=intersystems-community.vscode-objectscript) provides the `Load Studio Snippets` command, which will load any user defined snippets from Studio into VS Code. It works by reading the locations of Studio user defined snippets files from the Windows registry, converting the snippets contained in those files to VS Code's JSON format and lastly writes the snippets to a new global snippets file called `isc-studio.code-snippets`. This command will only convert snippets for ObjectScript, Class Definition Language (UDL) or HTML; all others will be ignored. To invoke the command, [open the command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and click the `ObjectScript: Load Studio Snippets` menu option.
>
> After loading the snippets it is recommended that you consider opening the generated file and enhancing the snippets so that they take advantage of [features available in VS Code](https://code.visualstudio.com/docs/editor/userdefinedsnippets) that Studio does not support, like tabstops and variable substitution. To open the file, click on the `Open File` button in the success notification box, or click on the Settings gear in the bottom-left corner of the window, select the `Configure User Snippets` menu option, and then select the `isc-studio.code-snippets` file in the dropdown that appears.
